"""Generated by the repo-restructure Phase 3 split (epic #52, #46).

Extracted from src/server.py; see src/core/CONTEXT.md or the matching domain
CONTEXT.md for what lives here and why.
"""
from __future__ import annotations

import base64
import os
import sys
import json
import logging
import math
import platform
import re
import shutil
import struct
import subprocess
import tempfile
import threading
import time
import zipfile
import zlib
from typing import Dict, Any, Optional, List, Tuple

from src.domains.color_grade.utils.cdl import normalize_cdl_payload
from src.core.mcp_stdio import run_fastmcp_stdio
from src.core.api_truth import lookup_api_truth, VERIFIED_ON as _API_TRUTH_VERIFIED_ON
from src.core.contracts import validate as _validate_params
from src.domains.project_lifecycle.utils.cloud_operations import cloud_sync_status_label
from src.domains.auto_edit.utils.cut_ir import build_cut_list as _build_cut_list
from src.core.page_lock import open_page_serialized as _open_page_serialized
from src.core.proc import preload_audit, resolve_spawn_env, safe_run, sanitized_spawn_env
from src.core.readback import verify_by_readback, verification_stats as _verification_stats
from src.core.update_check import (
    check_for_updates,
    clear_update_prompt_preferences,
    get_cached_update_status,
    get_update_channel,
    get_update_mode,
    ignore_update_version,
    set_update_mode,
    snooze_update_prompt,
    start_background_update_check,
    update_prompt_decision,
    update_state_path,
)
from src.domains.media_analysis.utils.caps_gating import (
    HOST_CHAT_PATHS_PROVIDER,
    HOST_CHAT_VISION_PROVIDERS,
    DEFAULT_VISION_ANALYSIS_PROMPT,
    VISION_SCHEMA_REFERENCE,
)
from src.domains.media_analysis.utils.clip_identity_registry import (
    resolve_output_root as resolve_media_analysis_output_root,
    short_hash,
    slugify,
)
from src.domains.media_analysis.utils.capabilities_and_planning import (
    build_plan as build_media_analysis_plan,
    detect_capabilities as detect_media_analysis_capabilities,
    install_guidance as media_analysis_install_guidance,
)
from src.domains.media_analysis.utils.execute_engine import (
    execute_plan_async as execute_media_analysis_plan_async,
    plan_requires_capabilities as media_analysis_plan_requires_capabilities,
)
from src.domains.media_analysis.utils.reports import (
    build_coverage_report as build_media_analysis_coverage_report,
    cleanup_artifacts as cleanup_media_analysis_artifacts,
    commit_visual_analysis,
    load_report as load_media_analysis_report,
    summarize_reports as summarize_media_analysis_reports,
)
from src.domains.media_analysis.utils.analysis_index_build import build_analysis_index
from src.domains.media_analysis.utils.analysis_index_query import (
    analysis_index_status,
    query_analysis_index,
)
from src.domains.media_analysis.utils.sync_detection import detect_sync_events_for_records as detect_media_sync_events
from src.core import actor_identity, background_jobs, resolve_busy
from src.core.resolve_busy import long_resolve_op
from src.domains.media_analysis.utils.media_analysis_jobs import (
    MEDIA_EXTENSIONS,
    batch_job_status as media_analysis_batch_job_status,
    cancel_batch_job as cancel_media_analysis_batch_job,
    create_batch_job as create_media_analysis_batch_job,
    list_batch_jobs as list_media_analysis_batch_jobs,
    resume_batch_job as resume_media_analysis_batch_job,
    run_batch_job_slice as run_media_analysis_batch_job_slice,
)
from src.core.platform import get_resolve_paths, get_resolve_plugin_paths
from src.domains.color_grade.utils.lut_paths import master_lut_dir, ensure_lut_in_master
from src.domains.extension_authoring.utils import fuse_templates, dctl_templates, script_templates
from src.domains.timeline_edit.utils.timeline_title_text import (
    candidate_title_property_keys as _candidate_title_property_keys,
    plain_to_minimal_styled_xml as _plain_to_minimal_styled_xml,
    timeline_item_get_property_map as _timeline_item_get_property_map,
)
from src.domains.media_pool_ingest.utils.multicam import build_multicam_setup_plan
from src.domains.timeline_conform_interchange.utils.timeline_xml import analyze_timeline_xml, sanitize_timeline_xml
from src.domains.fusion_composition.utils.fusion_group_settings import (
    FUSION_COMMIT_CHECKLIST,
    FUSION_GROUP_GUARDRAILS,
    default_backup_path,
    parse_setting_file,
    splice_inputs_block,
)
from src.core import analysis_runs as _analysis_runs
from src.core import brain_edits as _brain_edits
from src.domains.auto_edit.utils import edit_engine as _edit_engine_mod
from src.domains.auto_edit.utils import auto_edit as _auto_edit_mod
from src.domains.auto_edit.utils import montage_edit as _montage_edit_mod
from src.domains.orchestration.utils import orchestrate as _orchestrate_mod
from src.core import advanced_bridge as _advanced_bridge
from src.domains.auto_edit.utils import music_analysis as _music_analysis_mod
from src.domains.media_pool_ingest.utils import media_pool_changes as _media_pool_changes
from src.core import timeline_versioning as _timeline_versioning
from src.domains.project_lifecycle.utils import project_spec as _project_spec
from src.domains.project_lifecycle.utils import project_lint as _project_lint
from src.domains.timeline_edit.utils import clip_query as _clip_query
from src.core import destructive_hook as _destructive_hook
from src.core.destructive_hook import destructive_op as _destructive_op
import uuid as _ledger_uuid
from src.core import resolve_ai_ledger as _resolve_ai_ledger
from src.core import resolve_ai_governance as _resolve_ai_governance
import hashlib as _hashlib
import time as _time
import uuid as _uuid
from mcp.server.fastmcp import Context, FastMCP, Image
from mcp import types as mcp_types

logger = logging.getLogger("resolve-mcp")

from src.server import mcp

from src.core.envelope import (
    ERROR_CATEGORIES,
    _CATEGORY_RETRYABLE_DEFAULT,
    _RETRYABLE_UNSET,
    _callable_method_names,
    _check,
    _err,
    _has_method,
    _ok,
    _requires_method,
    _safe_clip_call,
    _safe_get_property,
    _ser,
    _unknown,
)
from src.core.tool_kernel import (
    _action_help,
    _activate_resolve_window,
    _ai_governance_check,
    _ai_governance_gate,
    _ai_governance_mode,
    _ai_governance_overrides,
    _ai_governance_preset,
    _ai_ledger_root,
    _ai_ledger_timed,
    _confirm_token_fingerprint,
    _confirm_token_gc,
    _confirm_token_required,
    _consume_confirm_token,
    _contact_sheet_png_bytes,
    _contact_sheet_sample_label,
    _draw_rect_rgb,
    _draw_tiny_text_rgb,
    _filter_to_keys,
    _find_timeline_item_by_id,
    _first_param,
    _has_any_param,
    _is_truncated,
    _issue_confirm_token,
    _media_analysis_effective_preferences,
    _normalize_sampling_mode_default,
    _normalize_setup_choice,
    _normalize_setup_list,
    _normalize_timed_marker_choice,
    _normalize_vision_default,
    _normalize_yes_no_ask,
    _opt_number,
    _path_error,
    _png_chunk,
    _read_json_strict,
    _read_media_analysis_preferences,
    _read_media_analysis_preferences_strict,
    _record_action_outcome,
    _resolve_enum_settings,
    _rgb_to_png_bytes,
    _run_maybe_background,
    _safe_int,
    _sampling_mode_choice_from_params,
    _send_resolve_keystroke_go_to_mark_in,
    _settings_diff,
    _setup_marker_limit,
    _setup_positive_int,
    _setup_text_key,
    _string_list_param,
    _thumbnail_data_to_png_bytes,
    _thumbnail_raw_rgb,
    _timed_marker_choice_from_params,
    _timeline_items_by_ids,
    _timeline_items_by_ids_report,
    _timeline_resolve_item_optional,
    _write_media_analysis_preferences,
)
from src.core.timeline_lookup import (
    _clip_file_size,
    _clip_name,
    _clip_summaries,
    _clips_from_params,
    _coerce_item_list,
    _collect_timeline_items_in_range,
    _current_timeline_frame_id,
    _find_clip,
    _find_clip_with_parent,
    _find_timeline_by_id,
    _find_timeline_by_name,
    _frame_id_to_timecode,
    _frame_int,
    _get_item,
    _get_mp,
    _get_selected_timeline_items,
    _get_tl,
    _metadata_write_field_for_field,
    _project_name_and_id,
    _project_summary,
    _range_frames_from_params,
    _range_track_indices,
    _range_track_types,
    _safe_timeline_item_id,
    _safe_timeline_item_name,
    _timecode_to_frame_id,
    _timeline_by_selector,
    _timeline_fps,
    _timeline_frame_id_to_timecode,
    _timeline_item_duration,
    _timeline_item_ids,
    _timeline_item_media_pool_item,
    _timeline_item_probe,
    _timeline_item_source_start,
    _timeline_item_summary,
    _timeline_item_track_info,
    _timeline_start_frame,
    _timeline_timecode_to_frame_id,
    _timeline_track_count,
    _track_items_sorted,
    _track_selector,
)
from src.core.live_connection import (
    get_resolve,
    _destructive_versioning_provider,
)

def _timeline_media_type(track_type: str):
    if track_type == "video":
        return 1
    if track_type == "audio":
        return 2
    return None

def _conform_capabilities():
    return {
        "supported": {
            "timeline_structure": [
                "timeline identity, frame bounds, start timecode, and track counts",
                "per-track item summaries across video, audio, and subtitle tracks",
                "timeline marker snapshot",
                "source MediaPoolItem identity and file path when Resolve exposes it",
            ],
            "analysis": [
                "same-track gap detection",
                "same-track overlap detection",
                "source range summaries grouped by MediaPoolItem",
                "missing-media detection from file path existence and status metadata",
                "timeline snapshot comparison by track and item order",
            ],
            "interchange": [
                "guarded timeline export to temp paths",
                "guarded timeline import from temp paths",
                "round-trip export/import/compare probe",
                "FCPXML, DRT, EDL, AAF, OTIO, and FCP7 XML aliases when Resolve exposes the constants",
            ],
            "relink_planning": [
                "read-only search-root scan by missing file basename",
                "plan output that can be reviewed before media_pool.safe_relink executes",
            ],
            "source_media_integrity": [
                "export/import probes write interchange files only under temp paths by default",
                "missing-media and relink-plan helpers never transcode, proxy, or alter source media",
            ],
        },
        "partially_supported": {
            "interchange_roundtrip": "Export/import survival varies by format, Resolve build, timeline contents, and installed codecs.",
            "timeline_item_semantics": "Generators, titles, compound clips, transitions, effects, Fusion comps, and grades may not survive every interchange format.",
            "missing_media_status": "Resolve status fields vary; the kernel combines status text with local file existence when a file path is readable.",
        },
        "unsupported": {
            "semantic_conform_decisions": "The public API does not decide creative conform intent; it can expose differences and relink candidates.",
            "transition_roundtrip_guarantee": "Transition internals are not fully inspectable through the public timeline item API.",
            "automatic_user_media_relink": "Relinking user media is not automatic. Plans are read-only unless the caller explicitly uses the existing safe relink API.",
        },
        "export_aliases": {
            name: {"type": values[0], "subtype": values[1], "extension": values[2]}
            for name, values in _TIMELINE_EXPORT_ALIASES.items()
        },
    }

def _timeline_item_conform_summary(item, track_type: str, track_index: int, item_index: int):
    summary = _timeline_item_summary(item, (track_type, track_index)) or {}
    summary["item_index"] = item_index
    media_pool_item = _timeline_item_media_pool_item(item)
    file_path = None
    clip_properties = None
    media_status = None
    if media_pool_item:
        try:
            clip_properties = _ser(media_pool_item.GetClipProperty(""))
        except Exception:
            clip_properties = None
        if isinstance(clip_properties, dict):
            file_path = clip_properties.get("File Path") or clip_properties.get("FilePath")
            for key in ("Status", "Media Status", "Offline", "Online Status"):
                if key in clip_properties:
                    media_status = clip_properties.get(key)
                    break
    summary["file_path"] = file_path
    summary["file_exists"] = bool(file_path and os.path.exists(str(file_path)))
    summary["media_status"] = media_status
    if clip_properties is not None:
        summary["clip_properties"] = clip_properties
    return summary

def _timeline_conform_snapshot(tl, p: Optional[Dict[str, Any]] = None):
    p = p or {}
    include_markers = bool(p.get("include_markers", True))
    include_clip_properties = bool(p.get("include_clip_properties", False))
    track_types = p.get("track_types") or ["video", "audio", "subtitle"]
    if not isinstance(track_types, list):
        return _err("track_types must be a list")
    tracks = {}
    item_count = 0
    for track_type in track_types:
        try:
            track_count = int(tl.GetTrackCount(track_type) or 0)
        except Exception:
            track_count = 0
        track_rows = []
        for track_index in range(1, track_count + 1):
            items = []
            for item_index, item in enumerate(tl.GetItemListInTrack(track_type, track_index) or []):
                summary = _timeline_item_conform_summary(item, track_type, track_index, item_index)
                if not include_clip_properties:
                    summary.pop("clip_properties", None)
                items.append(summary)
            item_count += len(items)
            track_rows.append({
                "track_index": track_index,
                "item_count": len(items),
                "items": items,
            })
        tracks[track_type] = {"track_count": track_count, "tracks": track_rows}
    markers = {}
    if include_markers and _has_method(tl, "GetMarkers"):
        try:
            markers = _ser(tl.GetMarkers() or {})
        except Exception as exc:
            markers = {"error": str(exc)}
    return {
        "name": tl.GetName() or "",
        "id": tl.GetUniqueId(),
        "start_frame": tl.GetStartFrame(),
        "end_frame": tl.GetEndFrame(),
        "start_timecode": tl.GetStartTimecode(),
        "item_count": item_count,
        "tracks": tracks,
        "markers": markers,
    }

def _detect_gaps_overlaps_from_snapshot(snapshot: Dict[str, Any], p: Optional[Dict[str, Any]] = None):
    p = p or {}
    track_types = p.get("track_types") or ["video", "audio"]
    min_gap = int(p.get("min_gap", 1))
    gaps = []
    overlaps = []
    tracks = snapshot.get("tracks", {})
    for track_type in track_types:
        for track in (tracks.get(track_type, {}) or {}).get("tracks", []):
            items = sorted(
                [item for item in track.get("items", []) if item.get("start") is not None and item.get("end") is not None],
                key=lambda row: (row.get("start"), row.get("end")),
            )
            for prev, curr in zip(items, items[1:]):
                prev_end = int(prev["end"])
                curr_start = int(curr["start"])
                if curr_start - prev_end >= min_gap:
                    gaps.append({
                        "track_type": track_type,
                        "track_index": track.get("track_index"),
                        "start": prev_end,
                        "end": curr_start,
                        "duration": curr_start - prev_end,
                        "after": prev.get("timeline_item_id"),
                        "before": curr.get("timeline_item_id"),
                    })
                elif curr_start < prev_end:
                    overlaps.append({
                        "track_type": track_type,
                        "track_index": track.get("track_index"),
                        "start": curr_start,
                        "end": prev_end,
                        "duration": prev_end - curr_start,
                        "left": prev.get("timeline_item_id"),
                        "right": curr.get("timeline_item_id"),
                    })
    return {"gaps": gaps, "overlaps": overlaps, "gap_count": len(gaps), "overlap_count": len(overlaps)}

def _source_ranges_from_snapshot(snapshot: Dict[str, Any], p: Optional[Dict[str, Any]] = None):
    p = p or {}
    handles = int(p.get("handles", 0))
    merge = bool(p.get("merge", True))
    ranges: Dict[str, List[List[int]]] = {}
    occurrences = []
    for track_type, type_payload in (snapshot.get("tracks") or {}).items():
        if track_type == "subtitle":
            continue
        for track in type_payload.get("tracks", []):
            for item in track.get("items", []):
                source_start = item.get("source_start")
                source_end = item.get("source_end")
                if source_start is None or source_end is None:
                    continue
                key = item.get("file_path") or item.get("media_pool_item_name") or item.get("name") or "unknown"
                start = max(0, int(source_start) - handles)
                end = int(source_end) + handles
                ranges.setdefault(key, []).append([start, end])
                occurrences.append({
                    "key": key,
                    "track_type": track_type,
                    "track_index": track.get("track_index"),
                    "timeline_item_id": item.get("timeline_item_id"),
                    "timeline_range": [item.get("start"), item.get("end")],
                    "source_range": [start, end],
                })
    if merge:
        for key, key_ranges in list(ranges.items()):
            ordered = sorted(key_ranges)
            merged = []
            for start, end in ordered:
                if not merged or start > merged[-1][1]:
                    merged.append([start, end])
                else:
                    merged[-1][1] = max(merged[-1][1], end)
            ranges[key] = merged
    return {"ranges": ranges, "occurrences": occurrences, "handles": handles, "merged": merge}

def _story_spine_from_snapshot(snapshot: Dict[str, Any]) -> Dict[str, Any]:
    from src.domains.review_annotation.actions import _timeline_marker_rows_from_snapshot
    markers = _timeline_marker_rows_from_snapshot(snapshot)
    tracks = snapshot.get("tracks") or {}
    track_summaries = []
    for track_type in ("video", "audio", "subtitle"):
        for track in ((tracks.get(track_type) or {}).get("tracks") or []):
            items = track.get("items") or []
            if not items:
                continue
            starts = [item.get("start") for item in items if item.get("start") is not None]
            ends = [item.get("end") for item in items if item.get("end") is not None]
            track_summaries.append({
                "track_type": track_type,
                "track_index": track.get("track_index"),
                "item_count": len(items),
                "first_frame": min(starts) if starts else None,
                "last_frame": max(ends) if ends else None,
                "items": [
                    {
                        "timeline_item_id": item.get("timeline_item_id"),
                        "name": item.get("name"),
                        "start": item.get("start"),
                        "end": item.get("end"),
                        "source_range": [item.get("source_start"), item.get("source_end")],
                        "media_pool_item_name": item.get("media_pool_item_name"),
                    }
                    for item in items
                ],
            })
    named_beats = [
        {
            "frame": marker.get("frame"),
            "name": marker.get("name"),
            "note": marker.get("note"),
            "color": marker.get("color"),
        }
        for marker in markers
    ]
    audio_items = sum(row["item_count"] for row in track_summaries if row["track_type"] == "audio")
    video_items = sum(row["item_count"] for row in track_summaries if row["track_type"] == "video")
    return {
        "timeline": {
            "name": snapshot.get("name"),
            "id": snapshot.get("id"),
            "start_frame": snapshot.get("start_frame"),
            "end_frame": snapshot.get("end_frame"),
            "start_timecode": snapshot.get("start_timecode"),
        },
        "marker_count": len(markers),
        "beats": named_beats,
        "track_summaries": track_summaries,
        "source_ranges": _source_ranges_from_snapshot(snapshot, {"handles": 0, "merge": True}),
        "audio_spine": {
            "present": audio_items > 0,
            "audio_item_count": audio_items,
            "video_item_count": video_items,
            "marker_guided": len(markers) > 0,
        },
        "editorial_notes": [
            "Use marker beats as intent, not proof; verify important beats with Resolve-rendered thumbnails.",
            "For short-form variants, preserve a clear audio spine before adding visual variety.",
            "Run detect_gaps_overlaps after creating or changing a variant.",
        ],
    }

def _timeline_export_value(value, resolve_obj=None):
    raw = str(value or "").strip()
    if not raw:
        return "", None
    const_name = raw if raw.startswith("EXPORT_") else None
    if const_name and resolve_obj is not None and hasattr(resolve_obj, const_name):
        return getattr(resolve_obj, const_name), const_name
    if const_name:
        return const_name, const_name
    return raw, None

def _timeline_export_spec(p: Dict[str, Any], resolve_obj=None):
    requested = p.get("format") or p.get("type") or p.get("export_type") or "fcpxml"
    key = str(requested).strip().lower().replace("-", "_").replace(" ", "_")
    alias = _TIMELINE_EXPORT_ALIASES.get(key)
    if alias:
        type_name, subtype_name, ext = alias
    else:
        type_name = str(requested)
        subtype_name = p.get("subtype") or p.get("export_subtype") or "EXPORT_NONE"
        ext = p.get("extension") or ".timeline"
    if p.get("subtype") or p.get("export_subtype"):
        subtype_name = p.get("subtype") or p.get("export_subtype")
    export_type, export_type_name = _timeline_export_value(type_name, resolve_obj)
    export_subtype, export_subtype_name = _timeline_export_value(subtype_name, resolve_obj)
    return {
        "requested": requested,
        "export_type": export_type,
        "export_type_name": export_type_name or type_name,
        "export_subtype": export_subtype,
        "export_subtype_name": export_subtype_name or subtype_name,
        "extension": ext,
    }

def _export_timeline_checked(tl, p: Dict[str, Any]):
    from src.domains.render_deliver.actions import _render_temp_path_ok
    path = p.get("path")
    if not path:
        return _err("path is required")
    if p.get("require_temp_path", True) and not _render_temp_path_ok(path):
        return _err("path must be under the system temp directory unless require_temp_path=False")
    folder = os.path.dirname(os.path.abspath(path))
    if folder:
        os.makedirs(folder, exist_ok=True)
    # Resolve enum constants via get_resolve(), not the module global `resolve`
    # (which can be None and silently degrade the EXPORT_* args to strings — the
    # same failure class as issue #70).
    spec = _timeline_export_spec(p, get_resolve())
    if p.get("dry_run"):
        return _ok(path=path, would_export=True, spec={k: v for k, v in spec.items() if k != "export_type"})

    def _work():
        success = bool(tl.Export(path, spec["export_type"], spec["export_subtype"]))
        files = []
        primary_file = path
        if success and os.path.isdir(path):
            for dirpath, _, filenames in os.walk(path):
                for filename in filenames:
                    file_path = os.path.join(dirpath, filename)
                    files.append({"path": file_path, "size": os.path.getsize(file_path)})
            preferred_exts = (".fcpxml", ".xml", ".edl", ".drt", ".aaf", ".otio")
            for ext in preferred_exts:
                match = next((row["path"] for row in files if row["path"].lower().endswith(ext)), None)
                if match:
                    primary_file = match
                    break
        size = 0
        if success and os.path.exists(path):
            if os.path.isdir(path):
                size = sum(row["size"] for row in files)
            else:
                size = os.path.getsize(path)
        return {
            "success": success,
            "path": path,
            "primary_file": primary_file,
            "is_directory": bool(success and os.path.isdir(path)),
            "files": files,
            "size": size,
            "format": spec["requested"],
            "export_type": spec["export_type_name"],
            "export_subtype": spec["export_subtype_name"],
        }

    return _run_maybe_background("timeline.export_timeline_checked", p, _work)

def _timeline_media_coverage(tl) -> Dict[str, Any]:
    """Count how many timeline items are linked to a Media Pool Item vs. offline.

    An FCP7/FCPXML imported timeline whose media did not link has items with no
    backing Media Pool Item — this surfaces that honestly instead of claiming a
    clean import.
    """
    total = 0
    linked = 0
    for track_type in ("video", "audio"):
        try:
            count = int(tl.GetTrackCount(track_type) or 0)
        except Exception:
            count = 0
        for i in range(1, count + 1):
            for item in (tl.GetItemListInTrack(track_type, i) or []):
                total += 1
                try:
                    if item.GetMediaPoolItem():
                        linked += 1
                except Exception:
                    pass
    return {"total": total, "linked": linked, "offline": total - linked}

def _binary_post_import_relink(tl, mp, search_roots):
    """Fuzzy-relink parity for binary interchange (AAF): after import, ask Resolve's media pool
    to relink the timeline's Media Pool Items against each search root. This is the media-pool
    analogue of the XML path-rewrite relink (which can't run on a binary file)."""
    from src.domains.media_pool_ingest.actions import _collect_media_pool_items
    roots = [r for r in (search_roots or []) if isinstance(r, str) and os.path.isdir(r)]
    if not roots:
        return {"attempted": False, "reason": "no existing search roots", "roots": search_roots or []}
    items = _collect_media_pool_items(tl)
    if not items:
        return {"attempted": False, "reason": "no Media Pool Items to relink", "roots": roots}
    before = _timeline_media_coverage(tl)
    calls = []
    for root in roots:
        try:
            ok = bool(mp.RelinkClips(items, root))
            calls.append({"root": root, "ok": ok})
        except Exception as e:
            calls.append({"root": root, "ok": False, "error": str(e)})
    after = _timeline_media_coverage(tl)
    return {
        "attempted": True,
        "roots": roots,
        "item_count": len(items),
        "calls": calls,
        "before": before,
        "after": after,
        "linked_delta": after["linked"] - before["linked"],
    }

def _import_timeline_checked(proj, mp, p: Dict[str, Any]):
    from src.domains.render_deliver.actions import _render_temp_path_ok
    path = p.get("path")
    if not path:
        return _err("path is required")
    if not os.path.exists(path):
        return _err(f"path does not exist: {path}")
    ext = os.path.splitext(path)[1].lower()
    if ext == ".prproj":
        return _err(_PRPROJ_REFUSAL, category="invalid_input")
    if p.get("verify_visually") or p.get("reference_movie") or p.get("verify_threshold") is not None:
        return _err(_VISUAL_VERIFY_REFUSAL, category="invalid_input")
    # AAF (and any binary interchange) is read natively by Resolve. The XML
    # sanitize/relink path parses the file as text, so it must be SKIPPED for AAF
    # even when sanitize_media / relink_search_roots is passed; fuzzy XML relink is
    # N/A (media links through the media pool). We still detect the created
    # (possibly offline) timeline via the before/after id diff.
    is_binary = ext in _BINARY_INTERCHANGE_EXTS
    # sanitize_media (alias: relink_media) rewrites the XML to drop clipitems that
    # reference missing media or are generators (slug/solid w/ no pathurl) — both
    # abort Resolve's scripting-API import and leave the timeline fully offline.
    # The original is only read; the sanitized copy lands in a temp dir, so the
    # temp-path guard never applies to it.
    sanitize_requested = bool(p.get("sanitize_media") or p.get("relink_media"))
    binary_relink_note = None
    _binary_has_roots = bool(p.get("relink_search_roots") or p.get("search_roots"))
    if is_binary and _binary_has_roots:
        binary_relink_note = (
            f"XML path-rewrite relink is N/A for {ext} (binary) — imported as-is, then relinked "
            "via the media pool against the search roots (see `relink`)."
        )
    elif is_binary and sanitize_requested:
        binary_relink_note = (
            f"sanitize_media is N/A for {ext} (binary) — Resolve reads it natively and media "
            "relinks via the media pool. Imported the file as-is; pass relink_search_roots to "
            "auto-relink after import."
        )
    sanitize = sanitize_requested and not is_binary
    if not sanitize and p.get("require_temp_path", True) and not _render_temp_path_ok(path):
        return _err(
            "path must be under the system temp directory unless require_temp_path=False",
            remediation="Pass require_temp_path=False to import from this location, or "
                        "sanitize_media=True to rewrite the XML for reliable media linking.",
        )
    options = dict(p.get("options") or {})
    if p.get("timeline_name") and "timelineName" not in options:
        options["timelineName"] = p["timeline_name"]
    if "import_source_clips" in p and "importSourceClips" not in options:
        options["importSourceClips"] = bool(p["import_source_clips"])

    # Optional fuzzy relink: when search roots are given, missing-at-original-path
    # clips are matched against on-disk media (exact/ext-agnostic/normalized/reel)
    # and their pathurl rewritten so they relink instead of being dropped.
    search_roots = p.get("relink_search_roots") or p.get("search_roots")
    if isinstance(search_roots, str):
        search_roots = [search_roots]
    if search_roots and not sanitize and not is_binary:
        sanitize = True  # relinking is meaningless without the sanitize/rewrite pass

    sanitize_report = None
    import_path = path
    if sanitize:
        san_kwargs = {}
        if search_roots:
            san_kwargs["search_roots"] = list(search_roots)
            if p.get("relink_min_confidence") is not None:
                san_kwargs["min_confidence"] = float(p["relink_min_confidence"])
        try:
            sres = sanitize_timeline_xml(path, **san_kwargs)
        except Exception as e:
            return _err(f"Failed to sanitize timeline XML: {e}",
                        category="invalid_input")
        import_path = sres["output_path"]
        sanitize_report = {
            k: sres[k] for k in (
                "output_path", "timeline_name", "clip_total", "kept",
                "removed_total", "missing_media_count", "generator_count",
                "missing_media", "generators", "relinked_count", "relinked",
                "ambiguous_count", "ambiguous", "scan",
            ) if k in sres
        }

    if p.get("dry_run"):
        out = _ok(path=path, import_path=import_path, options=options, would_import=True)
        if sanitize_report is not None:
            out["sanitize"] = sanitize_report
        if binary_relink_note:
            out["note"] = binary_relink_note
        return out

    def _work():
        before_ids = set()
        for index in range(1, int(proj.GetTimelineCount() or 0) + 1):
            tl_existing = proj.GetTimelineByIndex(index)
            if tl_existing:
                before_ids.add(str(tl_existing.GetUniqueId()))
        imported = mp.ImportTimelineFromFile(import_path, options)

        # Resolve's API returns None even when it created an (offline) timeline. Detect
        # the newly-created timeline via the before/after id diff so we never report a
        # false "Failed to import" for what is really a partial success.
        api_returned_object = bool(imported)
        if not imported:
            for index in range(1, int(proj.GetTimelineCount() or 0) + 1):
                t = proj.GetTimelineByIndex(index)
                if t and str(t.GetUniqueId()) not in before_ids:
                    imported = t
        if not imported:
            if is_binary:
                remediation = (
                    f"Resolve created no timeline from this {ext}. Verify it exports/opens in "
                    "Resolve directly, or convert to FCP7 XML / FCPXML upstream and import that."
                )
            elif sanitize:
                remediation = None
            else:
                remediation = (
                    "This XML may reference missing media or contain generator clips, which "
                    "abort the scripting-API import. Retry with sanitize_media=True."
                )
            return _err(
                "Failed to import timeline (Resolve created no timeline)",
                remediation=remediation,
            )

        imported_id = str(imported.GetUniqueId())
        media = _timeline_media_coverage(imported)
        # AAF fuzzy-relink parity: when search roots are given for a binary import, relink through
        # the media pool after import (the XML path-rewrite relink can't run on a binary file).
        relink_result = None
        if is_binary and search_roots:
            relink_result = _binary_post_import_relink(imported, mp, search_roots)
            if relink_result.get("after"):
                media = relink_result["after"]
        out = _ok(
            name=imported.GetName(),
            id=imported_id,
            created_new=imported_id not in before_ids,
            timeline_count=proj.GetTimelineCount(),
            api_returned_object=api_returned_object,
            media=media,
        )
        if sanitize_report is not None:
            out["sanitize"] = sanitize_report
        if relink_result is not None:
            out["relink"] = relink_result
        if binary_relink_note:
            out["note"] = binary_relink_note
        if media["total"] and media["offline"]:
            msg = f"{media['offline']} of {media['total']} timeline items are offline (no linked media)."
            if is_binary:
                msg += (" Relink via the media pool (right-click → Relink Clips) or point Resolve "
                        "at the media roots — AAF media links there, not by rewriting the file.")
            elif not sanitize:
                msg += (" Retry with sanitize_media=True to drop missing-media/generator "
                        "clips so the remaining media links automatically.")
            out["warning"] = msg
        return out

    return _run_maybe_background("timeline.import_timeline_checked", p, _work)

def _drp_seq_containers(zf) -> List[Dict[str, Any]]:
    """List a .drp/.drt zip's SeqContainers as [{entry, name, index}] (0-based, sorted)."""
    entries = sorted(n for n in zf.namelist() if not n.endswith("/") and _SEQ_CONTAINER_RE.search(n))
    out = []
    for index, entry in enumerate(entries):
        try:
            xml = zf.read(entry).decode("utf-8", "replace")
        except Exception:
            xml = ""
        m = re.search(r"<Name>([\s\S]*?)</Name>", xml)
        out.append({"entry": entry, "name": (m.group(1).strip() if m else None), "index": index})
    return out

def _extract_seqcontainer_from_drp(drp_path: str, seq_entry: str, out_path: str) -> None:
    """Write a minimal .drt (zip) holding one SeqContainer as Primary1/SeqContainer1.xml."""

    with zipfile.ZipFile(drp_path, "r") as zf:
        xml = zf.read(seq_entry)
    with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED) as out:
        out.writestr("Primary1/SeqContainer1.xml", xml)
        out.writestr(
            "metadata.json",
            json.dumps(
                {
                    "source": "import_from_drp",
                    "sourceDrp": drp_path,
                    "sourceSeqContainer": seq_entry,
                    "exportedFrom": "davinci-resolve-mcp timeline.import_from_drp",
                },
                indent=2,
            ),
        )

def _import_from_drp(proj, mp, p: Dict[str, Any]):
    """
    Extract the chosen timelines from a .drp (offline zip surgery) and import each into the
    running Resolve. Requires Resolve open. Mirrors: drt.extract_from_drp → import_timeline_checked,
    but as one call returning per-timeline results.
    """

    drp_path = p.get("drpPath") or p.get("drp_path") or p.get("path")
    if not drp_path:
        return _err("drpPath is required")
    if not os.path.exists(drp_path):
        return _err(f"drpPath does not exist: {drp_path}")
    ext = os.path.splitext(drp_path)[1].lower()
    if ext == ".prproj":
        return _err(_PRPROJ_REFUSAL, category="invalid_input")

    try:
        with zipfile.ZipFile(drp_path, "r") as zf:
            containers = _drp_seq_containers(zf)
    except zipfile.BadZipFile:
        return _err(f"Not a valid .drp/.drt (not a zip archive): {drp_path}", category="invalid_input")
    if not containers:
        return _err(f"No SeqContainer entries found in {drp_path} — is this a .drp/.drt?", category="invalid_input")

    # Selection: by name(s), by 0-based index(es), or ALL when neither is given.
    want_names = p.get("timelineNames") or p.get("timeline_names")
    if isinstance(want_names, str):
        want_names = [want_names]
    want_indexes = p.get("timelineIndexes") or p.get("timeline_indexes")
    if isinstance(want_indexes, int):
        want_indexes = [want_indexes]

    selected: List[Dict[str, Any]] = []
    available = [{"name": c["name"], "index": c["index"]} for c in containers]
    if want_names:
        by_name = {}
        for c in containers:
            if c["name"]:
                by_name.setdefault(c["name"], c)
        for nm in want_names:
            c = by_name.get(nm)
            if not c:
                return _err(
                    f"Timeline named {nm!r} not found in .drp",
                    remediation=f"Available: {[a['name'] for a in available]}",
                    category="invalid_input",
                )
            selected.append(c)
    elif want_indexes:
        for i in want_indexes:
            match = next((c for c in containers if c["index"] == int(i)), None)
            if not match:
                return _err(f"timelineIndex {i} out of range (0..{len(containers) - 1})", category="invalid_input")
            selected.append(match)
    else:
        selected = list(containers)

    # Per-timeline options passthrough (importSourceClips etc.) minus selection
    # keys; background is a top-level option, so each sub-step import runs
    # synchronously and the loop can verify it.
    base = {
        k: v
        for k, v in p.items()
        if k not in ("drpPath", "drp_path", "path", "timelineNames", "timeline_names", "timelineIndexes", "timeline_indexes", "dry_run", "background", "async_job")
    }

    tmp_dir = tempfile.mkdtemp(prefix="drp_import_")
    results = []
    imported_count = 0
    for c in selected:
        safe = re.sub(r"[^A-Za-z0-9._-]+", "_", c["name"] or f"seq{c['index'] + 1}")
        drt_path = os.path.join(tmp_dir, f"{c['index'] + 1}_{safe}.drt")
        entry = {"requested": c["name"], "index": c["index"]}
        try:
            _extract_seqcontainer_from_drp(drp_path, c["entry"], drt_path)
        except Exception as e:
            entry.update(success=False, error=f"extract failed: {e}")
            results.append(entry)
            continue
        if p.get("dry_run"):
            entry.update(success=True, would_import=True, drt_path=drt_path)
            results.append(entry)
            continue
        sub = dict(base)
        sub["path"] = drt_path
        # .drt lives under a temp dir; the temp-path guard passes regardless.
        res = _import_timeline_checked(proj, mp, sub)
        ok = bool(res.get("success"))
        entry.update(res)
        if ok:
            imported_count += 1
        results.append(entry)

    return _ok(
        drpPath=drp_path,
        selected=len(selected),
        imported=imported_count,
        available=available,
        results=results,
        dry_run=bool(p.get("dry_run")),
    )

def _timeline_identity(tl, index: Optional[int] = None) -> Dict[str, Any]:
    payload = {
        "name": tl.GetName() if tl else None,
        "id": tl.GetUniqueId() if tl else None,
    }
    if index is not None:
        payload["index"] = index
    return payload

def _compare_timeline_snapshots(left: Dict[str, Any], right: Dict[str, Any]):
    differences = []
    left_tracks = left.get("tracks", {})
    right_tracks = right.get("tracks", {})
    for track_type in sorted(set(left_tracks) | set(right_tracks)):
        left_type = left_tracks.get(track_type, {})
        right_type = right_tracks.get(track_type, {})
        if left_type.get("track_count", 0) != right_type.get("track_count", 0):
            differences.append({
                "kind": "track_count",
                "track_type": track_type,
                "left": left_type.get("track_count", 0),
                "right": right_type.get("track_count", 0),
            })
        left_track_map = {row.get("track_index"): row for row in left_type.get("tracks", [])}
        right_track_map = {row.get("track_index"): row for row in right_type.get("tracks", [])}
        for track_index in sorted(set(left_track_map) | set(right_track_map)):
            left_items = left_track_map.get(track_index, {}).get("items", [])
            right_items = right_track_map.get(track_index, {}).get("items", [])
            if len(left_items) != len(right_items):
                differences.append({
                    "kind": "item_count",
                    "track_type": track_type,
                    "track_index": track_index,
                    "left": len(left_items),
                    "right": len(right_items),
                })
            for item_index, (left_item, right_item) in enumerate(zip(left_items, right_items)):
                fields = ["name", "start", "end", "source_start", "source_end", "media_pool_item_name"]
                changed = {
                    field: {"left": left_item.get(field), "right": right_item.get(field)}
                    for field in fields
                    if left_item.get(field) != right_item.get(field)
                }
                if changed:
                    differences.append({
                        "kind": "item_mismatch",
                        "track_type": track_type,
                        "track_index": track_index,
                        "item_index": item_index,
                        "changes": changed,
                    })
    return {"match": len(differences) == 0, "difference_count": len(differences), "differences": differences}

def _compare_timelines(proj, tl, p: Dict[str, Any]):
    if isinstance(p.get("left_snapshot"), dict) and isinstance(p.get("right_snapshot"), dict):
        left = p["left_snapshot"]
        right = p["right_snapshot"]
    else:
        right_tl, err = _timeline_by_selector(proj, p, prefix="right")
        if err:
            return err
        left = _timeline_conform_snapshot(tl, p)
        right = _timeline_conform_snapshot(right_tl, p)
    return {"left": {"name": left.get("name"), "id": left.get("id")}, "right": {"name": right.get("name"), "id": right.get("id")}, **_compare_timeline_snapshots(left, right)}

def _probe_interchange_roundtrip(proj, mp, tl, p: Dict[str, Any]):
    from src.domains.render_deliver.actions import _render_temp_path_ok
    output_dir = p.get("output_dir") or tempfile.mkdtemp(prefix="mcp_conform_roundtrip_")
    if p.get("require_temp_path", True) and not _render_temp_path_ok(output_dir):
        return _err("output_dir must be under the system temp directory unless require_temp_path=False")
    os.makedirs(output_dir, exist_ok=True)
    spec = _timeline_export_spec(p, get_resolve())
    base_name = p.get("name") or f"roundtrip_{str(spec['requested']).lower()}"
    path = p.get("path") or os.path.join(output_dir, base_name + spec["extension"])
    # background is a top-level option; a sub-step export must run synchronously.
    export_result = _export_timeline_checked(tl, {**p, "path": path, "require_temp_path": p.get("require_temp_path", True), "background": False, "async_job": False})
    if export_result.get("error") or not export_result.get("success"):
        return {"success": False, "stage": "export", "export": export_result}
    import_path = export_result.get("primary_file") or export_result.get("path") or path
    import_options = dict(p.get("import_options") or {})
    requested_key = str(spec["requested"]).lower()
    if "drt" not in requested_key:
        import_options.setdefault("timelineName", p.get("imported_timeline_name", f"{tl.GetName()} {spec['requested']} Roundtrip"))
        import_options.setdefault("importSourceClips", bool(p.get("import_source_clips", False)))
    import_result = _import_timeline_checked(
        proj,
        mp,
        {
            "path": import_path,
            "options": import_options,
            "require_temp_path": p.get("require_temp_path", True),
        },
    )
    if import_result.get("error") or not import_result.get("success"):
        return {"success": False, "stage": "import", "export": export_result, "import": import_result}
    imported_tl = None
    if import_result.get("id"):
        imported_tl, _ = _timeline_by_selector(proj, {"right_timeline_id": import_result["id"]}, prefix="right")
    comparison = None
    if imported_tl:
        comparison = _compare_timeline_snapshots(_timeline_conform_snapshot(tl, p), _timeline_conform_snapshot(imported_tl, p))
    cleanup_result = None
    if p.get("cleanup_imported", True) and imported_tl:
        cleanup_result = {"success": bool(mp.DeleteTimelines([imported_tl]))}
    return {
        "success": True,
        "format": spec["requested"],
        "path": path,
        "export": export_result,
        "import": import_result,
        "comparison": comparison,
        "cleanup": cleanup_result,
    }

def _missing_media_diagnosis(missing_rows: List[Dict[str, Any]]) -> Dict[str, Any]:
    from src.domains.media_pool_ingest.actions import _media_path_volume_root, _sanitize_media_path
    by_media_pool_item: Dict[str, Dict[str, Any]] = {}
    missing_volumes: Dict[str, Dict[str, Any]] = {}
    missing_folders: Dict[str, Dict[str, Any]] = {}

    for row in missing_rows:
        file_path = row.get("file_path")
        media_pool_item_id = row.get("media_pool_item_id") or file_path or row.get("name")
        basename = os.path.basename(str(file_path or row.get("media_pool_item_name") or row.get("name") or ""))
        item = by_media_pool_item.setdefault(
            str(media_pool_item_id),
            {
                "media_pool_item_id": row.get("media_pool_item_id"),
                "media_pool_item_name": row.get("media_pool_item_name") or row.get("name"),
                "wanted_basename": basename,
                "file_path_sanitized": _sanitize_media_path(file_path),
                "volume_root_sanitized": _sanitize_media_path(_media_path_volume_root(file_path), keep_filename=False),
                "timeline_occurrence_count": 0,
                "track_refs": [],
            },
        )
        item["timeline_occurrence_count"] += 1
        item["track_refs"].append(
            {
                "track_type": row.get("track_type"),
                "track_index": row.get("track_index"),
                "timeline_item_id": row.get("timeline_item_id"),
            }
        )

        volume_root = _media_path_volume_root(file_path)
        if volume_root:
            volume_row = missing_volumes.setdefault(
                volume_root,
                {
                    "volume_root_sanitized": _sanitize_media_path(volume_root, keep_filename=False),
                    "mounted": os.path.isdir(volume_root),
                    "clip_count": 0,
                    "sample_basenames": [],
                },
            )
            volume_row["clip_count"] += 1
            if basename and basename not in volume_row["sample_basenames"] and len(volume_row["sample_basenames"]) < 8:
                volume_row["sample_basenames"].append(basename)

        folder = os.path.dirname(str(file_path)) if file_path else ""
        if folder:
            folder_row = missing_folders.setdefault(
                folder,
                {
                    "folder_sanitized": _sanitize_media_path(folder, keep_filename=False),
                    "exists": os.path.isdir(folder),
                    "clip_count": 0,
                    "sample_basenames": [],
                },
            )
            folder_row["clip_count"] += 1
            if basename and basename not in folder_row["sample_basenames"] and len(folder_row["sample_basenames"]) < 8:
                folder_row["sample_basenames"].append(basename)

    unique_items = list(by_media_pool_item.values())
    missing_volume_rows = list(missing_volumes.values())
    missing_folder_rows = list(missing_folders.values())
    absent_volumes = [row for row in missing_volume_rows if not row.get("mounted")]
    absent_folders = [row for row in missing_folder_rows if not row.get("exists")]
    primary_cause = "none"
    recommended_next_step = "No offline media detected."
    if absent_volumes:
        primary_cause = "volume_not_mounted"
        labels = ", ".join(row["volume_root_sanitized"] for row in absent_volumes[:3])
        recommended_next_step = f"Mount the missing volume(s): {labels}."
    elif absent_folders:
        primary_cause = "folder_not_found"
        labels = ", ".join(row["folder_sanitized"] for row in absent_folders[:3])
        recommended_next_step = f"Attach or locate the missing media folder(s): {labels}."
    elif unique_items:
        primary_cause = "files_missing_or_renamed"
        recommended_next_step = "Search approved media roots for the wanted basenames, then relink with media_pool.safe_relink."

    return {
        "unique_media_pool_item_count": len(unique_items),
        "timeline_occurrence_count": len(missing_rows),
        "primary_cause": primary_cause,
        "recommended_next_step": recommended_next_step,
        "missing_volumes": missing_volume_rows,
        "missing_folders": missing_folder_rows,
        "unique_media_pool_items": unique_items,
        "sanitized": True,
    }

def _detect_missing_media_from_snapshot(snapshot: Dict[str, Any]):
    missing = []
    present = []
    for track_type, type_payload in (snapshot.get("tracks") or {}).items():
        for track in type_payload.get("tracks", []):
            for item in track.get("items", []):
                file_path = item.get("file_path")
                status_text = str(item.get("media_status") or "").lower()
                exists = bool(file_path and os.path.exists(str(file_path)))
                is_missing = bool(file_path and not exists) or any(token in status_text for token in ("offline", "missing"))
                row = {
                    "track_type": track_type,
                    "track_index": track.get("track_index"),
                    "timeline_item_id": item.get("timeline_item_id"),
                    "media_pool_item_id": item.get("media_pool_item_id"),
                    "name": item.get("name"),
                    "media_pool_item_name": item.get("media_pool_item_name"),
                    "file_path": file_path,
                    "file_exists": exists,
                    "media_status": item.get("media_status"),
                }
                if is_missing:
                    missing.append(row)
                else:
                    present.append(row)
    diagnosis = _missing_media_diagnosis(missing)
    return {
        "missing": missing,
        "present_count": len(present),
        "missing_count": len(missing),
        "diagnosis": diagnosis,
    }

def _detect_missing_media(tl, p: Dict[str, Any]):
    from src.domains.media_pool_ingest.actions import _sanitize_media_path
    snapshot = _timeline_conform_snapshot(tl, {**p, "include_clip_properties": True})
    report = _detect_missing_media_from_snapshot(snapshot)
    if p.get("sanitize_paths") or p.get("sanitized"):
        report = dict(report)
        report["missing"] = [
            {
                **row,
                "file_path_sanitized": _sanitize_media_path(row.get("file_path")),
                "file_path": None if p.get("omit_raw_paths", True) else row.get("file_path"),
            }
            for row in report.get("missing", [])
        ]
    return report

def _build_relink_plan(tl, p: Dict[str, Any]):
    from src.domains.media_pool_ingest.actions import _bounded_basename_matches, _sanitize_media_path
    search_roots = p.get("search_roots") or p.get("roots") or []
    if not isinstance(search_roots, list) or not search_roots:
        return _err("search_roots must be a non-empty list")
    invalid = [root for root in search_roots if not isinstance(root, str) or not os.path.isdir(root)]
    if invalid:
        return _err(f"search_roots must be existing directories: {invalid}")
    missing_report = _detect_missing_media(tl, p)
    diagnosis = missing_report.get("diagnosis") or _missing_media_diagnosis(missing_report.get("missing", []))
    if p.get("skip_search_when_volume_missing", True) and any(
        not row.get("mounted") for row in diagnosis.get("missing_volumes", [])
    ):
        return {
            "success": True,
            "dry_run": True,
            "search_skipped": True,
            "skip_reason": "missing_source_volume_not_mounted",
            "search_roots": [_sanitize_media_path(root, keep_filename=False) for root in search_roots],
            "candidate_count": 0,
            "missing_count": missing_report.get("missing_count", 0),
            "diagnosis": diagnosis,
            "candidates": [],
            "execution_note": "Mount the missing source volume or pass skip_search_when_volume_missing=false to scan approved roots.",
        }
    candidates = []
    rows_by_basename: Dict[str, List[Dict[str, Any]]] = {}
    for row in missing_report.get("missing", []):
        wanted = os.path.basename(str(row.get("file_path") or row.get("media_pool_item_name") or row.get("name") or ""))
        if wanted:
            rows_by_basename.setdefault(wanted, []).append(row)
    for wanted, rows in rows_by_basename.items():
        row = rows[0]
        matches = []
        scan = {"files_scanned": 0, "dirs_scanned": 0, "stopped_reason": None}
        if wanted:
            matches, scan = _bounded_basename_matches(wanted, search_roots, p)
        sanitized_matches = [_sanitize_media_path(path) for path in matches]
        candidates.append(
            {
                **row,
                "wanted_basename": wanted,
                "timeline_occurrence_count": len(rows),
                "candidate_paths": [] if p.get("sanitize_paths") or p.get("sanitized") else matches,
                "candidate_paths_sanitized": sanitized_matches,
                "candidate_count": len(matches),
                "scan": scan,
            }
        )
    return {
        "success": True,
        "dry_run": True,
        "search_roots": [] if p.get("sanitize_paths") or p.get("sanitized") else search_roots,
        "search_roots_sanitized": [_sanitize_media_path(root, keep_filename=False) for root in search_roots],
        "candidate_count": sum(1 for row in candidates if row["candidate_count"]),
        "missing_count": missing_report.get("missing_count", 0),
        "unique_missing_basename_count": len(candidates),
        "diagnosis": diagnosis,
        "candidates": candidates,
        "execution_note": "Review this plan, then use media_pool.safe_relink with explicit synthetic or approved paths if desired.",
    }

def _conform_boundary_report(tl, p: Dict[str, Any]):
    snapshot = _timeline_conform_snapshot(tl, p)
    return {
        "capabilities": _conform_capabilities(),
        "timeline": snapshot,
        "gaps_overlaps": _detect_gaps_overlaps_from_snapshot(snapshot, p),
        "source_ranges": _source_ranges_from_snapshot(snapshot, p),
        "missing_media": _detect_missing_media_from_snapshot(snapshot),
    }

def _compare_timeline_append_readback(before, observed, expected_count: int):
    before_count = before.get("item_count") if isinstance(before, dict) and before.get("available") else None
    after_count = observed.get("item_count") if isinstance(observed, dict) and observed.get("available") else None
    delta = after_count - before_count if before_count is not None and after_count is not None else None
    return {
        "verified": delta is not None and delta >= expected_count and expected_count > 0,
        "before_item_count": before_count,
        "after_item_count": after_count,
        "item_count_delta": delta,
        "expected_item_count_delta": expected_count,
    }


_TIMELINE_EXPORT_ALIASES = {
    "aaf": ("EXPORT_AAF", "EXPORT_AAF_NEW", ".aaf"),
    "drt": ("EXPORT_DRT", "EXPORT_NONE", ".drt"),
    "edl": ("EXPORT_EDL", "EXPORT_NONE", ".edl"),
    "edl_cdl": ("EXPORT_EDL", "EXPORT_CDL", ".edl"),
    "edl_sdl": ("EXPORT_EDL", "EXPORT_SDL", ".edl"),
    "edl_missing_clips": ("EXPORT_EDL", "EXPORT_MISSING_CLIPS", ".edl"),
    "fcp7xml": ("EXPORT_FCP_7_XML", "EXPORT_NONE", ".xml"),
    "fcpxml": ("EXPORT_FCPXML_1_10", "EXPORT_NONE", ".fcpxml"),
    "fcpxml_1_8": ("EXPORT_FCPXML_1_8", "EXPORT_NONE", ".fcpxml"),
    "fcpxml_1_9": ("EXPORT_FCPXML_1_9", "EXPORT_NONE", ".fcpxml"),
    "fcpxml_1_10": ("EXPORT_FCPXML_1_10", "EXPORT_NONE", ".fcpxml"),
    "otio": ("EXPORT_OTIO", "EXPORT_NONE", ".otio"),
}


_PRPROJ_REFUSAL = (
    "Resolve has no native .prproj importer (Premiere's project format is gzip-compressed "
    "XML, not an interchange). Two offline routes, no Premiere needed: (1) read it with the "
    "advanced MCP — editorial.list_sequences / editorial.parse_interchange (format 'prproj'); "
    "(2) convert it to an importable interchange — editorial.convert_to_interchange "
    "(target 'otio'|'edl'|'drt') — then import that here with import_timeline_checked. "
    "Editorial timing/cuts/transitions/speed carry over; per-clip effects/Lumetri color do not. "
    "Alternatively export FCP7 XML / AAF / FCPXML from Premiere and conform that."
)


_BINARY_INTERCHANGE_EXTS = {".aaf"}

# Relink here matches by NAME (see utils/timeline_xml.match_references). Confirming a
# relink is the right PICTURE means sampling frames and diffing them against a
# reference render — that engine lives on the advanced MCP, so we refuse the argument
# outright instead of accepting it and quietly not verifying anything.
_VISUAL_VERIFY_REFUSAL = (
    "Visual relink verification (verify_visually / reference_movie / verify_threshold) is not "
    "available on this server — relink here matches by name only, and `sanitize.relinked` "
    "reports the tier that matched (exact/case_insensitive/ext_agnostic/normalized) plus "
    "anything `ambiguous`. For frame-accurate confirmation use the advanced MCP's `conform` "
    "tool: relink_scalefix (repoint + scale-fix against real footage roots) and qc (per-cut "
    "frame diff vs a reference render -> MATCH/OFFSET/WRONG). Re-run without these arguments "
    "to relink by name."
)


_SEQ_CONTAINER_RE = re.compile(r"(^|/)SeqContainer(\d*\.xml|/[^/]+\.xml)$")
