"""Generated by the repo-restructure Phase 3 split (epic #52, #46).

Extracted from src/server.py; see src/core/CONTEXT.md or the matching domain
CONTEXT.md for what lives here and why.
"""
from __future__ import annotations

import base64
import os
import sys
import json
import logging
import math
import platform
import re
import shutil
import struct
import subprocess
import tempfile
import threading
import time
import zipfile
import zlib
from typing import Dict, Any, Optional, List, Tuple

from src.domains.color_grade.utils.cdl import normalize_cdl_payload
from src.core.mcp_stdio import run_fastmcp_stdio
from src.core.api_truth import lookup_api_truth, VERIFIED_ON as _API_TRUTH_VERIFIED_ON
from src.core.contracts import validate as _validate_params
from src.domains.project_lifecycle.utils.cloud_operations import cloud_sync_status_label
from src.domains.auto_edit.utils.cut_ir import build_cut_list as _build_cut_list
from src.core.page_lock import open_page_serialized as _open_page_serialized
from src.core.proc import preload_audit, resolve_spawn_env, safe_run, sanitized_spawn_env
from src.core.readback import verify_by_readback, verification_stats as _verification_stats
from src.core.update_check import (
    check_for_updates,
    clear_update_prompt_preferences,
    get_cached_update_status,
    get_update_channel,
    get_update_mode,
    ignore_update_version,
    set_update_mode,
    snooze_update_prompt,
    start_background_update_check,
    update_prompt_decision,
    update_state_path,
)
from src.domains.media_analysis.utils.caps_gating import (
    HOST_CHAT_PATHS_PROVIDER,
    HOST_CHAT_VISION_PROVIDERS,
    DEFAULT_VISION_ANALYSIS_PROMPT,
    VISION_SCHEMA_REFERENCE,
)
from src.domains.media_analysis.utils.clip_identity_registry import (
    resolve_output_root as resolve_media_analysis_output_root,
    short_hash,
    slugify,
)
from src.domains.media_analysis.utils.capabilities_and_planning import (
    build_plan as build_media_analysis_plan,
    detect_capabilities as detect_media_analysis_capabilities,
    install_guidance as media_analysis_install_guidance,
)
from src.domains.media_analysis.utils.execute_engine import (
    execute_plan_async as execute_media_analysis_plan_async,
    plan_requires_capabilities as media_analysis_plan_requires_capabilities,
)
from src.domains.media_analysis.utils.reports import (
    build_coverage_report as build_media_analysis_coverage_report,
    cleanup_artifacts as cleanup_media_analysis_artifacts,
    commit_visual_analysis,
    load_report as load_media_analysis_report,
    summarize_reports as summarize_media_analysis_reports,
)
from src.domains.media_analysis.utils.analysis_index_build import build_analysis_index
from src.domains.media_analysis.utils.analysis_index_query import (
    analysis_index_status,
    query_analysis_index,
)
from src.domains.media_analysis.utils.sync_detection import detect_sync_events_for_records as detect_media_sync_events
from src.core import actor_identity, background_jobs, resolve_busy
from src.core.resolve_busy import long_resolve_op
from src.domains.media_analysis.utils.media_analysis_jobs import (
    MEDIA_EXTENSIONS,
    batch_job_status as media_analysis_batch_job_status,
    cancel_batch_job as cancel_media_analysis_batch_job,
    create_batch_job as create_media_analysis_batch_job,
    list_batch_jobs as list_media_analysis_batch_jobs,
    resume_batch_job as resume_media_analysis_batch_job,
    run_batch_job_slice as run_media_analysis_batch_job_slice,
)
from src.core.platform import get_resolve_paths, get_resolve_plugin_paths
from src.domains.color_grade.utils.lut_paths import master_lut_dir, ensure_lut_in_master
from src.domains.extension_authoring.utils import fuse_templates, dctl_templates, script_templates
from src.domains.timeline_edit.utils.timeline_title_text import (
    candidate_title_property_keys as _candidate_title_property_keys,
    plain_to_minimal_styled_xml as _plain_to_minimal_styled_xml,
    timeline_item_get_property_map as _timeline_item_get_property_map,
)
from src.domains.media_pool_ingest.utils.multicam import build_multicam_setup_plan
from src.domains.timeline_conform_interchange.utils.timeline_xml import analyze_timeline_xml, sanitize_timeline_xml
from src.domains.fusion_composition.utils.fusion_group_settings import (
    FUSION_COMMIT_CHECKLIST,
    FUSION_GROUP_GUARDRAILS,
    default_backup_path,
    parse_setting_file,
    splice_inputs_block,
)
from src.core import analysis_runs as _analysis_runs
from src.core import brain_edits as _brain_edits
from src.domains.auto_edit.utils import edit_engine as _edit_engine_mod
from src.domains.auto_edit.utils import auto_edit as _auto_edit_mod
from src.domains.auto_edit.utils import montage_edit as _montage_edit_mod
from src.domains.orchestration.utils import orchestrate as _orchestrate_mod
from src.core import advanced_bridge as _advanced_bridge
from src.domains.auto_edit.utils import music_analysis as _music_analysis_mod
from src.domains.media_pool_ingest.utils import media_pool_changes as _media_pool_changes
from src.core import timeline_versioning as _timeline_versioning
from src.domains.project_lifecycle.utils import project_spec as _project_spec
from src.domains.project_lifecycle.utils import project_lint as _project_lint
from src.domains.timeline_edit.utils import clip_query as _clip_query
from src.core import destructive_hook as _destructive_hook
from src.core.destructive_hook import destructive_op as _destructive_op
import uuid as _ledger_uuid
from src.core import resolve_ai_ledger as _resolve_ai_ledger
from src.core import resolve_ai_governance as _resolve_ai_governance
import hashlib as _hashlib
import time as _time
import uuid as _uuid
from mcp.server.fastmcp import Context, FastMCP, Image
from mcp import types as mcp_types

logger = logging.getLogger("resolve-mcp")

from src.server import mcp

from src.core.envelope import (
    ERROR_CATEGORIES,
    _CATEGORY_RETRYABLE_DEFAULT,
    _RETRYABLE_UNSET,
    _callable_method_names,
    _check,
    _err,
    _has_method,
    _ok,
    _requires_method,
    _safe_clip_call,
    _safe_get_property,
    _ser,
    _unknown,
)
from src.core.tool_kernel import (
    _action_help,
    _activate_resolve_window,
    _ai_governance_check,
    _ai_governance_gate,
    _ai_governance_mode,
    _ai_governance_overrides,
    _ai_governance_preset,
    _ai_ledger_root,
    _ai_ledger_timed,
    _confirm_token_fingerprint,
    _confirm_token_gc,
    _confirm_token_required,
    _consume_confirm_token,
    _contact_sheet_png_bytes,
    _contact_sheet_sample_label,
    _draw_rect_rgb,
    _draw_tiny_text_rgb,
    _filter_to_keys,
    _find_timeline_item_by_id,
    _first_param,
    _has_any_param,
    _is_truncated,
    _issue_confirm_token,
    _media_analysis_effective_preferences,
    _normalize_sampling_mode_default,
    _normalize_setup_choice,
    _normalize_setup_list,
    _normalize_timed_marker_choice,
    _normalize_vision_default,
    _normalize_yes_no_ask,
    _opt_number,
    _path_error,
    _png_chunk,
    _read_json_strict,
    _read_media_analysis_preferences,
    _read_media_analysis_preferences_strict,
    _record_action_outcome,
    _resolve_enum_settings,
    _rgb_to_png_bytes,
    _run_maybe_background,
    _safe_int,
    _sampling_mode_choice_from_params,
    _send_resolve_keystroke_go_to_mark_in,
    _settings_diff,
    _setup_marker_limit,
    _setup_positive_int,
    _setup_text_key,
    _string_list_param,
    _thumbnail_data_to_png_bytes,
    _thumbnail_raw_rgb,
    _timed_marker_choice_from_params,
    _timeline_items_by_ids,
    _timeline_items_by_ids_report,
    _timeline_resolve_item_optional,
    _write_media_analysis_preferences,
)
from src.core.timeline_lookup import (
    _clip_file_size,
    _clip_name,
    _clip_summaries,
    _clips_from_params,
    _coerce_item_list,
    _collect_timeline_items_in_range,
    _current_timeline_frame_id,
    _find_clip,
    _find_clip_with_parent,
    _find_timeline_by_id,
    _find_timeline_by_name,
    _frame_id_to_timecode,
    _frame_int,
    _get_item,
    _get_mp,
    _get_selected_timeline_items,
    _get_tl,
    _metadata_write_field_for_field,
    _project_name_and_id,
    _project_summary,
    _range_frames_from_params,
    _range_track_indices,
    _range_track_types,
    _safe_timeline_item_id,
    _safe_timeline_item_name,
    _timecode_to_frame_id,
    _timeline_by_selector,
    _timeline_fps,
    _timeline_frame_id_to_timecode,
    _timeline_item_duration,
    _timeline_item_ids,
    _timeline_item_media_pool_item,
    _timeline_item_probe,
    _timeline_item_source_start,
    _timeline_item_summary,
    _timeline_item_track_info,
    _timeline_start_frame,
    _timeline_timecode_to_frame_id,
    _timeline_track_count,
    _track_items_sorted,
    _track_selector,
)
from src.core.live_connection import (
    get_resolve,
    _destructive_versioning_provider,
)

def _orchestrate_project_context(p: Dict[str, Any], *, need_resolve: bool = False):
    """(resolve, proj, project_root, err) — same contract as auto_edit's.

    Unlike auto_edit, orchestrate defaults to need_resolve=False: a job's
    record lives under an analysis root and start_job/job_status/list_jobs
    must work with Resolve closed (that's the whole point of resumability).
    """
    analysis_root = p.get("analysis_root") or p.get("analysisRoot")
    if analysis_root and not os.path.isdir(str(analysis_root)):
        return None, None, None, _err(
            f"analysis_root is not a directory: {str(analysis_root)!r}")
    explicit_root = str(analysis_root) if analysis_root else None
    if not need_resolve and explicit_root:
        return None, None, explicit_root, None
    vctx = _destructive_versioning_provider()
    if vctx is not None:
        r, proj, project_root, _name = vctx
        return r, proj, explicit_root or project_root, None
    if explicit_root:
        return None, None, explicit_root, None
    return None, None, None, _err(
        "No project context — open a Resolve project, or pass analysis_root."
    )

def _orchestrate_default_analysis_base_root(project_root: str) -> str:
    return os.path.dirname(os.path.normpath(project_root))

def _orchestrate_capture_fingerprint(proj) -> Dict[str, Any]:
    """Cheap coarse probe: {timeline_item_count, grade_version_id,
    media_path_set_hash}. Best-effort — a probe failure degrades to a null/
    empty component rather than raising, since a fingerprint mismatch is
    exactly how "couldn't tell" should read (refuse to resume, don't guess)."""
    timeline_item_count = 0
    grade_versions: List[str] = []
    try:
        tl = proj.GetCurrentTimeline()
    except Exception:
        tl = None
    if tl is not None:
        for track_type in ("video", "audio"):
            try:
                count = int(tl.GetTrackCount(track_type) or 0)
            except Exception:
                count = 0
            for i in range(1, count + 1):
                try:
                    items = tl.GetItemListInTrack(track_type, i) or []
                except Exception:
                    items = []
                timeline_item_count += len(items)
                if track_type == "video":
                    for item in items:
                        try:
                            version = item.GetCurrentVersion()
                            grade_versions.append(json.dumps(version, sort_keys=True, default=str))
                        except Exception:
                            pass
    grade_version_id = (
        _hashlib.sha256("|".join(sorted(grade_versions)).encode("utf-8")).hexdigest()[:16]
        if grade_versions else None
    )
    media_paths: List[str] = []
    try:
        mp = proj.GetMediaPool()
        root = mp.GetRootFolder() if mp else None
    except Exception:
        root = None
    if root is not None:
        stack = [root]
        while stack:
            folder = stack.pop()
            try:
                clips = folder.GetClipList() or []
            except Exception:
                clips = []
            for clip in clips:
                try:
                    path = clip.GetClipProperty("File Path")
                except Exception:
                    path = None
                if path:
                    media_paths.append(str(path))
            try:
                stack.extend(folder.GetSubFolderList() or [])
            except Exception:
                pass
    media_path_set_hash = _hashlib.sha256(
        "|".join(sorted(set(media_paths))).encode("utf-8")).hexdigest()[:16]
    return {
        "timeline_item_count": timeline_item_count,
        "grade_version_id": grade_version_id,
        "media_path_set_hash": media_path_set_hash,
    }

def _orchestrate_take_snapshot(proj, *, job_id: str, stage: str) -> Dict[str, Any]:
    """Live pre-stage snapshot per SNAPSHOT_KIND_BY_STAGE. Best-effort: a
    failed snapshot is reported, never raised — the caller decides whether to
    proceed without rollback cover."""
    kind = _orchestrate_mod.SNAPSHOT_KIND_BY_STAGE.get(stage)
    if not kind:
        return {"success": True, "kind": None, "snapshot_id": None,
                "note": f"stage {stage!r} needs no pre-stage snapshot"}
    label = _orchestrate_mod.snapshot_label(job_id, stage)
    if kind == "timeline_duplicate":
        try:
            tl = proj.GetCurrentTimeline()
            if tl is None:
                return {"success": False, "error": "no current timeline to snapshot"}
            dup = tl.DuplicateTimeline(label)
            if not dup:
                return {"success": False, "error": "DuplicateTimeline failed"}
            return {"success": True, "kind": kind, "snapshot_id": label}
        except Exception as exc:
            return {"success": False, "error": f"{type(exc).__name__}: {exc}"}
    if kind == "grade_version":
        try:
            tl = proj.GetCurrentTimeline()
            item = tl.GetCurrentVideoItem() if tl and hasattr(tl, "GetCurrentVideoItem") else None
            if item is None:
                items = tl.GetItemListInTrack("video", 1) if tl else []
                item = items[0] if items else None
            if item is None:
                return {"success": False, "error": "no video item to snapshot a grade version for"}
            ok = bool(item.AddVersion(label, 0))
            return {"success": ok, "kind": kind, "snapshot_id": label if ok else None}
        except Exception as exc:
            return {"success": False, "error": f"{type(exc).__name__}: {exc}"}
    return {"success": False, "error": f"unknown snapshot kind {kind!r}"}

def _orchestrate_gc_snapshots_live(proj, cleared: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Best-effort live deletion of GC'd snapshot artifacts. Never blocks gate
    approval on cleanup failure — same posture as destructive_hook's archive
    step: the user's forward progress must not depend on housekeeping."""
    deleted, failed = [], []
    duplicate_ids = {s["id"] for s in cleared if s.get("kind") == "timeline_duplicate"}
    if duplicate_ids:
        try:
            mp = proj.GetMediaPool()
            count = proj.GetTimelineCount()
            targets = []
            for i in range(1, int(count or 0) + 1):
                tl = proj.GetTimelineByIndex(i)
                if tl and tl.GetName() in duplicate_ids:
                    targets.append(tl)
            if targets and mp:
                mp.DeleteTimelines(targets)
                deleted.extend(t.GetName() for t in targets)
        except Exception as exc:
            failed.append(f"timeline_duplicate cleanup: {type(exc).__name__}: {exc}")
    for snap in cleared:
        if snap.get("kind") == "grade_version":
            try:
                tl = proj.GetCurrentTimeline()
                items = tl.GetItemListInTrack("video", 1) if tl else []
                for item in items:
                    try:
                        if item.DeleteVersionByName(snap["id"], 0):
                            deleted.append(snap["id"])
                            break
                    except Exception:
                        continue
            except Exception as exc:
                failed.append(f"grade_version cleanup: {type(exc).__name__}: {exc}")
    return {"deleted": deleted, "failed": failed}

def _orchestrate_restore_snapshot(proj, *, kind: str, snapshot_id: str) -> Dict[str, Any]:
    """Live restore for rollback_stage. timeline_duplicate: the snapshot
    timeline BECOMES current (the failed mutation's timeline is deleted) —
    no rename-back needed, so no bookkeeping has to track the pre-mutation
    name. grade_version: LoadVersion switches back without consuming the
    snapshot (it stays available for a second rollback if needed)."""
    if kind == "timeline_duplicate":
        try:
            count = proj.GetTimelineCount()
            snapshot_tl, current_tl = None, None
            try:
                current_tl = proj.GetCurrentTimeline()
            except Exception:
                current_tl = None
            for i in range(1, int(count or 0) + 1):
                tl = proj.GetTimelineByIndex(i)
                if tl and tl.GetName() == snapshot_id:
                    snapshot_tl = tl
                    break
            if snapshot_tl is None:
                return {"success": False, "error": f"snapshot timeline {snapshot_id!r} not found",
                        "consumed": False}
            if current_tl is not None and current_tl.GetUniqueId() != snapshot_tl.GetUniqueId():
                try:
                    mp = proj.GetMediaPool()
                    if mp:
                        mp.DeleteTimelines([current_tl])
                except Exception:
                    pass  # best-effort — the snapshot still becomes current below
            proj.SetCurrentTimeline(snapshot_tl)
            return {"success": True, "consumed": True}
        except Exception as exc:
            return {"success": False, "error": f"{type(exc).__name__}: {exc}", "consumed": False}
    if kind == "grade_version":
        try:
            tl = proj.GetCurrentTimeline()
            items = tl.GetItemListInTrack("video", 1) if tl else []
            for item in items:
                try:
                    if item.LoadVersionByName(snapshot_id, 0):
                        return {"success": True, "consumed": False}
                except Exception:
                    continue
            return {"success": False, "error": f"grade version {snapshot_id!r} not found on any item",
                    "consumed": False}
        except Exception as exc:
            return {"success": False, "error": f"{type(exc).__name__}: {exc}", "consumed": False}
    return {"success": False, "error": f"unknown snapshot kind {kind!r}", "consumed": False}

async def _orchestrate_plan_stage_talking_head(
    job: Dict[str, Any], job_id: str, project_root: str
) -> Dict[str, Any]:
    """Kick/poll auto_edit's start_brief -> plan_cut for the edit stage,
    recording the brief_id/plan_id foreign keys. Shared by the plan_stage
    action and run_stage("edit")/("analysis") for talking-head jobs — the
    only planner that exists in this phase."""
    from src.domains.auto_edit.actions import auto_edit
    brief = job.get("brief") or {}
    fks = (job["stages"]["edit"].get("foreign_keys") or {})
    # plan_id is checked first — it's further along the pipeline than
    # brief_id and implies a brief exists, so it's the authoritative
    # "already planned" signal regardless of what else foreign_keys holds.
    plan_id = fks.get("plan_id")
    if plan_id:
        summary = await auto_edit("get_cut_summary", {"plan_id": plan_id, "analysis_root": project_root})
        return {"success": True, "stage": "edit", "brief_id": fks.get("brief_id"), "plan_id": plan_id,
                "already_planned": True, **summary}
    brief_id = fks.get("brief_id")
    if not brief_id:
        started = await auto_edit("start_brief", {
            "files": brief.get("files"), "music": brief.get("music"),
            "target_duration_seconds": brief.get("target_duration_seconds"),
            "genre": brief.get("genre") or "talking_head", "deliverable": brief.get("deliverable"),
            "title_text": brief.get("title_text"), "analysis_root": project_root,
        })
        if not started.get("success"):
            return started
        _orchestrate_mod.set_stage_foreign_keys(
            project_root, job_id, "edit", brief_id=started["brief_id"])
        return {"success": True, "stage": "edit", "waiting_on": "analysis",
                "brief_id": started["brief_id"],
                "analysis_job_id": started.get("analysis_job_id")}
    status = await auto_edit("brief_status", {"brief_id": brief_id, "analysis_root": project_root})
    if not status.get("success"):
        return status
    state = (status.get("brief") or {}).get("state")
    if state != "ready":
        return {"success": True, "stage": "edit", "brief_id": brief_id,
                "waiting_on": "analysis", "brief_state": state}
    planned = await auto_edit("plan_cut", {"brief_id": brief_id, "analysis_root": project_root})
    if not planned.get("success"):
        return planned
    _orchestrate_mod.set_stage_foreign_keys(
        project_root, job_id, "edit", plan_id=planned["plan_id"])
    return {"success": True, "stage": "edit", "brief_id": brief_id, **planned}

async def _orchestrate_execute_reversible_stage(project_root, job_id, stage, proj, mutate_fn):
    """Shared run_stage body for reversible stages: snapshot -> mutate ->
    done+fingerprint | failed (never auto-rolls-back — that's the separate
    explicit rollback_stage action; a failure here just stops and leaves the
    snapshot in place for it). A pending confirm-token isn't a failure — the
    stage stays "running" so a retry with the token can complete it, and no
    second snapshot is taken on that retry."""
    job = _orchestrate_mod.load_job(project_root, job_id)
    already_has_snapshot = bool((job.get("stages", {}).get(stage) or {}).get("snapshot_ids"))
    _orchestrate_mod.advance_stage(project_root, job_id, stage, "running")
    if not already_has_snapshot:
        snap = _orchestrate_take_snapshot(proj, job_id=job_id, stage=stage)
        if snap.get("snapshot_id"):
            _orchestrate_mod.record_snapshot(project_root, job_id, stage, snap["snapshot_id"], kind=snap["kind"])
    try:
        result = await mutate_fn()
    except Exception as exc:
        result = {"success": False, "error": f"{type(exc).__name__}: {exc}"}
    if isinstance(result, dict) and result.get("status") == "confirmation_required":
        return result
    if not (isinstance(result, dict) and result.get("success")):
        _orchestrate_mod.advance_stage(
            project_root, job_id, stage, "failed",
            notes=[str((result or {}).get("error") if isinstance(result, dict) else result)])
        return result
    fp = _orchestrate_capture_fingerprint(proj)
    _orchestrate_mod.advance_stage(project_root, job_id, stage, "done", fingerprint=fp)
    result.setdefault("stage", stage)
    return result

async def _orchestrate_run_ingest(job, job_id, project_root, proj) -> Dict[str, Any]:
    """Additive/non-destructive — no snapshot (nothing to protect: nothing
    existed before an import). Reuses the exact bin-scaffold helpers
    auto_edit.start_brief uses."""
    from src.domains.media_pool_ingest.actions import _ensure_folder_path, _safe_import_media
    _orchestrate_mod.advance_stage(project_root, job_id, "ingest", "running")
    brief = job.get("brief") or {}
    files, music = brief.get("files") or [], brief.get("music")
    mp = proj.GetMediaPool()
    if not mp:
        _orchestrate_mod.advance_stage(project_root, job_id, "ingest", "failed", notes=["no media pool"])
        return _err("No media pool")
    imported: Dict[str, Any] = {}
    for bin_name, paths in (("Footage", list(files)), ("Music", [music] if music else [])):
        if not paths:
            continue
        _folder, folder_err = _ensure_folder_path(mp, bin_name)
        if folder_err:
            _orchestrate_mod.advance_stage(project_root, job_id, "ingest", "failed", notes=[str(folder_err)])
            return folder_err
        result = _safe_import_media(mp, {"paths": paths, "target_folder": bin_name})
        if result.get("error"):
            _orchestrate_mod.advance_stage(project_root, job_id, "ingest", "failed", notes=[str(result)])
            return result
        imported[bin_name] = result
    fp = _orchestrate_capture_fingerprint(proj)
    _orchestrate_mod.advance_stage(project_root, job_id, "ingest", "done", fingerprint=fp)
    return {"success": True, "stage": "ingest", "imported": imported}

async def _orchestrate_run_analysis(job, job_id, project_root, proj) -> Dict[str, Any]:
    """Auto-assembling genres (auto_edit.GENRES — talking-head, montage):
    fused with the edit stage's own brief pipeline (analysis IS what
    start_brief kicks — a separate pass would be redundant). Every other
    genre: kick/poll a generic media_analysis batch job over the whole
    project; per the locked design this is expensive and never auto-driven
    slice-by-slice here — the host progresses it (directly, or by calling
    run_stage again) exactly like the original "never auto-run" intent."""
    from src.domains.media_analysis.actions import media_analysis
    genre = (job.get("brief") or {}).get("genre") or "talking_head"
    _orchestrate_mod.advance_stage(project_root, job_id, "analysis", "running")
    if genre in _auto_edit_mod.GENRES:
        planned = await _orchestrate_plan_stage_talking_head(job, job_id, project_root)
        if not planned.get("success"):
            _orchestrate_mod.advance_stage(
                project_root, job_id, "analysis", "failed",
                notes=[str(planned.get("error") or planned)])
            return planned
        if planned.get("waiting_on"):
            return {"success": True, "stage": "analysis", "waiting_on": planned["waiting_on"],
                    "brief_id": planned.get("brief_id"), "brief_state": planned.get("brief_state")}
        fp = _orchestrate_capture_fingerprint(proj)
        _orchestrate_mod.advance_stage(project_root, job_id, "analysis", "done", fingerprint=fp)
        return {"success": True, "stage": "analysis", "brief_id": planned.get("brief_id")}

    fks = (job["stages"]["analysis"].get("foreign_keys") or {})
    batch_job_id = fks.get("batch_job_id")
    if not batch_job_id:
        started = await media_analysis("start_batch_job", {
            "target": {"type": "project"}, "analysis_root": project_root,
        })
        if not started.get("success"):
            _orchestrate_mod.advance_stage(project_root, job_id, "analysis", "failed", notes=[str(started)])
            return started
        batch_job_id = started.get("job_id")
        _orchestrate_mod.set_stage_foreign_keys(project_root, job_id, "analysis", batch_job_id=batch_job_id)
        return {"success": True, "stage": "analysis", "waiting_on": "analysis", "batch_job_id": batch_job_id,
                "note": "batch job started — drive it (or call run_stage again to poll)"}
    status = await media_analysis("batch_job_status", {"job_id": batch_job_id, "analysis_root": project_root})
    if not status.get("success"):
        return status
    if str(status.get("status") or "").startswith("completed"):
        fp = _orchestrate_capture_fingerprint(proj)
        _orchestrate_mod.advance_stage(project_root, job_id, "analysis", "done", fingerprint=fp)
        return {"success": True, "stage": "analysis", "batch_job_id": batch_job_id}
    return {"success": True, "stage": "analysis", "waiting_on": "analysis", "batch_job_id": batch_job_id,
            "job_status": status.get("status"), "progress": status.get("progress")}

async def _orchestrate_run_edit(job, job_id, project_root, proj, p: Dict[str, Any]) -> Dict[str, Any]:
    """Auto-assembling genres (auto_edit.GENRES): continues plan_stage ->
    requires G1 valid -> build_timeline (adopted gate, per the epic's core
    design decision). Every other genre: the bring-your-own-timeline escape
    hatch — pause until the host reports byo_ready=true, then just
    fingerprint whatever timeline exists."""
    from src.domains.auto_edit.actions import auto_edit
    genre = (job.get("brief") or {}).get("genre") or "talking_head"
    _orchestrate_mod.advance_stage(project_root, job_id, "edit", "running")
    if genre not in _auto_edit_mod.GENRES:
        if not p.get("byo_ready"):
            return {"success": True, "stage": "edit", "waiting_on": "byo_timeline",
                    "message": "cut it in Resolve, then call run_stage again with byo_ready=true"}
        fp = _orchestrate_capture_fingerprint(proj)
        _orchestrate_mod.advance_stage(project_root, job_id, "edit", "done", fingerprint=fp)
        return {"success": True, "stage": "edit", "byo": True, "fingerprint": fp}

    planned = await _orchestrate_plan_stage_talking_head(job, job_id, project_root)
    if not planned.get("success"):
        _orchestrate_mod.advance_stage(project_root, job_id, "edit", "failed",
                                        notes=[str(planned.get("error") or planned)])
        return planned
    if planned.get("waiting_on"):
        return {"success": True, **planned}
    plan_id = planned.get("plan_id")
    if not plan_id:
        return {"success": True, "stage": "edit", "waiting_on": "plan", **planned}

    job = _orchestrate_mod.load_job(project_root, job_id)  # refresh — plan_stage updated foreign_keys
    fp_now = _orchestrate_capture_fingerprint(proj)
    if not _orchestrate_mod.gate_is_valid(job["stages"]["edit"].get("gate"), fp_now):
        return {"success": True, "stage": "edit", "waiting_on": "G1_approval", "plan_id": plan_id}

    if not (job["stages"]["edit"].get("snapshot_ids")):
        snap = _orchestrate_take_snapshot(proj, job_id=job_id, stage="edit")
        if snap.get("snapshot_id"):
            _orchestrate_mod.record_snapshot(project_root, job_id, "edit", snap["snapshot_id"], kind=snap["kind"])

    inner_params = {"plan_id": plan_id, "analysis_root": project_root}
    if p.get("confirm_token"):
        inner_params["confirm_token"] = p["confirm_token"]
    built = await auto_edit("build_timeline", inner_params)
    if built.get("status") == "confirmation_required":
        return built
    if not built.get("success"):
        _orchestrate_mod.advance_stage(project_root, job_id, "edit", "failed",
                                        notes=[str(built.get("error") or built)])
        return built
    _orchestrate_mod.set_stage_foreign_keys(project_root, job_id, "edit", timeline_name=built.get("timeline_name"))
    fp = _orchestrate_capture_fingerprint(proj)
    _orchestrate_mod.advance_stage(project_root, job_id, "edit", "done", fingerprint=fp)
    return {"success": True, "stage": "edit", "plan_id": plan_id, **built}

async def _orchestrate_run_conform(job, job_id, project_root, proj, p: Dict[str, Any]) -> Dict[str, Any]:
    """Read-only QC by default (gaps/overlaps, missing media) — refuses on
    findings unless explicitly accepted. Relink is left to the host driving
    `timeline` directly; this stage's job is to surface problems honestly,
    not to silently decide they're fine."""
    from src.domains.timeline_edit.actions import timeline
    async def _mutate():
        gaps = timeline("detect_gaps_overlaps", {})
        missing = timeline("detect_missing_media", {})
        problems = []
        if gaps.get("gap_count") or gaps.get("overlap_count"):
            if not p.get("accept_gaps"):
                problems.append(
                    f"{gaps.get('gap_count', 0)} gap(s)/{gaps.get('overlap_count', 0)} overlap(s) — "
                    "pass accept_gaps=true to proceed anyway")
        if missing.get("missing_count"):
            if not p.get("accept_missing"):
                problems.append(
                    f"{missing.get('missing_count')} missing media reference(s) — "
                    "pass accept_missing=true, or relink first")
        if problems:
            return {"success": False, "error": "; ".join(problems), "gaps": gaps, "missing": missing}
        return {"success": True, "gaps": gaps, "missing": missing}

    return await _orchestrate_execute_reversible_stage(project_root, job_id, "conform", proj, _mutate)

async def _orchestrate_run_grade(job, job_id, project_root, proj, p: Dict[str, Any]) -> Dict[str, Any]:
    """Applies a grade via timeline_item_color IF the brief (or the call)
    specifies one; otherwise a no-op done — G2's vision checkpoint still
    fires regardless (a look assessment of "no grade applied" is honest
    too).

    ``options.grade.compute`` is the offline-compute-then-apply path
    (epic #37): ``{action, clips, outDir, ...}`` forwarded verbatim to the
    advanced server's ``drx`` tool via ``advanced_bridge.run_drx_compute``
    — Resolve stays open the whole call, no quit/relaunch dance (that's
    only needed for tools that require Resolve CLOSED, which drx doesn't).
    Single-target apply only: the first computed grade is applied via the
    same safe_apply_drx path a manually-supplied drx_path would use —
    per-clip individualized application across multiple timeline items
    (matching each grade to its own clip) is future work."""
    from src.domains.color_grade.actions import timeline_item_color
    grade_opts = dict(((job.get("brief") or {}).get("options") or {}).get("grade") or {})
    grade_opts.update(p.get("grade") or {})
    if not grade_opts:
        _orchestrate_mod.advance_stage(project_root, job_id, "grade", "running")
        fp = _orchestrate_capture_fingerprint(proj)
        _orchestrate_mod.advance_stage(project_root, job_id, "grade", "done", fingerprint=fp)
        return {"success": True, "stage": "grade", "note": "no grade specified — nothing to apply"}

    compute_spec = grade_opts.pop("compute", None)
    compute_report = None
    if compute_spec:
        # Mark running before the compute call — it happens outside
        # _orchestrate_execute_reversible_stage's own "running" transition,
        # and a compute failure needs a legal pending->failed path (advance_stage
        # only allows failed from running, never straight from pending).
        _orchestrate_mod.advance_stage(project_root, job_id, "grade", "running")
        compute_action = str(compute_spec.get("action") or "")
        compute_args = {k: v for k, v in compute_spec.items() if k != "action"}
        computed = _advanced_bridge.run_drx_compute(compute_action, compute_args)
        if not computed.get("success"):
            _orchestrate_mod.advance_stage(
                project_root, job_id, "grade", "failed",
                notes=[f"offline compute failed: {computed.get('error')}"])
            return {"success": False, "stage": "grade",
                    "error": f"offline compute failed: {computed.get('error')}", "compute": computed}
        grades = ((computed.get("result") or {}).get("grades")) or []
        if not grades:
            _orchestrate_mod.advance_stage(
                project_root, job_id, "grade", "failed", notes=["offline compute produced no grades"])
            return {"success": False, "stage": "grade",
                    "error": "offline compute produced no grades", "compute": computed}
        grade_opts["drx_path"] = grades[0]["drxPath"]
        compute_report = computed.get("result")

    async def _mutate():
        call_params = dict(grade_opts)
        drx_path = call_params.pop("drx_path", None) or call_params.get("path")
        if drx_path:
            call_params["path"] = drx_path
            grade_action = "safe_apply_drx"
        else:
            grade_action = "safe_set_cdl"
        result = timeline_item_color(grade_action, call_params)
        if compute_report is not None and isinstance(result, dict):
            result = dict(result, compute_report=compute_report)
        return result

    return await _orchestrate_execute_reversible_stage(project_root, job_id, "grade", proj, _mutate)

async def _orchestrate_run_audio(job, job_id, project_root, proj, p: Dict[str, Any]) -> Dict[str, Any]:
    """No default audio processing — pass options.audio (brief-level or at
    call time) to apply specific levels/properties; otherwise a no-op done.
    Requires G2 approved first — the mandatory vision handoff gates every
    stage downstream of grade, not just deliver."""
    from src.domains.timeline_edit.actions import timeline
    fp_now = _orchestrate_capture_fingerprint(proj)
    if not _orchestrate_mod.gate_is_valid(job["stages"]["grade"].get("gate"), fp_now):
        return {"success": True, "stage": "audio", "waiting_on": "G2_approval"}
    audio_opts = dict(((job.get("brief") or {}).get("options") or {}).get("audio") or {})
    audio_opts.update(p.get("audio") or {})
    if not audio_opts:
        _orchestrate_mod.advance_stage(project_root, job_id, "audio", "running")
        fp = _orchestrate_capture_fingerprint(proj)
        _orchestrate_mod.advance_stage(project_root, job_id, "audio", "done", fingerprint=fp)
        return {"success": True, "stage": "audio", "note": "no audio settings specified — nothing to apply"}

    async def _mutate():
        return timeline("safe_set_audio_properties", audio_opts)

    return await _orchestrate_execute_reversible_stage(project_root, job_id, "audio", proj, _mutate)

async def _orchestrate_run_review(job, job_id, project_root, proj) -> Dict[str, Any]:
    from src.domains.review_annotation.actions import timeline_markers
    _orchestrate_mod.advance_stage(project_root, job_id, "review", "running")
    report = timeline_markers("export_review_report", {})
    if isinstance(report, dict) and report.get("error"):
        _orchestrate_mod.advance_stage(project_root, job_id, "review", "failed", notes=[str(report)])
        return report
    fp = _orchestrate_capture_fingerprint(proj)
    _orchestrate_mod.advance_stage(project_root, job_id, "review", "done", fingerprint=fp)
    return {"success": True, "stage": "review", "report": report}

async def _orchestrate_run_deliver(job, job_id, project_root, proj, p: Dict[str, Any]) -> Dict[str, Any]:
    """Special-cased per the locked design: G3 must already be approved (a
    SEPARATE precondition from can_run_stage's cursor check); no pre-stage
    snapshot and no auto-rollback on failure — the render queue itself is
    the recovery mechanism (mark failed-resumable-via-Resolve, let the host
    resume via Resolve's own render lifecycle rather than restart)."""
    from src.domains.render_deliver.actions import _prepare_render_job
    fp_now = _orchestrate_capture_fingerprint(proj)
    if not _orchestrate_mod.gate_is_valid(job["stages"]["deliver"].get("gate"), fp_now):
        return {"success": True, "stage": "deliver", "waiting_on": "G3_approval"}
    _orchestrate_mod.advance_stage(project_root, job_id, "deliver", "running")

    render_opts = dict(((job.get("brief") or {}).get("options") or {}).get("render") or {})
    render_opts.update(p.get("render") or {})
    target_dir = str(render_opts.get("target_dir") or render_opts.get("targetDir") or "")
    if not target_dir:
        from src.domains.media_analysis.utils import analysis_memory as _analysis_memory
        target_dir = os.path.join(_analysis_memory.memory_dir(project_root), "orchestrate", job_id, "renders")
    os.makedirs(target_dir, exist_ok=True)
    custom_name = str(render_opts.get("custom_name") or render_opts.get("customName") or f"orchestrate_{job_id}")
    prepared = _prepare_render_job(proj, {
        "target_dir": target_dir, "settings": render_opts.get("settings") or {},
        "format": render_opts.get("format"), "codec": render_opts.get("codec"),
        "custom_name": custom_name, "require_temp_target": False,
    })
    if not prepared.get("success"):
        _orchestrate_mod.advance_stage(project_root, job_id, "deliver", "failed",
                                        notes=["failed-resumable-via-Resolve", str(prepared)])
        return {"success": False, "stage": "deliver", "error": "prepare_render_job failed", "render": prepared}
    render_job_id = prepared["job_id"]

    def _render_work():
        render_started = time.time()
        started = bool(proj.StartRendering([render_job_id], False))
        if not started:
            return {"success": False, "error": "StartRendering returned false", "job_id": render_job_id}
        while proj.IsRenderingInProgress():
            time.sleep(2)
        status = _ser(proj.GetRenderJobStatus(render_job_id))
        job_failed = str((status or {}).get("JobStatus") if isinstance(status, dict)
                         else "").lower() in ("failed", "cancelled", "canceled")
        outputs = []
        for fname in os.listdir(target_dir):
            if not fname.startswith(custom_name):
                continue
            full = os.path.join(target_dir, fname)
            if os.path.getmtime(full) >= render_started - 2:
                outputs.append(full)
        outputs.sort(key=os.path.getmtime, reverse=True)
        output_path = outputs[0] if outputs else None
        out = {"success": bool(output_path and os.path.isfile(output_path)) and not job_failed,
               "job_id": render_job_id, "status": status, "output_path": output_path}
        if not output_path:
            out["error"] = "no output file found after render"
        elif job_failed:
            out["error"] = "render job did not complete"
        return out

    import anyio
    render_result = await anyio.to_thread.run_sync(
        lambda: _run_maybe_background("orchestrate.run_stage.deliver", p, _render_work))
    if not (isinstance(render_result, dict) and render_result.get("success")):
        _orchestrate_mod.advance_stage(project_root, job_id, "deliver", "failed",
                                        notes=["failed-resumable-via-Resolve", str(render_result)])
        return {"success": False, "stage": "deliver", "render": render_result}
    _orchestrate_mod.set_stage_foreign_keys(project_root, job_id, "deliver", output_path=render_result["output_path"])

    # Optional offline QC against the rendered output (epic #37 phase A
    # extension) — deliverable/loudness compliance checks, pure ffprobe/
    # ffmpeg reads, no Resolve interaction, run in-band right after render.
    # Report-only per the advanced tool's own posture (gate: review — never
    # auto-pass-clear): findings never fail this stage, they're surfaced for
    # the host to act on.
    qc_opts = dict(((job.get("brief") or {}).get("options") or {}).get("deliver_qc") or {})
    qc_opts.update(p.get("deliver_qc") or {})
    qc_report = None
    if qc_opts:
        qc_report = {}
        if qc_opts.get("spec"):
            qc_report["deliverable_qc"] = _advanced_bridge.run_advanced_tool(
                "deliverable", "deliverable_qc",
                {"file": render_result["output_path"], "spec": qc_opts["spec"]})
        if qc_opts.get("loudness_target"):
            qc_report["loudness_qc"] = _advanced_bridge.run_advanced_tool(
                "deliverable", "loudness_qc",
                {"file": render_result["output_path"], "target": qc_opts["loudness_target"]})

    fp = _orchestrate_capture_fingerprint(proj)
    _orchestrate_mod.advance_stage(project_root, job_id, "deliver", "done", fingerprint=fp)
    result = {"success": True, "stage": "deliver", "render": render_result}
    if qc_report is not None:
        result["qc"] = qc_report
    return result

def _orchestrate_resolve_fingerprint(p: Dict[str, Any], proj):
    """(fingerprint, err). An explicit override lets check_resume/approve_gate
    be offline-testable and lets a host that already probed once reuse it."""
    override = p.get("current_fingerprint") or p.get("currentFingerprint")
    if isinstance(override, dict):
        return override, None
    if proj is None:
        return None, _err(
            "current_fingerprint not provided and no Resolve project is open — "
            "pass current_fingerprint explicitly, or open a project."
        )
    return _orchestrate_capture_fingerprint(proj), None

@mcp.tool()
async def orchestrate(action: str, params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Resumable ingest-to-deliver post-production conductor.

    Sequences the domain tools (media_pool, media_analysis, auto_edit,
    timeline, timeline_item_color, render, ...) across a durable, resumable
    job record — the sole reason this exists as a tool rather than host
    prose is surviving context death mid-job. Phase 3 (current): run_stage
    delegates every stage to its domain tool (craft is never reimplemented —
    orchestrate calls the domain functions and holds foreign keys), plus
    rollback_stage and finish_job. fusion stays unimplemented (opt-in, no
    default ops yet).

    Actions:
      start_job(files, music?, target_duration_seconds?, genre?, deliverable?,
        title_text?, options?, stages?, include_fusion?, gates?, holder_id?,
        analysis_root?) -> {job_id, job, holder_id} — validates files (exist
        on disk), infers the stage manifest from the brief (override with
        `stages`), marks intake done, persists, and acquires the initial
        lease. `gates`: auto|standard|paranoid (default standard). Does NOT
        auto-run analysis or any other stage.
      job_status(job_id, analysis_root?) -> {job, cursor, manifest,
        lease_expired} — read-only; never touches the lease.
      list_jobs(analysis_root? | analysis_base_root?, limit?, rebuild?,
        job_state?) -> {jobs} — reads the global index (auto-rebuilds if
        missing); rebuild=true forces a fresh scan of every project root
        under analysis_base_root.
      check_resume(job_id, current_fingerprint?, analysis_root?) -> {drifted,
        checked_stage, expected, actual, message} — re-probes (or accepts an
        explicit current_fingerprint) and compares against the last done
        stage's recorded checkpoint. Never mutates.
      force_replan_stage(job_id, stage, analysis_root?) -> resets a drifted
        done stage back to pending (and clears its gate) — the concrete
        remediation check_resume points at.
      plan_stage(job_id, stage="edit", analysis_root?) -> talking-head only
        today: kicks/polls auto_edit's start_brief -> plan_cut and records
        the brief_id/plan_id as the edit stage's foreign keys. Other genres
        get the bring-your-own-timeline refusal; other stages refuse (no
        planner yet).
      revise_stage(job_id, stage="edit", notes?, edits?, analysis_root?) ->
        delegates to auto_edit.revise_cut, updates the stage's plan_id, and
        VOIDS any G1 approval (it approved a plan that no longer exists).
      approve_gate(job_id, gate=G1|G2|G3, current_fingerprint?,
        vision_assessment?, preview_frame_path?, force?, confirm_token?) ->
        {approved_at, adopted, forced, snapshots_cleaned}. G1 on an
        auto-assembling edit stage (auto_edit.GENRES — talking-head,
        montage) ADOPTS auto_edit.approve_cut verbatim (its own
        confirm-token ceremony, not a second one). G2 always requires
        vision_assessment + preview_frame_path — no blind grade approval,
        not even under force. `force` bypasses only the drift-halt.
        Fingerprint-bound: a drifted approval auto-voids and the gate
        reopens. GC's the gated stage's pre-stage snapshots live on success.
      run_stage(job_id, stage?, analysis_root?, ...stage params) -> runs the
        current cursor stage (or an explicit `stage`), delegating to its
        domain tool: ingest -> media_pool import; analysis -> the edit
        stage's own brief pipeline (talking-head) or a generic
        media_analysis batch job (other genres — kicked/polled, never
        auto-driven slice-by-slice, per the locked "expensive, never
        auto-run" design); edit -> plan+build via auto_edit (talking-head,
        requires G1) or the bring-your-own-timeline pause (`byo_ready=true`
        to confirm the manual cut is done); conform -> read-only gap/
        overlap/missing-media QC (refuses on findings unless
        `accept_gaps`/`accept_missing`); grade -> timeline_item_color
        safe_apply_drx/safe_set_cdl if `grade` options are given, else a
        no-op; audio -> timeline safe_set_audio_properties if `audio`
        options are given, else a no-op; deliver -> requires G3, then a
        validated render (special-cased: no snapshot, no auto-rollback —
        failure marks `failed-resumable-via-Resolve`, lean on Resolve's own
        render-queue resume); review -> timeline_markers export_review_report.
        Reversible stages snapshot before mutating and leave the stage
        "failed" (snapshot intact) on error — rollback_stage is the
        explicit next step, never automatic.
      request_offline_op(job_id, stage?, tool, op_action, args?, instruction?,
        analysis_root?) -> {waiting_on: "offline_artifact", pending_offline_op}
        — parks the current cursor stage on a narrow slice of the advanced
        (Node) server that needs the Resolve project CLOSED
        (conform.fix_reverse_clip; offline_ref.link_in_project/
        unlink_in_project; project_db.relayout_node_graphs; fairlight's DB
        path). Refuses any (tool, op_action) outside that whitelist — those
        are pure file/DB-read and belong on the in-band
        advanced_bridge.run_advanced_tool path instead, no pause needed.
        This action never quits or relaunches Resolve itself: the host
        still does that via the existing quit_app/restart_app/launch tools
        (each separately permissioned) — this only records what's
        outstanding so a fresh session can see it via job_status and resume
        cleanly after a context reset.
      resolve_offline_op(job_id, result, analysis_root?) -> un-parks the
        stage a prior request_offline_op parked, per the host-reported
        `result` of actually running the op with Resolve closed. Success
        resumes "running" (call run_stage again to finish the stage);
        failure marks the stage "failed" (same clean-retry path any other
        stage failure gets).
      rollback_stage(job_id, stage, analysis_root?) -> restores the stage's
        latest recorded snapshot live (timeline_duplicate: the snapshot
        becomes the current timeline; grade_version: LoadVersion switches
        back) and resets the stage to pending for a clean retry.
      finish_job(job_id, keep_snapshots?, analysis_root?) -> refuses unless
        every manifest stage is done; verifies the deliver stage's
        output_path exists, purges every remaining `_orch_{job_id}_*`
        snapshot (live deletion + count), and marks the job finished.
        `keep_snapshots=true` opts out of the purge.
    """
    from src.domains.auto_edit.actions import auto_edit
    p = params or {}

    def _job_id_param() -> str:
        return str(p.get("job_id") or p.get("jobId") or "")

    if action == "start_job":
        r, proj, project_root, err = _orchestrate_project_context(p, need_resolve=False)
        if err:
            return err
        files = p.get("files") or []
        music = p.get("music")
        problems = _orchestrate_mod.validate_job_inputs(
            files=files,
            genre=p.get("genre") or "talking_head",
            deliverable=p.get("deliverable") or _orchestrate_mod.DEFAULT_DELIVERABLE,
            target_duration_seconds=p.get("target_duration_seconds") or p.get("targetDurationSeconds"),
            title_text=p.get("title_text") or p.get("titleText"),
            stages=p.get("stages"),
        )
        for path in list(files) + ([music] if music else []):
            if not isinstance(path, str) or not os.path.isfile(path):
                problems.append(f"file not found: {path!r}")
        if problems:
            return _err("invalid job brief: " + "; ".join(problems))
        created = _orchestrate_mod.create_job(
            project_root,
            files=files,
            music=music,
            target_duration_seconds=p.get("target_duration_seconds") or p.get("targetDurationSeconds"),
            genre=p.get("genre") or "talking_head",
            deliverable=p.get("deliverable") or _orchestrate_mod.DEFAULT_DELIVERABLE,
            title_text=p.get("title_text") or p.get("titleText"),
            options=p.get("options"),
            stages=p.get("stages"),
            include_fusion=bool(p.get("include_fusion") or p.get("includeFusion")),
            holder_id=p.get("holder_id") or p.get("holderId"),
            gates=p.get("gates"),
        )
        if not created.get("success"):
            return _err("; ".join(created.get("problems") or [created.get("error") or "start_job failed"]))
        return created

    if action == "job_status":
        _r, _proj, project_root, err = _orchestrate_project_context(p, need_resolve=False)
        if err:
            return err
        result = _orchestrate_mod.job_status(project_root, _job_id_param())
        if not result.get("success"):
            return _err(result.get("error") or "job_status failed")
        return result

    if action == "list_jobs":
        analysis_base_root = p.get("analysis_base_root") or p.get("analysisBaseRoot")
        if not analysis_base_root:
            _r, _proj, project_root, err = _orchestrate_project_context(p, need_resolve=False)
            if err:
                return err
            analysis_base_root = _orchestrate_default_analysis_base_root(project_root)
        return _orchestrate_mod.list_jobs(
            str(analysis_base_root),
            limit=int(p.get("limit") or 20),
            rebuild=bool(p.get("rebuild")),
            job_state=p.get("job_state") or p.get("jobState"),
        )

    if action == "check_resume":
        r, proj, project_root, err = _orchestrate_project_context(p, need_resolve=False)
        if err:
            return err
        job = _orchestrate_mod.load_job(project_root, _job_id_param())
        if not job:
            return _err(f"job not found: {_job_id_param()!r}")
        if job.get("_corrupt"):
            return _err("job fingerprint mismatch — record corrupted or tampered")
        fp, ferr = _orchestrate_resolve_fingerprint(p, proj)
        if ferr:
            return ferr
        return _orchestrate_mod.check_resume(job, fp)

    if action == "force_replan_stage":
        _r, _proj, project_root, err = _orchestrate_project_context(p, need_resolve=False)
        if err:
            return err
        result = _orchestrate_mod.force_replan_stage(
            project_root, _job_id_param(), str(p.get("stage") or ""))
        if not result.get("success"):
            return _err(result.get("error") or "force_replan_stage failed")
        return result

    if action == "plan_stage":
        r, proj, project_root, err = _orchestrate_project_context(p, need_resolve=False)
        if err:
            return err
        job_id = _job_id_param()
        stage = str(p.get("stage") or "edit")
        job = _orchestrate_mod.load_job(project_root, job_id)
        if not job:
            return _err(f"job not found: {job_id!r}")
        if job.get("_corrupt"):
            return _err("job fingerprint mismatch — record corrupted or tampered")
        if stage != "edit":
            return _err(f"plan_stage does not support stage {stage!r} yet — "
                        "only 'edit' has a planner in this phase")
        genre = (job.get("brief") or {}).get("genre") or "talking_head"
        if genre not in _auto_edit_mod.GENRES:
            return _err(
                f"genre {genre!r} uses the bring-your-own-timeline escape hatch — "
                "no auto-plan. Cut it in Resolve; stage handoff lands in a later phase."
            )
        return await _orchestrate_plan_stage_talking_head(job, job_id, project_root)

    if action == "revise_stage":
        _r, _proj, project_root, err = _orchestrate_project_context(p, need_resolve=False)
        if err:
            return err
        job_id = _job_id_param()
        stage = str(p.get("stage") or "edit")
        job = _orchestrate_mod.load_job(project_root, job_id)
        if not job:
            return _err(f"job not found: {job_id!r}")
        if job.get("_corrupt"):
            return _err("job fingerprint mismatch — record corrupted or tampered")
        if stage != "edit":
            return _err(f"revise_stage does not support stage {stage!r} yet — "
                        "only 'edit' has a planner in this phase")
        fks = (job["stages"]["edit"].get("foreign_keys") or {})
        brief_id = fks.get("brief_id")
        plan_id = fks.get("plan_id")
        if not brief_id or not plan_id:
            return _err("no plan yet for this stage — call plan_stage first")
        revised = await auto_edit("revise_cut", {
            "brief_id": brief_id, "plan_id": plan_id, "notes": p.get("notes") or "",
            "edits": p.get("edits"), "analysis_root": project_root,
        })
        if not revised.get("success"):
            return revised
        _orchestrate_mod.set_stage_foreign_keys(project_root, job_id, "edit", plan_id=revised["plan_id"])
        # A revision invalidates any G1 approval — it approved a plan that no longer exists.
        _orchestrate_mod.void_stage_gate(project_root, job_id, "edit")
        return {"success": True, "stage": "edit", "plan_id": revised["plan_id"], **revised}

    if action == "approve_gate":
        r, proj, project_root, err = _orchestrate_project_context(p, need_resolve=False)
        if err:
            return err
        job_id = _job_id_param()
        gate = str(p.get("gate") or "")
        job = _orchestrate_mod.load_job(project_root, job_id)
        if not job:
            return _err(f"job not found: {job_id!r}")
        if job.get("_corrupt"):
            return _err("job fingerprint mismatch — record corrupted or tampered")
        stage = _orchestrate_mod.GATE_STAGE.get(gate)
        if stage is None:
            return _err(f"unknown gate {gate!r} (must be one of {_orchestrate_mod.GATE_NAMES})")
        force = bool(p.get("force"))
        fp, ferr = _orchestrate_resolve_fingerprint(p, proj)
        if ferr and not force:
            return ferr

        genre = (job.get("brief") or {}).get("genre")
        if gate == "G1" and genre in _auto_edit_mod.GENRES and not force:
            fks = (job["stages"]["edit"].get("foreign_keys") or {})
            plan_id = fks.get("plan_id")
            if not plan_id:
                return _err("no approved-cut plan yet for this job — call plan_stage first")
            inner_params = {k: v for k, v in p.items() if k != "gate"}
            inner_params["plan_id"] = plan_id
            inner_params["analysis_root"] = project_root
            inner = await auto_edit("approve_cut", inner_params)
            if not inner.get("success"):
                return inner  # bubbles confirmation_required / errors as-is
            _orchestrate_mod.set_stage_foreign_keys(
                project_root, job_id, "edit", inner_gate_approved_at=inner.get("approved_at"))
            job = _orchestrate_mod.load_job(project_root, job_id)

        evaluated = _orchestrate_mod.evaluate_gate_request(
            job, gate, current_fingerprint=fp,
            vision_assessment=p.get("vision_assessment"),
            preview_frame_path=p.get("preview_frame_path") or p.get("previewFramePath"),
            force=force,
        )
        if not evaluated.get("success"):
            return _err(evaluated.get("error") or "approve_gate failed")
        if evaluated.get("already_approved"):
            return {"success": True, "gate": gate, "stage": stage,
                    "already_approved": True, "record": evaluated["gate"]}
        if evaluated.get("needs_confirm"):
            token_action = f"orchestrate.approve_gate.{gate}"
            if "confirm_token" not in p and "confirmToken" not in p and _confirm_token_required():
                preview = {
                    "operation": token_action, "stage": stage, "job_id": job_id,
                    "warning": f"Approves {gate} ({stage}) — the pipeline advances past this checkpoint.",
                }
                if gate == "G2":
                    preview["vision_assessment"] = p.get("vision_assessment")
                    preview["preview_frame_path"] = p.get("preview_frame_path") or p.get("previewFramePath")
                return _issue_confirm_token(action=token_action, params=p, preview=preview)
            blocked = _consume_confirm_token(action=token_action, params=p)
            if blocked:
                return blocked

        recorded = _orchestrate_mod.record_gate_approval(project_root, job_id, gate, evaluated["record"])
        if not recorded.get("success"):
            return _err(recorded.get("error") or "failed to record gate approval")
        cleanup = {"deleted": [], "failed": []}
        if recorded.get("snapshots_to_clean") and proj is not None:
            cleanup = _orchestrate_gc_snapshots_live(proj, recorded["snapshots_to_clean"])
        return {
            "success": True, "gate": gate, "stage": stage,
            "approved_at": recorded["gate"]["approved_at"],
            "adopted": recorded["gate"].get("adopted"),
            "forced": recorded["gate"].get("forced"),
            "snapshots_cleaned": cleanup,
        }

    if action == "run_stage":
        r, proj, project_root, err = _orchestrate_project_context(p, need_resolve=True)
        if err:
            return err
        job_id = _job_id_param()
        job = _orchestrate_mod.load_job(project_root, job_id)
        if not job:
            return _err(f"job not found: {job_id!r}")
        if job.get("_corrupt"):
            return _err("job fingerprint mismatch — record corrupted or tampered")
        stage = str(p.get("stage") or job.get("cursor") or "")
        refusal = _orchestrate_mod.can_run_stage(job, stage)
        if refusal:
            return _err(refusal)
        if stage == "ingest":
            return await _orchestrate_run_ingest(job, job_id, project_root, proj)
        if stage == "analysis":
            return await _orchestrate_run_analysis(job, job_id, project_root, proj)
        if stage == "edit":
            return await _orchestrate_run_edit(job, job_id, project_root, proj, p)
        if stage == "conform":
            return await _orchestrate_run_conform(job, job_id, project_root, proj, p)
        if stage == "grade":
            return await _orchestrate_run_grade(job, job_id, project_root, proj, p)
        if stage == "audio":
            return await _orchestrate_run_audio(job, job_id, project_root, proj, p)
        if stage == "review":
            return await _orchestrate_run_review(job, job_id, project_root, proj)
        if stage == "deliver":
            return await _orchestrate_run_deliver(job, job_id, project_root, proj, p)
        return _err(f"run_stage does not support stage {stage!r} yet")

    if action == "request_offline_op":
        # Bookkeeping only — parks the stage and hands back an instruction.
        # The actual quit/patch/relaunch stays on the existing, separately
        # permissioned tools (resolve_control quit_app/restart_app, this
        # server's launch); this action never touches Resolve's process.
        r, proj, project_root, err = _orchestrate_project_context(p, need_resolve=False)
        if err:
            return err
        job_id = _job_id_param()
        job = _orchestrate_mod.load_job(project_root, job_id)
        if not job:
            return _err(f"job not found: {job_id!r}")
        if job.get("_corrupt"):
            return _err("job fingerprint mismatch — record corrupted or tampered")
        stage = str(p.get("stage") or job.get("cursor") or "")
        result = _orchestrate_mod.request_offline_op(
            project_root, job_id, stage,
            tool=str(p.get("tool") or ""),
            action=str(p.get("op_action") or ""),
            args=p.get("args") or {},
            instruction=p.get("instruction"),
        )
        if not result.get("success"):
            return _err(result.get("error") or "request_offline_op failed")
        return {"success": True, "stage": stage, "waiting_on": "offline_artifact", **result}

    if action == "resolve_offline_op":
        r, proj, project_root, err = _orchestrate_project_context(p, need_resolve=False)
        if err:
            return err
        job_id = _job_id_param()
        result = _orchestrate_mod.resolve_offline_op(project_root, job_id, result=p.get("result") or {})
        if not result.get("success"):
            return _err(result.get("error") or "resolve_offline_op failed")
        return result

    if action == "rollback_stage":
        r, proj, project_root, err = _orchestrate_project_context(p, need_resolve=True)
        if err:
            return err
        job_id = _job_id_param()
        stage = str(p.get("stage") or "")
        job = _orchestrate_mod.load_job(project_root, job_id)
        if not job:
            return _err(f"job not found: {job_id!r}")
        if job.get("_corrupt"):
            return _err("job fingerprint mismatch — record corrupted or tampered")
        snapshots = list((job.get("stages", {}).get(stage) or {}).get("snapshot_ids") or [])
        if not snapshots:
            return _err(f"stage {stage!r} has no recorded snapshot to roll back to")
        latest = snapshots[-1]
        restored = _orchestrate_restore_snapshot(proj, kind=latest["kind"], snapshot_id=latest["id"])
        if not restored.get("success"):
            return _err(restored.get("error") or "snapshot restore failed")
        result = _orchestrate_mod.rollback_stage(
            project_root, job_id, stage, snapshot_consumed=bool(restored.get("consumed")))
        if not result.get("success"):
            return _err(result.get("error") or "rollback bookkeeping failed")
        return {"success": True, "stage": stage, "restored": latest, "job": result["job"]}

    if action == "finish_job":
        r, proj, project_root, err = _orchestrate_project_context(p, need_resolve=False)
        if err:
            return err
        job_id = _job_id_param()
        keep_snapshots = bool(p.get("keep_snapshots"))
        job = _orchestrate_mod.load_job(project_root, job_id)
        if not job:
            return _err(f"job not found: {job_id!r}")
        if job.get("_corrupt"):
            return _err("job fingerprint mismatch — record corrupted or tampered")
        output_path = (job.get("stages", {}).get("deliver") or {}).get("foreign_keys", {}).get("output_path")
        output_verified = bool(output_path and os.path.isfile(str(output_path)))
        finished = _orchestrate_mod.finish_job(project_root, job_id, output_path=output_path)
        if not finished.get("success"):
            return _err(finished.get("error") or "finish_job failed")
        cleanup = {"deleted": [], "failed": []}
        if not keep_snapshots and finished.get("snapshots_to_clean") and proj is not None:
            cleanup = _orchestrate_gc_snapshots_live(proj, finished["snapshots_to_clean"])
        return {
            "success": True, "job_id": job_id, "output_path": output_path,
            "output_verified": output_verified,
            "purged_count": len(cleanup["deleted"]),
            "purge_failed": cleanup["failed"],
            "kept_snapshots": keep_snapshots,
            "finished_at": finished["job"].get("finished_at"),
        }

    return _unknown(action, [
        "start_job", "job_status", "list_jobs",
        "check_resume", "force_replan_stage",
        "plan_stage", "revise_stage", "approve_gate",
        "run_stage", "request_offline_op", "resolve_offline_op",
        "rollback_stage", "finish_job",
    ])
