"""Generated by the repo-restructure Phase 3 split (epic #52, #46).

Extracted from src/server.py; see src/core/CONTEXT.md or the matching domain
CONTEXT.md for what lives here and why.
"""
from __future__ import annotations

import base64
import os
import sys
import json
import logging
import math
import platform
import re
import shutil
import struct
import subprocess
import tempfile
import threading
import time
import zipfile
import zlib
from typing import Dict, Any, Optional, List, Tuple

from src.domains.color_grade.utils.cdl import normalize_cdl_payload
from src.core.mcp_stdio import run_fastmcp_stdio
from src.core.api_truth import lookup_api_truth, VERIFIED_ON as _API_TRUTH_VERIFIED_ON
from src.core.contracts import validate as _validate_params
from src.domains.project_lifecycle.utils.cloud_operations import cloud_sync_status_label
from src.domains.auto_edit.utils.cut_ir import build_cut_list as _build_cut_list
from src.core.page_lock import open_page_serialized as _open_page_serialized
from src.core.proc import preload_audit, resolve_spawn_env, safe_run, sanitized_spawn_env
from src.core.readback import verify_by_readback, verification_stats as _verification_stats
from src.core.update_check import (
    check_for_updates,
    clear_update_prompt_preferences,
    get_cached_update_status,
    get_update_channel,
    get_update_mode,
    ignore_update_version,
    set_update_mode,
    snooze_update_prompt,
    start_background_update_check,
    update_prompt_decision,
    update_state_path,
)
from src.domains.media_analysis.utils.caps_gating import (
    HOST_CHAT_PATHS_PROVIDER,
    HOST_CHAT_VISION_PROVIDERS,
    DEFAULT_VISION_ANALYSIS_PROMPT,
    VISION_SCHEMA_REFERENCE,
)
from src.domains.media_analysis.utils.clip_identity_registry import (
    resolve_output_root as resolve_media_analysis_output_root,
    short_hash,
    slugify,
)
from src.domains.media_analysis.utils.capabilities_and_planning import (
    build_plan as build_media_analysis_plan,
    detect_capabilities as detect_media_analysis_capabilities,
    install_guidance as media_analysis_install_guidance,
)
from src.domains.media_analysis.utils.execute_engine import (
    execute_plan_async as execute_media_analysis_plan_async,
    plan_requires_capabilities as media_analysis_plan_requires_capabilities,
)
from src.domains.media_analysis.utils.reports import (
    build_coverage_report as build_media_analysis_coverage_report,
    cleanup_artifacts as cleanup_media_analysis_artifacts,
    commit_visual_analysis,
    load_report as load_media_analysis_report,
    summarize_reports as summarize_media_analysis_reports,
)
from src.domains.media_analysis.utils.analysis_index_build import build_analysis_index
from src.domains.media_analysis.utils.analysis_index_query import (
    analysis_index_status,
    query_analysis_index,
)
from src.domains.media_analysis.utils.sync_detection import detect_sync_events_for_records as detect_media_sync_events
from src.core import actor_identity, background_jobs, resolve_busy
from src.core.resolve_busy import long_resolve_op
from src.domains.media_analysis.utils.media_analysis_jobs import (
    MEDIA_EXTENSIONS,
    batch_job_status as media_analysis_batch_job_status,
    cancel_batch_job as cancel_media_analysis_batch_job,
    create_batch_job as create_media_analysis_batch_job,
    list_batch_jobs as list_media_analysis_batch_jobs,
    resume_batch_job as resume_media_analysis_batch_job,
    run_batch_job_slice as run_media_analysis_batch_job_slice,
)
from src.core.platform import get_resolve_paths, get_resolve_plugin_paths
from src.domains.color_grade.utils.lut_paths import master_lut_dir, ensure_lut_in_master
from src.domains.extension_authoring.utils import fuse_templates, dctl_templates, script_templates
from src.domains.timeline_edit.utils.timeline_title_text import (
    candidate_title_property_keys as _candidate_title_property_keys,
    plain_to_minimal_styled_xml as _plain_to_minimal_styled_xml,
    timeline_item_get_property_map as _timeline_item_get_property_map,
)
from src.domains.media_pool_ingest.utils.multicam import build_multicam_setup_plan
from src.domains.timeline_conform_interchange.utils.timeline_xml import analyze_timeline_xml, sanitize_timeline_xml
from src.domains.fusion_composition.utils.fusion_group_settings import (
    FUSION_COMMIT_CHECKLIST,
    FUSION_GROUP_GUARDRAILS,
    default_backup_path,
    parse_setting_file,
    splice_inputs_block,
)
from src.core import analysis_runs as _analysis_runs
from src.core import brain_edits as _brain_edits
from src.domains.auto_edit.utils import edit_engine as _edit_engine_mod
from src.domains.auto_edit.utils import auto_edit as _auto_edit_mod
from src.domains.auto_edit.utils import montage_edit as _montage_edit_mod
from src.domains.orchestration.utils import orchestrate as _orchestrate_mod
from src.core import advanced_bridge as _advanced_bridge
from src.domains.auto_edit.utils import music_analysis as _music_analysis_mod
from src.domains.media_pool_ingest.utils import media_pool_changes as _media_pool_changes
from src.core import timeline_versioning as _timeline_versioning
from src.domains.project_lifecycle.utils import project_spec as _project_spec
from src.domains.project_lifecycle.utils import project_lint as _project_lint
from src.domains.timeline_edit.utils import clip_query as _clip_query
from src.core import destructive_hook as _destructive_hook
from src.core.destructive_hook import destructive_op as _destructive_op
import uuid as _ledger_uuid
from src.core import resolve_ai_ledger as _resolve_ai_ledger
from src.core import resolve_ai_governance as _resolve_ai_governance
import hashlib as _hashlib
import time as _time
import uuid as _uuid
from mcp.server.fastmcp import Context, FastMCP, Image
from mcp import types as mcp_types

logger = logging.getLogger("resolve-mcp")

from src.server import mcp

from src.core.envelope import (
    ERROR_CATEGORIES,
    _CATEGORY_RETRYABLE_DEFAULT,
    _RETRYABLE_UNSET,
    _callable_method_names,
    _check,
    _err,
    _has_method,
    _ok,
    _requires_method,
    _safe_clip_call,
    _safe_get_property,
    _ser,
    _unknown,
)
from src.core.tool_kernel import (
    _action_help,
    _activate_resolve_window,
    _ai_governance_check,
    _ai_governance_gate,
    _ai_governance_mode,
    _ai_governance_overrides,
    _ai_governance_preset,
    _ai_ledger_root,
    _ai_ledger_timed,
    _confirm_token_fingerprint,
    _confirm_token_gc,
    _confirm_token_required,
    _consume_confirm_token,
    _contact_sheet_png_bytes,
    _contact_sheet_sample_label,
    _draw_rect_rgb,
    _draw_tiny_text_rgb,
    _filter_to_keys,
    _find_timeline_item_by_id,
    _first_param,
    _has_any_param,
    _is_truncated,
    _issue_confirm_token,
    _media_analysis_effective_preferences,
    _normalize_sampling_mode_default,
    _normalize_setup_choice,
    _normalize_setup_list,
    _normalize_timed_marker_choice,
    _normalize_vision_default,
    _normalize_yes_no_ask,
    _opt_number,
    _path_error,
    _png_chunk,
    _read_json_strict,
    _read_media_analysis_preferences,
    _read_media_analysis_preferences_strict,
    _record_action_outcome,
    _resolve_enum_settings,
    _rgb_to_png_bytes,
    _run_maybe_background,
    _safe_int,
    _sampling_mode_choice_from_params,
    _send_resolve_keystroke_go_to_mark_in,
    _settings_diff,
    _setup_marker_limit,
    _setup_positive_int,
    _setup_text_key,
    _string_list_param,
    _thumbnail_data_to_png_bytes,
    _thumbnail_raw_rgb,
    _timed_marker_choice_from_params,
    _timeline_items_by_ids,
    _timeline_items_by_ids_report,
    _timeline_resolve_item_optional,
    _write_media_analysis_preferences,
)
from src.core.timeline_lookup import (
    _clip_file_size,
    _clip_name,
    _clip_summaries,
    _clips_from_params,
    _coerce_item_list,
    _collect_timeline_items_in_range,
    _current_timeline_frame_id,
    _find_clip,
    _find_clip_with_parent,
    _find_timeline_by_id,
    _find_timeline_by_name,
    _frame_id_to_timecode,
    _frame_int,
    _get_item,
    _get_mp,
    _get_selected_timeline_items,
    _get_tl,
    _metadata_write_field_for_field,
    _probe_keyframes,
    _project_name_and_id,
    _project_summary,
    _range_frames_from_params,
    _range_track_indices,
    _range_track_types,
    _safe_timeline_item_id,
    _safe_timeline_item_name,
    _timecode_to_frame_id,
    _timeline_by_selector,
    _timeline_fps,
    _timeline_frame_id_to_timecode,
    _timeline_item_duration,
    _timeline_item_ids,
    _timeline_item_media_pool_item,
    _timeline_item_probe,
    _timeline_item_source_start,
    _timeline_item_summary,
    _timeline_item_track_info,
    _timeline_start_frame,
    _timeline_timecode_to_frame_id,
    _timeline_track_count,
    _track_items_sorted,
    _track_selector,
)
from src.core.live_connection import (
    get_resolve,
    _destructive_versioning_provider,
)

def _copy_grades(source_item, duplicate_item):
    try:
        return {"success": bool(source_item.CopyGrades([duplicate_item]))}
    except Exception as exc:
        return {"success": False, "error": f"CopyGrades failed: {exc}"}


def _extract_clip_frames(clip, p: Dict[str, Any]) -> Dict[str, Any]:
    """Extract still frames from a clip's source media at given timestamps.

    Source-safe: reads the source file with ffmpeg and writes JPEGs to a scratch
    output directory only — it never modifies, transcodes, or proxies the source.
    `timestamps` is a list of seconds. Returns the written frame paths.
    """
    try:
        src = clip.GetClipProperty("File Path")
    except Exception:
        src = None
    if not src or not os.path.isfile(src):
        return _err("Clip has no readable source file (File Path)")
    timestamps = p.get("timestamps")
    if not isinstance(timestamps, list) or not timestamps:
        return _err("extract_frames requires 'timestamps' (a non-empty list of seconds)")
    if not shutil.which("ffmpeg"):
        return _err("ffmpeg not found on PATH")
    out_dir = p.get("output_dir") or tempfile.mkdtemp(prefix="mcp_frames_")
    try:
        os.makedirs(out_dir, exist_ok=True)
    except OSError as exc:
        return _err(f"Could not create output_dir: {exc}")
    paths, errors = [], []
    for i, ts in enumerate(timestamps):
        out_path = os.path.join(out_dir, f"frame_{i:04d}.jpg")
        try:
            safe_run(
                ["ffmpeg", "-y", "-ss", str(float(ts)), "-i", src,
                 "-frames:v", "1", "-q:v", "2", out_path],
                capture_output=True, timeout=60,
            )
        except (OSError, subprocess.SubprocessError, ValueError) as exc:
            errors.append({"timestamp": ts, "error": str(exc)})
            continue
        if os.path.isfile(out_path):
            paths.append(out_path)
        else:
            errors.append({"timestamp": ts, "error": "no frame written (timestamp out of range?)"})
    return {
        "success": bool(paths),
        "source": src,
        "output_dir": out_dir,
        "frame_paths": paths,
        "count": len(paths),
        "errors": errors,
    }

def _normalize_cdl(cdl):
    """Normalize CDL payloads to the string format Resolve's SetCDL expects."""
    return normalize_cdl_payload(cdl)

def _grade_temp_path_ok(path):
    from src.domains.render_deliver.actions import _render_temp_path_ok
    return _render_temp_path_ok(path)

def _resolve_lut_export_type(export_type, resolve_obj=None):
    if isinstance(export_type, int) and not isinstance(export_type, bool):
        return export_type, None
    raw = str(export_type if export_type is not None else "33ptcube").strip()
    key = raw.lower().replace("-", "").replace("_", "").replace(" ", "")
    const_name = _LUT_EXPORT_TYPES.get(key)
    if not const_name and raw.startswith("EXPORT_LUT_"):
        const_name = raw
    if not const_name:
        return None, _err(f"Unknown LUT export type: {raw}")
    if resolve_obj and hasattr(resolve_obj, const_name):
        return getattr(resolve_obj, const_name), None
    return const_name, None

def _validate_cdl_payload(cdl):
    if not isinstance(cdl, dict):
        return None, _err(
            "cdl must be an object",
            code="INVALID_CDL",
            category="invalid_input",
            remediation="Pass cdl as a dict with NodeIndex, Slope, Offset, Power, Saturation.",
        )
    errors = []
    node_index = cdl.get("NodeIndex", 1)
    if isinstance(node_index, bool):
        errors.append("NodeIndex must be an integer")
    else:
        try:
            node_index = int(node_index)
            if node_index < 1:
                errors.append("NodeIndex must be >= 1")
        except (TypeError, ValueError):
            errors.append("NodeIndex must be an integer")
    normalized = dict(cdl)
    normalized["NodeIndex"] = node_index
    for key in ("Slope", "Offset", "Power"):
        value = cdl.get(key, [1.0, 1.0, 1.0] if key != "Offset" else [0.0, 0.0, 0.0])
        if isinstance(value, str):
            parts = value.split()
        elif isinstance(value, (list, tuple)):
            parts = list(value)
        else:
            errors.append(f"{key} must be a 3-value list or space-separated string")
            continue
        if len(parts) != 3:
            errors.append(f"{key} must contain exactly 3 values")
            continue
        try:
            normalized[key] = [float(part) for part in parts]
        except (TypeError, ValueError):
            errors.append(f"{key} values must be numeric")
    saturation = cdl.get("Saturation", 1.0)
    try:
        normalized["Saturation"] = float(saturation)
    except (TypeError, ValueError):
        errors.append("Saturation must be numeric")
    return {"valid": not errors, "errors": errors, "cdl": normalized}, None

def _graph_snapshot(g, *, include_nodes=True, max_nodes=3):
    if not g:
        return {"available": False}
    out = {
        "available": True,
        "methods": _callable_method_names(g, _GRAPH_METHODS),
        "num_nodes": None,
        "nodes": [],
        "errors": [],
    }
    try:
        out["num_nodes"] = g.GetNumNodes()
    except Exception as exc:
        out["errors"].append({"method": "GetNumNodes", "error": str(exc)})
        return out
    if not include_nodes:
        return out
    try:
        max_nodes = max(0, int(max_nodes))
    except (TypeError, ValueError):
        max_nodes = 3
    for node_index in range(1, min(out["num_nodes"] or 0, max_nodes) + 1):
        row = {"node_index": node_index}
        for key, method_name in (
            ("lut", "GetLUT"),
            ("cache_mode", "GetNodeCacheMode"),
            ("label", "GetNodeLabel"),
            ("tools", "GetToolsInNode"),
        ):
            if not _has_method(g, method_name):
                continue
            try:
                row[key] = _ser(getattr(g, method_name)(node_index))
            except Exception as exc:
                row.setdefault("errors", []).append({"method": method_name, "error": str(exc)})
        out["nodes"].append(row)
    return out

def _color_graph_from_params(proj, item, p: Dict[str, Any]):
    source = p.get("source", "item")
    if source == "item":
        graph = item.GetNodeGraph(p["layer_index"]) if "layer_index" in p else item.GetNodeGraph()
        return graph, "item", None
    if source == "timeline":
        _, tl, err = _get_tl()
        if err:
            return None, source, err
        return tl.GetNodeGraph(), "timeline", None
    if source in ("color_group_pre", "color_group_post"):
        group_name = p.get("group_name")
        if not group_name:
            return None, source, _err("group_name is required for color group graph sources")
        for group in proj.GetColorGroupsList() or []:
            if group.GetName() == group_name:
                graph = group.GetPreClipNodeGraph() if source == "color_group_pre" else group.GetPostClipNodeGraph()
                return graph, source, None
        return None, source, _err(f"Color group '{group_name}' not found")
    return None, source, _err(f"Unknown color graph source: {source}")

def _grade_version_snapshot(item, p: Dict[str, Any]):
    out = {"current": None, "local": [], "remote": [], "errors": []}
    try:
        out["current"] = _ser(item.GetCurrentVersion())
    except Exception as exc:
        out["errors"].append({"method": "GetCurrentVersion", "error": str(exc)})
    for version_type, key in ((0, "local"), (1, "remote")):
        try:
            out[key] = _ser(item.GetVersionNameList(version_type) or [])
        except Exception as exc:
            out["errors"].append({"method": f"GetVersionNameList({version_type})", "error": str(exc)})
    return out

def _grade_item_snapshot(item, proj=None, p: Optional[Dict[str, Any]] = None):
    p = p or {}
    out = {
        "name": None,
        "id": None,
        "methods": _callable_method_names(item, _COLOR_ITEM_METHODS),
        "versions": _grade_version_snapshot(item, p),
        "node_graph": None,
        "color_group": None,
        "cache": {},
        "errors": [],
    }
    for key, method_name in (("name", "GetName"), ("id", "GetUniqueId")):
        if _has_method(item, method_name):
            try:
                out[key] = getattr(item, method_name)()
            except Exception as exc:
                out["errors"].append({"method": method_name, "error": str(exc)})
    try:
        graph = item.GetNodeGraph(p["layer_index"]) if "layer_index" in p else item.GetNodeGraph()
        out["node_graph"] = _graph_snapshot(graph, include_nodes=p.get("include_nodes", True), max_nodes=p.get("max_nodes", 3))
    except Exception as exc:
        out["node_graph"] = {"available": False, "error": str(exc)}
    try:
        group = item.GetColorGroup()
        out["color_group"] = group.GetName() if group else None
    except Exception as exc:
        out["errors"].append({"method": "GetColorGroup", "error": str(exc)})
    for key, method_name in (
        ("color_output", "GetIsColorOutputCacheEnabled"),
        ("fusion_output", "GetIsFusionOutputCacheEnabled"),
    ):
        if _has_method(item, method_name):
            try:
                out["cache"][key] = _ser(getattr(item, method_name)())
            except Exception as exc:
                out["errors"].append({"method": method_name, "error": str(exc)})
    return out

def _grade_capabilities(item, proj):
    gallery = proj.GetGallery() if proj and _has_method(proj, "GetGallery") else None
    groups = proj.GetColorGroupsList() if proj and _has_method(proj, "GetColorGroupsList") else []
    return {
        "item_methods": _callable_method_names(item, _COLOR_ITEM_METHODS),
        "graph_sources": ["item", "timeline", "color_group_pre", "color_group_post"],
        "graph_methods": _GRAPH_METHODS,
        "lut_export_types": sorted(set(_LUT_EXPORT_TYPES.values())),
        "version_types": {"local": 0, "remote": 1},
        "grade_modes": {"no_keyframes": 0, "source_timecode_aligned": 1, "start_frames_aligned": 2},
        "gallery_available": gallery is not None,
        "color_group_count": len(groups or []),
        "guards": {
            "safe_export_lut_requires_temp_path": True,
            "safe_apply_drx_requires_temp_path_by_default": True,
            "safe_copy_grade_requires_target_timeline_item_ids": True,
            "ai_tools_report_callability_but_are_not_forced_by_boundary_report": True,
        },
        "boundaries": [
            "Node graph internals are only partially inspectable through Resolve's public API.",
            "ApplyGradeFromDRX replaces the target graph; there is no append mode.",
            "LUT export writes files and is guarded to temp paths by default.",
            "Stabilize, Smart Reframe, and Magic Mask can be asynchronous and page dependent.",
        ],
    }

def _probe_color_node_graph(proj, item, p: Dict[str, Any]):
    graph, source, err = _color_graph_from_params(proj, item, p)
    if err:
        return err
    snapshot = _graph_snapshot(
        graph,
        include_nodes=p.get("include_nodes", True),
        max_nodes=p.get("max_nodes", 3),
    )
    snapshot["source"] = source
    return snapshot

def _safe_set_cdl(item, p: Dict[str, Any]):
    validation, err = _validate_cdl_payload(p.get("cdl"))
    if err:
        return err
    if not validation["valid"]:
        return {"success": False, "validation": validation}
    normalized = _normalize_cdl(validation["cdl"])
    if p.get("dry_run"):
        return _ok(validation=validation, normalized=normalized)
    return {
        "success": bool(item.SetCDL(normalized)),
        "validation": validation,
        "normalized": normalized,
    }

def _timeline_items_for_grade_copy(tl, target_ids):
    targets = []
    missing = set(target_ids or [])
    if not target_ids:
        return targets, []
    for track_index in range(1, tl.GetTrackCount("video") + 1):
        for candidate in (tl.GetItemListInTrack("video", track_index) or []):
            item_id = candidate.GetUniqueId()
            if item_id in missing:
                targets.append(candidate)
                missing.remove(item_id)
    return targets, sorted(missing)

def _safe_copy_grade(item, p: Dict[str, Any]):
    target_ids = p.get("target_ids") or []
    if not isinstance(target_ids, list) or not target_ids:
        return _err("target_ids must be a non-empty list of timeline item IDs",
                    code="MISSING_TARGET_IDS", category="invalid_input")
    _, tl, err = _get_tl()
    if err:
        return err
    targets, missing = _timeline_items_for_grade_copy(tl, target_ids)
    target_summaries = [_timeline_item_summary(target) for target in targets]
    if p.get("dry_run"):
        return _ok(targets=target_summaries, missing=missing, would_copy=not missing)
    if missing:
        return {"success": False, "targets": target_summaries, "missing": missing}
    # F6 / B2 — Whole-grade copy is a destructive replacement on every target.
    # Gameplan §3 B2 lists safe_copy_grade among ops that must require confirmation.
    if "confirm_token" not in p and "confirmToken" not in p:
        if _confirm_token_required():
            preview = {
                "operation": "safe_copy_grade",
                "warning": "Replaces the entire node graph on every successfully resolved target item.",
                "target_count": len(target_summaries),
                "target_ids": [t.get("timeline_item_id") for t in target_summaries],
            }
            return _issue_confirm_token(action="safe_copy_grade", params=p, preview=preview)
    blocked = _consume_confirm_token(action="safe_copy_grade", params=p)
    if blocked:
        return blocked
    return {"success": bool(item.CopyGrades(targets)), "targets": target_summaries, "missing": missing}

def _safe_export_lut(item, p: Dict[str, Any]):
    path = p.get("path")
    if not path:
        return _err("path is required")
    if p.get("require_temp_path", True) and not _grade_temp_path_ok(path):
        return _err("path must be under the system temp directory unless require_temp_path=False")
    folder = os.path.dirname(os.path.abspath(path))
    if folder:
        os.makedirs(folder, exist_ok=True)
    resolve_obj = get_resolve()
    export_type, type_err = _resolve_lut_export_type(p.get("type", "33ptcube"), resolve_obj)
    if type_err:
        return type_err
    if p.get("dry_run"):
        return _ok(path=path, type=export_type, would_export=True)
    before_exists = os.path.exists(path)
    success = bool(item.ExportLUT(export_type, path))
    return {
        "success": success,
        "path": path,
        "type": export_type,
        "file_exists": os.path.exists(path),
        "size": os.path.getsize(path) if os.path.exists(path) else 0,
        "overwrote_existing": before_exists and os.path.exists(path),
    }

def _safe_apply_drx(proj, item, p: Dict[str, Any]):
    path = p.get("path")
    if not path:
        return _err("path is required", code="MISSING_PATH", category="invalid_input")
    if not os.path.isfile(path):
        return _err(f"DRX file not found: {path}", code="DRX_NOT_FOUND", category="invalid_input")
    if p.get("require_temp_path", True) and not _grade_temp_path_ok(path):
        return _err("DRX path must be under the system temp directory unless require_temp_path=False",
                    code="DRX_PATH_NOT_TEMP", category="invalid_input")
    graph, source, err = _color_graph_from_params(proj, item, p)
    if err:
        return err
    if not _has_method(graph, "ApplyGradeFromDRX"):
        return _err(f"{source} graph does not expose ApplyGradeFromDRX",
                    code="APPLY_DRX_UNSUPPORTED", category="unsupported")
    if p.get("dry_run"):
        return _ok(path=path, source=source, grade_mode=p.get("grade_mode", p.get("mode", 0)), would_apply=True)
    # B2 — Whole-grade replacement is catastrophic; require confirmation.
    if "confirm_token" not in p and "confirmToken" not in p:
        if _confirm_token_required():
            preview = {
                "operation": "safe_apply_drx",
                "warning": "REPLACES the target graph entirely. There is no append mode.",
                "path": path,
                "source": source,
                "grade_mode": p.get("grade_mode", p.get("mode", 0)),
            }
            return _issue_confirm_token(action="safe_apply_drx", params=p, preview=preview)
    blocked = _consume_confirm_token(action="safe_apply_drx", params=p)
    if blocked:
        return blocked
    success = bool(graph.ApplyGradeFromDRX(path, p.get("grade_mode", p.get("mode", 0))))
    return {"success": success, "path": path, "source": source}

def _grade_version_restore(item, p: Dict[str, Any]):
    name = p.get("name")
    if not name:
        return _err("name is required")
    version_type = p.get("type", 0)
    snapshot = _grade_version_snapshot(item, p)
    names = snapshot["local"] if version_type == 0 else snapshot["remote"]
    if name not in names:
        return {"success": False, "snapshot": snapshot, "error": f"Version '{name}' not found"}
    if p.get("dry_run"):
        return _ok(snapshot=snapshot, would_load=name, type=version_type)
    return {"success": bool(item.LoadVersionByName(name, version_type)), "snapshot": snapshot}

def _color_group_capabilities(proj):
    groups = proj.GetColorGroupsList() or []
    return {
        "count": len(groups),
        "groups": [
            {
                "name": group.GetName(),
                "pre_clip_graph": _graph_snapshot(group.GetPreClipNodeGraph(), include_nodes=False),
                "post_clip_graph": _graph_snapshot(group.GetPostClipNodeGraph(), include_nodes=False),
            }
            for group in groups
        ],
        "project_methods": _callable_method_names(proj, ["GetColorGroupsList", "AddColorGroup", "DeleteColorGroup"]),
    }

def _gallery_capabilities(proj):
    gallery = proj.GetGallery()
    if not gallery:
        return {"available": False}
    still_albums = gallery.GetGalleryStillAlbums() or []
    power_albums = gallery.GetGalleryPowerGradeAlbums() or []
    return {
        "available": True,
        "still_albums": [{"name": gallery.GetAlbumName(album), "index": index} for index, album in enumerate(still_albums)],
        "power_grade_albums": [{"name": gallery.GetAlbumName(album), "index": index} for index, album in enumerate(power_albums)],
        "current_album_available": gallery.GetCurrentStillAlbum() is not None,
        "methods": _callable_method_names(
            gallery,
            [
                "GetAlbumName",
                "SetAlbumName",
                "GetCurrentStillAlbum",
                "SetCurrentStillAlbum",
                "GetGalleryStillAlbums",
                "GetGalleryPowerGradeAlbums",
                "CreateGalleryStillAlbum",
                "CreateGalleryPowerGradeAlbum",
            ],
        ),
    }

def _grade_boundary_report(proj, item, p: Dict[str, Any]):
    report = {
        "capabilities": _grade_capabilities(item, proj),
        "item": _grade_item_snapshot(item, proj, p),
        "color_groups": _color_group_capabilities(proj),
        "gallery": _gallery_capabilities(proj),
    }
    if p.get("include_timeline_graph", True):
        report["timeline_graph"] = _probe_color_node_graph(proj, item, {"source": "timeline", "include_nodes": False})
    return report

def _bulk_match_to_hero(proj, p: Dict[str, Any]) -> Dict[str, Any]:
    """C1 — map-reduce shot matching: propose per-target CDLs or copy-grade plans from a hero.

    Methods:
      - copy_grade: emit a plan to CopyGrades from hero to each target. Execute uses hero.CopyGrades([targets]).
      - cdl_delta: NOT YET IMPLEMENTED — returns invalid_input with a clear remediation.

    Two-step contract:
      1. First call (no confirm_token, dry_run=true by default): returns {proposals, blocked, confirm_token}
      2. Second call with confirm_token: executes the planned mutations.
    """
    hero_id = p.get("hero_id")
    target_ids = p.get("target_ids") or []
    method = (p.get("method") or "copy_grade").strip().lower()
    if not hero_id:
        return _err("hero_id is required", code="MISSING_HERO_ID", category="invalid_input",
                    remediation="Pass hero_id: the timeline item unique ID for the reference shot.")
    if not isinstance(target_ids, list) or not target_ids:
        return _err("target_ids must be a non-empty list of timeline item IDs",
                    code="MISSING_TARGETS", category="invalid_input")
    if method not in {"copy_grade", "cdl_delta"}:
        return _err(f"method must be 'copy_grade' or 'cdl_delta' (got {method!r})",
                    code="INVALID_METHOD", category="invalid_input")

    _, tl, err = _get_tl()
    if err:
        return err

    # Resolve hero
    hero = _find_timeline_item_by_id(tl, hero_id)
    if hero is None:
        return _err(f"hero item not found in current timeline: {hero_id}",
                    code="HERO_NOT_FOUND", category="invalid_input",
                    remediation="Call timeline(action='get_items', ...) to enumerate valid timeline item IDs.")

    # Resolve hero evidence base (used for the leading line + min_trust gate)
    hero_evidence = _grade_evidence_base(proj, hero, {"include_coverage": False, "max_nodes": 4})
    hero_summary = {
        "id": hero_id,
        "name": getattr(hero, "GetName", lambda: None)(),
        "evidence_base": hero_evidence.get("evidence_base"),
    }

    # Resolve targets
    targets: List[Any] = []
    blocked: List[Dict[str, Any]] = []
    found_ids = set()
    for track_index in range(1, tl.GetTrackCount("video") + 1):
        for it in (tl.GetItemListInTrack("video", track_index) or []):
            try:
                uid = it.GetUniqueId()
            except Exception:
                continue
            if uid in target_ids and uid != hero_id:
                targets.append(it)
                found_ids.add(uid)
    for tid in target_ids:
        if tid not in found_ids and tid != hero_id:
            blocked.append({"target_id": tid, "reason": "not_found_in_current_timeline",
                            "error_code": "TARGET_NOT_FOUND"})

    # Build proposals
    proposals: List[Dict[str, Any]] = []
    if method == "copy_grade":
        for it in targets:
            try:
                name = it.GetName()
            except Exception:
                name = None
            proposals.append({
                "target_id": it.GetUniqueId(),
                "name": name,
                "method": "copy_grade",
                "copy_source": hero_id,
                "warnings": [],
            })
    else:  # cdl_delta
        for it in targets:
            try:
                name = it.GetName()
            except Exception:
                name = None
            proposals.append({
                "target_id": it.GetUniqueId(),
                "name": name,
                "method": "cdl_delta",
                "proposed_cdl": None,
                "warnings": [
                    "cdl_delta is not yet implemented — use method='copy_grade' for now, "
                    "or hand-roll safe_set_cdl per target."
                ],
            })
        # Return early as a structured invalid_input so the caller doesn't proceed to execute.
        return _err(
            "method='cdl_delta' is not implemented yet",
            code="CDL_DELTA_UNIMPLEMENTED",
            category="unsupported",
            remediation="Use method='copy_grade' or call safe_set_cdl per target with hand-rolled values.",
        )

    dry_run = bool(p.get("dry_run", True))
    payload: Dict[str, Any] = {
        "hero": hero_summary,
        "proposals": proposals,
        "blocked": blocked,
        "method": method,
        "dry_run": dry_run,
    }

    if dry_run:
        # A dry-run that produced at least one proposal is a successful
        # validation, even if some targets are blocked — the caller can still
        # act on the resolvable subset. success=False is reserved for the
        # case where the call produced no actionable output.
        payload["success"] = bool(proposals)
        return payload

    # Execute path: confirm-token gated.
    if "confirm_token" not in p and "confirmToken" not in p and _confirm_token_required():
        issued = _issue_confirm_token(
            action="timeline_item_color.bulk_match_to_hero",
            params=p,
            preview={
                "operation": "bulk_match_to_hero",
                "method": method,
                "hero_id": hero_id,
                "target_count": len(proposals),
                "blocked": blocked,
                "warning": "Mutates grade state on every successfully resolved target item.",
            },
        )
        issued.update(payload)  # surface proposals in the issued response too
        return issued
    blocked_token = _consume_confirm_token(action="timeline_item_color.bulk_match_to_hero", params=p)
    if blocked_token:
        return blocked_token

    if blocked:
        payload["success"] = False
        payload["error_summary"] = "refusing to execute because some targets could not be resolved"
        return payload

    # Execute copy_grade in one API call.
    try:
        success = bool(hero.CopyGrades(targets))
    except Exception as exc:
        return _err(f"CopyGrades failed: {exc}",
                    code="COPY_GRADES_FAILED", category="resolve_api_failed", retryable=False)
    payload["success"] = success
    payload["executed"] = True
    return payload

def _propose_grade_validate(p: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """Validate a propose_grade payload. Returns None if valid, else a structured error."""
    if not isinstance(p, dict):
        return _err("params must be an object", code="INVALID_PARAMS", category="invalid_input")
    target_id = p.get("target_id")
    if not target_id:
        return _err("target_id is required",
                    code="MISSING_TARGET_ID", category="invalid_input",
                    remediation="Pass target_id: the timeline item unique ID this proposal applies to.")
    evidence_base = p.get("evidence_base")
    if not evidence_base or not isinstance(evidence_base, str):
        return _err("evidence_base is required and must be a non-empty string",
                    code="MISSING_EVIDENCE_BASE", category="invalid_input",
                    remediation="Call timeline_item_color(action='grade_evidence_base') and use its evidence_base string.")
    if not evidence_base.lstrip().lower().startswith("evidence base:"):
        return _err("evidence_base must start with 'evidence base:' — call grade_evidence_base first",
                    code="EVIDENCE_BASE_MALFORMED", category="invalid_input")
    frame_paths = p.get("frame_paths") or []
    if not isinstance(frame_paths, list) or not frame_paths:
        return _err("frame_paths must be a non-empty list of absolute paths",
                    code="MISSING_FRAME_PATHS", category="invalid_input",
                    remediation="Include the frame(s) used to make this grade decision.")
    operation_class = (p.get("operation_class") or "").strip().lower()
    if operation_class not in _PROPOSE_GRADE_OPERATION_CLASSES:
        return _err(
            f"operation_class must be one of {sorted(_PROPOSE_GRADE_OPERATION_CLASSES)} (got {operation_class!r})",
            code="INVALID_OPERATION_CLASS", category="invalid_input",
        )
    artifact = p.get("cdl_delta_or_artifact") or {}
    if operation_class == "direct":
        cdl = artifact.get("cdl") if isinstance(artifact, dict) else None
        if not cdl:
            return _err("operation_class='direct' requires cdl_delta_or_artifact.cdl",
                        code="DIRECT_REQUIRES_CDL", category="invalid_input")
    elif operation_class == "opaque":
        if not (isinstance(artifact, dict) and (artifact.get("drx_path") or artifact.get("copy_source"))):
            return _err("operation_class='opaque' requires drx_path or copy_source",
                        code="OPAQUE_REQUIRES_ARTIFACT", category="invalid_input")
    elif operation_class == "asset":
        if not (isinstance(artifact, dict) and artifact.get("lut_path")):
            return _err("operation_class='asset' requires lut_path",
                        code="ASSET_REQUIRES_LUT_PATH", category="invalid_input")
    elif operation_class == "review_only":
        if len(frame_paths) < 2:
            return _err("operation_class='review_only' requires at least 2 frame_paths (e.g. untreated + current)",
                        code="REVIEW_NEEDS_FRAMES", category="invalid_input")
    elif operation_class == "unsupported":
        expl = p.get("unsupported_request_explanation")
        if not expl or not isinstance(expl, str):
            return _err(
                "operation_class='unsupported' requires unsupported_request_explanation: str",
                code="UNSUPPORTED_NEEDS_EXPLANATION", category="invalid_input",
            )
    return None

def _propose_grade(proj, p: Dict[str, Any]) -> Dict[str, Any]:
    """C2 — Structured-output action. Validates a color recommendation as a proper artifact.

    With execute=False (default): returns {accepted: True, plan_id, validation, preview_path?}.
    With execute=True: routes through bulk_match_to_hero / safe_set_cdl / safe_apply_drx
    based on operation_class. Confirm_token gating applies as usual.
    """
    err = _propose_grade_validate(p)
    if err:
        return err

    plan_id = f"plan_{_uuid.uuid4().hex[:12]}"
    operation_class = p["operation_class"].strip().lower()
    payload: Dict[str, Any] = {
        "accepted": True,
        "plan_id": plan_id,
        "operation_class": operation_class,
        "target_id": p["target_id"],
        "evidence_base": p["evidence_base"],
        "frame_paths": list(p.get("frame_paths") or []),
        "validation": {"valid": True, "notes": []},
    }
    if not p.get("execute"):
        payload["executed"] = False
        return payload

    # review_only never mutates — no confirm_token needed.
    if operation_class == "review_only":
        payload["executed"] = False
        payload["validation"]["notes"].append("review_only: no mutation; frame references recorded.")
        return payload

    # Execute path for mutating classes — gate behind confirm_token like other destructive ops.
    if "confirm_token" not in p and "confirmToken" not in p and _confirm_token_required():
        issued = _issue_confirm_token(
            action="timeline_item_color.propose_grade",
            params=p,
            preview={
                "operation": "propose_grade.execute",
                "plan_id": plan_id,
                "operation_class": operation_class,
                "target_id": p["target_id"],
                "warning": "Mutates grade state on the target item.",
            },
        )
        issued.update(payload)
        return issued
    blocked = _consume_confirm_token(action="timeline_item_color.propose_grade", params=p)
    if blocked:
        return blocked

    # Routing — operation_class determines which mutator runs.
    # For C2 v1 we wire the two simple paths (direct CDL, review_only no-op) and leave
    # opaque/asset as recorded plans for the caller to execute via the matching safe_* action.
    if operation_class == "review_only":
        payload["executed"] = False
        payload["validation"]["notes"].append("review_only: no mutation; frame references recorded.")
        return payload

    if operation_class == "direct":
        # Resolve the target item via timeline lookup, then call safe_set_cdl.
        _, tl, err = _get_tl()
        if err:
            return err
        target_item = _find_timeline_item_by_id(tl, p["target_id"])
        if target_item is None:
            return _err(f"target_id not found in current timeline: {p['target_id']}",
                        code="TARGET_NOT_FOUND", category="invalid_input")
        cdl_payload = (p.get("cdl_delta_or_artifact") or {}).get("cdl")
        result = _safe_set_cdl(target_item, {"cdl": cdl_payload})
        payload["executed"] = True
        payload["execution"] = result
        payload["success"] = bool(result.get("success"))
        # F5 — propose_grade.execute writes a brain_edits row per gameplan §3 C2:
        # "metric=color_intent, rationale=<evidence_base>". The inner _safe_set_cdl
        # call doesn't go through the destructive_hook wrapper, so we log here.
        if payload["success"]:
            try:
                ctx = _destructive_versioning_provider()
                if ctx is not None:
                    _, proj_h, project_root, project_name = ctx
                    run_id = _destructive_hook._extract_analysis_run_id(p, project_root=project_root)
                    initiator = _destructive_hook._extract_initiator(p)
                    timeline_name = None
                    try:
                        cur_tl = proj_h.GetCurrentTimeline()
                        if cur_tl is not None:
                            timeline_name = cur_tl.GetName()
                    except Exception:
                        timeline_name = None
                    _brain_edits.log_brain_edit(
                        project_root=project_root,
                        analysis_run_id=run_id,
                        edit_type="timeline_item_color.propose_grade",
                        tool_name="timeline_item_color",
                        action_name="propose_grade",
                        timeline_before=timeline_name,
                        timeline_after=timeline_name,
                        target_metric=_brain_edits.METRIC_COLOR_INTENT,
                        rationale=p.get("evidence_base"),
                        params={
                            "target_id": p.get("target_id"),
                            "operation_class": operation_class,
                            "plan_id": plan_id,
                            "frame_paths": list(p.get("frame_paths") or []),
                            "cdl": cdl_payload,
                        },
                        result_summary={
                            "success": payload["success"],
                            "normalized": result.get("normalized"),
                        },
                        project_name=project_name,
                        initiator=initiator,
                    )
            except Exception as exc:
                logger.warning("propose_grade brain_edit log failed (non-fatal): %s", exc)
        return payload

    # opaque/asset/unsupported require the caller to follow up with the matching safe_* action.
    payload["executed"] = False
    payload["validation"]["notes"].append(
        f"operation_class={operation_class}: plan accepted but propose_grade does not execute this class directly. "
        "Use the matching safe_* action (safe_apply_drx, graph.set_lut, etc.)."
    )
    return payload

def _grade_evidence_line(*, item_name, version_label, num_nodes, has_lut, group_name,
                        coverage_summary, coverage_warnings_count):
    """Compose the one-line evidence_base sentence for color recommendations."""
    bits = []
    name = item_name or "current item"
    parts = []
    if version_label:
        parts.append(f"Version {version_label}")
    if num_nodes is not None:
        parts.append(f"{num_nodes} nodes")
    if has_lut:
        parts.append("LUT")
    if group_name:
        parts.append(f"group={group_name}")
    grade_state = f" ({', '.join(parts)})" if parts else " (default graph)"
    bits.append(f"evidence base: hero shot {name} graded{grade_state}")
    if coverage_summary is not None:
        total = coverage_summary.get("clips_total", 0)
        analyzed = coverage_summary.get("clips_analyzed", 0)
        bits.append(f"{analyzed} of {total} target shots have current visual reports")
        relink = coverage_summary.get("clips_reuse_blocked", 0) + coverage_summary.get("clips_superseded_by_relink", 0)
        if relink:
            bits.append(f"{relink} superseded_by_relink")
    if coverage_warnings_count:
        bits.append(f"{coverage_warnings_count} warnings")
    return "; ".join(bits)

def _grade_evidence_base(proj, item, p: Dict[str, Any]) -> Dict[str, Any]:
    """Composite read: grade version snapshot + node graph + color group + coverage.

    Pure read; never mutates. Mirrors media_analysis.coverage_report's
    `evidence_base` line so color recommendations lead with one composed
    summary instead of synthesizing across three calls.

    Returns: {evidence_base: str, structured: {version_snapshot, node_graph,
              color_group, coverage?, capabilities}, warnings: [...]}
    """
    from src.domains.media_analysis.actions import _media_analysis_records_from_target
    structured: Dict[str, Any] = {}
    warnings: List[str] = []

    # Version snapshot
    snap = _grade_version_snapshot(item, p)
    structured["version_snapshot"] = snap
    current_version = snap.get("current")
    version_label = None
    if isinstance(current_version, dict):
        # Resolve's GetCurrentVersion returns {"versionName": ..., "versionType": ...}
        # (camelCase). Accept the historical PascalCase keys too for safety.
        version_label = (
            current_version.get("versionName")
            or current_version.get("VersionName")
            or current_version.get("name")
        )
    elif isinstance(current_version, str):
        version_label = current_version
    # Strip a leading "Version " prefix so the formatted line doesn't duplicate
    # it ("Version Version 1").
    if isinstance(version_label, str):
        stripped = version_label.strip()
        if stripped.lower().startswith("version "):
            stripped = stripped[len("version "):].strip()
        version_label = stripped or None

    # Node graph
    node_graph_probe = _probe_color_node_graph(
        proj, item,
        {"source": p.get("source", "item"), "include_nodes": True, "max_nodes": int(p.get("max_nodes", 8))},
    )
    structured["node_graph"] = node_graph_probe
    num_nodes = node_graph_probe.get("num_nodes")
    has_lut = False
    for n in (node_graph_probe.get("nodes") or []):
        if n.get("lut"):
            has_lut = True
            break

    # Color group
    group_name = None
    try:
        group = item.GetColorGroup()
        group_name = group.GetName() if group else None
    except Exception as exc:
        warnings.append(f"GetColorGroup failed: {exc}")
    structured["color_group"] = {"name": group_name}

    # Item identity
    item_name = None
    try:
        item_name = item.GetName()
    except Exception:
        pass

    # Optional coverage (best-effort; coverage_report needs a media pool item)
    coverage_summary = None
    coverage_warnings_count = 0
    if p.get("include_coverage", True):
        mp_item = _timeline_item_media_pool_item(item)
        if mp_item is not None:
            try:
                project_name = proj.GetName() if proj else None
                project_id = proj.GetUniqueId() if proj else None
                clip_id = mp_item.GetUniqueId()
                target = {"type": "clip", "clip_ids": [clip_id]}
                # Build a minimal records list directly to avoid the media_pool lookup re-entry.
                cov_params = dict(p)
                cov_params["target"] = target
                cov_params.setdefault("min_source_trust", "medium")
                records, normalized_target, cov_warnings, target_err = _media_analysis_records_from_target(
                    proj.GetMediaPool(), cov_params, project=proj,
                )
                if target_err:
                    warnings.append(f"coverage_report skipped: {target_err.get('error', {}).get('message', target_err.get('error'))}")
                else:
                    coverage = build_media_analysis_coverage_report(
                        project_name=project_name,
                        project_id=project_id,
                        records=records or [],
                        target=normalized_target,
                        params=cov_params,
                        capabilities={},
                    )
                    structured["coverage"] = coverage
                    coverage_summary = coverage.get("summary")
                    coverage_warnings_count = len(coverage.get("warnings") or []) + len(cov_warnings or [])
            except Exception as exc:
                warnings.append(f"coverage_report failed: {exc}")
        else:
            warnings.append("no media pool item for coverage_report")

    # Capabilities (small; useful at the top so the agent knows what's possible)
    structured["capabilities"] = _grade_capabilities(item, proj)

    evidence = _grade_evidence_line(
        item_name=item_name,
        version_label=version_label,
        num_nodes=num_nodes,
        has_lut=has_lut,
        group_name=group_name,
        coverage_summary=coverage_summary,
        coverage_warnings_count=coverage_warnings_count,
    )

    return {
        "success": True,
        "evidence_base": evidence,
        "structured": structured,
        "warnings": warnings,
        "notes": [
            "grade_evidence_base is a pure read — it never mutates.",
            "Lead any color recommendation with the `evidence_base` line.",
        ],
    }

@mcp.tool()
@_destructive_op("timeline_item_color")
def timeline_item_color(action: str, params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Color grading, versions, LUTs, cache, and AI tools on timeline items. Identify by track_type, track_index, item_index (item_index is 0-BASED: 0 = first clip; track_index is 1-based).

    <when_to_use>
    - For ANY grade recommendation, lead with action="grade_evidence_base" — composes
      version_snapshot + node_graph + color_group + coverage_report into one line.
    - For batch matching, use bulk_match_to_hero (returns confirm_token; dry_run first).
    - To formalize a recommendation, use propose_grade — validated structured output.
    - PREFER safe_*/probe_*/*_capabilities/*_boundary_report variants over raw mutators.
    </when_to_use>

    <returns>
    grade_evidence_base -> {evidence_base: str, structured: {coverage, version_snapshot, node_graph, color_group, warnings}}
    bulk_match_to_hero  -> {hero, proposals: [{target_id, name, proposed_cdl|copy_source, warnings}], blocked: [...], confirm_token?}
    propose_grade       -> {accepted: bool, validation, plan_id?, preview_path?, error?}
    safe_set_cdl        -> {success, validation, normalized}
    safe_copy_grade     -> {success, targets, missing}
    safe_apply_drx      -> {success, path, source}  # first call may return confirm_token
    grade_capabilities  -> {item_methods, graph_sources, lut_export_types, guards}
    grade_boundary_report -> {capabilities, item, color_groups, gallery}
    All actions may return {"error": {code, category, retryable, message, remediation, reason?}}.
    </returns>

    PREFER the safe_* / probe_* / *_capabilities / *_boundary_report variants. They validate inputs,
    support dry_run, and return structured errors. Raw actions are kept for advanced callers but
    bypass guardrails.

    Read-only / boundary actions (safe to call any time):
      grade_evidence_base(include_coverage?, max_nodes?, ...) -> {evidence_base, structured, warnings}
        PREFERRED PRE-FLIGHT for any color recommendation. Composes version_snapshot +
        node_graph + color_group + coverage_report into one one-line `evidence_base` summary.
        Lead your response with the `evidence_base` line.
        # example: action_help(name='<action_name>')
      grade_capabilities(...) -> {item_methods, graph_sources, lut_export_types, guards}
      probe_grade_item(...) -> {methods, versions, node_graph, color_group, cache}
      probe_node_graph(source?, max_nodes?, ...) -> {available, num_nodes, nodes}
      grade_version_snapshot(...) -> {current, local, remote}
      color_group_capabilities(...) -> {count, groups}
      gallery_capabilities(...) -> {available, still_albums, power_grade_albums}
      grade_boundary_report(...) -> {capabilities, item, color_groups, gallery}
      get_current_version(...) -> {version}
      get_version_names(type?, ...) -> {names}
      get_node_graph(layer_index?, ...) -> {available}
      get_color_group(...) -> {name}
      get_color_cache(...) -> {enabled}
      get_fusion_cache(...) -> {enabled}

    Guarded mutators (PREFERRED for grade work):
      safe_set_cdl(cdl, dry_run?, ...) -> {success, validation, normalized}
        Validates input, supports dry_run, returns normalized CDL. Use this for primary corrections.
        # example: action_help(name='<action_name>')
      safe_copy_grade(target_ids, dry_run?, ...) -> {success, targets, missing}
        Copies grade to N items; dry_run reports targets without mutating.
        # example: action_help(name='<action_name>')
      safe_apply_drx(path, source?, grade_mode?, require_temp_path?) -> {success}
        REPLACES the target graph. Captures a version snapshot first; require_temp_path defaults True.
        # example: action_help(name='<action_name>')
      safe_export_lut(type?, path, require_temp_path?) -> {success, path, size}
        Sandboxed LUT export.
      grade_version_restore(name, type?, dry_run?, ...) -> {success}

    Raw mutators (UNSAFE direct mutation — prefer the safe_* sibling):
      set_cdl(cdl, ...) -> {success}
        UNSAFE. No validation; no dry_run. Prefer safe_set_cdl.
      copy_grades(target_ids, ...) -> {success}
        UNSAFE. No target existence check. Prefer safe_copy_grade.
      export_lut(type, path, ...) -> {success}
        UNSAFE. No path sandboxing. Prefer safe_export_lut.
      reset_all_node_colors(...) -> {success}
        DESTRUCTIVE. Erases per-node color labels on the item's graph.
      add_version(name, type?, ...) -> {success}  — type: 0=local, 1=remote
      load_version(name, type?, ...) -> {success}
      rename_version(old_name, new_name, type?, ...) -> {success}
      delete_version(name, type?, ...) -> {success}
        DESTRUCTIVE. Deletes a named grade version.
      assign_color_group(group_name, ...) -> {success}
      remove_from_color_group(...) -> {success}
      set_color_cache(enabled, ...) -> {success}
      set_fusion_cache(enabled, ...) -> {success}
      stabilize(...) -> {success}
      smart_reframe(...) -> {success}
      create_magic_mask(mode, ...) -> {success}  — mode: "F" forward, "B" backward, "BI" bidirectional
      regenerate_magic_mask(...) -> {success}

    Default: track_type="video", track_index=1, item_index=0

    For long-form per-action guidance and a worked example, call:
      timeline_item_color(action="action_help", params={"name": "<action>"})
    """
    p = params or {}
    if action == "action_help":
        return _action_help("timeline_item_color", p)
    _, item, err = _get_item(p)
    if err:
        return err

    _, proj, _ = _check()

    if action == "grade_capabilities":
        return _grade_capabilities(item, proj)
    elif action == "grade_evidence_base":
        return _grade_evidence_base(proj, item, p)
    elif action == "bulk_match_to_hero":
        return _bulk_match_to_hero(proj, p)
    elif action == "propose_grade":
        return _propose_grade(proj, p)
    elif action == "probe_grade_item":
        return _grade_item_snapshot(item, proj, p)
    elif action == "probe_node_graph":
        return _probe_color_node_graph(proj, item, p)
    elif action == "safe_set_cdl":
        return _safe_set_cdl(item, p)
    elif action == "safe_copy_grade":
        return _safe_copy_grade(item, p)
    elif action == "safe_apply_drx":
        return _safe_apply_drx(proj, item, p)
    elif action == "safe_export_lut":
        return _safe_export_lut(item, p)
    elif action == "grade_version_snapshot":
        return _grade_version_snapshot(item, p)
    elif action == "grade_version_restore":
        return _grade_version_restore(item, p)
    elif action == "color_group_capabilities":
        return _color_group_capabilities(proj)
    elif action == "gallery_capabilities":
        return _gallery_capabilities(proj)
    elif action == "grade_boundary_report":
        return _grade_boundary_report(proj, item, p)
    elif action == "set_cdl":
        # Validate ASC-CDL shape before SetCDL (malformed CDL is silently rejected
        # by Resolve); the raw action shares the safe twin's validator now (P3 #22).
        validation, err = _validate_cdl_payload(p.get("cdl"))
        if err:
            return err
        return {"success": bool(item.SetCDL(_normalize_cdl(validation["cdl"])))}
    elif action == "copy_grades":
        # Find target items by IDs
        _, tl, _ = _get_tl()
        targets = []
        target_ids = set(p["target_ids"])
        if tl:
            for tt in ["video"]:
                for ti in range(1, tl.GetTrackCount(tt) + 1):
                    for it in (tl.GetItemListInTrack(tt, ti) or []):
                        if it.GetUniqueId() in target_ids:
                            targets.append(it)
        return {"success": bool(item.CopyGrades(targets))}
    elif action == "add_version":
        return {"success": bool(item.AddVersion(p["name"], p.get("type", 0)))}
    elif action == "get_current_version":
        return {"version": _ser(item.GetCurrentVersion())}
    elif action == "get_version_names":
        return {"names": _ser(item.GetVersionNameList(p.get("type", 0)))}
    elif action == "load_version":
        return {"success": bool(item.LoadVersionByName(p["name"], p.get("type", 0)))}
    elif action == "rename_version":
        return {"success": bool(item.RenameVersionByName(p["old_name"], p["new_name"], p.get("type", 0)))}
    elif action == "delete_version":
        return {"success": bool(item.DeleteVersionByName(p["name"], p.get("type", 0)))}
    elif action == "get_node_graph":
        g = item.GetNodeGraph(p["layer_index"]) if "layer_index" in p else item.GetNodeGraph()
        return {"available": g is not None}
    elif action == "get_color_group":
        g = item.GetColorGroup()
        return {"name": g.GetName() if g else None}
    elif action == "assign_color_group":
        groups = proj.GetColorGroupsList() or []
        for g in groups:
            if g.GetName() == p["group_name"]:
                return {"success": bool(item.AssignToColorGroup(g))}
        return _err(f"Color group '{p['group_name']}' not found")
    elif action == "remove_from_color_group":
        return {"success": bool(item.RemoveFromColorGroup())}
    elif action == "export_lut":
        return {"success": bool(item.ExportLUT(p["type"], p["path"]))}
    elif action == "get_color_cache":
        return {"enabled": item.GetIsColorOutputCacheEnabled()}
    elif action == "set_color_cache":
        return {"success": bool(item.SetColorOutputCache(p["enabled"]))}
    elif action == "get_fusion_cache":
        return {"enabled": item.GetIsFusionOutputCacheEnabled()}
    elif action == "set_fusion_cache":
        return {"success": bool(item.SetFusionOutputCache(p["enabled"]))}
    elif action == "reset_all_node_colors":
        return {"success": bool(item.ResetAllNodeColors())}
    elif action == "stabilize":
        return {"success": bool(item.Stabilize())}
    elif action == "smart_reframe":
        return {"success": bool(item.SmartReframe())}
    elif action == "create_magic_mask":
        return {"success": bool(item.CreateMagicMask(p.get("mode", "F")))}
    elif action == "regenerate_magic_mask":
        return {"success": bool(item.RegenerateMagicMask())}
    return _unknown(action, ["set_cdl","copy_grades","add_version","get_current_version","get_version_names","load_version","rename_version","delete_version","get_node_graph","get_color_group","assign_color_group","remove_from_color_group","export_lut","get_color_cache","set_color_cache","get_fusion_cache","set_fusion_cache","reset_all_node_colors","stabilize","smart_reframe","create_magic_mask","regenerate_magic_mask","action_help",*_COLOR_GRADE_KERNEL_ACTIONS])

@mcp.tool()
def gallery(action: str, params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Gallery album management.

    Actions:
      get_album_name(album_index?) -> {name}
      set_album_name(name, album_index?) -> {success}
      get_current_album() -> {available}
      set_current_album(album_index) -> {success}
      get_still_albums() -> {albums}
      get_power_grade_albums() -> {albums}
      create_still_album() -> {success}
      create_power_grade_album() -> {success}

    album_index is 0-based into the still albums list.
    """
    p = params or {}
    _, proj, err = _check()
    if err:
        return err

    gal = proj.GetGallery()
    if not gal:
        return _err("Gallery not available")

    if action == "get_album_name":
        albums = gal.GetGalleryStillAlbums() or []
        idx = p.get("album_index", 0)
        if idx < len(albums):
            return {"name": gal.GetAlbumName(albums[idx])}
        return _err("Album index out of range")
    elif action == "set_album_name":
        albums = gal.GetGalleryStillAlbums() or []
        idx = p.get("album_index", 0)
        if idx < len(albums):
            return {"success": bool(gal.SetAlbumName(albums[idx], p["name"]))}
        return _err("Album index out of range")
    elif action == "get_current_album":
        album = gal.GetCurrentStillAlbum()
        return {"available": album is not None}
    elif action == "set_current_album":
        albums = gal.GetGalleryStillAlbums() or []
        idx = p.get("album_index", 0)
        if idx < len(albums):
            return {"success": bool(gal.SetCurrentStillAlbum(albums[idx]))}
        return _err("Album index out of range")
    elif action == "get_still_albums":
        albums = gal.GetGalleryStillAlbums() or []
        return {"albums": [{"name": gal.GetAlbumName(a), "index": i} for i, a in enumerate(albums)]}
    elif action == "get_power_grade_albums":
        albums = gal.GetGalleryPowerGradeAlbums() or []
        return {"albums": [{"name": gal.GetAlbumName(a), "index": i} for i, a in enumerate(albums)]}
    elif action == "create_still_album":
        album = gal.CreateGalleryStillAlbum()
        return _ok() if album else _err("Failed to create still album")
    elif action == "create_power_grade_album":
        album = gal.CreateGalleryPowerGradeAlbum()
        return _ok() if album else _err("Failed to create power grade album")
    return _unknown(action, ["get_album_name","set_album_name","get_current_album","set_current_album","get_still_albums","get_power_grade_albums","create_still_album","create_power_grade_album"])

@mcp.tool()
def gallery_stills(action: str, params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Manage stills in gallery albums (best results on Color page).

    Actions:
      get_stills(album_index?) -> {count}
      get_label(still_index, album_index?) -> {label}
      set_label(still_index, label, album_index?) -> {success}
      import_stills(paths, album_index?) -> {success}
      export_stills(folder_path, prefix?, format?, album_index?) -> {success}
      grab_and_export(folder_path, prefix?, format?, album_index?, delete_after?, cleanup?) -> {files}
      delete_stills(still_indices, album_index?) -> {success}

    album_index defaults to current album. still_index is 0-based.
    format for export: dpx, cin, tif, jpg, png, ppm, bmp, xpm, drx (default: dpx).
    grab_and_export grabs a still from the current frame and exports it immediately,
    keeping the live GalleryStill reference (more reliable than separate grab + export).
    Requires Color page. Automatically produces a companion .drx grade file.
    File data is inlined in the response (DRX as text, images as base64).
    cleanup (default true) deletes exported files from disk after inlining.
    """
    from src.domains.extension_authoring.actions import _resolve_safe_dir
    p = params or {}
    _, proj, err = _check()
    if err:
        return err

    gal = proj.GetGallery()
    if not gal:
        return _err("Gallery not available")

    album_idx = p.get("album_index")
    if album_idx is not None:
        albums = gal.GetGalleryStillAlbums() or []
        if album_idx < len(albums):
            album = albums[album_idx]
        else:
            return _err("Album index out of range")
    else:
        album = gal.GetCurrentStillAlbum()
        if not album:
            albums = gal.GetGalleryStillAlbums() or []
            album = albums[0] if albums else None
    if not album:
        return _err("No still album available")

    if action == "get_stills":
        stills = album.GetStills() or []
        return {"count": len(stills)}
    elif action == "get_label":
        stills = album.GetStills() or []
        idx = p.get("still_index", 0)
        if idx < len(stills):
            return {"label": album.GetLabel(stills[idx])}
        return _err("Still index out of range")
    elif action == "set_label":
        stills = album.GetStills() or []
        idx = p.get("still_index", 0)
        if idx < len(stills):
            return {"success": bool(album.SetLabel(stills[idx], p["label"]))}
        return _err("Still index out of range")
    elif action == "import_stills":
        return {"success": bool(album.ImportStills(p["paths"]))}
    elif action == "export_stills":
        stills = album.GetStills() or []
        if not stills:
            return _err("No stills to export")
        return {"success": bool(album.ExportStills(stills, p["folder_path"], p.get("prefix", "still"), p.get("format", "dpx")))}
    elif action == "grab_and_export":
        import time, os
        folder_path = p.get("folder_path")
        if not folder_path:
            return _err("folder_path is required")
        prefix = p.get("prefix", "still")
        fmt = p.get("format", "dpx")
        delete_after = p.get("delete_after", True)
        # Redirect sandbox/temp paths that Resolve can't access
        folder_path = _resolve_safe_dir(folder_path)
        os.makedirs(folder_path, exist_ok=True)
        # Snapshot directory before export
        before = set(os.listdir(folder_path))
        # Grab still — requires Color page with a clip under the playhead
        _, tl, err2 = _get_tl()
        if err2:
            return err2
        still = tl.GrabStill()
        if not still:
            return _err("GrabStill failed — ensure Color page is active with a clip under the playhead")
        time.sleep(0.5)
        # Export using the live still reference with format fallback chain
        export_ok = False
        used_format = fmt
        for try_fmt in [fmt, "tif", "dpx"]:
            result = album.ExportStills([still], folder_path, prefix, try_fmt)
            if result:
                export_ok = True
                used_format = try_fmt
                break
            time.sleep(0.3)
        # Clean up still from gallery
        if delete_after:
            album.DeleteStills([still])
        if not export_ok:
            return _err("ExportStills failed — ensure the Gallery panel is open on the Color page (Workspace > Gallery)")
        # Wait for filesystem
        time.sleep(0.3)
        # Find new files
        after = set(os.listdir(folder_path))
        new_files = sorted(after - before)
        file_details = []
        for f in new_files:
            fpath = os.path.join(folder_path, f)
            entry = {"name": f, "path": fpath, "size": os.path.getsize(fpath)}
            # Inline file data so cleanup can safely remove files
            try:
                with open(fpath, "rb") as fh:
                    raw = fh.read()
                if f.endswith(".drx"):
                    # DRX files are small XML — inline as text
                    try:
                        entry["data"] = raw.decode("utf-8")
                    except UnicodeDecodeError:
                        entry["data_base64"] = base64.b64encode(raw).decode("ascii")
                else:
                    entry["data_base64"] = base64.b64encode(raw).decode("ascii")
            except OSError:
                pass
            file_details.append(entry)
        # Cleanup: remove exported files now that data is inlined (default: True)
        cleanup = p.get("cleanup", True)
        if cleanup:
            for f in file_details:
                try:
                    os.remove(f["path"])
                except OSError:
                    pass
            # Remove the directory if empty
            try:
                if os.path.isdir(folder_path) and not os.listdir(folder_path):
                    os.rmdir(folder_path)
            except OSError:
                pass
        return {"files": file_details, "format": used_format, "folder": folder_path, "cleaned_up": cleanup}
    elif action == "delete_stills":
        stills = album.GetStills() or []
        to_delete = [stills[i] for i in p["still_indices"] if i < len(stills)]
        return {"success": bool(album.DeleteStills(to_delete))} if to_delete else _err("No valid still indices")
    return _unknown(action, ["get_stills","get_label","set_label","import_stills","export_stills","grab_and_export","delete_stills"])

@mcp.tool()
@_destructive_op("graph")
def graph(action: str, params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Node graph operations (color grading nodes). Source can be timeline, timeline item, or color group.

    PREFER timeline_item_color.probe_node_graph / safe_apply_drx for inspection and
    replacement. These raw graph actions do not capture a version snapshot before mutating.

    Read-only:
      get_num_nodes(source?, ...) -> {count}
      get_lut(node_index, source?, ...) -> {lut}
      get_node_cache(node_index, source?, ...) -> {cache}
      get_node_label(node_index, source?, ...) -> {label}
      get_tools_in_node(node_index, source?, ...) -> {tools}

    Mutators (UNSAFE — bypass grade-version snapshot; prefer timeline_item_color.safe_* where available):
      set_lut(node_index, lut_path, source?, ...) -> {success}
        UNSAFE. Assigns a LUT to an existing node. No snapshot/dry_run.
      set_node_cache(node_index, cache_value, source?, ...) -> {success}
      set_node_enabled(node_index, enabled, source?, ...) -> {success}
      apply_grade_from_drx(path, grade_mode?, source?, ...) -> {success}
        CATASTROPHIC. REPLACES the entire node graph. Prefer timeline_item_color.safe_apply_drx
        (confirm-token gated + validated; it does NOT snapshot — grab a still/.drx backup
        first, and ALWAYS pass track_type/track_index/item_index explicitly: the default
        target is video track 1 item 0, not the current clip). All grade_modes are full
        replacement — there is no append mode. Same-structure applies keep the existing
        node layout (positions in the .drx are ignored unless the graph differs, e.g.
        after reset_all_grades).
        grade_mode: 0="No keyframes" (default), 1="Source Timecode aligned", 2="Start Frames aligned"
      apply_arri_cdl_lut(source?, ...) -> {success}
        DESTRUCTIVE. Bakes a CDL LUT into the graph.
      reset_all_grades(source?, ...) -> {success}
        CATASTROPHIC. Wipes the entire grade on the source.

    source: "timeline" (default), "item" (needs track_type/track_index/item_index),
            "color_group_pre"/"color_group_post" (needs group_name)

    For long-form per-action guidance and a worked example, call:
      graph(action="action_help", params={"name": "<action>"})
    """
    p = params or {}
    if action == "action_help":
        return _action_help("graph", p)
    source = p.get("source", "timeline")

    # Get the graph object based on source
    g = None
    if source == "timeline":
        _, tl, err = _get_tl()
        if err:
            return err
        g = tl.GetNodeGraph()
    elif source == "item":
        _, item, err = _get_item(p)
        if err:
            return err
        g = item.GetNodeGraph(p["layer_index"]) if "layer_index" in p else item.GetNodeGraph()
    elif source in ("color_group_pre", "color_group_post"):
        _, proj, err = _check()
        if err:
            return err
        groups = proj.GetColorGroupsList() or []
        for cg in groups:
            if cg.GetName() == p.get("group_name"):
                g = cg.GetPreClipNodeGraph() if source == "color_group_pre" else cg.GetPostClipNodeGraph()
                break
        if g is None:
            return _err(f"Color group '{p.get('group_name')}' not found")

    if not g:
        return _err("No node graph available for the specified source")

    if action == "get_num_nodes":
        return {"count": g.GetNumNodes()}
    elif action == "get_lut":
        return {"lut": g.GetLUT(p["node_index"])}
    elif action == "set_lut":
        node_index = p["node_index"]
        lut_path = p["lut_path"]
        ok = bool(g.SetLUT(node_index, lut_path))
        if not ok:
            # Resolve resolves LUTs for SetLUT only against the master LUT dir,
            # not the per-user dir that dctl install writes to. Relocate and retry.
            relocated = ensure_lut_in_master(lut_path)
            if relocated:
                try:
                    _, proj, _lut_err = _check()
                    if proj:
                        proj.RefreshLUTList()
                except Exception:
                    pass
                ok = bool(g.SetLUT(node_index, relocated))
                if ok:
                    return {"success": True, "resolved_lut": relocated,
                            "note": "LUT staged under the master LUT dir "
                                    "(MCP/ subfolder) and applied; SetLUT does "
                                    "not resolve the user LUT dir."}
        return {"success": ok}
    elif action == "get_node_cache":
        return {"cache": g.GetNodeCacheMode(p["node_index"])}
    elif action == "set_node_cache":
        return {"success": bool(g.SetNodeCacheMode(p["node_index"], p["cache_value"]))}
    elif action == "get_node_label":
        return {"label": g.GetNodeLabel(p["node_index"])}
    elif action == "get_tools_in_node":
        return {"tools": _ser(g.GetToolsInNode(p["node_index"]))}
    elif action == "set_node_enabled":
        return {"success": bool(g.SetNodeEnabled(p["node_index"], p["enabled"]))}
    elif action == "apply_grade_from_drx":
        if "confirm_token" not in p and "confirmToken" not in p and _confirm_token_required():
            return _issue_confirm_token(
                action="graph.apply_grade_from_drx",
                params=p,
                preview={"operation": "graph.apply_grade_from_drx",
                         "warning": "REPLACES the entire node graph. There is no append mode.",
                         "path": p.get("path"), "grade_mode": p.get("grade_mode", p.get("mode", 0))},
            )
        blocked = _consume_confirm_token(action="graph.apply_grade_from_drx", params=p)
        if blocked:
            return blocked
        return {"success": bool(g.ApplyGradeFromDRX(p["path"], p.get("grade_mode", p.get("mode", 0))))}
    elif action == "apply_arri_cdl_lut":
        return {"success": bool(g.ApplyArriCdlLut())}
    elif action == "reset_all_grades":
        if "confirm_token" not in p and "confirmToken" not in p and _confirm_token_required():
            return _issue_confirm_token(
                action="graph.reset_all_grades",
                params=p,
                preview={"operation": "graph.reset_all_grades",
                         "warning": "Wipes the entire grade on the source. Cannot be selectively undone."},
            )
        blocked = _consume_confirm_token(action="graph.reset_all_grades", params=p)
        if blocked:
            return blocked
        return {"success": bool(g.ResetAllGrades())}
    return _unknown(action, ["get_num_nodes","get_lut","set_lut","get_node_cache","set_node_cache","get_node_label","get_tools_in_node","set_node_enabled","apply_grade_from_drx","apply_arri_cdl_lut","reset_all_grades","action_help"])

@mcp.tool()
def color_group(action: str, params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Manage color groups and their node graphs.

    Actions:
      list() -> {groups}
      get_name(group_name) -> {name}
      set_name(group_name, new_name) -> {success}
      get_clips(group_name) -> {clips}
      get_pre_clip_graph(group_name) -> {available, num_nodes}
      get_post_clip_graph(group_name) -> {available, num_nodes}
    """
    p = params or {}
    _, proj, err = _check()
    if err:
        return err

    if action == "list":
        groups = proj.GetColorGroupsList() or []
        return {"groups": [g.GetName() for g in groups]}

    # All other actions need a group
    groups = proj.GetColorGroupsList() or []
    group = None
    for g in groups:
        if g.GetName() == p.get("group_name"):
            group = g
            break
    if not group:
        return _err(f"Color group '{p.get('group_name')}' not found")

    if action == "get_name":
        return {"name": group.GetName()}
    elif action == "set_name":
        return {"success": bool(group.SetName(p["new_name"]))}
    elif action == "get_clips":
        tl = proj.GetCurrentTimeline()
        clips = group.GetClipsInTimeline(tl) if tl else []
        return {"clips": [{"name": c.GetName(), "id": c.GetUniqueId()} for c in (clips or [])]}
    elif action == "get_pre_clip_graph":
        g = group.GetPreClipNodeGraph()
        return {"available": g is not None, "num_nodes": g.GetNumNodes() if g else 0}
    elif action == "get_post_clip_graph":
        g = group.GetPostClipNodeGraph()
        return {"available": g is not None, "num_nodes": g.GetNumNodes() if g else 0}
    return _unknown(action, ["list","get_name","set_name","get_clips","get_pre_clip_graph","get_post_clip_graph"])


_COLOR_GRADE_KERNEL_ACTIONS = [
    "grade_capabilities",
    "grade_evidence_base",
    "bulk_match_to_hero",
    "propose_grade",
    "probe_grade_item",
    "probe_node_graph",
    "safe_set_cdl",
    "safe_copy_grade",
    "safe_apply_drx",
    "safe_export_lut",
    "grade_version_snapshot",
    "grade_version_restore",
    "color_group_capabilities",
    "gallery_capabilities",
    "grade_boundary_report",
]


_COLOR_ITEM_METHODS = [
    "SetCDL",
    "CopyGrades",
    "AddVersion",
    "GetCurrentVersion",
    "GetVersionNameList",
    "LoadVersionByName",
    "RenameVersionByName",
    "DeleteVersionByName",
    "GetNodeGraph",
    "GetColorGroup",
    "AssignToColorGroup",
    "RemoveFromColorGroup",
    "ExportLUT",
    "GetIsColorOutputCacheEnabled",
    "SetColorOutputCache",
    "GetIsFusionOutputCacheEnabled",
    "SetFusionOutputCache",
    "ResetAllNodeColors",
    "Stabilize",
    "SmartReframe",
    "CreateMagicMask",
    "RegenerateMagicMask",
]


_GRAPH_METHODS = [
    "GetNumNodes",
    "GetLUT",
    "SetLUT",
    "GetNodeCacheMode",
    "SetNodeCacheMode",
    "GetNodeLabel",
    "GetToolsInNode",
    "SetNodeEnabled",
    "ApplyGradeFromDRX",
    "ApplyArriCdlLut",
    "ResetAllGrades",
]


_LUT_EXPORT_TYPES = {
    "17": "EXPORT_LUT_17PTCUBE",
    "17pt": "EXPORT_LUT_17PTCUBE",
    "17ptcube": "EXPORT_LUT_17PTCUBE",
    "export_lut_17ptcube": "EXPORT_LUT_17PTCUBE",
    "33": "EXPORT_LUT_33PTCUBE",
    "33pt": "EXPORT_LUT_33PTCUBE",
    "33ptcube": "EXPORT_LUT_33PTCUBE",
    "export_lut_33ptcube": "EXPORT_LUT_33PTCUBE",
    "65": "EXPORT_LUT_65PTCUBE",
    "65pt": "EXPORT_LUT_65PTCUBE",
    "65ptcube": "EXPORT_LUT_65PTCUBE",
    "export_lut_65ptcube": "EXPORT_LUT_65PTCUBE",
    "panasonic": "EXPORT_LUT_PANASONICVLUT",
    "panasonicvlut": "EXPORT_LUT_PANASONICVLUT",
    "export_lut_panasonicvlut": "EXPORT_LUT_PANASONICVLUT",
}


_PROPOSE_GRADE_OPERATION_CLASSES = frozenset({"direct", "opaque", "asset", "review_only", "unsupported"})
