"""Generated by the repo-restructure Phase 3 split (epic #52, #46).

Extracted from src/server.py; see src/core/CONTEXT.md or the matching domain
CONTEXT.md for what lives here and why.
"""
from __future__ import annotations

import base64
import os
import sys
import json
import logging
import math
import platform
import re
import shutil
import struct
import subprocess
import tempfile
import threading
import time
import zipfile
import zlib
from typing import Dict, Any, Optional, List, Tuple

from src.domains.color_grade.utils.cdl import normalize_cdl_payload
from src.core.mcp_stdio import run_fastmcp_stdio
from src.core.api_truth import lookup_api_truth, VERIFIED_ON as _API_TRUTH_VERIFIED_ON
from src.core.contracts import validate as _validate_params
from src.domains.project_lifecycle.utils.cloud_operations import cloud_sync_status_label
from src.domains.auto_edit.utils.cut_ir import build_cut_list as _build_cut_list
from src.core.page_lock import open_page_serialized as _open_page_serialized
from src.core.proc import preload_audit, resolve_spawn_env, safe_run, sanitized_spawn_env
from src.core.readback import verify_by_readback, verification_stats as _verification_stats
from src.core.update_check import (
    check_for_updates,
    clear_update_prompt_preferences,
    get_cached_update_status,
    get_update_channel,
    get_update_mode,
    ignore_update_version,
    set_update_mode,
    snooze_update_prompt,
    start_background_update_check,
    update_prompt_decision,
    update_state_path,
)
from src.domains.media_analysis.utils.media_analysis import (
    HOST_CHAT_PATHS_PROVIDER,
    HOST_CHAT_VISION_PROVIDERS,
    DEFAULT_VISION_ANALYSIS_PROMPT,
    VISION_SCHEMA_REFERENCE,
    analysis_index_status,
    build_plan as build_media_analysis_plan,
    build_coverage_report as build_media_analysis_coverage_report,
    build_analysis_index,
    cleanup_artifacts as cleanup_media_analysis_artifacts,
    commit_visual_analysis,
    detect_capabilities as detect_media_analysis_capabilities,
    execute_plan_async as execute_media_analysis_plan_async,
    install_guidance as media_analysis_install_guidance,
    load_report as load_media_analysis_report,
    plan_requires_capabilities as media_analysis_plan_requires_capabilities,
    query_analysis_index,
    resolve_output_root as resolve_media_analysis_output_root,
    short_hash,
    slugify,
    summarize_reports as summarize_media_analysis_reports,
)
from src.domains.media_analysis.utils.sync_detection import detect_sync_events_for_records as detect_media_sync_events
from src.core import actor_identity, background_jobs, resolve_busy
from src.core.resolve_busy import long_resolve_op
from src.domains.media_analysis.utils.media_analysis_jobs import (
    MEDIA_EXTENSIONS,
    batch_job_status as media_analysis_batch_job_status,
    cancel_batch_job as cancel_media_analysis_batch_job,
    create_batch_job as create_media_analysis_batch_job,
    list_batch_jobs as list_media_analysis_batch_jobs,
    resume_batch_job as resume_media_analysis_batch_job,
    run_batch_job_slice as run_media_analysis_batch_job_slice,
)
from src.core.platform import get_resolve_paths, get_resolve_plugin_paths
from src.domains.color_grade.utils.lut_paths import master_lut_dir, ensure_lut_in_master
from src.domains.extension_authoring.utils import fuse_templates, dctl_templates, script_templates
from src.domains.timeline_edit.utils.timeline_title_text import (
    candidate_title_property_keys as _candidate_title_property_keys,
    plain_to_minimal_styled_xml as _plain_to_minimal_styled_xml,
    timeline_item_get_property_map as _timeline_item_get_property_map,
)
from src.domains.media_pool_ingest.utils.multicam import build_multicam_setup_plan
from src.domains.timeline_conform_interchange.utils.timeline_xml import analyze_timeline_xml, sanitize_timeline_xml
from src.domains.fusion_composition.utils.fusion_group_settings import (
    FUSION_COMMIT_CHECKLIST,
    FUSION_GROUP_GUARDRAILS,
    default_backup_path,
    parse_setting_file,
    splice_inputs_block,
)
from src.core import analysis_runs as _analysis_runs
from src.core import brain_edits as _brain_edits
from src.domains.auto_edit.utils import edit_engine as _edit_engine_mod
from src.domains.auto_edit.utils import auto_edit as _auto_edit_mod
from src.domains.auto_edit.utils import montage_edit as _montage_edit_mod
from src.domains.orchestration.utils import orchestrate as _orchestrate_mod
from src.core import advanced_bridge as _advanced_bridge
from src.domains.auto_edit.utils import music_analysis as _music_analysis_mod
from src.domains.media_pool_ingest.utils import media_pool_changes as _media_pool_changes
from src.core import timeline_versioning as _timeline_versioning
from src.domains.project_lifecycle.utils import project_spec as _project_spec
from src.domains.project_lifecycle.utils import project_lint as _project_lint
from src.domains.timeline_edit.utils import clip_query as _clip_query
from src.core import destructive_hook as _destructive_hook
from src.core.destructive_hook import destructive_op as _destructive_op
import uuid as _ledger_uuid
from src.core import resolve_ai_ledger as _resolve_ai_ledger
from src.core import resolve_ai_governance as _resolve_ai_governance
from src.domains.media_analysis.utils import media_analysis as _media_analysis_module
import hashlib as _hashlib
import time as _time
import uuid as _uuid
from mcp.server.fastmcp import Context, FastMCP, Image
from mcp import types as mcp_types

logger = logging.getLogger("resolve-mcp")

from src.server import mcp

from src.core.envelope import (
    ERROR_CATEGORIES,
    _CATEGORY_RETRYABLE_DEFAULT,
    _RETRYABLE_UNSET,
    _callable_method_names,
    _check,
    _err,
    _has_method,
    _ok,
    _requires_method,
    _safe_clip_call,
    _safe_get_property,
    _ser,
    _unknown,
)
from src.core.tool_kernel import (
    _media_analysis_bool,
    _action_help,
    _activate_resolve_window,
    _ai_governance_check,
    _ai_governance_gate,
    _ai_governance_mode,
    _ai_governance_overrides,
    _ai_governance_preset,
    _ai_ledger_root,
    _ai_ledger_timed,
    _confirm_token_fingerprint,
    _confirm_token_gc,
    _confirm_token_required,
    _consume_confirm_token,
    _contact_sheet_png_bytes,
    _contact_sheet_sample_label,
    _draw_rect_rgb,
    _draw_tiny_text_rgb,
    _filter_to_keys,
    _find_timeline_item_by_id,
    _first_param,
    _has_any_param,
    _is_truncated,
    _issue_confirm_token,
    _media_analysis_effective_preferences,
    _normalize_sampling_mode_default,
    _normalize_setup_choice,
    _normalize_setup_list,
    _normalize_timed_marker_choice,
    _normalize_vision_default,
    _normalize_yes_no_ask,
    _opt_number,
    _path_error,
    _png_chunk,
    _read_json_strict,
    _read_media_analysis_preferences,
    _read_media_analysis_preferences_strict,
    _record_action_outcome,
    _resolve_enum_settings,
    _rgb_to_png_bytes,
    _run_maybe_background,
    _safe_int,
    _sampling_mode_choice_from_params,
    _send_resolve_keystroke_go_to_mark_in,
    _settings_diff,
    _setup_marker_limit,
    _setup_positive_int,
    _setup_text_key,
    _string_list_param,
    _thumbnail_data_to_png_bytes,
    _thumbnail_raw_rgb,
    _timed_marker_choice_from_params,
    _timeline_items_by_ids,
    _timeline_items_by_ids_report,
    _timeline_resolve_item_optional,
    _write_media_analysis_preferences,
)
from src.core.timeline_lookup import (
    _clip_file_size,
    _clip_name,
    _clip_summaries,
    _clips_from_params,
    _coerce_item_list,
    _collect_timeline_items_in_range,
    _current_timeline_frame_id,
    _find_clip,
    _find_clip_with_parent,
    _find_timeline_by_id,
    _find_timeline_by_name,
    _frame_id_to_timecode,
    _frame_int,
    _get_item,
    _get_mp,
    _get_selected_timeline_items,
    _get_tl,
    _metadata_write_field_for_field,
    _project_name_and_id,
    _project_summary,
    _range_frames_from_params,
    _range_track_indices,
    _range_track_types,
    _safe_timeline_item_id,
    _safe_timeline_item_name,
    _timecode_to_frame_id,
    _timeline_by_selector,
    _timeline_fps,
    _timeline_frame_id_to_timecode,
    _timeline_item_duration,
    _timeline_item_ids,
    _timeline_item_media_pool_item,
    _timeline_item_probe,
    _timeline_item_source_start,
    _timeline_item_summary,
    _timeline_item_track_info,
    _timeline_start_frame,
    _timeline_timecode_to_frame_id,
    _timeline_track_count,
    _track_items_sorted,
    _track_selector,
)
from src.core.live_connection import (
    get_resolve,
    _destructive_versioning_provider,
)

def _apply_cuts_skip_reason(cut):
    """Why a CutList entry is not applicable by apply_cuts, or None if it is."""
    if not isinstance(cut, dict):
        return "not an object"
    if cut.get("action") not in ("lift", "ripple_delete"):
        return f"action {cut.get('action')!r} is not lift or ripple_delete"
    span = cut.get("span")
    if not isinstance(span, dict):
        return "missing span"
    if span.get("start") is None or span.get("end") is None:
        return "span missing start/end"
    return None

def _strata_clip_ref(p: Dict[str, Any]) -> Any:
    """The clip ref from any accepted alias — one place, so aliases can't drift
    between action handlers."""
    for key in _STRATA_CLIP_REF_KEYS:
        value = p.get(key)
        if value:
            return value
    return None

def _edit_engine_collect_items(tl, *, track_index: Optional[int] = None) -> List[Dict[str, Any]]:
    """Serialize video timeline items with the source mapping the planner needs."""
    rows: List[Dict[str, Any]] = []
    track_count = int(tl.GetTrackCount("video") or 0)
    indices = [int(track_index)] if track_index else range(1, track_count + 1)
    for index in indices:
        try:
            items = tl.GetItemListInTrack("video", index) or []
        except Exception:
            continue
        for item in items:
            try:
                row: Dict[str, Any] = {
                    "track_index": index,
                    "item_name": item.GetName(),
                    "timeline_start_frame": _frame_int(item.GetStart()),
                    "timeline_end_frame": _frame_int(item.GetEnd()),
                }
            except Exception:
                continue
            source_start = None
            if _has_method(item, "GetSourceStartFrame"):
                try:
                    source_start = _frame_int(item.GetSourceStartFrame())
                except Exception:
                    source_start = None
            if source_start is None and _has_method(item, "GetLeftOffset"):
                try:
                    source_start = _frame_int(item.GetLeftOffset())
                except Exception:
                    source_start = None
            row["source_start_frame"] = source_start or 0
            try:
                mpi = item.GetMediaPoolItem()
                if mpi is not None:
                    row["media_ref"] = mpi.GetUniqueId()
                    try:
                        row["media_path"] = mpi.GetClipProperty("File Path")
                    except Exception:
                        pass
            except Exception:
                pass
            # Linked audio track indices so the planner can mirror kept ranges
            # onto sound (see #67 — tighten variants were coming out silent).
            try:
                audio_indices, _audio_note = _edit_engine_linked_audio_tracks(
                    tl, item, row["timeline_start_frame"], row["timeline_end_frame"]
                )
                row["audio_track_indices"] = audio_indices
            except Exception:
                row["audio_track_indices"] = []
            rows.append(row)
    return rows

def _edit_engine_timeline_fps(tl) -> float:
    try:
        fps = float(tl.GetSetting("timelineFrameRate") or 0)
        return fps if fps > 0 else 24.0
    except Exception:
        return 24.0

def _edit_engine_capture(tl) -> Dict[str, Any]:
    """Duration/clip-count readback for execute results."""
    out: Dict[str, Any] = {}
    try:
        out["duration_seconds"] = _brain_edits.capture_metric(_brain_edits.METRIC_DURATION_SECONDS, tl)
        out["clip_count"] = _brain_edits.capture_metric(_brain_edits.METRIC_CLIP_COUNT, tl)
    except Exception:
        pass
    return out

def _edit_engine_track_counts(tl) -> Dict[str, int]:
    """Per-track-type item counts — the swap symmetry signal in readback."""
    counts: Dict[str, int] = {}
    for tt in ("video", "audio"):
        total = 0
        try:
            n = int(tl.GetTrackCount(tt) or 0)
        except Exception:
            n = 0
        for ti in range(1, n + 1):
            try:
                total += len(tl.GetItemListInTrack(tt, ti) or [])
            except Exception:
                continue
        counts[tt] = total
    return counts

def _edit_engine_find_slot_item(tl, track_index: int, slot_start: int, slot_end: int):
    """The video item occupying exactly [slot_start, slot_end] on a track."""
    try:
        for cand in (tl.GetItemListInTrack("video", int(track_index)) or []):
            if _frame_int(cand.GetStart()) == slot_start and _frame_int(cand.GetEnd()) == slot_end:
                return cand
    except Exception:
        pass
    return None

def _edit_engine_linked_audio_tracks(
    tl, target_item, slot_start: int, slot_end: int,
) -> Tuple[List[int], str]:
    """Audio track indices carrying the target item's linked audio.

    Prefers GetLinkedItems; falls back to matching slot-overlapping audio
    items that share the target's media-pool source. ([], note) when there is
    no linked audio (audio-only handling stays untouched) or no target item.
    """
    if target_item is None:
        return [], "target video item not found on its track; audio left untouched"
    linked_ids: set = set()
    get_linked = getattr(target_item, "GetLinkedItems", None)
    if callable(get_linked):
        try:
            for linked_item in (get_linked() or []):
                uid = getattr(linked_item, "GetUniqueId", None)
                if callable(uid):
                    linked_ids.add(str(uid()))
        except Exception:
            linked_ids = set()
    target_media_id = None
    try:
        mpi = target_item.GetMediaPoolItem()
        if mpi is not None:
            target_media_id = str(mpi.GetUniqueId())
    except Exception:
        target_media_id = None
    if not linked_ids and not target_media_id:
        return [], "GetLinkedItems unavailable and no media id to match; audio left untouched"

    indices: List[int] = []
    try:
        audio_tracks = int(tl.GetTrackCount("audio") or 0)
    except Exception:
        audio_tracks = 0
    for ti in range(1, audio_tracks + 1):
        try:
            items = tl.GetItemListInTrack("audio", ti) or []
        except Exception:
            continue
        for cand in items:
            try:
                c_start = _frame_int(cand.GetStart())
                c_end = _frame_int(cand.GetEnd())
            except Exception:
                continue
            if c_start is None or c_end is None or c_start >= slot_end or c_end <= slot_start:
                continue
            is_linked = False
            if linked_ids:
                uid = getattr(cand, "GetUniqueId", None)
                if callable(uid):
                    try:
                        is_linked = str(uid()) in linked_ids
                    except Exception:
                        is_linked = False
            if not is_linked and target_media_id:
                try:
                    c_mpi = cand.GetMediaPoolItem()
                    is_linked = c_mpi is not None and str(c_mpi.GetUniqueId()) == target_media_id
                except Exception:
                    is_linked = False
            if is_linked and ti not in indices:
                indices.append(ti)
    if not indices:
        return [], "no linked audio found for the target item"
    return indices, ""

@mcp.tool()
@_destructive_op("edit_engine")
def edit_engine(action: str, params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Evidence-driven edit loops (Phase E): selects assembly, tighten, swap.

    Every loop is plan → confirm → execute. plan_* actions are dry-run by
    construction: they query the DB-canonical analysis store and return a
    per-decision rationale plus a stored plan_id. execute_* actions require a
    confirm_token, run under the version-on-mutate hook (the timeline is
    archived first), and return before/after metrics as readback.

    Actions:
    - plan_selects(min_select_potential?, max_duration_seconds?, timeline_name?,
      max_shots?, handle_seconds?, analysis_root?) — rank shots by deep-tier
      select potential (clip-level fallback), story-spine order. Additive.
    - execute_selects(plan_id, confirm_token?) — creates a NEW selects timeline
      from the plan's clip in/out ranges. Nothing existing is touched.
    - plan_tighten(timeline_name?, target_ratio?, min_pause_seconds?,
      handle_seconds?, include_audio?) — dead-air lifts from transcript-gap
      evidence for the current (or named) timeline. Kept ranges mirror onto the
      items' linked audio tracks by default so the variant is audible; pass
      include_audio=false for a video-only (silent) assembly.
    - execute_tighten(plan_id, confirm_token?, include_details?) — assembles a
      tightened VARIANT timeline from the plan's keep ranges (video + mirrored
      audio), never mutating the original. Readback includes an audio_accounting
      block and a compact structural_diff (counts + a small sample); the full
      per-item diff is persisted in the plan record (get_plan → execution_summary)
      and returned inline only when include_details=true.
    - plan_swap(track_index?, timeline_start_frame | item_name, kind?, limit?)
      — alternates for one timeline item via the similarity index.
    - execute_swap(plan_id, alternate_index, confirm_token?) — replaces the
      item in place (lift + positioned append, same slot) on the current
      timeline (version-archived first).
    - list_plans(limit?) / get_plan(plan_id)
    """
    from src.domains.timeline_edit.actions import _build_append_clip_info_dict, _timeline_create_variant_from_ranges, _timeline_lift_range_impl
    from src.domains.media_pool_ingest.actions import _compact_structural_diff
    p = params or {}

    def _project_context(*, need_resolve: bool) -> Tuple[Optional[Any], Optional[Any], Optional[str], Optional[Dict[str, Any]]]:
        # An explicit analysis_root always wins — the evidence DB the caller
        # analyzed into may differ from the provider's derived root (e.g. a
        # headless analysis keyed by project name only).
        analysis_root = p.get("analysis_root") or p.get("analysisRoot")
        explicit_root = str(analysis_root) if analysis_root and os.path.isdir(str(analysis_root)) else None
        vctx = _destructive_versioning_provider()
        if vctx is not None:
            r, proj, project_root, _name = vctx
            return r, proj, explicit_root or project_root, None
        if not need_resolve and explicit_root:
            return None, None, explicit_root, None
        return None, None, None, _err(
            "No project context — open a Resolve project (or pass analysis_root for plan_selects)."
        )

    if action == "list_plans":
        _r, _proj, project_root, err = _project_context(need_resolve=False)
        if err:
            return err
        return _edit_engine_mod.list_plans(project_root, limit=int(p.get("limit") or 20))

    if action == "get_plan":
        _r, _proj, project_root, err = _project_context(need_resolve=False)
        if err:
            return err
        plan = _edit_engine_mod.load_plan(project_root, str(p.get("plan_id") or p.get("planId") or ""))
        if not plan:
            return _err("plan not found")
        if plan.get("_corrupt"):
            return _err("plan file failed its fingerprint check — re-plan")
        return {"success": True, "plan": plan}

    if action == "plan_selects":
        _r, _proj, project_root, err = _project_context(need_resolve=False)
        if err:
            return err
        return _edit_engine_mod.plan_selects(
            project_root,
            timeline_name=p.get("timeline_name") or p.get("timelineName"),
            max_duration_seconds=p.get("max_duration_seconds") or p.get("maxDurationSeconds"),
            min_select_potential=str(p.get("min_select_potential") or p.get("minSelectPotential") or "medium"),
            handle_seconds=float(p.get("handle_seconds") or p.get("handleSeconds") or _edit_engine_mod.DEFAULT_HANDLE_SECONDS),
            max_shots=int(p.get("max_shots") or p.get("maxShots") or 60),
        )

    if action == "plan_tighten":
        _r, proj, project_root, err = _project_context(need_resolve=True)
        if err:
            return err
        tl = (_find_timeline_by_name(proj, p.get("timeline_name") or p.get("timelineName"))[0] if (p.get("timeline_name") or p.get("timelineName")) else proj.GetCurrentTimeline())
        if not tl:
            return _err("Timeline not found")
        items = _edit_engine_collect_items(tl, track_index=p.get("track_index") or p.get("trackIndex"))
        return _edit_engine_mod.plan_tighten(
            project_root,
            items=items,
            timeline_name=tl.GetName(),
            timeline_fps=_edit_engine_timeline_fps(tl),
            target_ratio=p.get("target_ratio") or p.get("targetRatio"),
            min_pause_seconds=float(p.get("min_pause_seconds") or p.get("minPauseSeconds") or _edit_engine_mod.DEFAULT_MIN_PAUSE_SECONDS),
            handle_seconds=float(p.get("handle_seconds") or p.get("handleSeconds") or _edit_engine_mod.DEFAULT_HANDLE_SECONDS),
            include_audio=str(p.get("include_audio", p.get("includeAudio", True))).strip().lower() not in {"false", "0", "no", "none", "off"},
        )

    if action == "plan_swap":
        _r, proj, project_root, err = _project_context(need_resolve=True)
        if err:
            return err
        tl = (_find_timeline_by_name(proj, p.get("timeline_name") or p.get("timelineName"))[0] if (p.get("timeline_name") or p.get("timelineName")) else proj.GetCurrentTimeline())
        if not tl:
            return _err("Timeline not found")
        items = _edit_engine_collect_items(tl, track_index=p.get("track_index") or p.get("trackIndex"))
        target = None
        wanted_start = p.get("timeline_start_frame") if p.get("timeline_start_frame") is not None else p.get("timelineStartFrame")
        wanted_name = p.get("item_name") or p.get("itemName")
        for row in items:
            if wanted_start is not None and int(row["timeline_start_frame"]) == int(wanted_start):
                target = row
                break
            if wanted_name and row.get("item_name") == wanted_name:
                target = row
                break
        if target is None:
            return _err(
                "Target item not found — pass timeline_start_frame or item_name "
                f"(items: {[{'name': r.get('item_name'), 'start': r['timeline_start_frame']} for r in items[:20]]})"
            )
        return _edit_engine_mod.plan_swap(
            project_root,
            item=target,
            timeline_name=tl.GetName(),
            timeline_fps=_edit_engine_timeline_fps(tl),
            kind=str(p.get("kind") or "visual"),
            limit=int(p.get("limit") or 5),
        )

    if action == "execute_selects":
        _r, proj, project_root, err = _project_context(need_resolve=True)
        if err:
            return err
        plan = _edit_engine_mod.load_plan(project_root, str(p.get("plan_id") or p.get("planId") or ""))
        if not plan or plan.get("_corrupt"):
            return _err("plan not found (or failed its fingerprint check) — re-plan")
        if plan.get("kind") != "selects":
            return _err(f"plan {plan.get('plan_id')} is a {plan.get('kind')} plan")
        if "confirm_token" not in p and "confirmToken" not in p and _confirm_token_required():
            return _issue_confirm_token(
                action="edit_engine.execute_selects", params=p,
                preview={
                    "operation": "edit_engine.execute_selects",
                    "warning": "Creates a NEW selects timeline; no existing timeline is modified.",
                    "timeline_name": plan.get("timeline_name"),
                    "decision_count": len(plan.get("decisions") or []),
                    "estimated_duration_seconds": plan.get("estimated_duration_seconds"),
                },
            )
        blocked = _consume_confirm_token(action="edit_engine.execute_selects", params=p)
        if blocked:
            return blocked
        mp = proj.GetMediaPool()
        if not mp:
            return _err("No media pool")
        root_folder = mp.GetRootFolder()
        name = str(plan.get("timeline_name") or "Selects")
        if _find_timeline_by_name(proj, name)[0]:
            name = f"{name} {time.strftime('%H%M%S')}"
        tl = mp.CreateEmptyTimeline(name)
        if not tl:
            return _err("Failed to create selects timeline")
        try:
            proj.SetCurrentTimeline(tl)
        except Exception:
            pass
        timeline_start = _timeline_start_frame(tl)
        built = []
        build_errors = []
        record_cursor = 0
        for i, ci in enumerate(plan.get("clip_infos") or []):
            append_ci = dict(ci)
            # Sequential assembly: each select lands after the previous one.
            append_ci.setdefault("record_frame", record_cursor)
            append_ci.setdefault("track_index", 1)
            row, row_err = _build_append_clip_info_dict(root_folder, append_ci, i, timeline_start)
            if row_err:
                build_errors.append({"index": i, "error": row_err.get("error")})
                continue
            built.append(row)
            # AppendToTimeline endFrame is exclusive: the item occupies
            # (end - start) frames. Advancing by +1 more leaves a 1-frame gap
            # (black flash) between consecutive selects. See api_truth endFrame entry.
            record_cursor += int(append_ci.get("end_frame", 0)) - int(append_ci.get("start_frame", 0))
        appended = mp.AppendToTimeline(built) if built else None
        readback = _edit_engine_capture(tl)
        # A diff against a source timeline is meaningless for a fresh assembly;
        # a usage-snapshot summary is the structural readback that fits.
        try:
            usage = _timeline_versioning.capture_timeline_clip_usage(tl)
            by_type: Dict[str, int] = {}
            for usage_row in usage:
                by_type[usage_row["track_type"]] = by_type.get(usage_row["track_type"], 0) + 1
            readback["usage_summary"] = {"items": len(usage), "by_track_type": by_type}
        except Exception:
            pass
        run_id = _analysis_runs.current_run_id()
        try:
            _brain_edits.log_brain_edit(
                project_root=project_root,
                analysis_run_id=run_id or "edit-engine",
                edit_type="edit_engine.selects_result",
                tool_name="edit_engine",
                action_name="execute_selects",
                timeline_after=tl.GetName(),
                target_metric=_brain_edits.METRIC_CLIP_COUNT,
                metric_direction="target_value",
                after_value=readback.get("clip_count"),
                rationale=plan.get("summary"),
                params={"plan_id": plan.get("plan_id")},
                result_summary={"appended": len(built), "build_errors": build_errors},
            )
        except Exception:
            pass
        _edit_engine_mod.mark_plan_executed(project_root, plan["plan_id"], {
            "timeline_name": tl.GetName(),
            "appended": len(built),
            "build_errors": build_errors,
            **readback,
        })
        return {
            "success": bool(appended),
            "timeline_name": tl.GetName(),
            "appended": len(built),
            "build_errors": build_errors,
            "readback": readback,
            "plan_id": plan.get("plan_id"),
        }

    if action == "execute_tighten":
        _r, proj, project_root, err = _project_context(need_resolve=True)
        if err:
            return err
        plan = _edit_engine_mod.load_plan(project_root, str(p.get("plan_id") or p.get("planId") or ""))
        if not plan or plan.get("_corrupt"):
            return _err("plan not found (or failed its fingerprint check) — re-plan")
        if plan.get("kind") != "tighten":
            return _err(f"plan {plan.get('plan_id')} is a {plan.get('kind')} plan")
        lifts = plan.get("lifts") or []
        keep_ranges = plan.get("keep_ranges") or []
        if not keep_ranges:
            return _err("plan has no keep_ranges — re-plan with this version")
        audio_keep_ranges = sum(1 for r in keep_ranges if str(r.get("track_type", "video")).lower() == "audio")
        video_keep_ranges = len(keep_ranges) - audio_keep_ranges
        if "confirm_token" not in p and "confirmToken" not in p and _confirm_token_required():
            return _issue_confirm_token(
                action="edit_engine.execute_tighten", params=p,
                preview={
                    "operation": "edit_engine.execute_tighten",
                    "warning": (
                        "Assembles a tightened VARIANT timeline from the plan's keep "
                        "ranges; the original timeline is not modified."
                    ),
                    "timeline_name": plan.get("timeline_name"),
                    "lift_count": len(lifts),
                    "keep_range_count": len(keep_ranges),
                    "video_keep_range_count": video_keep_ranges,
                    "audio_keep_range_count": audio_keep_ranges,
                    "audio_note": (
                        f"Variant carries audio ({audio_keep_ranges} audio ranges mirror the video cuts)."
                        if audio_keep_ranges
                        else "WARNING: variant is VIDEO-ONLY (silent) — plan has no audio ranges."
                    ),
                    "estimated_removed_seconds": sum(l.get("duration_seconds") or 0 for l in lifts),
                },
            )
        blocked = _consume_confirm_token(action="edit_engine.execute_tighten", params=p)
        if blocked:
            return blocked
        source_tl, _src_index = _find_timeline_by_name(proj, plan.get("timeline_name"))
        if not source_tl:
            return _err(f"Timeline '{plan.get('timeline_name')}' not found")
        before = _edit_engine_capture(source_tl)
        variant_name = f"{plan.get('timeline_name')} — tightened {time.strftime('%H%M%S')}"
        variant = _timeline_create_variant_from_ranges(proj, source_tl, {
            "ranges": keep_ranges,
            "name": variant_name,
        })
        if not variant.get("success"):
            return {"success": False, "error": f"variant assembly failed: {variant.get('error')}", "variant": variant}
        new_tl, _new_index = _find_timeline_by_name(proj, variant.get("name") or variant_name)
        after = _edit_engine_capture(new_tl) if new_tl else {}
        # Cross-name structural diff (source vs variant): trustworthy readback
        # without archived version rows — variants are new-name timelines.
        structural_diff = None
        if new_tl is not None:
            try:
                structural_diff = _timeline_versioning.compare_usage_snapshots(
                    _timeline_versioning.capture_timeline_clip_usage(source_tl),
                    _timeline_versioning.capture_timeline_clip_usage(new_tl),
                )
            except Exception as diff_exc:
                structural_diff = {"error": f"{type(diff_exc).__name__}: {diff_exc}"}
        run_id = _analysis_runs.current_run_id()
        try:
            _brain_edits.log_brain_edit(
                project_root=project_root,
                analysis_run_id=run_id or "edit-engine",
                edit_type="edit_engine.tighten_result",
                tool_name="edit_engine",
                action_name="execute_tighten",
                timeline_before=plan.get("timeline_name"),
                timeline_after=variant.get("name") or variant_name,
                target_metric=_brain_edits.METRIC_DURATION_SECONDS,
                metric_direction="decrease",
                before_value=before.get("duration_seconds"),
                after_value=after.get("duration_seconds"),
                rationale=plan.get("summary"),
                params={"plan_id": plan.get("plan_id")},
                result_summary={"keep_ranges": len(keep_ranges), "lifts": len(lifts)},
            )
        except Exception:
            pass
        # The full per-item structural diff is persisted in the plan record so it
        # stays retrievable (edit_engine get_plan) without bloating every
        # response — see issue #84. The MCP response carries a compact form by
        # default and the full diff only when include_details=true.
        include_details = _media_analysis_bool(
            p.get("include_details", p.get("includeDetails")), False
        )
        _edit_engine_mod.mark_plan_executed(project_root, plan["plan_id"], {
            "variant_timeline": variant.get("name") or variant_name,
            "keep_ranges": len(keep_ranges),
            "lifts": len(lifts),
            "before": before,
            "after": after,
            "structural_diff": structural_diff,
        })
        return {
            "success": True,
            "original_timeline": plan.get("timeline_name"),
            "variant_timeline": variant.get("name") or variant_name,
            "lifts_applied": len(lifts),
            "keep_ranges": len(keep_ranges),
            "lift_rationales": [
                {"lift": [l["timeline_start_frame"], l["timeline_end_frame"]], "rationale": l.get("rationale")}
                for l in lifts
            ],
            "readback": {
                "before": before,
                "after": after,
                "removed_seconds": (
                    round(before["duration_seconds"] - after["duration_seconds"], 2)
                    if before.get("duration_seconds") is not None and after.get("duration_seconds") is not None
                    else None
                ),
                "structural_diff": (
                    structural_diff if include_details
                    else _compact_structural_diff(structural_diff)
                ),
                "audio_accounting": {
                    "planned_audio_ranges": audio_keep_ranges,
                    "planned_video_ranges": video_keep_ranges,
                    # variant_* count placed items; variant["audio"] counts requested ranges.
                    "variant_audio_items": sum(
                        1 for it in (variant.get("items") or [])
                        if (it.get("range") or {}).get("media_type") == 2
                    ),
                    "variant_video_items": sum(
                        1 for it in (variant.get("items") or [])
                        if (it.get("range") or {}).get("media_type") == 1
                    ),
                    "note": (
                        "Variant carries audio mirrored from the video cuts."
                        if audio_keep_ranges
                        else "Variant is VIDEO-ONLY (silent) — re-plan with include_audio=True for sound."
                    ),
                },
            },
            "plan_id": plan.get("plan_id"),
        }

    if action == "execute_swap":
        _r, proj, project_root, err = _project_context(need_resolve=True)
        if err:
            return err
        plan = _edit_engine_mod.load_plan(project_root, str(p.get("plan_id") or p.get("planId") or ""))
        if not plan or plan.get("_corrupt"):
            return _err("plan not found (or failed its fingerprint check) — re-plan")
        if plan.get("kind") != "swap":
            return _err(f"plan {plan.get('plan_id')} is a {plan.get('kind')} plan")
        alternates = plan.get("alternates") or []
        try:
            alt_index = int(p.get("alternate_index") if p.get("alternate_index") is not None else p.get("alternateIndex"))
        except (TypeError, ValueError):
            return _err(f"execute_swap requires alternate_index (0-{len(alternates) - 1})")
        if not (0 <= alt_index < len(alternates)):
            return _err(f"alternate_index out of range (0-{len(alternates) - 1})")
        alternate = alternates[alt_index]
        item_block = plan.get("item") or {}
        if "confirm_token" not in p and "confirmToken" not in p and _confirm_token_required():
            return _issue_confirm_token(
                action="edit_engine.execute_swap", params=p,
                preview={
                    "operation": "edit_engine.execute_swap",
                    "warning": (
                        "Replaces one timeline item in place (lift + positioned append). "
                        "A timeline version is archived first."
                    ),
                    "timeline_name": plan.get("timeline_name"),
                    "slot": [item_block.get("timeline_start_frame"), item_block.get("timeline_end_frame")],
                    "replacement": {
                        "clip_name": alternate.get("clip_name"),
                        "shot_index": alternate.get("shot_index"),
                        "score": alternate.get("score"),
                    },
                },
            )
        blocked = _consume_confirm_token(action="edit_engine.execute_swap", params=p)
        if blocked:
            return blocked
        tl, _tl_index = _find_timeline_by_name(proj, plan.get("timeline_name"))
        if not tl:
            return _err(f"Timeline '{plan.get('timeline_name')}' not found")
        try:
            proj.SetCurrentTimeline(tl)
        except Exception:
            pass
        before = _edit_engine_capture(tl)
        before["track_counts"] = _edit_engine_track_counts(tl)
        slot_start = int(item_block.get("timeline_start_frame"))
        slot_end = int(item_block.get("timeline_end_frame"))
        target_track = int(item_block.get("track_index") or 1)
        # Capture the target's linked audio BEFORE the lift so the audio lift
        # is scoped to exactly those tracks (the replacement appends linked
        # video+audio, so both sides of the swap stay symmetric).
        target_item = _edit_engine_find_slot_item(tl, target_track, slot_start, slot_end)
        linked_audio_indices, audio_note = _edit_engine_linked_audio_tracks(
            tl, target_item, slot_start, slot_end,
        )
        lift = _timeline_lift_range_impl(tl, {
            "start_frame": slot_start,
            "end_frame": slot_end,
            "track_types": ["video"],
            "track_indices": [target_track],
            "allow_partial_item_delete": True,
            "ripple": False,
        })
        if not lift.get("success"):
            return {"success": False, "error": f"lift failed: {lift.get('error')}", "lift": lift}
        audio_lift = None
        if linked_audio_indices:
            audio_lift = _timeline_lift_range_impl(tl, {
                "start_frame": slot_start,
                "end_frame": slot_end,
                "track_types": ["audio"],
                "track_indices": linked_audio_indices,
                "allow_partial_item_delete": True,
                "ripple": False,
            })
            if not audio_lift.get("success"):
                return {
                    "success": False,
                    "error": f"linked-audio lift failed: {audio_lift.get('error')}",
                    "lift": lift,
                    "audio_lift": audio_lift,
                }
        mp = proj.GetMediaPool()
        root_folder = mp.GetRootFolder()
        timeline_start = _timeline_start_frame(tl)
        frame_range = alternate.get("source_frame_range") or [0, 0]
        ci = {
            "clip_id": alternate.get("resolve_clip_id"),
            "start_frame": int(frame_range[0]),
            "end_frame": int(frame_range[1]),
            # Item starts come from item.GetStart() — absolute timeline frames.
            "record_frame": int(item_block.get("timeline_start_frame")),
            "record_frame_mode": "absolute",
            "track_index": int(item_block.get("track_index") or 1),
        }
        row, row_err = _build_append_clip_info_dict(root_folder, ci, 0, timeline_start)
        if row_err:
            return {"success": False, "error": f"swap append failed: {row_err.get('error')}", "lifted": lift}
        # No mediaType on the clip info: the replacement appends video+audio
        # linked, mirroring the video + linked-audio lift above.
        appended = mp.AppendToTimeline([row])
        after = _edit_engine_capture(tl)
        after["track_counts"] = _edit_engine_track_counts(tl)
        run_id = _analysis_runs.current_run_id()
        try:
            _brain_edits.log_brain_edit(
                project_root=project_root,
                analysis_run_id=run_id or "edit-engine",
                edit_type="edit_engine.swap_result",
                tool_name="edit_engine",
                action_name="execute_swap",
                timeline_after=tl.GetName(),
                target_metric=_brain_edits.METRIC_CLIP_COUNT,
                metric_direction="target_value",
                before_value=before.get("clip_count"),
                after_value=after.get("clip_count"),
                rationale=(
                    f"Swapped slot {item_block.get('timeline_start_frame')}-"
                    f"{item_block.get('timeline_end_frame')} with "
                    f"{alternate.get('clip_name')} shot {alternate.get('shot_index')}: "
                    f"{alternate.get('rationale')}"
                ),
                params={"plan_id": plan.get("plan_id"), "alternate_index": alt_index},
                result_summary={"appended": bool(appended)},
            )
        except Exception:
            pass
        _edit_engine_mod.mark_plan_executed(project_root, plan["plan_id"], {
            "alternate_index": alt_index,
            "replacement": alternate.get("clip_name"),
            "before": before,
            "after": after,
        })
        readback: Dict[str, Any] = {"before": before, "after": after}
        readback["audio_accounting"] = {
            "linked_audio_tracks_lifted": linked_audio_indices,
            "audio_items_lifted": (audio_lift or {}).get("deleted", 0),
            "video_items_lifted": lift.get("deleted", 0),
            **({"note": audio_note} if audio_note else {}),
        }
        return {
            "success": bool(appended),
            "timeline_name": tl.GetName(),
            "replaced_slot": [item_block.get("timeline_start_frame"), item_block.get("timeline_end_frame")],
            "replacement": {
                "clip_name": alternate.get("clip_name"),
                "shot_index": alternate.get("shot_index"),
                "score": alternate.get("score"),
            },
            "readback": readback,
            "plan_id": plan.get("plan_id"),
        }

    return _unknown(action, [
        "plan_selects",
        "execute_selects",
        "plan_tighten",
        "execute_tighten",
        "plan_swap",
        "execute_swap",
        "list_plans",
        "get_plan",
    ])

def _auto_edit_project_context(p: Dict[str, Any], *, need_resolve: bool):
    """(resolve, proj, project_root, err) — same contract as edit_engine's."""
    analysis_root = p.get("analysis_root") or p.get("analysisRoot")
    if analysis_root and not os.path.isdir(str(analysis_root)):
        # A typo'd root must not silently fall back to the open project's store
        # (briefs/plans would be read from — or written to — the wrong place).
        return None, None, None, _err(
            f"analysis_root is not a directory: {str(analysis_root)!r}")
    explicit_root = str(analysis_root) if analysis_root else None
    if not need_resolve and explicit_root:
        # Offline actions with an explicit evidence root never touch Resolve.
        return None, None, explicit_root, None
    vctx = _destructive_versioning_provider()
    if vctx is not None:
        r, proj, project_root, _name = vctx
        return r, proj, explicit_root or project_root, None
    return None, None, None, _err(
        "No project context — open a Resolve project (or pass analysis_root for offline actions)."
    )

def _auto_edit_build_rows(plan: Dict[str, Any], record_offset: int = 0) -> List[Dict[str, Any]]:
    """CutList -> AppendToTimeline row dicts (pure; offline-testable).

    Ordering follows the proven append-rebuild mechanism: V1 speech with
    mirrored audio, V2 b-roll overlays as positioned appends, then the music
    on A2 trimmed to the cut. All frame ranges are half-open; record frames
    shift by ``record_offset`` (the intro-title footprint at the head of V1).
    """
    rows: List[Dict[str, Any]] = []
    for seg in plan.get("segments") or []:
        base = {
            "clip_id": seg.get("clip_id") or seg.get("clip_uuid"),
            "start_frame": int(seg["source_start_frame"]),
            "end_frame": int(seg["source_end_frame"]),
            "record_frame": int(seg.get("record_start_frame", 0)) + record_offset,
        }
        rows.append({**base, "track_index": 1, "media_type": 1, "role": "speech",
                     "punch_in": seg.get("punch_in")})
        for audio_track in (seg.get("audio_track_indices") or [1]):
            rows.append({**base, "track_index": int(audio_track), "media_type": 2,
                         "role": "speech_audio"})
    for overlay in plan.get("overlays") or []:
        rows.append({
            "clip_id": overlay.get("clip_id") or overlay.get("clip_uuid"),
            "start_frame": int(overlay["source_start_frame"]),
            "end_frame": int(overlay["source_end_frame"]),
            "record_frame": int(overlay.get("record_start_frame", 0)) + record_offset,
            "track_index": int(overlay.get("track_index") or 2),
            "media_type": 1,
            "role": "broll",
        })
    music = plan.get("music")
    if music:
        duration = int(music.get("record_end_frame", 0)) - int(music.get("record_start_frame", 0))
        if duration > 0:
            rows.append({
                "clip_path": music.get("bed_path") or music.get("path"),
                "start_frame": 0,
                "end_frame": duration,
                "record_frame": int(music.get("record_start_frame", 0)) + record_offset,
                "track_index": int(music.get("track_index") or 2),
                "media_type": 2,
                "role": "music",
            })
    return rows

def _auto_edit_ffprobe_ok(path: str) -> Tuple[bool, str]:
    """Light ffprobe validation; degrades to extension-only when absent."""
    import shutil as _shutil
    if _shutil.which("ffprobe") is None:
        return True, "ffprobe not installed — existence check only"
    try:
        proc = safe_run(
            ["ffprobe", "-v", "error", "-show_entries", "format=duration",
             "-of", "default=nw=1", path],
            capture_output=True, timeout=30, check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return False, f"ffprobe failed: {exc}"
    if proc.returncode != 0:
        return False, (proc.stderr or b"").decode("utf-8", "replace")[:200] or "unreadable media"
    return True, ""

def _is_montage_plan(plan: Dict[str, Any]) -> bool:
    """CutLists carry no genre field (montage adds roles, not schema) — detect
    by role instead of threading genre through plan/revise/summary calls."""
    return any(
        seg.get("role") in _auto_edit_mod.cut_ir.MONTAGE_SEGMENT_ROLES
        for seg in (plan.get("segments") or [])
    )

@mcp.tool()
@_destructive_op("auto_edit")
async def auto_edit(action: str, params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Autonomous brief-to-rendered-video pipeline (Phase 1: talking head).

    The user states a brief (files, music, target length); analysis runs; the
    decision layer assembles a CutList; ONE human checkpoint (approve_cut,
    confirm-token gated, includes the music-bed-render consent line) approves
    it; then the timeline is append-rebuilt and finished (grade/subtitles/
    render). Revisions rebuild — timelines are stateless artifacts.

    Actions:
      start_brief(files, music?, target_duration_seconds?, genre?, deliverable?,
        title_text?, options?) -> {brief_id, analysis_job_id} — validates files
        (exist + ffprobe), scaffolds Footage/Music bins (safe import), kicks a
        media_analysis batch job (transcription + visuals per defaults; the
        host completes commit_vision for deep passes).
      brief_status(brief_id) | status(brief_id) -> {brief, analysis?} — brief
        state; polls the analysis job and advances analyzing -> ready.
      plan_cut(brief_id) -> {plan_id, plan, summary} — build the CutList from
        evidence (word-level Pass-1, story beats, b-roll similarity) and render
        the markdown checkpoint summary.
      revise_cut(brief_id, notes?, edits?) -> revision+1 — structured overrides
        (reorder/keep/drop/title), new plan_id, old revisions stay loadable.
        Drop indices refer to the plan as displayed: a drop-only batch removes
        exactly those segments (listed in any order); drops mixed with
        reorder/keep must be descending or the batch is rejected.
      get_cut_summary(plan_id, format?) -> {summary} — markdown (default) or json.
      approve_cut(plan_id, music_bed_consent?, confirm_token?) — THE one human
        checkpoint. The confirm-token preview embeds the cut summary and the
        music-bed-render consent line; consent decides static vs rendered_bed.
      build_timeline(plan_id, title_generator?, confirm_token?) -> {timeline_name,
        readback} — append-rebuild from the approved CutList: intro title, V1
        speech + mirrored audio, V2 b-roll, punch-in zoom, A2 music (ducked bed
        only when consented). Readback-verified.
      polish_timeline(plan_id, options?, confirm_token?) -> {polished_timeline,
        transitions, lower_thirds, media_link} — Phase-2 pro polish the scripting
        API can't do. Exports the built timeline as .drt, runs verified drp-format
        vendor ops (cross-dissolves at flagged cuts via place_transition,
        lower-thirds on an upper track via place_fusion_title), and reimports as a
        NEW "(polished)" timeline; export-then-modify keeps media linked. options:
        lower_thirds[], dissolve_at_segments[], dissolve_on_beat_change,
        dissolve_frames, lower_third_frames/track, no_dissolves, no_lower_thirds.
      finish(plan_id, grade?, subtitles?, render?, confirm_token?) -> {output}
        — grade (lut_path | cdl | drx_path), optional subtitles, validated
        render; reports the output path.
      list_briefs() -> {briefs}
    """
    from src.domains.timeline_edit.actions import _build_append_clip_info_dict, _unique_timeline_name
    from src.domains.media_pool_ingest.actions import _ensure_folder_path, _find_clip_by_file_path, _safe_import_media
    from src.domains.timeline_conform_interchange.actions import _export_timeline_checked, _import_timeline_checked, _timeline_media_coverage
    from src.domains.color_grade.actions import _normalize_cdl
    from src.domains.render_deliver.actions import _prepare_render_job, _render_cut_summary_for
    from src.domains.audio_fairlight.actions import _safe_create_subtitles
    from src.domains.media_analysis.actions import media_analysis
    p = params or {}

    def _plan_id_param() -> str:
        return str(p.get("plan_id") or p.get("planId") or "")

    def _brief_id_param() -> str:
        return str(p.get("brief_id") or p.get("briefId") or "")

    if action == "start_brief":
        r, proj, project_root, err = _auto_edit_project_context(p, need_resolve=True)
        if err:
            return err
        files = p.get("files") or []
        music = p.get("music")
        # Fail-fast pre-flight: catch bad inputs before the expensive ffprobe
        # pass and irreversible media import below. create_brief re-validates as
        # the authoritative check for direct callers — deliberate layering.
        problems = _auto_edit_mod.validate_brief_inputs(
            files=files, music=music,
            target_duration_seconds=p.get("target_duration_seconds") or p.get("targetDurationSeconds"),
            genre=p.get("genre") or "talking_head",
            deliverable=p.get("deliverable") or "youtube_1080p",
            title_text=p.get("title_text") or p.get("titleText"),
        )
        # Genre-specific rules (montage requires music) live here, not in
        # auto_edit.py — that module stays unaware of montage's own rules to
        # avoid a circular import (montage_edit already imports auto_edit).
        if str(p.get("genre") or "talking_head") == _montage_edit_mod.GENRE:
            problems.extend(_montage_edit_mod.validate_montage_brief_inputs(
                files=files, music=music,
                target_duration_seconds=p.get("target_duration_seconds") or p.get("targetDurationSeconds"),
            ))
        probe_targets = []
        for path in list(files) + ([music] if music else []):
            if not isinstance(path, str) or not os.path.isfile(path):
                problems.append(f"file not found: {path!r}")
                continue
            probe_targets.append(path)
        if probe_targets:
            # The probes are independent; run them concurrently instead of
            # paying one spawn+probe latency per file back to back. Probes can
            # take up to 30s each, and auto_edit is async — keep the wait off
            # the event loop.
            def _probe_all():
                from concurrent.futures import ThreadPoolExecutor
                with ThreadPoolExecutor(max_workers=min(4, len(probe_targets))) as pool:
                    return list(pool.map(_auto_edit_ffprobe_ok, probe_targets))
            import anyio
            for path, (ok, why) in zip(
                    probe_targets, await anyio.to_thread.run_sync(_probe_all)):
                if not ok:
                    problems.append(f"unreadable media {path!r}: {why}")
        if problems:
            return _err("invalid brief: " + "; ".join(problems))
        mp = proj.GetMediaPool()
        if not mp:
            return _err("No media pool")
        imported: Dict[str, Any] = {}
        for bin_name, paths in (("Footage", list(files)), ("Music", [music] if music else [])):
            if not paths:
                continue
            _folder, folder_err = _ensure_folder_path(mp, bin_name)
            if folder_err:
                return folder_err
            result = _safe_import_media(mp, {"paths": paths, "target_folder": bin_name})
            if result.get("error"):
                return result
            imported[bin_name] = result
        created = _auto_edit_mod.create_brief(
            project_root,
            files=list(files), music=music,
            target_duration_seconds=p.get("target_duration_seconds") or p.get("targetDurationSeconds"),
            genre=str(p.get("genre") or "talking_head"),
            deliverable=str(p.get("deliverable") or "youtube_1080p"),
            title_text=p.get("title_text") or p.get("titleText"),
            options=p.get("options") or {},
        )
        if not created.get("success"):
            return _err("; ".join(created.get("problems") or [created.get("error") or "brief failed"]))
        brief_id = created["brief_id"]
        analysis_job_id = None
        analysis_warning = None
        # Transcription is the load-bearing artifact for planning. LLM vision
        # (host_chat_paths) needs an interactive host to commit frames, which an
        # autonomous brief cannot satisfy, so it is off by default here (opt in
        # via options.vision). An explicit sampling_mode stops start_batch_job
        # from returning its first-run frame-sampling prompt instead of a job.
        brief_options = p.get("options") or {}
        try:
            kicked = await media_analysis("start_batch_job", {
                "target": {"type": "bin", "path": "Footage", "recursive": False},
                "name": f"auto_edit {brief_id}",
                "analysis_root": project_root,
                "sampling_mode": brief_options.get("sampling_mode") or "adaptive_capped",
                "transcription": {"enabled": True, "allow_model_download": True},
                "vision": {"enabled": bool(brief_options.get("vision"))},
            })
            # create_batch_job nests the id under "job"; a first-run sampling
            # prompt or a capability gap returns no job at all.
            analysis_job_id = ((kicked or {}).get("job") or {}).get("job_id")
            if not analysis_job_id:
                analysis_warning = (kicked or {}).get("error") or (
                    kicked or {}).get("message") or "analysis kick returned no job_id"
        except Exception as exc:
            analysis_warning = f"analysis kick failed: {type(exc).__name__}: {exc}"
        _auto_edit_mod.advance_brief(
            project_root, brief_id,
            "analyzing" if analysis_job_id else "created",
            analysis_job_id=analysis_job_id,
        )
        out = {
            "success": True,
            "brief_id": brief_id,
            "analysis_job_id": analysis_job_id,
            "imported": imported,
            "next": "poll brief_status until state=ready, then plan_cut",
        }
        if analysis_warning:
            out["warning"] = analysis_warning + " — run media_analysis manually, then plan_cut."
        return out

    if action in ("brief_status", "status"):
        _r, _proj, project_root, err = _auto_edit_project_context(p, need_resolve=False)
        if err:
            return err
        brief = _auto_edit_mod.load_brief(project_root, _brief_id_param())
        if not brief:
            return _err(f"brief not found: {_brief_id_param()!r}")
        analysis = None
        if brief.get("state") == "analyzing" and brief.get("analysis_job_id"):
            job_id = brief["analysis_job_id"]
            # brief_status is the ONLY surface that drives this job's slices —
            # start_brief just queues it, nothing else pumps it. Run bounded
            # slices until the job is terminal or this call's time budget is
            # spent; large briefs finish across successive polls.
            budget = _time.monotonic() + 300
            try:
                analysis = await media_analysis("batch_job_status", {"job_id": job_id})
                _terminal = ("completed", "completed_with_errors", "canceled", "failed")
                while str((analysis or {}).get("status") or "").lower() not in _terminal:
                    if _time.monotonic() >= budget:
                        break
                    sliced = await media_analysis("run_batch_job_slice", {
                        "job_id": job_id, "max_clips": 4, "max_seconds": 240})
                    analysis = (sliced or {}).get("job") or await media_analysis(
                        "batch_job_status", {"job_id": job_id})
                    # No progress (nothing pending / slice failed) — stop looping.
                    if not (sliced or {}).get("success") or not (sliced or {}).get("processed_count"):
                        break
                job_state = str((analysis or {}).get("status") or "").lower()
                # Terminal job statuses are completed | completed_with_errors |
                # canceled (media_analysis_jobs); a partly-failed batch still
                # readies the brief — planning fails honestly on missing clips.
                if job_state in ("completed", "completed_with_errors"):
                    brief = _auto_edit_mod.advance_brief(
                        project_root, brief["plan_id"], "ready")["brief"]
            except Exception as exc:
                analysis = {"error": f"{type(exc).__name__}: {exc}"}
        return {"success": True, "brief": brief,
                **({"analysis": analysis} if analysis is not None else {})}

    if action == "plan_cut":
        _r, _proj, project_root, err = _auto_edit_project_context(p, need_resolve=False)
        if err:
            return err
        brief = _auto_edit_mod.load_brief(project_root, _brief_id_param())
        if not brief:
            return _err(f"brief not found: {_brief_id_param()!r}")
        if brief.get("state") in ("created", "analyzing"):
            # Planning needs evidence; move to ready only if the DB has it —
            # build_cut_list_for_brief fails honestly when analysis is missing.
            _auto_edit_mod.advance_brief(project_root, brief["plan_id"], "ready")
            brief = _auto_edit_mod.load_brief(project_root, brief["plan_id"]) or brief
        genre = str(brief.get("genre") or "talking_head")
        if genre == _montage_edit_mod.GENRE:
            # No ducking/voiceover in montage — the loudness-bed-gain pass
            # exists only to feed talking-head's ducking ladder.
            built = _montage_edit_mod.build_cut_list_for_brief(project_root, brief)
        else:
            music_gain_db = None
            if brief.get("music") and os.path.isfile(str(brief["music"])):
                music_path = str(brief["music"])
                try:
                    music_mtime = os.path.getmtime(music_path)
                except OSError:
                    music_mtime = None
                gain_cache = brief.get("music_gain_cache") or {}
                if gain_cache.get("path") == music_path and gain_cache.get("mtime") == music_mtime:
                    music_gain_db = gain_cache.get("gain_db")
                else:
                    # Full ffmpeg loudness pass — measure once per music file and
                    # cache on the brief so re-planning doesn't re-decode it.
                    bed = _music_analysis_mod.analyze_music_bed(music_path)
                    music_gain_db = bed.get("gain_db")
                    if music_gain_db is not None:
                        _auto_edit_mod.advance_brief(
                            project_root, brief["plan_id"], str(brief.get("state") or "ready"),
                            music_gain_cache={"path": music_path, "mtime": music_mtime,
                                              "gain_db": music_gain_db})
            built = _auto_edit_mod.build_cut_list_for_brief(
                project_root, brief, music_gain_db=music_gain_db)
        if not built.get("success"):
            return _err(built.get("error") or "planning failed",
                        ) | {"problems": built.get("problems") or []}
        plan = built["plan"]
        _auto_edit_mod.advance_brief(
            project_root, brief["plan_id"], "planned", latest_plan_id=plan["plan_id"])
        return {
            "success": True,
            "brief_id": brief["plan_id"],
            "plan_id": plan["plan_id"],
            "plan": plan,
            "summary": _render_cut_summary_for(plan),
            "next": "review the summary; approve_cut(plan_id) or revise_cut(brief_id, edits)",
        }

    if action == "revise_cut":
        _r, _proj, project_root, err = _auto_edit_project_context(p, need_resolve=False)
        if err:
            return err
        brief = _auto_edit_mod.load_brief(project_root, _brief_id_param())
        if not brief:
            return _err(f"brief not found: {_brief_id_param()!r}")
        plan_id = _plan_id_param() or str(brief.get("latest_plan_id") or "")
        if not plan_id:
            return _err("brief has no cut list yet — plan_cut first")
        revised = _auto_edit_mod.apply_revision(
            project_root, plan_id,
            notes=str(p.get("notes") or ""), edits=p.get("edits"))
        if not revised.get("success"):
            return _err(revised.get("error") or "revision failed",
                        ) | {"problems": revised.get("problems") or []}
        plan = revised["plan"]
        _auto_edit_mod.advance_brief(
            project_root, brief["plan_id"], "planned", latest_plan_id=plan["plan_id"])
        return {
            "success": True,
            "brief_id": brief["plan_id"],
            "plan_id": plan["plan_id"],
            "revision": plan.get("revision"),
            "plan": plan,
            "summary": _render_cut_summary_for(plan),
        }

    if action == "get_cut_summary":
        _r, _proj, project_root, err = _auto_edit_project_context(p, need_resolve=False)
        if err:
            return err
        plan = _edit_engine_mod.load_plan(project_root, _plan_id_param())
        if not plan or plan.get("_corrupt") or plan.get("kind") != _auto_edit_mod.cut_ir.CUT_LIST_KIND:
            return _err(f"cut list not found: {_plan_id_param()!r}")
        if str(p.get("format") or "markdown").lower() == "json":
            return {"success": True, "plan": plan}
        return {"success": True, "plan_id": plan["plan_id"],
                "summary": _render_cut_summary_for(plan)}

    if action == "approve_cut":
        _r, _proj, project_root, err = _auto_edit_project_context(p, need_resolve=False)
        if err:
            return err
        plan = _edit_engine_mod.load_plan(project_root, _plan_id_param())
        if not plan or plan.get("_corrupt") or plan.get("kind") != _auto_edit_mod.cut_ir.CUT_LIST_KIND:
            return _err(f"cut list not found (or failed its fingerprint check): {_plan_id_param()!r}")
        is_montage = _is_montage_plan(plan)
        # Montage has no voiceover to duck under — force static regardless of
        # what's passed, never honor a stray consent flag into a rendered
        # derivative for a genre that was designed to never need one.
        music_bed_consent = False if is_montage else bool(
            p.get("music_bed_consent") or p.get("musicBedConsent"))
        # Tier-2 ducking (issue #14): write the bed gain into the .drt volume during
        # polish_timeline — no rendered derivative, so no consent needed.
        prefer_drt_ducking = False if is_montage else bool(
            p.get("prefer_drt_ducking") or p.get("preferDrtDucking"))
        if "confirm_token" not in p and "confirmToken" not in p and _confirm_token_required():
            preview: Dict[str, Any] = {
                "operation": "auto_edit.approve_cut",
                "warning": "THE one human checkpoint: approving authorizes the "
                           "timeline build and downstream finish steps.",
                "plan_id": plan["plan_id"],
                "revision": plan.get("revision"),
                "estimates": plan.get("estimates"),
                "summary_markdown": _render_cut_summary_for(plan),
            }
            if plan.get("music") and not is_montage:
                preview["music_bed_consent_requested"] = music_bed_consent
                preview["prefer_drt_ducking"] = prefer_drt_ducking
                # drt_automation writes no derivative media, so the consent line is
                # moot when it's chosen.
                if not prefer_drt_ducking:
                    preview["music_bed_consent_line"] = _auto_edit_mod.MUSIC_BED_CONSENT_LINE
            return _issue_confirm_token(
                action="auto_edit.approve_cut", params=p, preview=preview)
        blocked = _consume_confirm_token(action="auto_edit.approve_cut", params=p)
        if blocked:
            return blocked
        approved = _auto_edit_mod.mark_approved(
            project_root, plan["plan_id"], music_bed_consent=music_bed_consent,
            prefer_drt_ducking=prefer_drt_ducking)
        if not approved.get("success"):
            return _err(approved.get("error") or "approval failed")
        if approved["plan"].get("brief_id"):
            _auto_edit_mod.advance_brief(
                project_root, approved["plan"]["brief_id"], "approved")
        return {
            "success": True,
            "plan_id": approved["plan_id"],
            "approved_at": approved["plan"].get("approved_at"),
            "music_bed_consent": music_bed_consent,
            "ducking_mode": (approved["plan"].get("music") or {}).get("ducking", {}).get("mode"),
            "next": "build_timeline(plan_id)",
        }

    if action == "build_timeline":
        _r, proj, project_root, err = _auto_edit_project_context(p, need_resolve=True)
        if err:
            return err
        gate = _auto_edit_mod.require_approved_plan(project_root, _plan_id_param())
        if not gate.get("success"):
            return _err(gate.get("error") or "plan gate failed")
        plan = gate["plan"]
        if "confirm_token" not in p and "confirmToken" not in p and _confirm_token_required():
            ducking = ((plan.get("music") or {}).get("ducking") or {})
            return _issue_confirm_token(
                action="auto_edit.build_timeline", params=p,
                preview={
                    "operation": "auto_edit.build_timeline",
                    "warning": "Creates a NEW timeline from the approved CutList; "
                               "no existing timeline is modified."
                               + (" A ducked music-bed file will be rendered "
                                  "(consented at approve_cut)."
                                  if ducking.get("mode") == "rendered_bed" else ""),
                    "plan_id": plan["plan_id"],
                    "segments": len(plan.get("segments") or []),
                    "overlays": len(plan.get("overlays") or []),
                    "estimates": plan.get("estimates"),
                },
            )
        blocked = _consume_confirm_token(action="auto_edit.build_timeline", params=p)
        if blocked:
            return blocked
        mp = proj.GetMediaPool()
        if not mp:
            return _err("No media pool")
        root_folder = mp.GetRootFolder()
        fps = float(plan.get("fps") or 24.0)

        # Tier-1 ducked bed (consent-gated at approve_cut; refusal falls back
        # to the original music at a static level).
        music = plan.get("music")
        bed_note = None
        if music and (music.get("ducking") or {}).get("mode") == "rendered_bed":
            from src.domains.media_analysis.utils import analysis_memory as _analysis_memory
            bed_dir = os.path.join(_analysis_memory.memory_dir(project_root), "auto_edit")
            bed_path = os.path.join(bed_dir, f"{plan['plan_id']}_bed.wav")
            duration_s = (int(music.get("record_end_frame", 0))
                          - int(music.get("record_start_frame", 0))) / fps
            bed = _music_analysis_mod.render_ducked_bed(
                str(music.get("path")), bed_path,
                duration_seconds=duration_s,
                gain_db=music.get("gain_db"),
                user_approved_render=bool((music.get("ducking") or {}).get("user_approved_render")),
            )
            if bed.get("success"):
                music["bed_path"] = bed["output_path"]
                imported_bed = _safe_import_media(
                    mp, {"paths": [bed["output_path"]], "target_folder": "Music"})
                if imported_bed.get("error"):
                    bed_note = f"bed import failed ({imported_bed.get('error')}); using original music"
                    music.pop("bed_path", None)
            else:
                bed_note = bed.get("error")

        name = _unique_timeline_name(proj, str(
            p.get("timeline_name") or p.get("timelineName")
            or ((plan.get("titles") or [{}])[0].get("text") if plan.get("titles") else None)
            or "Auto Edit"))
        tl = mp.CreateEmptyTimeline(name)
        if not tl:
            return _err("Failed to create timeline")
        try:
            proj.SetCurrentTimeline(tl)
        except Exception:
            pass
        timeline_start = _timeline_start_frame(tl)

        # 1) Intro title at the head of V1 — the only reliable placement.
        title_result = None
        record_offset = 0
        titles = plan.get("titles") or []
        if titles:
            generator = str(p.get("title_generator") or p.get("titleGenerator") or "Text")
            try:
                inserted = bool(tl.InsertTitleIntoTimeline(generator))
            except Exception as exc:
                inserted = False
                title_result = {"inserted": False, "error": f"{type(exc).__name__}: {exc}"}
            if inserted:
                text_set = False
                try:
                    items = tl.GetItemListInTrack("video", 1) or []
                    if items:
                        title_item = items[0]
                        record_offset = max(
                            0, int(title_item.GetEnd()) - int(timeline_start or 0))
                        for key in ("Text", "Text1", "StyledText"):
                            try:
                                if title_item.SetProperty(key, str(titles[0].get("text") or "")):
                                    text_set = True
                                    break
                            except Exception:
                                continue
                except Exception:
                    pass
                title_result = {"inserted": True, "text_set": text_set,
                                "record_offset": record_offset}

        # 2..5) Speech + mirrored audio, b-roll overlays, music — one append pass.
        rows = _auto_edit_build_rows(plan, record_offset)
        # Overlay rows (and offline-analyzed sources) may carry only the
        # analysis-DB clip_uuid, which _find_clip cannot resolve; translate
        # any unknown id to a media-pool clip via the DB's recorded file path.
        pending_ids = {row["clip_id"] for row in rows
                       if row.get("clip_id") and not _find_clip(root_folder, row["clip_id"])}
        if pending_ids:
            from src.core import timeline_brain_db as _tbdb
            translated: Dict[str, Any] = {}
            try:
                conn = _tbdb.connect(project_root)
                for cid in pending_ids:
                    db_row = conn.execute(
                        "SELECT file_path, clip_name FROM clips WHERE clip_uuid = ?",
                        (cid,)).fetchone()
                    if db_row is None:
                        continue
                    mp_clip = _find_clip_by_file_path(
                        root_folder, str(db_row["file_path"] or db_row["clip_name"] or ""))
                    if mp_clip:
                        translated[cid] = mp_clip.GetUniqueId()
            except Exception:
                pass
            for row in rows:
                if row.get("clip_id") in translated:
                    row["clip_id"] = translated[row["clip_id"]]
        built = []
        build_errors = []
        punch_targets = []
        for i, row in enumerate(rows):
            append_ci = dict(row)
            clip_path = append_ci.pop("clip_path", None)
            punch = append_ci.pop("punch_in", None)
            append_ci.pop("role", None)
            if clip_path and not append_ci.get("clip_id"):
                clip = _find_clip_by_file_path(root_folder, str(clip_path))
                if not clip:
                    build_errors.append({"index": i, "error": f"media pool clip not found for {clip_path!r}"})
                    continue
                append_ci["clip_id"] = clip.GetUniqueId()
            ci_row, row_err = _build_append_clip_info_dict(root_folder, append_ci, i, timeline_start)
            if row_err:
                build_errors.append({"index": i, "error": row_err.get("error")})
                continue
            built.append(ci_row)
            if punch and row.get("media_type") == 1:
                punch_targets.append({
                    "record_frame": int(append_ci["record_frame"]),
                    "zoom": float(punch.get("zoom") or _auto_edit_mod.PUNCH_IN_ZOOM),
                })
        # A positioned append to A2+ is SILENTLY DROPPED unless the audio track
        # already exists (verified live — api_truth #12 probe 6), so the music bed
        # on A2 vanishes without this. Create the audio tracks the rows target
        # before the append. (CreateEmptyTimeline starts with one audio track.)
        need_audio = max(
            [int(r.get("trackIndex", 1)) for r in built
             if int(r.get("mediaType", 1)) == 2] or [0])
        while need_audio and int(tl.GetTrackCount("audio") or 1) < need_audio:
            if not tl.AddTrack("audio"):
                # AddTrack can refuse (locked timeline, modal open); bail rather
                # than spin — the append below then drops the A2+ rows, which the
                # build_errors surface makes visible.
                build_errors.append({
                    "error": f"AddTrack('audio') refused; need {need_audio} audio "
                             f"tracks, have {tl.GetTrackCount('audio')}"})
                break
        appended = mp.AppendToTimeline(built) if built else None

        # 4) Punch-in zoom on jump-cut segments (static transform per item).
        punch_results = []
        if punch_targets:
            try:
                items = tl.GetItemListInTrack("video", 1) or []
                base = int(timeline_start or 0)
                items_by_record: Dict[int, Any] = {}
                for it in items:
                    items_by_record.setdefault(int(it.GetStart()) - base, it)
                for target in punch_targets:
                    hit = items_by_record.get(target["record_frame"])
                    if hit is None:
                        punch_results.append({**target, "applied": False, "reason": "item not found"})
                        continue
                    ok_x = bool(hit.SetProperty("ZoomX", target["zoom"]))
                    ok_y = bool(hit.SetProperty("ZoomY", target["zoom"]))
                    punch_results.append({**target, "applied": ok_x and ok_y})
            except Exception as exc:
                punch_results.append({"error": f"{type(exc).__name__}: {exc}"})

        readback = _edit_engine_capture(tl)
        try:
            usage = _timeline_versioning.capture_timeline_clip_usage(tl)
            by_type: Dict[str, int] = {}
            for usage_row in usage:
                by_type[usage_row["track_type"]] = by_type.get(usage_row["track_type"], 0) + 1
            readback["usage_summary"] = {"items": len(usage), "by_track_type": by_type}
        except Exception:
            pass
        _edit_engine_mod.mark_plan_executed(project_root, plan["plan_id"], {
            "timeline_name": tl.GetName(),
            "appended": len(built),
            "build_errors": build_errors,
            # Persist the intro-title footprint: polish_timeline shifts its op
            # positions by this record_offset so cross-dissolves/lower-thirds
            # line up with the built timeline's record frames.
            "title": title_result,
            **readback,
        })
        if plan.get("brief_id"):
            _auto_edit_mod.advance_brief(
                project_root, plan["brief_id"], "built",
                built_timeline=tl.GetName())
        out = {
            "success": bool(appended),
            "timeline_name": tl.GetName(),
            "appended": len(built),
            "build_errors": build_errors,
            "title": title_result,
            "punch_ins": punch_results,
            "readback": readback,
            "plan_id": plan["plan_id"],
            "next": "finish(plan_id, render={target_dir}) to grade/subtitle/render",
        }
        if bed_note:
            out["music_bed_note"] = bed_note
        return out

    if action == "finish":
        _r, proj, project_root, err = _auto_edit_project_context(p, need_resolve=True)
        if err:
            return err
        gate = _auto_edit_mod.require_approved_plan(project_root, _plan_id_param())
        if not gate.get("success"):
            return _err(gate.get("error") or "plan gate failed")
        plan = gate["plan"]
        built_name = (plan.get("execution_summary") or {}).get("timeline_name")
        if not built_name:
            return _err("plan has no built timeline yet — build_timeline first")
        tl, _idx = _find_timeline_by_name(proj, built_name)
        if not tl:
            return _err(f"built timeline {built_name!r} not found in the project")
        grade = p.get("grade") if isinstance(p.get("grade"), dict) else None
        subtitles = p.get("subtitles") if isinstance(p.get("subtitles"), dict) else None
        render = p.get("render") if isinstance(p.get("render"), dict) else None
        if "confirm_token" not in p and "confirmToken" not in p and _confirm_token_required():
            return _issue_confirm_token(
                action="auto_edit.finish", params=p,
                preview={
                    "operation": "auto_edit.finish",
                    "warning": "Applies grade/subtitles to the built timeline and "
                               "renders an output file.",
                    "timeline": built_name,
                    "grade": {k: v for k, v in (grade or {}).items() if k != "cdl"},
                    "subtitles": bool(subtitles),
                    "render_target": (render or {}).get("target_dir"),
                },
            )
        blocked = _consume_confirm_token(action="auto_edit.finish", params=p)
        if blocked:
            return blocked
        try:
            proj.SetCurrentTimeline(tl)
        except Exception:
            pass
        result: Dict[str, Any] = {"success": True, "timeline": built_name}

        if grade:
            graded: Dict[str, Any] = {}
            items = tl.GetItemListInTrack("video", 1) or []
            if grade.get("lut_path"):
                ok_count = 0
                for item in items:
                    try:
                        g = item.GetNodeGraph()
                        if g and g.SetLUT(int(grade.get("node_index") or 1), str(grade["lut_path"])):
                            ok_count += 1
                    except Exception:
                        continue
                graded["lut"] = {"applied": ok_count, "of": len(items)}
            if grade.get("cdl"):
                normalized = _normalize_cdl(grade["cdl"])
                ok_count = 0
                for item in items:
                    try:
                        if item.SetCDL(normalized):
                            ok_count += 1
                    except Exception:
                        continue
                graded["cdl"] = {"applied": ok_count, "of": len(items)}
            if grade.get("drx_path"):
                try:
                    ok = bool(tl.ApplyGradeFromDRX(
                        str(grade["drx_path"]), int(grade.get("grade_mode") or 0), items))
                except Exception as exc:
                    ok = False
                    graded["drx_error"] = f"{type(exc).__name__}: {exc}"
                graded["drx"] = {"applied": ok}
            result["grade"] = graded

        if subtitles:
            result["subtitles"] = _safe_create_subtitles(tl, subtitles)

        if render:
            target_dir = str(render.get("target_dir") or render.get("targetDir") or "")
            if not target_dir:
                from src.domains.media_analysis.utils import analysis_memory as _analysis_memory
                target_dir = os.path.join(
                    _analysis_memory.memory_dir(project_root), "auto_edit", "renders")
            os.makedirs(target_dir, exist_ok=True)
            custom_name = str(render.get("custom_name") or render.get("customName")
                              or f"auto_edit_{plan['plan_id']}")
            prepared = _prepare_render_job(proj, {
                "target_dir": target_dir,
                "settings": render.get("settings") or {},
                "format": render.get("format"),
                "codec": render.get("codec"),
                "custom_name": custom_name,
                "require_temp_target": False,
            })
            if not prepared.get("success"):
                result["success"] = False
                result["render"] = prepared
                return result
            job_id = prepared["job_id"]

            def _render_work():
                render_started = time.time()
                started = bool(proj.StartRendering([job_id], False))
                if not started:
                    return {"success": False, "error": "StartRendering returned false", "job_id": job_id}
                while proj.IsRenderingInProgress():
                    time.sleep(2)
                status = _ser(proj.GetRenderJobStatus(job_id))
                job_failed = str((status or {}).get("JobStatus") if isinstance(status, dict)
                                 else "").lower() in ("failed", "cancelled", "canceled")
                # Only files written by THIS render count — a prior finish of
                # the same plan leaves same-prefix files behind (2s tolerance
                # for coarse filesystem mtimes).
                outputs = []
                for fname in os.listdir(target_dir):
                    if not fname.startswith(custom_name):
                        continue
                    full = os.path.join(target_dir, fname)
                    if os.path.getmtime(full) >= render_started - 2:
                        outputs.append(full)
                outputs.sort(key=os.path.getmtime, reverse=True)
                output_path = outputs[0] if outputs else None
                out = {
                    "success": bool(output_path and os.path.isfile(output_path)) and not job_failed,
                    "job_id": job_id,
                    "status": status,
                    "output_path": output_path,
                }
                if not output_path:
                    out["error"] = "no output file found after render"
                elif job_failed:
                    out["error"] = "render job did not complete"
                return out

            # auto_edit is async, so the inline (non-background) render path —
            # a poll loop that lasts the whole render — must not run on the
            # event loop; every concurrent MCP request would stall until done.
            import anyio
            render_result = await anyio.to_thread.run_sync(
                lambda: _run_maybe_background("auto_edit.finish_render", p, _render_work))
            result["render"] = render_result
            if isinstance(render_result, dict) and render_result.get("success") is False:
                result["success"] = False
        if result["success"] and plan.get("brief_id"):
            _auto_edit_mod.advance_brief(project_root, plan["brief_id"], "finished")
        return result

    if action == "polish_timeline":
        # Phase-2 pro polish: the append-rebuild scripting API cannot author
        # transitions or place titles on upper tracks, so export the built
        # timeline as .drt (the only lossless project-native round-trip), run
        # verified drp-format vendor ops on it in scratch, and reimport as a
        # NEW "(polished)" timeline. Export-then-modify preserves the media-link
        # blobs byte-for-byte, so media stays linked without a relink pass.
        _r, proj, project_root, err = _auto_edit_project_context(p, need_resolve=True)
        if err:
            return err
        gate = _auto_edit_mod.require_approved_plan(project_root, _plan_id_param())
        if not gate.get("success"):
            return _err(gate.get("error") or "plan gate failed")
        plan = gate["plan"]
        exec_summary = plan.get("execution_summary") or {}
        built_name = exec_summary.get("timeline_name")
        if not built_name:
            return _err("plan has no built timeline yet — build_timeline first")
        tl, _idx = _find_timeline_by_name(proj, built_name)
        if not tl:
            return _err(f"built timeline {built_name!r} not found in the project")

        # Decide the ops offline (pure). An exported .drt encodes ABSOLUTE frame
        # positions — the timeline's start frame (01:00:00:00 → 86400 @ 24fps) is
        # baked into every clip's Start (verified live on Resolve Studio 21). So op
        # positions = timeline_start + build_timeline's intro-title footprint +
        # the plan's record frames. Passing only the title offset would place
        # dissolves near frame 0, outside the clips.
        timeline_start = int(_timeline_start_frame(tl) or 0)
        title_offset = int((exec_summary.get("title") or {}).get("record_offset") or 0)
        polish = _auto_edit_mod.plan_polish_ops(
            plan, record_offset=timeline_start + title_offset, options=p.get("options"))
        ops = polish.get("ops") or []
        if not ops:
            return _err(
                "nothing to polish: no flagged cuts or lower-thirds for this cut "
                "(single-source cuts have no source-change dissolves; pass "
                "options.lower_thirds or options.dissolve_on_beat_change)",
            ) | {"polish": polish}

        # Honest refusal before touching Resolve: the surgery needs the Node
        # advanced-server bridge (drp-format vendor ops).
        if not _advanced_bridge.node_available():
            return _err(
                "polish requires the Node advanced-server bridge (drp-format), "
                "and Node.js was not found on PATH — install Node 18+ to enable it.",
            ) | {"polish": polish}

        if "confirm_token" not in p and "confirmToken" not in p and _confirm_token_required():
            return _issue_confirm_token(
                action="auto_edit.polish_timeline", params=p,
                preview={
                    "operation": "auto_edit.polish_timeline",
                    "warning": "Exports the built timeline as .drt, applies "
                               f"{polish['transitions']} cross-dissolve(s) and "
                               f"{polish['lower_thirds']} lower-third(s) via offline "
                               "drt surgery, and imports a NEW '(polished)' timeline. "
                               "No existing timeline is modified.",
                    "built_timeline": built_name,
                    "transitions": polish["transitions"],
                    "lower_thirds": polish["lower_thirds"],
                    "ops": [{"op": o["op"], "reason": o.get("reason")} for o in ops],
                    "notes": polish.get("notes"),
                },
            )
        blocked = _consume_confirm_token(action="auto_edit.polish_timeline", params=p)
        if blocked:
            return blocked

        # Baseline the built timeline's media coverage BEFORE the round-trip: it
        # already carries media-less generators (the intro title) that read as
        # "offline". The polished timeline is judged against this, not a raw count,
        # so those known generators don't false-alarm as dropped source clips.
        baseline_media = _timeline_media_coverage(tl)

        scratch = tempfile.mkdtemp(prefix="auto_edit_polish_")
        export_path = os.path.join(scratch, f"{plan['plan_id']}.drt")
        exported = _export_timeline_checked(tl, {
            "path": export_path, "format": "drt",
            "require_temp_path": False, "background": False, "async_job": False,
        })
        if not exported.get("success"):
            return _err("drt export failed — cannot polish") | {"export": exported}
        drt_src = exported.get("primary_file") or export_path

        chain = _advanced_bridge.run_drp_op_chain(
            ops, drt_src, scratch_dir=os.path.join(scratch, "ops"))
        if not chain.get("success"):
            return _err(chain.get("error") or "polish op chain failed") | {
                "chain": chain, "polish": polish}
        polished_drt = chain["output_path"]

        mp = proj.GetMediaPool()
        if not mp:
            return _err("No media pool")
        polished_name = _unique_timeline_name(proj, f"{built_name} (polished)")
        imported = _import_timeline_checked(proj, mp, {
            "path": polished_drt, "timeline_name": polished_name,
            "require_temp_path": False,
        })
        if not imported.get("success"):
            return _err(imported.get("error") or "reimport of polished .drt failed") | {
                "import": imported, "chain": chain}

        # Resolve names the imported timeline after the .drt container, ignoring the
        # timelineName import option (verified live on 21) — rename it explicitly so
        # the polished timeline reads as "<built> (polished)".
        final_name = imported.get("name") or polished_name
        imp_tl = None
        for _i in range(1, int(proj.GetTimelineCount() or 0) + 1):
            cand = proj.GetTimelineByIndex(_i)
            if cand and str(cand.GetUniqueId()) == str(imported.get("id")):
                imp_tl = cand
                break
        if imp_tl is not None:
            try:
                if imp_tl.SetName(polished_name):
                    final_name = polished_name
            except Exception:
                pass

        # NOTE (checked, intentional): ImportTimelineFromFile makes the polished
        # timeline Resolve's CURRENT one, same mechanism Stage 3.1 (#21) found
        # and restores-away for its trim/move/split/etc. actions. Deliberately
        # left as-is here: `finish` looks up the built timeline by NAME via the
        # plan and calls proj.SetCurrentTimeline(tl) itself before doing any
        # work (see the "finish" branch above), so it never depends on current-
        # timeline state either way — and the docstring's own next-step guidance
        # ("review the (polished) timeline") wants it front-and-center in the
        # Resolve UI right after this call, unlike the small composable Stage
        # 3.1 edits where switching the user's context away is a surprise.

        # Media-link honesty: the polish adds media-less items (a lower-third Text+
        # and, in the reimported timeline, a cross-dissolve transition item) that
        # all read as "offline", so an offline-count diff false-positives. The
        # robust signal is the LINKED count — a dropped source clip is the only
        # thing that reduces it (verified live on a two-source cut: built 9/8 linked
        # → polished 11/8 linked, offline +2, zero clips dropped). Diff linked
        # against the built timeline's pre-round-trip coverage.
        media = imported.get("media") or {}
        real_offline = _auto_edit_mod.dropped_source_clips(
            baseline_linked=int(baseline_media.get("linked", 0)),
            polished_linked=int(media.get("linked", 0)))
        out = {
            "success": True,
            "polished_timeline": final_name,
            "source_timeline": built_name,
            "transitions": polish["transitions"],
            "lower_thirds": polish["lower_thirds"],
            "ops_applied": len(ops),
            "media_link": media,  # {total, linked, offline}; offline includes added generators
            "baseline_media_link": baseline_media,  # built timeline before the round-trip
            "clips_relinked": real_offline == 0,
            "notes": polish.get("notes"),
            "plan_id": plan["plan_id"],
            "next": "review the (polished) timeline; finish(plan_id) still targets "
                    "the built timeline for grade/render",
        }
        if real_offline:
            out["warning"] = (
                f"{real_offline} source clip(s) went offline after the drt round-trip "
                "(beyond the intro title and added lower-thirds) — check media relinking.")
        _edit_engine_mod.mark_plan_executed(project_root, plan["plan_id"], {
            **exec_summary,
            "polished": {
                "timeline_name": out["polished_timeline"],
                "transitions": polish["transitions"],
                "lower_thirds": polish["lower_thirds"],
                "media_link": media,
            },
        })
        return out

    if action == "list_briefs":
        _r, _proj, project_root, err = _auto_edit_project_context(p, need_resolve=False)
        if err:
            return err
        rows = _edit_engine_mod.list_plans(project_root, limit=int(p.get("limit") or 50))
        briefs = [row for row in rows.get("plans") or []
                  if row.get("kind") == _auto_edit_mod.BRIEF_KIND]
        return {"success": True, "briefs": briefs}

    return _unknown(action, [
        "start_brief",
        "brief_status",
        "status",
        "plan_cut",
        "revise_cut",
        "get_cut_summary",
        "approve_cut",
        "build_timeline",
        "polish_timeline",
        "finish",
        "list_briefs",
    ])


_STRATA_CLIP_REF_KEYS = (
    "clip_id", "clipId", "clip_uuid", "clipUuid",
    "clip_dir", "clipDir", "file_path", "filePath",
)
