"""Behaviorally-verified facts about the DaVinci Resolve scripting API.

The Resolve scripting API is under-documented and frequently behaves differently
from its apparent signature: methods live on objects you wouldn't expect, return
values lie, string keys are silently rejected, and some documented-looking calls
don't exist. This module records facts we have *verified against live Resolve* so
agents and code can look the reality up instead of rediscovering it the hard way.

Each entry is a small dict. Grow it opportunistically — every readback recipe and
every fix that uncovers a surprising behavior should add an entry. Facts are
stamped with the Resolve build they were verified on so drift is visible when a
new version ships.

Optional keys on an entry feed the Blackmagic-facing limitations report
(``docs/reference/api-limitations.md``, generated by
``scripts/gen_api_limitations.py``):

  - ``submit``: ``"missing"`` (a capability Blackmagic should add) or ``"bug"``
    (a behavior Blackmagic should fix). Entries without ``submit`` are internal
    quirks/tips and stay out of the report.
  - ``issue``: GitHub issue number (int) that drove the finding, for cross-ref.

When you add or change a ``submit``-tagged entry, regenerate the report
(``venv/bin/python scripts/gen_api_limitations.py``) or the
``tests.test_api_limitations_doc`` drift guard fails.
"""
from typing import Any, Dict, List, Optional

VERIFIED_ON = "DaVinci Resolve Studio 21.0.0"

# Each entry: symbol, object, reality, recommended, tags. `signature` optional.
API_TRUTH: List[Dict[str, Any]] = [
    {
        "symbol": "MediaPool.AutoSyncAudio",
        "object": "MediaPool",
        "signature": "(clips, settings) -> bool",
        "reality": "The boolean return does not reflect whether clips actually "
                   "linked, and string enum keys in `settings` are silently "
                   "rejected (the call returns False).",
        "recommended": "Resolve the AUDIO_SYNC_* enum constants via the live "
                       "resolve handle, and verify by reading each clip's "
                       "'Synced Audio' property (see verify_by_readback).",
        "tags": ["unreliable-return", "silent-failure", "audio", "enum"],
        "submit": "bug",
        "mitigation": ["_normalize_auto_sync_settings", "_safe_auto_sync_audio"],
    },
    {
        "symbol": "Timeline.CreateSubtitlesFromAudio",
        "object": "Timeline",
        "signature": "(autoCaptionSettings) -> bool",
        "reality": "Same failure mode as AutoSyncAudio: the autoCaptionSettings "
                   "dict is keyed by resolve.SUBTITLE_* enum constants with "
                   "resolve.AUTO_CAPTION_* enum values, so plain string keys like "
                   "{'language': 'korean'} are silently rejected (returns False, "
                   "no subtitle track created). The boolean is also unreliable.",
        "recommended": "Resolve the SUBTITLE_*/AUTO_CAPTION_* constants via the "
                       "live resolve handle (server._normalize_auto_caption_settings) "
                       "and verify by reading the timeline's subtitle track count "
                       "before/after (server._safe_create_subtitles).",
        "tags": ["unreliable-return", "silent-failure", "subtitle", "enum"],
        "submit": "bug",
        "mitigation": ["_normalize_auto_caption_settings", "_safe_create_subtitles"],
    },
    {
        "symbol": "ProjectManager CloudProject family (Create/Load/Import/RestoreCloudProject)",
        "object": "ProjectManager",
        "signature": "(..., cloudSettings) -> Project | bool",
        "reality": "All four take an enum-keyed {cloudSettings} dict "
                   "(resolve.CLOUD_SETTING_* keys, resolve.CLOUD_SYNC_* sync-mode "
                   "values). Plain string keys are silently rejected, so a settings "
                   "dict built from human-readable keys yields no project / False.",
        "recommended": "Resolve the CLOUD_SETTING_*/CLOUD_SYNC_* constants via the "
                       "live resolve handle (server._normalize_cloud_settings) "
                       "before calling, and treat the bool return from "
                       "Import/RestoreCloudProject as advisory — verify by reading "
                       "ProjectManager.GetProjectListInCurrentFolder() back "
                       "(server._verify_cloud_import_restore, mirrored by "
                       "cloud_operations._verify_cloud_mutation for the granular "
                       "surface) rather than trusting it.",
        "tags": ["silent-failure", "project", "cloud", "enum"],
        "submit": "bug",
        "mitigation": ["_normalize_cloud_settings", "_verify_cloud_import_restore"],
    },
    {
        "symbol": "Timeline.Export",
        "object": "Timeline",
        "signature": "(fileName, exportType, exportSubtype) -> bool",
        "reality": "exportType/exportSubtype must be resolve.EXPORT_* enum *values* "
                   "resolved from the live handle. A JSON/MCP caller cannot pass a "
                   "live enum, and a plain string ('fcpxml', or even the constant "
                   "name 'EXPORT_FCPXML_1_10') is silently rejected with no file "
                   "written.",
        "recommended": "Map a friendly format/subtype to the EXPORT_* constant and "
                       "resolve it against the live handle "
                       "(server._timeline_export_spec) before calling; verify the "
                       "output file exists afterward.",
        "tags": ["silent-failure", "timeline", "export", "enum"],
        "submit": "bug",
        "mitigation": ["_timeline_export_spec", "_timeline_export_value"],
    },
    {
        "symbol": "ProjectManager.DeleteProject",
        "object": "ProjectManager",
        "signature": "(projectName) -> bool",
        "reality": "Returns False (no deletion) when the target project is, or "
                   "recently was, the current project, and is flaky on the first "
                   "attempt — so a single bool() call leaves the project undeleted "
                   "with no useful error. Guard re-verified live on Studio 21.0.2.4 "
                   "(Stage 4, #24): delete_project_safely deleted the disposable "
                   "project in 1 attempt across multiple runs, so the "
                   "switch-away-then-retry mitigation still holds.",
        "recommended": "Load/close away from the target first, then retry; use "
                       "src/domains/project_lifecycle/utils/project_cleanup.py:delete_project_safely.",
        "tags": ["unreliable-return", "project", "flaky"],
        "submit": "bug",
    },
    {
        "symbol": "Composition.Paste",
        "object": "Fusion Composition",
        "reality": "Passing tool.SaveSettings()'s in-memory table to Paste() / "
                   "LoadSettings() fails across the Python bridge with an "
                   "OrderedDict/null-argument error and creates no node, while "
                   "reporting nothing useful.",
        "recommended": "Duplicate via AddTool(RegID) + SaveSettings(path)/"
                       "LoadSettings(path) through a temp .setting FILE, which "
                       "round-trips reliably. Identify the new node by name diff.",
        "tags": ["fusion", "bridge", "silent-failure"],
        "submit": "bug",
        "mitigation": ["fusion_comp copy_tool"],
    },
    {
        "symbol": "FlowView.SetPos / FlowView.GetPosTable",
        "object": "Fusion FlowView (comp.CurrentFrame.FlowView)",
        "reality": "Node positions are read/written through the FlowView, not the "
                   "tool. SetPos returns nothing reliable; GetPosTable returns a "
                   "1-indexed table (or dict/tuple depending on bridge). "
                   "comp.CurrentFrame is only populated while the Fusion page is "
                   "active — resolving a comp via timeline scope (no page switch) "
                   "gives CurrentFrame=None, so FlowView is unavailable until "
                   "resolve.OpenPage('fusion') runs first. Round-trip re-verified "
                   "live on Resolve Studio 21.0.2.4 (server.fusion_comp "
                   "set_position/get_position via copy_tool's new node): position "
                   "sets and reads back within ~0.001 float tolerance once the "
                   "Fusion page is open.",
        "recommended": "Use comp.CurrentFrame.FlowView.SetPos(tool, x, y); confirm "
                       "with GetPosTable and a liberal position parser. Call "
                       "resolve.OpenPage('fusion') before get_position/set_position "
                       "when working via timeline scope (server._fusion_flow_view "
                       "now returns a wrong_page error with that remediation).",
        "tags": ["fusion", "unreliable-return", "wrong-page"],
        "submit": "bug",
        "mitigation": ["_fusion_flow_view"],
    },
    {
        "symbol": "Timeline.GetTimelineByName",
        "object": "Project",
        "reality": "Does not exist. Timelines are looked up by index.",
        "recommended": "Iterate GetTimelineByIndex(1..GetTimelineCount()).",
        "tags": ["missing-method", "timeline"],
        "submit": "missing",
    },
    {
        "symbol": "Resolve.GetUIManager",
        "object": "Resolve",
        "reality": "Does not exist. There is no scripting API to open the Project "
                   "Settings or Preferences dialogs, save/load UI layouts via a "
                   "UIManager object, or enumerate layout presets from disk "
                   "(layout presets are not stored under Presets/UILayouts). "
                   "Tools built on this fabricated surface could never succeed "
                   "and were removed (2026-07-20 audit).",
        "recommended": "Use the real layout-preset API instead: "
                       "Resolve.SaveLayoutPreset / LoadLayoutPreset / "
                       "ExportLayoutPreset / ImportLayoutPreset / "
                       "DeleteLayoutPreset / UpdateLayoutPreset. Dialogs cannot "
                       "be opened programmatically at all.",
        "tags": ["missing-method", "ui", "layout-presets"],
        "submit": "missing",
    },
    {
        "symbol": "Project render methods (AddRenderJob, SetRenderSettings, ...)",
        "object": "Project",
        "reality": "Render methods live on the Project object, not on a separate "
                   "render-settings interface.",
        "recommended": "Call proj.AddRenderJob(), proj.SetRenderSettings(), "
                       "proj.LoadRenderPreset() directly on the project.",
        "tags": ["render"],
    },
    {
        "symbol": "MediaPoolItem.GetClipProperty('Transcription')",
        "object": "MediaPoolItem",
        "reality": "Returns a PREVIEW of the transcription that ends in an "
                   "ellipsis when the full transcript is longer than the property "
                   "exposes. Not re-triggered live on 21.0.2.4 during Stage 4 "
                   "(#24): reproducing the truncation needs real speech content "
                   "long enough to overflow the property, which synthetic "
                   "silent/tone clips can't provide; the `truncated`-flag guard "
                   "code is unchanged since it was added. Re-probe with real "
                   "dictation media to get a live 21.0.2.4 stamp on this entry.",
        "recommended": "Treat a trailing ellipsis as truncation (see "
                       "media_pool_item get_transcription's `truncated` flag).",
        "tags": ["transcription", "truncation"],
        "submit": "bug",
        "mitigation": ["get_transcription truncated flag"],
    },
    {
        "symbol": "ProjectManager.CreateProject (with a dirty Untitled project)",
        "object": "ProjectManager",
        "reality": "Returns None and pops a modal 'Save Current Project' dialog "
                   "when the current unsaved/Untitled project blocks the switch. "
                   "SaveProject() on an Untitled project re-triggers the same modal. "
                   "Not live-retriggered on 21.0.2.4 during Stage 4 (#24) by "
                   "deliberate choice: reproducing it means leaving a dirty "
                   "Untitled project current and calling raw CreateProject, which "
                   "risks popping a real blocking modal in the operator's live "
                   "Resolve session with no scripted way to dismiss it. The "
                   "recommended workaround is documentation-only (no shipped "
                   "server.py guard currently routes 'create' through "
                   "CloseProject first), so there is no code path to verify here — "
                   "callers/agents must follow it manually.",
        "recommended": "CloseProject(current) to discard the untitled project "
                       "without a prompt, then CreateProject; restore with "
                       "LoadProject afterward.",
        "tags": ["project", "modal", "silent-failure"],
        "submit": "bug",
    },
    {
        "symbol": "Timeline.InsertFusionCompositionIntoTimeline",
        "object": "Timeline",
        "reality": "Reliable way to obtain a Fusion comp on an otherwise empty "
                   "timeline: it inserts a Fusion composition clip whose comp is "
                   "then reachable via GetFusionCompByIndex(1).",
        "recommended": "Use it (rather than InsertGeneratorIntoTimeline) when you "
                       "need a comp to operate on.",
        "tags": ["fusion", "timeline"],
    },
    {
        "symbol": "Source Track Selector / destination track for Insert*IntoTimeline",
        "object": "Timeline",
        "reality": "There is no API to read or set the Source/Auto Track Selector "
                   "(the Edit-page patch panel that picks the destination track). "
                   "InsertTitleIntoTimeline, InsertFusionTitleIntoTimeline, "
                   "InsertGeneratorIntoTimeline, InsertFusionGeneratorIntoTimeline, "
                   "InsertOFXGeneratorIntoTimeline and "
                   "InsertFusionCompositionIntoTimeline take no trackIndex and "
                   "always drop the clip on the selector's current target (V1 in "
                   "practice). Locking lower video tracks does NOT redirect the "
                   "insert — verified live on 21.0.0: locking V1 makes the insert "
                   "FAIL rather than land on V2. Titles/generators also can't be "
                   "moved afterward (no MediaPoolItem, so AppendToTimeline clipInfo "
                   "and MoveClips don't apply). Re-probed on 21.0.2.4 (issue #23, "
                   "3.3.5): dir(Timeline) still exposes NO selector/target-track/"
                   "patch method — the gap is unchanged in 21.0.",
        "recommended": "Placement layer shipped (issue #23, 3.3.5): timeline "
                       "safe_place_overlay wraps the Insert*IntoTimeline calls — it "
                       "pre-checks the V1 lock (so a locked target fails loudly with "
                       "V1_LOCKED instead of silently misfiring), warns when a non-V1 "
                       "target is requested (unreachable), and confirms the insert "
                       "landed by counting V1 items. Live-verified on 21.0.2.4 "
                       "(tests/domains/timeline_edit/live_track_selector_probe.py). Still V1-only and still "
                       "unmovable afterward. For clips that DO have a MediaPoolItem, "
                       "target a track with MediaPool.AppendToTimeline's clipInfo "
                       "'trackIndex' (media_pool append_to_timeline clip_infos). See "
                       "issue #74.",
        "tags": ["missing-method", "timeline", "title", "generator", "track"],
        "submit": "missing",
        "issue": 74,
    },
    {
        "symbol": "Per-clip audio channel-format conversion (Stereo<->Mono)",
        "object": "MediaPoolItem / TimelineItem / drp MpFolder",
        "reality": "No scripting method sets an individual clip's audio channel "
                   "format live. ConvertTimelineToStereo is timeline-wide, and "
                   "CreateStereoClip builds a 3D *visual* stereoscopic clip, not an "
                   "audio mono->stereo change. The Edit-page 'Clip Attributes > "
                   "Audio' channel mapping is UI-only. Verified live on Resolve "
                   "Studio 21.0.2.4 (issue #22, 3.2.3): SetClipProperty('Audio Ch'|"
                   "'Format'|'Audio Channels'|'Channels'|'Audio Format', ...) all "
                   "return False with no change; 'Audio Ch' is a READ-ONLY property "
                   "that reflects the format (2 for a stereo clip, 1 after a manual "
                   "Mono override). OFFLINE, however, the override DOES round-trip "
                   "into an exported .drp (NOT the .drt — this is a source-clip "
                   "attribute, not a timeline property): a Stereo->Mono change in "
                   "Clip Attributes populates the media-pool item's "
                   "<VirtualAudioTracksBA> element in MediaPool/Master/MpFolder.xml. "
                   "Default/source-native format serializes as empty "
                   "(<VirtualAudioTracksBA/>) in BOTH the item's baseline and a "
                   "no-op re-export; only an explicit override writes a populated "
                   "blob, so the encoding is override-only. The blob is a keyed "
                   "binary archive (same UTF-16BE keyed-dict family as FieldsBlob) "
                   "with two keys: 'ChannelsBA' (nested source-channel -> track -> "
                   "channel-in-track mapping) and 'AudioType' (the format enum; a "
                   "Mono override's tail decodes to AudioType=1). One verified "
                   "sample (stereo wav -> Mono, single Embedded Channel 1 -> Audio 1 "
                   "Mono): <VirtualAudioTracksBA> 000000010000000100000002003000000"
                   "00c0000000054000000010000000200000014004300680061006e006e006506"
                   "c0073004200410000000c000000000c0000000200000001000040010000001"
                   "20041007500640069006f0054007900700065000000020000000001. The "
                   "per-format 'ChannelsBA' sub-layout (5.1, LCR, etc.) is NOT yet "
                   "mapped -- only the Stereo->Mono single-sample shape is known.",
        "recommended": "Live: not possible -- use the supported surface (timeline "
                       "add_track with audioType, get_track_sub_type, "
                       "convert_to_stereo (timeline-wide), timeline_item "
                       "get_source_audio_channel_mapping). Offline: a .drp-surgery "
                       "workaround is possible in principle (the override IS "
                       "representable as <VirtualAudioTracksBA> via "
                       "resolve-advanced/vendor/drp-format keyed-dict), but is NOT "
                       "implemented -- it needs (a) mapping the 'ChannelsBA' "
                       "sub-layout across formats via more single-variable "
                       "export-diff samples, and (b) a full-project .drp "
                       "export->edit->reimport path (heavier than the timeline-level "
                       ".drt reimport used for clip volume/pan, since the attribute "
                       "lives on the source clip, not the timeline). See issue #73.",
        "tags": ["missing-method", "audio", "channel", "drp", "offline",
                 "investigated-not-implemented"],
        "issue": 73,
    },
    {
        "symbol": "Native multicam clip creation",
        "object": "MediaPool",
        "reality": "There is no scripting method to create a native multicam clip "
                   "from a set of angles (the R21 API doc has zero multicam mentions). "
                   "Angles can be stacked onto tracks programmatically "
                   "(media_pool setup_multicam_timeline), but the multicam-clip "
                   "conversion itself is a UI-only step. The on-disk encoding IS "
                   "captured (tests/domains/timeline_conform_interchange/live_multicam_drt_probe.py, export-diff of the UI "
                   "conversion on 21.0.2.4): the multicam clip is its own "
                   "Sm2SequenceContainer (a new SeqContainer/<uuid>.xml, NOT an "
                   "MpVideoClip) with one Sm2TiTrack per angle in VideoTrackVec + a "
                   "mirrored AudioTrackVec; each angle track carries a protobuf "
                   "FieldsBlob (NumLayers, AngleId='Camera N'), UserDefinedName "
                   "'Angle N', a shared <Sequence> uuid, and an Items->Sm2TiVideoClip "
                   "pointing at the source MediaRef/MediaFilePath with Start/Duration "
                   "set from the sync (timecode). Media-pool side: the source clips are "
                   "relocated into a new '000_Original Clips' MpFolder and the master "
                   "gains a STANDARD_CLIP '<first> Multicam' entry whose "
                   "VirtualAudioTracksBA references the container.",
        "recommended": "Live: not possible -- prepare a stacked timeline "
                       "(media_pool setup_multicam_timeline) and finish the "
                       "multicam-clip conversion in the Resolve UI. Offline: authorable "
                       "in principle via resolve-advanced/vendor/drp-format "
                       "SeqContainer machinery, but NOT implemented -- it is a heavy new "
                       "vendor op (author a fresh Sm2SequenceContainer + per-angle "
                       "Sm2TiTrack, re-encode the zstd-compressed protobuf FieldsBlobs "
                       "-- same codec family cracked in 3.2.4 -- relocate originals into "
                       "a subfolder, add the '<first> Multicam' master clip, and thread "
                       "it through a full-project .drp export->edit->reimport). See "
                       "issue #30 (3.1.7).",
        "tags": ["missing-method", "media-pool", "multicam", "drp", "offline",
                 "investigated-not-implemented"],
        "submit": "missing",
        "issue": 30,
    },
    {
        "symbol": "Transition create / copy / clone",
        "object": "Timeline / TimelineItem",
        "reality": "The scripting API exposes no method to add, read, copy, or "
                   "clone an edit transition (cross-dissolve, etc.). Transitions "
                   "applied in the UI are invisible to and unmodifiable by scripts.",
        "recommended": "Apply/duplicate transitions in the Resolve UI, or use "
                       "timeline(action='add_transition'|'list_transitions') — offline "
                       "drt surgery via resolve-advanced (drp-format place_transition), "
                       "landing on a NEW timeline (Stage 3.1, issue #21).",
        "tags": ["missing-method", "timeline", "transition"],
        "submit": "missing",
    },
    {
        "symbol": "Cloud project enumeration / export / user management",
        "object": "ProjectManager",
        "reality": "Only CreateCloudProject, LoadCloudProject, ImportCloudProject "
                   "and RestoreCloudProject exist. There is no GetCloudProjectList "
                   "(list available cloud projects), no ExportToCloud, and no "
                   "Add/RemoveUserToCloudProject — so cloud collaboration can't be "
                   "fully automated.",
        "recommended": "Drive cloud project listing, export, and collaborator "
                       "management from the Resolve UI; only create/load/import/"
                       "restore are scriptable.",
        "tags": ["missing-method", "project", "cloud"],
        "submit": "missing",
    },
    {
        "symbol": "TimelineItem trim / move / re-time (no position setters)",
        "object": "TimelineItem",
        "reality": "TimelineItem exposes GetStart, GetEnd, GetDuration, "
                   "GetLeftOffset, GetRightOffset and GetSourceStart/EndFrame, but "
                   "NO matching setters. A clip cannot be trimmed, slipped, slid, "
                   "rolled, moved to another time/track, or have its duration "
                   "changed once it is on the timeline. Verified via dir() on "
                   "Resolve 21.0.0 (getters only).",
        "recommended": "Do edit-point adjustments in the Resolve UI, or use "
                       "timeline(action='trim_clip'|'move_clip'|'slide_clip'|'slip_clip') "
                       "— offline drt surgery via resolve-advanced (drp-format), landing "
                       "on a NEW timeline (Stage 3.1, issue #21). slip_clip supports both "
                       "directions since issue #30 (3.1.5): a single vendor slip primitive "
                       "shifts the source in-point by +/- frames, live-bounds-checked at "
                       "BOTH ends (GetLeftOffset/GetRightOffset headroom) before export.",
        "tags": ["missing-method", "timeline", "edit", "trim"],
        "submit": "missing",
    },
    {
        "symbol": "Razor / blade / split a timeline item",
        "object": "Timeline / TimelineItem",
        "reality": "There is no method to split/cut/blade a clip at a given frame. "
                   "Verified absent on Timeline and TimelineItem (dir(), 21.0.0).",
        "recommended": "Split in the Resolve UI, construct the cut up-front by "
                       "appending two clipInfos with the desired in/out points, or use "
                       "timeline(action='split_clip') — offline drt surgery via "
                       "resolve-advanced (drp-format), landing on a NEW timeline "
                       "(Stage 3.1, issue #21).",
        "tags": ["missing-method", "timeline", "edit"],
        "submit": "missing",
    },
    {
        "symbol": "Clip speed / retime ratio and speed ramps",
        "object": "TimelineItem",
        "reality": "SetProperty exposes only retime *quality* (RetimeProcess, "
                   "MotionEstimation) and transform/crop/composite/opacity keys — "
                   "not the speed value itself. There is no way to set a clip to a "
                   "given % speed, reverse it, or author a speed ramp. Verified "
                   "against the documented SetProperty key list AND by live "
                   "mutating attempt on 21.0.0: SetProperty('Speed'|'PlaybackSpeed'"
                   "|'RetimeSpeed'|'ClipSpeed', 50) all return False, while "
                   "SetProperty('RetimeProcess', 1) returns True.",
        "recommended": "Workaround shipped (issue #30, 3.1.5): "
                       "timeline(action='set_clip_speed') — offline drt surgery that "
                       "swaps the clip's MediaTimemapBA blob (constant speed, reset to "
                       "1x, or a variable-speed ramp via record/source keyframes) and "
                       "rescales the record Duration, landing on a NEW timeline. "
                       "fit_to_fill_edit derives the speed from a target duration; ramp "
                       "new_duration auto-derives from the last keyframe's record_sec x "
                       "fps. The codec (vendor retime-clip.js) round-trips live-captured "
                       "50% and dynamic-ramp blobs byte-for-byte. "
                       "retime_linked_audio=True retimes the linked audio in the same "
                       "pass (pitch changes); default leaves audio untouched.",
        "tags": ["missing-method", "timeline", "retime", "speed", "workaround"],
        "submit": "missing",
    },
    {
        "symbol": "Color node graph editing and primary grade values",
        "object": "Graph / TimelineItem",
        "reality": "The Graph object exposes node enable/label/count, LUT get/set, "
                   "cache mode, ResetAllGrades, ApplyGradeFromDRX and "
                   "ApplyArriCdlLut; TimelineItem adds SetCDL, CopyGrades and color "
                   "versions. But you cannot add, delete, or connect nodes, and you "
                   "cannot read or write primary grade values (lift/gamma/gain/"
                   "offset/contrast/curves/qualifiers/power windows). Grading is "
                   "limited to CDL, whole-grade DRX/LUT application and copying.",
        "recommended": "Build node trees and dial grades in the Resolve UI, or "
                       "author them OFFLINE and apply live: the resolve-advanced "
                       "`drx` codec now writes node trees + primaries (issue #23, "
                       "3.3.1), applied via ApplyGradeFromDRX. Per-parameter grade "
                       "control is still not "
                       "scriptable through the LIVE API (no live read/write of "
                       "primaries or node edits).",
        "tags": ["missing-method", "color", "grade", "node"],
        "submit": "missing",
    },
    {
        "symbol": "Color grade authoring — .drx (offline) node tree + primaries",
        "object": "drx codec / Graph.ApplyGradeFromDRX",
        "reality": "The live API can't add/connect nodes or write primary grade "
                   "values (see the entry above), but a full node tree WITH "
                   "primaries can be authored offline as a .drx and applied live "
                   "(issue #23, 3.3.1). The resolve-advanced `drx` codec exposes "
                   "`generate` (single-node primaries), `merge` (graft nodes onto an "
                   "existing .drx) and `build_graph` (author a whole N-node serial "
                   "tree 1->2->...->N in one call). Primaries (lift/gamma/gain/"
                   "offset/contrast/pivot/saturation), power windows, qualifiers, "
                   "HSL/custom curves and OFX all round-trip in the calibrated set; "
                   "decoded primary values are ground truth. Proven end to end on "
                   "Resolve Studio 21.0.2.4: an offline-authored 2-node tree applied "
                   "via `timeline_item_color safe_apply_drx` takes a clip's graph "
                   "from 1 node to 2 (tests/domains/color_grade/live_drx_grade_authoring_probe.py). "
                   "Read-only caveats remain: ApplyGradeFromDRX REPLACES the whole "
                   "graph (no surgical single-node live edit, no append), and the "
                   "live API still can't READ primaries back -- the only readback is "
                   "export-still-to-.drx then offline parse.",
        "recommended": "Author the grade offline with resolve-advanced `drx` "
                       "build_graph/generate/merge (space='ui' panel units by "
                       "default), then apply live via safe_apply_drx / "
                       "ApplyGradeFromDRX. Back up a still first -- the apply is a "
                       "whole-graph replace with no undo inside the API.",
        "tags": ["color", "grade", "node", "drx", "offline", "authoring"],
        "issue": 23,
    },
    {
        "symbol": "Fairlight audio levels / pan / EQ / automation / FairlightFX",
        "object": "TimelineItem / Timeline",
        "reality": "There is no API to set clip or track volume, pan, EQ, audio "
                   "automation, or to add/configure FairlightFX. SetProperty covers "
                   "video transform only; the audio surface is read-only "
                   "(GetSourceAudioChannelMapping, GetAudioMapping, voice "
                   "isolation). Verified via dir() + SetProperty docs AND by live "
                   "mutating attempt on 21.0.0: SetProperty('Volume'|'Level'|'Gain'"
                   "|'AudioVolume', 0) all return False (note 'Pan' is the VIDEO "
                   "transform key, not audio pan, so it misleadingly succeeds).",
        "recommended": "Mix in the Fairlight UI; only voice-isolation state and "
                       "channel-mapping reads are scriptable. Offline .drt-surgery "
                       "workarounds exist for SOME of these -- see the paired "
                       "entries below: clip volume (issue #14) and clip pan (issue "
                       "#22) are solved; track/channel EQ is confirmed to have no "
                       ".drt workaround; clip-level FairlightFX round-trips but "
                       "isn't decoded yet.",
        "tags": ["missing-method", "audio", "fairlight"],
        "submit": "missing",
    },
    {
        "symbol": "Clip audio volume — .drt (offline) encoding, EffectFiltersBA",
        "object": "drt SeqContainer / Sm2TiAudioClip",
        "reality": "The API can't set clip volume (see the Fairlight entry above), "
                   "but a clip audio-level edit DOES round-trip through an exported "
                   ".drt, so the offline drp-format codec can author it (issue #14 "
                   "Tier-2). Reverse-engineered by export-diff on Resolve Studio "
                   "21.0.2.4: at unity (0 dB) the audio clip's <EffectFiltersBA> "
                   "element is empty (<EffectFiltersBA/>). A non-unity level "
                   "populates it with a fixed 38-byte audio-volume filter blob: "
                   "prefix 000000020000001e800a1b087c4a0f085f1a0b0a0911, then the "
                   "level in dB as a little-endian IEEE-754 float64, then suffix "
                   "4a004a004a004a00 — and inserts a 2001 flag into the clip's "
                   "<FieldsBlob> (length bytes bump 0c->0e). Two verified samples: "
                   "+12.0 dB -> 0000000000002840, +3.7 dB -> a099999999990d40 "
                   "(both LE float64 of the dB value). GetProperty('Volume') still "
                   "returns None, so the level is invisible to scripting even after "
                   "it is set in the UI — the .drt blob is the only readable/"
                   "writable carrier.",
        "recommended": "For Tier-2 ducking, author the <EffectFiltersBA> blob + "
                       "<FieldsBlob> flag on the target audio clip in the exported "
                       ".drt via resolve-advanced/vendor/drp-format, then reimport; "
                       "verify the level shows in the Fairlight/Inspector on a live "
                       "round-trip before trusting the writer.",
        "tags": ["audio", "fairlight", "drt", "offline", "encoding", "ducking"],
        "issue": 14,
    },
    {
        "symbol": "Clip audio pan — .drt (offline) encoding, EffectFiltersBA",
        "object": "drt SeqContainer / Sm2TiAudioClip",
        "reality": "The API can't set clip pan (see the Fairlight entry above; the "
                   "scripting 'Pan' key is the VIDEO transform, not audio pan), but "
                   "a clip pan edit DOES round-trip through an exported .drt (issue "
                   "#22, 3.2.1). Reverse-engineered by export-diff on Resolve Studio "
                   "21.0.2.4 (pan set to 50 by hand in the Edit-page Inspector Audio "
                   "panel). Same protobuf template as clip volume — outer f1 group "
                   "-> f9 { f1 = paramId, f3 { f1 { f2 = fixed64 double } } } — but "
                   "filter kind (outer f1) = 144 not 124, param id (f9's f1) = 96 "
                   "not 95, only ONE f9 (no four empty channel placeholders), and "
                   "the double is the RAW pan value (e.g. 50.0), not dB-scaled. "
                   "One verified sample: pan=50 -> EffectFiltersBA "
                   "0000000200000017800a140890014a0f08601a0b0a09110000000000004940. "
                   "Same <FieldsBlob> 2001 flag as volume. Live round-trip verified: "
                   "authoring pan=-80 via the writer, reimporting into Resolve, and "
                   "re-exporting decodes back to -80 (Resolve's own re-export adds "
                   "an extra field7=2 not present in the authored blob — harmless, "
                   "doesn't affect the decoded value — cause not yet investigated).",
        "recommended": "Author the <EffectFiltersBA> blob + <FieldsBlob> flag on the "
                       "target audio clip in the exported .drt via "
                       "resolve-advanced/vendor/drp-format (setClipPan), then "
                       "reimport; exposed as the timeline set_clip_pan action.",
        "tags": ["audio", "fairlight", "drt", "offline", "encoding", "pan"],
        "issue": 22,
    },
    {
        "symbol": "Track-level Fairlight EQ (mixer channel strip) — does NOT round-trip",
        "object": "drt SeqContainer / Sm2TiTrack",
        "reality": "Unlike clip volume/pan, a TRACK-level EQ edit (the 6-band "
                   "parametric EQ on a channel strip in the Fairlight page mixer, "
                   "not a clip effect) does not carry its parameter data through an "
                   "exported .drt at all (issue #22, 3.2.2). Verified live on "
                   "Resolve Studio 21.0.2.4: setting a channel's Band 1 gain to "
                   "+9.0 dB, exporting, and diffing against a baseline shows the "
                   "clip's <FieldsBlob> 'has effect filters' flag flip (the same "
                   "f4=1 bit clip volume/pan use), but <EffectFiltersBA> stays "
                   "empty (<EffectFiltersBA/>) in BOTH the baseline and the edited "
                   "export — the +9.0 dB value is nowhere in the file. Sm2TiTrack "
                   "itself has no EffectFiltersBA element at all (confirmed "
                   "structurally). The fader/EQ state almost certainly lives "
                   "entirely in the project-level FLStudioModelBA blob (the "
                   "`fairlight` tool already reads this for bus routing — see the "
                   "Audio/Fairlight kernel), which a .drt (a timeline-only export) "
                   "never touches.",
        "recommended": "No .drt-based workaround exists for track/channel EQ. If "
                       "ever pursued, it needs its own investigation of the "
                       "project-level FLStudioModelBA blob (DB-patch route, project "
                       "closed + relaunch, like fairlight bus-routing import_template "
                       "-- not a drt-surgery variant).",
        "tags": ["audio", "fairlight", "drt", "offline", "eq", "impossible"],
        "issue": 22,
    },
    {
        "symbol": "Clip-level FairlightFX chain (e.g. Fairlight EQ) — round-trips, encoding not yet decoded",
        "object": "drt SeqContainer / Sm2TiAudioClip",
        "reality": "Unlike track EQ, a CLIP-level FairlightFX plugin (dragged from "
                   "the Effects Library 'Audio' tab onto the clip itself, e.g. "
                   "'Fairlight EQ') DOES round-trip through an exported .drt — but "
                   "through a completely different mechanism than clip volume/pan. "
                   "Verified live (Resolve Studio 21.0.2.4, Fairlight EQ Band 1 "
                   "gain set to 6.0 dB): <EffectFiltersBA> stays empty "
                   "(<EffectFiltersBA/>); the entire FX chain instead lands in the "
                   "clip's own <FieldsBlob>, which grows from 12 bytes to ~396 "
                   "bytes. Structure: the same 8-byte version+length header as "
                   "other blobs, then a short protobuf preamble containing the "
                   "literal string 'FL::ClipFX', then a zlib-deflated (0x78 0x9c "
                   "header) payload. Decompressed, that payload is ~2.7KB and "
                   "opens with a plugin identifier string "
                   "'bmd:Fairlight EQ:<numeric id>' followed by what appears to be "
                   "a Blackmagic proprietary binary plugin-parameter layout (not "
                   "protobuf) -- NOT yet decoded to individual band "
                   "freq/gain/Q/type fields. Decoding it needs the same "
                   "export-diff method as volume/pan but with several more "
                   "isolated-variable samples (change ONE band's ONE parameter "
                   "per sample) to map the byte layout -- out of scope for this "
                   "pass.",
        "recommended": "A workaround is plausible in principle (the data IS in the "
                       ".drt) but needs substantially more reverse-engineering than "
                       "volume/pan before it can be authored: capture several "
                       "single-variable export-diff samples of the decompressed "
                       "'FL::ClipFX' payload, map the per-band field offsets, then "
                       "write an encoder + decompressor pairing with "
                       "resolve-advanced/vendor/drp-format. Not implemented.",
        "tags": ["audio", "fairlight", "drt", "offline", "eq", "fairlightfx",
                 "investigated-not-implemented"],
        "issue": 22,
    },
    {
        "symbol": "Proxy / optimized-media generation",
        "object": "MediaPoolItem",
        "reality": "Only LinkProxyMedia, UnlinkProxyMedia and "
                   "LinkFullResolutionMedia exist (attach/detach EXISTING proxies). "
                   "There is no method to generate proxies or optimized media. "
                   "Verified via MediaPoolItem dir() (21.0.0).",
        "recommended": "Workaround shipped (issue #23, 3.3.4): render build_proxies "
                       "composes the render queue with LinkProxyMedia — renders the "
                       "target clips as INDIVIDUAL clips into a proxy dir "
                       "(ExportAudio=False to dodge the headless Fairlight/PipeWire "
                       "0%-stall), matches each output to its source by filename, "
                       "LinkProxyMedia, and verifies via the clip's 'Proxy Media "
                       "Path' readback. Live-verified on 21.0.2.4 "
                       "(tests/domains/render_deliver/live_proxy_build_probe.py). GOTCHA: Resolve's render "
                       "queue refuses to write into the system temp dir (AddRenderJob "
                       "fails), so proxy_dir must be a real media location — the "
                       "action defaults require_temp_target=False for that reason. "
                       "Optimized media (as distinct from proxies) still has no "
                       "generate or link API and stays UI-only.",
        "tags": ["missing-method", "media-pool", "proxy"],
        "submit": "missing",
        "issue": 23,
    },
    {
        "symbol": "Insert / Overwrite / Replace / Fit-to-Fill edit modes",
        "object": "MediaPool / Timeline",
        "reality": "MediaPool.AppendToTimeline (with optional recordFrame "
                   "positioning) is the only programmatic placement. The standard "
                   "edit modes — insert (ripple), overwrite, replace, fit-to-fill, "
                   "place-on-top — have no API. Verified via dir() (21.0.0).",
        "recommended": "Position clips with AppendToTimeline clipInfo recordFrame, or "
                       "use the composed workarounds: timeline(action='insert_edit'|"
                       "'replace_edit'|'place_on_top_edit') (Stage 3.1, issue #21) and "
                       "timeline(action='fit_to_fill_edit') (issue #30, 3.1.5 — retimes "
                       "the clip so its source segment fills a target duration via the "
                       "MediaTimemapBA codec).",
        "tags": ["missing-method", "timeline", "edit"],
        "submit": "missing",
    },
    {
        "symbol": "Render in Place / bake a timeline clip to new media",
        "object": "Timeline / TimelineItem / MediaPool",
        "reality": "There is no scripting method for the Edit-page clip "
                   "context-menu action 'Render in Place', which bakes a clip "
                   "(including its Fusion composition and effects) into a NEW "
                   "rendered media file and drops that file back on the timeline "
                   "at the same position, replacing the source clip. No "
                   "Render*/Bake*/Freeze* method exists on Timeline, TimelineItem "
                   "or MediaPool in the Resolve scripting API reference (BMD docs) "
                   "or a dir() audit. NOTE the frequently-confused-but-distinct "
                   "sibling: the render *cache* (a temporary, non-destructive "
                   "cache of a clip's Color/Fusion output that reduces playback "
                   "load WITHOUT creating a new media file) IS scriptable — "
                   "TimelineItem.SetColorOutputCache / SetFusionOutputCache "
                   "('Render Cache Color/Fusion Output' menu actions) and "
                   "Graph.SetNodeCacheMode. Render in Place is the permanent, "
                   "media-producing bake; the render cache is the transient one.",
        "recommended": "If the goal is only to reduce playback/render load, use "
                       "the render cache — exposed as timeline_item "
                       "get_color_cache/set_color_cache/get_fusion_cache/"
                       "set_fusion_cache and the Color-page graph node cache_mode "
                       "(no new media, fully reversible). For a baked media file, "
                       "the composed workaround shipped in issue #30 (3.1.6): "
                       "timeline(action='render_in_place') — single-clip render of "
                       "the clip's record range (MarkIn/MarkOut) into a real media "
                       "dir, import, and same-position replace. isolate=True "
                       "(default) disables the other video tracks during the render "
                       "(restored after) so the bake matches the UI's isolated-clip "
                       "semantics; isolate=False bakes the track composite and warns "
                       "when other tracks overlap. See issue #86.",
        "tags": ["missing-method", "timeline", "render", "cache", "render-in-place", "bake"],
        "submit": "missing",
        "issue": 86,
    },
    {
        "symbol": "Smart Bins / Power Bins creation",
        "object": "MediaPool",
        "reality": "Only AddSubFolder (a regular bin) exists. Smart Bins (rule-"
                   "based) and Power Bins (cross-project) cannot be created or "
                   "configured. Verified via MediaPool dir() (21.0.0).",
        "recommended": "Create Smart/Power Bins in the Resolve UI; only regular "
                       "bins are scriptable. Offline-authoring verdict (issue #23, "
                       "3.3.2): see the paired DB-representation entry below.",
        "tags": ["missing-method", "media-pool", "bins"],
        "submit": "missing",
    },
    {
        "symbol": "Smart Bins / Power Bins — offline project-DB representation",
        "object": "Project.db Sm2MpSmartFolder / (Power Bins: none)",
        "reality": "Investigated the offline DB representation for 3.3.2 (issue "
                   "#23) on Resolve Studio 21.0.2.4 disk databases. SMART BINS are "
                   "stored per-project in the `Sm2MpSmartFolder` table: columns "
                   "Name, MpFolder, ParentFolder, ManuallyOrdered and — crucially — "
                   "a `SearchFilter` BLOB (the rule set) plus a `FieldsBlob`. So a "
                   "smart bin travels inside a .drp and is structurally reachable "
                   "by the offline project_db layer. BUT authoring one is blocked: "
                   "the SearchFilter rule encoding is an opaque BLOB not yet "
                   "reverse-engineered, and a smart folder with an empty/absent "
                   "SearchFilter matches nothing (useless). Cracking it needs a "
                   "UI-authored oracle to export-diff (same method as the 3.2 "
                   "audio/subtitle blobs) — that requires manual Resolve UI "
                   "interaction, so it is deferred, not shipped. POWER BINS are "
                   "cross-project by design and appear in NO Project.db (nor any "
                   "on-disk SQLite database under the Resolve Project Library — "
                   "confirmed by a full table scan). The advanced server operates "
                   "on a single closed Project.db, so it structurally cannot author "
                   "Power Bins offline; that is a hard impossibility for this layer.",
        "recommended": "No offline tool shipped. Smart Bins: reachable in principle "
                       "via project_db (Sm2MpSmartFolder) but blocked on RE of the "
                       "SearchFilter rule BLOB — grab a UI-authored smart bin and "
                       "export-diff the DB to crack it before writing a tool. Power "
                       "Bins: create in the Resolve UI; no offline path exists.",
        "tags": ["media-pool", "bins", "smart-bin", "power-bin", "project-db", "offline"],
        "issue": 23,
    },
    {
        "symbol": "Per-subtitle text content and timing editing",
        "object": "TimelineItem (subtitle track)",
        "reality": "No live setter: a subtitle TimelineItem exposes only the 21 "
                   "transform/composite properties, with no GetText/SetText or "
                   "start/end/duration mutators. (Read is partial: GetName() "
                   "returns the cue text and GetStart()/GetEnd() the timing, so "
                   "server._timeline_transcript already reads subtitles.) "
                   "INVESTIGATED for 3.2.4 (issue #22) via export-diff on "
                   "21.0.2.4 (tests/domains/audio_fairlight/live_subtitle_probe.py): FCPXML is a dead "
                   "end both ways — Resolve exports zero subtitle data and "
                   "ignores hand-authored <caption> on import (6 role/placement "
                   "variants -> 0 subtitle tracks). The .drt DOES carry them: a "
                   "subtitle track is an Sm2TiTrack SubType=3 in "
                   "<SubtitleTrackVec>; each cue is an Sm2TiGenerator whose "
                   "TIMING is plain XML <Start>/<Duration> (frames) and whose "
                   "TEXT lives in <EffectFiltersBA> (00000002 + 4-byte-BE len + "
                   "0x81 + zstd frame -> a protobuf envelope wrapping a BMD "
                   "4-byte-LE inner struct holding the UTF-16LE text plus font/"
                   "colour). .drt export->reimport round-trips cues, and a "
                   "text edit was proven end-to-end (decode zstd, swap UTF-16LE "
                   "text, recompress).",
        "recommended": "Workaround shipped (issue #30): the oracle-validated codec "
                       "lives in src/domains/audio_fairlight/utils/subtitle_codec.py (BMD-exact zstd framing "
                       "— level 3, write_content_size=True, write_checksum=False — "
                       "plus the protobuf-aware re-serializer for the nested length "
                       "cascade, so arbitrary-length text works). Timing edits are "
                       "plain-integer <Start>/<Duration>. Consumed by "
                       "timeline(action='import_srt'), which authors whole cue sets "
                       "into the exported .drt's SubtitleTrackVec and reimports a NEW "
                       "timeline. Requires the `zstandard` package.",
        "tags": ["missing-method", "subtitle", "text", "timing", "drt",
                 "offline", "workaround"],
    },
    {
        "symbol": "Subtitle track styling and presets",
        "object": "TimelineItem / Timeline / Project",
        "reality": "There is no API method to set or query subtitle font "
                   "family, font size, text color, background color, outline, "
                   "shadow, position, alignment, or to apply/query subtitle "
                   "style presets. TimelineItem.GetProperty() on subtitle "
                   "items returns only transform/composite keys. "
                   "Timeline.GetSetting() and Project.GetSetting() return "
                   "None for all probed subtitle-style keys (e.g. "
                   "'subtitleFontName', 'subtitleFontSize', "
                   "'subtitleTextColor', 'subtitleBackgroundColor', "
                   "'subtitlePosition', 'subtitleAlignment', "
                   "'subtitlePreset', 'subtitleStyle'). Verified via dir(), "
                   "GetProperty(), and GetSetting() on Resolve 21.0.0.48.",
        "recommended": "Per-cue styling IS writable offline (issue #30, 3.2.6): the "
                       "cue's EffectFiltersBA BMD leaf carries, after the text, "
                       "[u32-LE len][FontName UTF-16LE][float32-LE size][u32-LE len]"
                       "['#rrggbb' UTF-16LE] — font swaps ride the validated length "
                       "cascade, size is a fixed float overwrite, color a string swap "
                       "(src/domains/audio_fairlight/utils/subtitle_codec.py read_cue_style/author_cue_effblob; "
                       "exposed as the style option of timeline import_srt). Track-level "
                       "presets and the remaining attributes (background, outline, "
                       "shadow, alignment) stay UI-only pending further RE.",
        "tags": ["missing-method", "subtitle", "style", "preset", "workaround"],
        "submit": "missing",
    },
    {
        "symbol": "Speech recognition engine selection",
        "object": "Timeline",
        "reality": "Timeline.CreateSubtitlesFromAudio(autoCaptionSettings) "
                   "always uses the built-in Resolve speech recognition "
                   "engine. There is no API parameter to select an alternative "
                   "provider (e.g. whisper-cli, Google Speech, AWS Transcribe). "
                   "The language selection via resolve.AUTO_CAPTION_LANGUAGE_* "
                   "is the only customization; the engine itself cannot be "
                   "changed.",
        "recommended": "No workaround for provider selection. To use an external "
                       "ASR engine, transcribe outside Resolve and bring the "
                       "result in as a subtitle track (see the SRT-import entry).",
        "tags": ["missing-method", "subtitle", "transcription",
                 "speech-recognition", "asr"],
        "submit": "missing",
    },
    {
        "symbol": "Programmatic SRT / external-subtitle import",
        "object": "Timeline / MediaPool",
        "reality": "There is no scripting method to import an SRT into a subtitle "
                   "track (File -> Import -> Subtitle is UI-only), and Resolve's "
                   "FCPXML importer ignores <caption> elements (verified 3.2.4, "
                   "21.0.2.4). INVESTIGATED for 3.2.5 (issue #22): a subtitle track "
                   "CAN be authored in the `.drt` directly and reimported. Each cue "
                   "is an Sm2TiGenerator in <SubtitleTrackVec> with timing in plain "
                   "XML <Start>/<Duration> and text in a zstd-compressed protobuf "
                   "<EffectFiltersBA> blob. A validated codec "
                   "(tests/domains/audio_fairlight/live_srt_import_probe.py) authors arbitrary-length "
                   "UTF-16LE cue text — pinned by an offline oracle (re-encoding "
                   "cue1 with cue2's text reproduces cue2's real blob byte-for-byte) "
                   "and confirmed end-to-end: a 3-cue SRT (incl. unicode: café, "
                   "em-dash, 日本語) round-tripped with exact text + frame timing.",
        "recommended": "Workaround shipped (issue #30 productization decision): "
                       "timeline(action='import_srt') parses the SRT, authors the "
                       "exported .drt's SubtitleTrackVec (one Sm2TiGenerator per "
                       "cue; frames from timeline fps + start frame; optional "
                       "per-cue style {font,size,color}; mode replace|append) via "
                       "src/domains/audio_fairlight/utils/subtitle_codec.py and reimports a NEW "
                       "'(subtitled)' timeline. Cue template: the timeline's own "
                       "subtitle track if present, else template_drt, else the "
                       "EMBEDDED synthetic template (proven live on 21.0.2.4 to "
                       "survive reimport — no seeding needed). `zstandard` is a "
                       "repo dependency (requirements.txt). This unlocks external "
                       "ASR engines (whisper-cli etc.) feeding proper subtitle "
                       "tracks.",
        "tags": ["missing-method", "subtitle", "srt", "import", "drt",
                 "offline", "asr", "workaround"],
    },
    {
        "symbol": "Media Pool folder rename",
        "object": "MediaPool",
        "reality": "MediaPool exposes AddSubFolder(name), "
                   "DeleteSubFolders([names]), and "
                   "MoveFolders([names], targetFolder) but no "
                   "RenameSubFolder(oldName, newName) method. Folders can be "
                   "created, deleted, and moved, but their names cannot be "
                   "changed through the API. Verified via dir() on Resolve "
                   "21.0.0.",
        "recommended": "Two workarounds shipped (issue #23, 3.3.3). LOSSLESS "
                       "(preferred): close Resolve and rename offline via the "
                       "advanced server's project_db rename_folder — a direct "
                       "Sm2MpFolder.Name UPDATE (backup + schema guard). LIVE "
                       "fallback: media_pool rename_folder does a delete-recreate "
                       "that PRESERVES clips + subfolders but LOSES the ColorTag, "
                       "the folder UniqueId (references break) and manual clip "
                       "ordering — confirm-gated, with a dry_run preview. Both "
                       "live-verified on 21.0.2.4 "
                       "(tests/domains/color_grade/live_folder_rename_probe.py, "
                       "test/project-db-rename-roundtrip.test.mjs).",
        "tags": ["missing-method", "media-pool", "folder"],
        "submit": "missing",
        "issue": 23,
    },
    {
        "symbol": "hasattr() / getattr() on Resolve API objects (attribute fabrication)",
        "object": "(all Resolve scripting objects)",
        "reality": "getattr(obj, name) returns None (not an AttributeError) for ANY "
                   "attribute name, so hasattr(obj, 'TotallyMadeUpMethod') is always "
                   "True even though the attribute doesn't exist and the returned "
                   "value isn't callable. This makes capability detection by hasattr "
                   "impossible — re-verified on Resolve Studio 21.0.2.4: "
                   "getattr(mediaPool, 'SetStart'/'Razor'/'AddNode'/'GenerateProxy') "
                   "all returned None (callable() is False), yet hasattr() for the "
                   "same names was True and none appeared in dir(). Only dir() lists "
                   "the real methods.",
        "recommended": "Never probe method existence with hasattr/getattr; test "
                       "membership against dir(obj) instead. Calling the fabricated "
                       "attribute (obj.MadeUpMethod()) raises TypeError: 'NoneType' "
                       "object is not callable, rather than returning False silently.",
        "tags": ["bridge", "introspection", "silent-failure"],
        "submit": "bug",
    },
    {
        "symbol": "subprocess inheriting stdin under the MCP stdio server",
        "object": "(server runtime)",
        "reality": "A child process that inherits stdin can race-read bytes off "
                   "the JSON-RPC protocol stream and corrupt it; capture_output "
                   "redirects only stdout/stderr.",
        "recommended": "Pass stdin=subprocess.DEVNULL on every subprocess that can "
                       "run while serving over stdio.",
        "tags": ["runtime", "stdio", "subprocess"],
    },
    {
        "symbol": "MediaPoolItem.SetClipProperty('Reel Name', ...)",
        "object": "MediaPoolItem",
        "signature": "(propertyName, propertyValue) -> bool",
        "reality": "Setting the 'Reel Name' clip property returns True but the "
                   "value is silently dropped on read-back when the project is "
                   "configured to derive reel names automatically "
                   "(General Options > 'Assist using reel names from the:' set "
                   "to source clip file / embedding / filename pattern). The "
                   "same True-but-unpersisted behavior occurs via "
                   "SetMetadata('Reel Name', ...). Other clip properties on the "
                   "same clip (e.g. 'Comments') write and persist normally, so "
                   "this is field-specific, not a bridge/permission failure. "
                   "Verified on Resolve 21.0.0; reported as issue #77. Re-verified "
                   "live on Studio 21.0.2.4 (Stage 4, #24): on a disposable "
                   "project's default gate setting, SetClipProperty actually "
                   "returned False outright rather than True-with-drop this time — "
                   "the guard doesn't trust either return value and independently "
                   "confirms via read-back, so it caught the failure regardless of "
                   "which shape Resolve reports.",
        "recommended": "After writing 'Reel Name', read it back with "
                       "GetClipProperty('Reel Name') and refuse to report "
                       "success on mismatch; surface the project-setting gate to "
                       "the caller (server._verify_clip_property_writeback).",
        "tags": ["unreliable-return", "silent-failure", "metadata", "reel-name"],
        "submit": "bug",
        "issue": 77,
        "mitigation": ["_verify_clip_property_writeback", "_verify_writeback"],
    },
    {
        "symbol": "Graph.ApplyGradeFromDRX (node layout preserved on same-structure apply)",
        "object": "Graph",
        "signature": "(path, gradeMode) -> bool",
        "reality": "When the applied .drx has the same node structure/ids as the "
                   "target's current graph, Resolve matches nodes and KEEPS the "
                   "existing node-editor x/y layout — the .drx's stored node "
                   "positions are silently ignored (returns True). Positions from "
                   "the .drx are only honored when the target graph differs "
                   "structurally (e.g. after ResetAllGrades, or a different node "
                   "count/ids). Verified on Resolve 19.1.3: applying a "
                   "positions-only-modified copy of a clip's own grade back to it "
                   "is a layout no-op.",
        "recommended": "To programmatically re-layout a clip's node graph "
                       "(Cleanup Node Graph has no API), reset the grade first, "
                       "then apply the re-positioned .drx: grab still → rewrite "
                       "node x/y → ResetAllGrades → ApplyGradeFromDRX. Grade "
                       "values round-trip byte-identically via the lossless Body "
                       "pass-through.",
        "tags": ["silent-failure", "color", "node-graph", "layout", "drx"],
    },
    {
        "symbol": "MediaPool.AppendToTimeline clipInfo endFrame (exclusive bound)",
        "object": "MediaPool",
        "signature": "([{mediaPoolItem, startFrame, endFrame, recordFrame, "
                     "trackIndex, mediaType}]) -> [TimelineItem]",
        "reality": "clipInfo endFrame is an EXCLUSIVE bound: the appended item's "
                   "duration is endFrame - startFrame frames, not "
                   "endFrame - startFrame + 1. Verified by readback probe on "
                   "Resolve Studio 21.0 — appending {startFrame: 6254, "
                   "endFrame: 6348} yields a 94-frame item, and 130 such "
                   "appends whose absolute recordFrames advance by exactly "
                   "(endFrame - startFrame) assemble a gap-free track whose "
                   "total length equals the sum of (end - start). Code that "
                   "assumes an inclusive bound drifts one frame per clip: "
                   "advancing a record cursor by (end - start + 1) leaves a "
                   "1-frame hole between consecutive clips, and converting a "
                   "half-open range with (end - 1) shaves the range's last "
                   "frame.",
        "recommended": "Treat [startFrame, endFrame) as half-open everywhere: "
                       "duration = endFrame - startFrame; next recordFrame = "
                       "previous recordFrame + duration; no ±1 corrections "
                       "when mirroring keep-ranges into clipInfos.",
        "tags": ["timeline", "edit", "off-by-one", "readback"],
    },
    {
        "symbol": "Timeline.Export(EXPORT_DRT) → offline drp-format surgery → MediaPool.ImportTimelineFromFile round-trip",
        "object": "Timeline / MediaPool",
        "signature": "Export(path, EXPORT_DRT, EXPORT_NONE) -> bool; "
                     "ImportTimelineFromFile(path, options) -> Timeline",
        "reality": "An exported .drt encodes ABSOLUTE timeline frames: every "
                   "clip's <Start> includes the timeline's StartFrame (e.g. 86400 "
                   "for the default 01:00:00:00 @ 24fps), not 0-based record "
                   "positions. Running drp-format vendor ops on the exported "
                   "container (place_transition, place_fusion_title) at those "
                   "absolute frames and reimporting is lossless for source media: "
                   "verified on Resolve Studio 21.0.2.4 — both source clips came "
                   "back linked (export-then-modify preserves the media-link blobs "
                   "byte-for-byte). Note: a placed cross-dissolve ('Cross Dissolve') "
                   "and a placed Fusion title ('Text+') have no MediaPoolItem, so a "
                   "GetMediaPoolItem() coverage scan counts them as 'offline' — that "
                   "is expected for generators/transitions, NOT a broken source link.",
        "recommended": "Position drt ops for a built timeline at ABSOLUTE frames = "
                       "timeline StartFrame + intro-title footprint + the plan's "
                       "record frame (auto_edit.polish_timeline does this). Judge "
                       "media health by whether SOURCE clips relinked, subtracting "
                       "the transitions/titles you knowingly added from the offline "
                       "count.",
        "tags": ["timeline", "conform", "drt", "interchange", "media-link", "absolute-frames"],
        "issue": 12,
    },
    {
        "symbol": "MediaPool.ImportTimelineFromFile timelineName option (.drt)",
        "object": "MediaPool",
        "signature": "(path, {timelineName, ...}) -> Timeline",
        "reality": "The timelineName key in the options dict is IGNORED for a .drt "
                   "import — Resolve names the new timeline after the .drt's "
                   "container/sequence name (e.g. an op-chain output file "
                   "'lk.01.place_fusion_title' produced a timeline of that name). "
                   "Timeline.SetName() AFTER import does work and returns True. "
                   "Verified on Resolve Studio 21.0.2.4.",
        "recommended": "Don't rely on the timelineName import option for .drt; rename "
                       "the imported timeline with Timeline.SetName() afterwards "
                       "(auto_edit.polish_timeline renames to '<built> (polished)').",
        "tags": ["timeline", "conform", "drt", "import", "naming", "silent-failure"],
        "issue": 12,
    },
    {
        "symbol": "Timeline.InsertTitleIntoTimeline on an EMPTY timeline",
        "object": "Timeline",
        "signature": "InsertTitleIntoTimeline(titleName) -> bool",
        "reality": "Works on a completely empty timeline (no prior clips): returns "
                   "True and places the title at the head of V1. The duration is a "
                   "fixed default of 120 frames (5s @ 24fps) and is deterministic "
                   "across inserts. It is NOT adjustable via the API afterwards: "
                   "TimelineItem.SetProperty('Duration'|'End', ...) returns False and "
                   "leaves geometry unchanged (SetProperty only reaches Fusion text "
                   "params like 'Text'). A subsequent MediaPool.AppendToTimeline "
                   "lands exactly at the title's GetEnd() — no gap, no overlap — so "
                   "record_offset = title.GetEnd() - timeline_start is sound. "
                   "Verified live on Resolve Studio 21.0.2.4 (probe 4, issue #12).",
        "recommended": "Insert the intro title first, then read GetEnd() off the "
                       "title item and use it as the append offset (what "
                       "auto_edit.build_timeline does). Don't try to resize the "
                       "title via the API; plan around the 120-frame default.",
        "tags": ["timeline", "edit", "title", "generator", "empty-timeline",
                 "duration", "append"],
        "issue": 12,
    },
    {
        "symbol": "MediaPool.AppendToTimeline audio-only positioned append to A2",
        "object": "MediaPool / Timeline",
        "signature": "AppendToTimeline([{mediaPoolItem, mediaType: 2, trackIndex: 2, "
                     "recordFrame}]) -> [TimelineItem]",
        "reality": "A positioned audio-only append to A2 lands at exactly the "
                   "requested absolute recordFrame — but ONLY if the track already "
                   "exists. A new empty timeline has 1 audio track; appending to "
                   "trackIndex 2 without it neither errors nor creates the track: "
                   "Resolve returns a list containing None (not an empty list), the "
                   "track count stays 1, and nothing is placed. After "
                   "Timeline.AddTrack('audio') the same call succeeds and readback "
                   "shows the clip at the requested frame. Verified live on Resolve "
                   "Studio 21.0.2.4 (probe 6, issue #12).",
        "recommended": "Ensure the target audio track exists (GetTrackCount + "
                       "AddTrack) before a positioned append, and treat a None "
                       "element in AppendToTimeline's result as a per-clip failure "
                       "— check items, not just list truthiness.",
        "tags": ["media-pool", "timeline", "audio", "append", "track",
                 "silent-failure", "positioned-append"],
        "issue": 12,
    },
    {
        "symbol": "Project.GenerateSpeech",
        "object": "Project",
        "signature": "({speechGenerationSettings}, timecode) -> MediaPoolItem",
        "reality": "Live-tested on Resolve Studio 21.0.2.4 with a plain "
                   "{'TextInput': '...'} dict (this is NOT an enum-keyed dict — "
                   "unlike AutoSyncAudio/CreateSubtitlesFromAudio, there is no "
                   "resolve.SPEECH_*/VOICE_* constant defined on the live "
                   "resolve handle at all, confirmed via dir(resolve)). The call "
                   "returns None in well under a second — too fast to be an "
                   "actual synthesis attempt — consistent with the AI Speech "
                   "Generator Extra not being installed on this machine, though "
                   "the API gives no error string to confirm that diagnosis; a "
                   "box with the Extra installed is needed to verify the "
                   "settings-dict shape end to end.",
        "recommended": "Treat a None return as 🔬 hardware/package-gated "
                       "(missing AI Speech Generator Extra) rather than a "
                       "settings-shape bug; re-probe on a machine with the "
                       "Extra installed before assuming the plain-string-key "
                       "shape is complete (e.g. VoiceModel value formats are "
                       "still unverified).",
        "tags": ["ai", "speech", "extra-gated", "resolve-21", "unverified-live",
                 "silent-failure"],
        "submit": "bug",
        "issue": 20,
    },
    {
        "symbol": "Folder.RemoveMotionBlur",
        "object": "MediaPool Folder",
        "signature": "(clipList) -> [{1: origMediaPoolItem, 2: newMediaPoolItem}, ...]",
        "reality": "The batch, folder-level RemoveMotionBlur returns a list of "
                   "int-keyed dicts per processed clip — {1: orig, 2: new} — not "
                   "the [orig, new] 2-tuples/lists the obvious call shape "
                   "suggests. `orig, new = pair` on such a dict silently unpacks "
                   "its KEYS (1, 2) instead of the values, so orig/new end up as "
                   "bare ints; calling .GetName() on them threw AttributeError "
                   "that a broad except then swallowed — folder-level deblur "
                   "reported success=True with an always-empty `created` list, "
                   "silently dropping every result. Live-verified on Resolve "
                   "Studio 21.0.2.4 (issue #20). MediaPoolItem.RemoveMotionBlur "
                   "(single-clip, non-batch) already returns the new clip "
                   "directly and is unaffected.",
        "recommended": "Detect the dict shape explicitly: "
                       "(pair[1], pair[2]) if isinstance(pair, dict) else pair. "
                       "Fixed in src/granular/folder.py and server.py's folder() "
                       "compound action; the offline test stub "
                       "(Folder21.RemoveMotionBlur in test_resolve21_actions.py) "
                       "previously returned the wrong tuple shape too and was "
                       "updated to the live-verified dict shape so regressions "
                       "are caught offline.",
        "tags": ["unreliable-return", "undocumented-shape", "media-pool",
                 "silent-failure", "resolve-21"],
        "submit": "bug",
        "issue": 20,
        "mitigation": ["folder() compound action (server.py)", "granular/folder.py"],
    },
]


def lookup_api_truth(query: Optional[str] = None) -> List[Dict[str, Any]]:
    """Return verified facts matching `query`, or all facts if no query.

    Matches a case-insensitive substring against the symbol, tags, and reality.
    """
    if not query:
        return list(API_TRUTH)
    q = query.lower()
    out = []
    for e in API_TRUTH:
        hay = " ".join([
            e.get("symbol", ""),
            e.get("object", ""),
            e.get("reality", ""),
            " ".join(e.get("tags", [])),
        ]).lower()
        if q in hay:
            out.append(e)
    return out


def submittable_limitations() -> Dict[str, List[Dict[str, Any]]]:
    """Group ``submit``-tagged entries for the Blackmagic-facing report.

    Returns ``{"missing": [...], "bug": [...]}`` — entries Blackmagic should add
    vs. behaviors they should fix — preserving API_TRUTH order within each group.
    """
    groups: Dict[str, List[Dict[str, Any]]] = {"missing": [], "bug": []}
    for e in API_TRUTH:
        kind = e.get("submit")
        if kind in groups:
            groups[kind].append(e)
    return groups
