"""Make the Fairlight ALSA fix apply however Resolve is started.

``resolve_spawn_env()`` builds a raw-hw ALSA config so Fairlight's audio engine
initializes instead of retry-looping against PipeWire/Pulse (without it, renders
wedge mid-run — see the headless-render-hang work). But it only reaches Resolve
when *this connector* spawns it. Start Resolve from the desktop launcher or a
terminal and the variable is simply absent, and renders wedge exactly as before.

This module installs a small user-scoped shim that closes that gap:

- ``~/.local/bin/resolve`` — terminal launches on ``PATH``.
- ``~/.local/share/applications/DaVinciResolve.desktop`` — a user-level override
  shadowing the system entry, so the GUI launcher goes through the shim too.

Both are user-owned and reversible, and neither touches ``/opt/resolve`` (which a
Resolve update would overwrite anyway). The shim re-computes the environment at
launch time rather than baking in a config path: ``resolve_spawn_env()`` picks
the hw playback/capture pair from ``/proc/asound`` per spawn and returns the env
unchanged when no free pair exists, so a frozen path would go stale the moment
devices change.

Linux only — every entry point no-ops cleanly elsewhere.
"""

from __future__ import annotations

import os
import platform
import re
import shutil
from typing import Any, Dict, List, Optional

RESOLVE_BINARY = "/opt/resolve/bin/resolve"
SYSTEM_DESKTOP_ENTRY = "/usr/share/applications/DaVinciResolve.desktop"

# Marks files this module owns, so uninstall never removes something a user
# hand-wrote at the same path.
SHIM_MARKER = "davinci-resolve-mcp-launch-shim"

_SHIM_TEMPLATE = """\
#!/usr/bin/env python3
# {marker}
# Generated by the DaVinci Resolve MCP connector. Safe to delete: removing this
# file restores the stock launch behaviour (and loses the Fairlight ALSA fix).
#
# Applies resolve_spawn_env()'s raw-hw ALSA config, then execs the real Resolve
# binary, so a desktop-launcher or terminal start gets the same environment the
# connector uses when it spawns Resolve itself.
import os
import sys

sys.path.insert(0, {repo_root!r})

try:
    from src.core.proc import resolve_spawn_env
    env = resolve_spawn_env()
except Exception as exc:
    # Never let the shim be the reason Resolve won't start: fall back to the
    # inherited environment, which is exactly the stock behaviour. But say so —
    # a silent fallback means renders can wedge again with no visible cause
    # (typical trigger: the MCP repo moved or was deleted).
    print(
        "resolve launch shim: could not load resolve_spawn_env "
        f"({{exc.__class__.__name__}}: {{exc}}); starting Resolve without the "
        "Fairlight ALSA fix. Reinstall via "
        "resolve_control(action='install_launch_shim') if the MCP repo moved.",
        file=sys.stderr,
    )
    env = dict(os.environ)

os.execve({binary!r}, [{binary!r}] + sys.argv[1:], env)
"""


def _is_linux() -> bool:
    return platform.system().lower() == "linux"


def _repo_root() -> str:
    return os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def shim_path() -> str:
    return os.path.expanduser("~/.local/bin/resolve")


def desktop_entry_path() -> str:
    return os.path.expanduser("~/.local/share/applications/DaVinciResolve.desktop")


def _owned_by_us(path: str) -> bool:
    """True if `path` exists and carries our marker."""
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return SHIM_MARKER in handle.read(4096)
    except OSError:
        return False


def _shim_embedded_repo_root(path: str) -> Optional[str]:
    """Repo root baked into an installed shim's ``sys.path.insert`` line.

    The shim imports ``resolve_spawn_env`` from the repo that installed it; if
    that repo has since moved, the shim still *runs* (it falls back to the
    stock environment) but silently loses the ALSA fix. Parsing the path back
    out lets ``status``/``launch_advisory`` surface that instead. None when the
    file is missing, not ours, or the line is unrecognizable.
    """
    try:
        with open(path, "r", encoding="utf-8") as handle:
            source = handle.read()
    except OSError:
        return None
    m = re.search(r"sys\.path\.insert\(0,\s*(['\"])(.+?)\1\)", source)
    return m.group(2) if m else None


def _desktop_entry_source() -> Optional[str]:
    """The system .desktop entry to base the override on, if readable."""
    try:
        with open(SYSTEM_DESKTOP_ENTRY, "r", encoding="utf-8") as handle:
            return handle.read()
    except OSError:
        return None


def _rewrite_exec_lines(source: str, shim: str) -> str:
    """Point every Exec= line at the shim, preserving field codes (%u, %f, …)."""
    out: List[str] = []
    for line in source.splitlines():
        if line.startswith("Exec=") and RESOLVE_BINARY in line:
            out.append(line.replace(RESOLVE_BINARY, shim, 1))
        else:
            out.append(line)
    return "\n".join(out) + "\n"


def _stamp_marker(entry: str) -> str:
    """Add our ownership marker as a comment *inside* the group.

    The marker has to survive in the file for ``_owned_by_us``/``uninstall``, but
    a .desktop file must open with its group header — a comment above
    ``[Desktop Entry]`` trips stricter parsers — so it goes on the line after.
    """
    lines = entry.splitlines()
    for i, line in enumerate(lines):
        if line.strip() == "[Desktop Entry]":
            lines.insert(i + 1, f"# {SHIM_MARKER}")
            break
    else:  # no group header at all — nothing valid to stamp into
        return entry
    return "\n".join(lines) + "\n"


def _fallback_desktop_entry(shim: str) -> str:
    """Minimal entry for when the system one isn't readable."""
    return (
        "[Desktop Entry]\n"
        "Version=1.0\n"
        "Type=Application\n"
        "Name=DaVinci Resolve\n"
        "GenericName=DaVinci Resolve\n"
        "Path=/opt/resolve/\n"
        f"Exec={shim} %u\n"
        "Terminal=false\n"
        "MimeType=application/x-resolveproj;\n"
        "Icon=davinci-resolve\n"
        "StartupNotify=true\n"
        "StartupWMClass=resolve\n"
    )


def status() -> Dict[str, Any]:
    """Report whether the shim is installed and whether it will actually be used."""
    if not _is_linux():
        return {
            "supported": False,
            "installed": False,
            "reason": f"launch shim is Linux-only (this platform: {platform.system()})",
        }

    shim = shim_path()
    desktop = desktop_entry_path()
    shim_installed = _owned_by_us(shim)
    desktop_installed = _owned_by_us(desktop)

    # A shim in ~/.local/bin only wins for terminal launches if it comes before
    # /opt/resolve/bin on PATH — report what would actually run.
    resolved = shutil.which("resolve")

    warnings: List[str] = []
    if shim_installed and resolved and os.path.realpath(resolved) != os.path.realpath(shim):
        warnings.append(
            f"'resolve' on PATH resolves to {resolved}, not the shim — "
            "add ~/.local/bin earlier on PATH for terminal launches to use it"
        )
    if shim_installed and not resolved:
        warnings.append("~/.local/bin is not on PATH — terminal launches will bypass the shim")
    if not os.path.exists(RESOLVE_BINARY):
        warnings.append(f"{RESOLVE_BINARY} not found — is Resolve installed here?")

    # A moved/deleted repo leaves the shim functional but silently without the
    # ALSA fix (it falls back to the stock environment).
    embedded_repo = _shim_embedded_repo_root(shim) if shim_installed else None
    if shim_installed and embedded_repo and not os.path.isdir(
        os.path.join(embedded_repo, "src", "core")
    ):
        warnings.append(
            f"shim points at {embedded_repo}, which no longer holds this repo — "
            "launches fall back to the stock environment (no Fairlight ALSA fix); "
            "reinstall the shim from the repo's current location"
        )
    elif shim_installed and embedded_repo and os.path.realpath(embedded_repo) != os.path.realpath(_repo_root()):
        warnings.append(
            f"shim was installed from {embedded_repo}, but this repo now runs from "
            f"{_repo_root()} — reinstall the shim so launches use the current copy"
        )

    return {
        "supported": True,
        "installed": shim_installed and desktop_installed,
        "shim": {"path": shim, "installed": shim_installed},
        "desktop_entry": {"path": desktop, "installed": desktop_installed},
        "resolve_on_path": resolved,
        "warnings": warnings,
    }


def launch_advisory() -> Optional[Dict[str, Any]]:
    """Warn only when an *installed* shim has been silently bypassed.

    The shim's terminal half wins only if ``~/.local/bin`` beats ``/opt/resolve/bin``
    on PATH, and nothing enforces that — a Resolve reinstall or a shell-profile
    edit can quietly undo it. Left to `launch_shim_status`, the realistic
    discovery path is "run a render, watch it wedge", which is the cost the shim
    existed to remove. So `resolve_control(action="launch")` — which already runs
    before anything renders — carries this.

    Returns None when there is nothing to say: not Linux, shim not installed
    (declining the shim is a legitimate choice, not a defect to nag about), or
    installed and effective. Never raises: an advisory must not be able to fail
    a launch.
    """
    try:
        if not _is_linux():
            return None
        state = status()
        if not state.get("shim", {}).get("installed"):
            return None
        resolved = state.get("resolve_on_path")
        shim = shim_path()
        effective = bool(resolved) and os.path.realpath(resolved) == os.path.realpath(shim)
        if effective:
            return None
        return {
            "installed": True,
            "effective": False,
            "resolve_on_path": resolved,
            "warnings": state.get("warnings", []),
            "impact": (
                "Terminal `resolve` launches bypass the shim and lose the Fairlight "
                "ALSA config, so renders started from such an instance can wedge "
                "mid-run. Desktop-launcher starts are unaffected."
            ),
        }
    except Exception:  # noqa: BLE001 — advisory must never break launch
        return None


def install() -> Dict[str, Any]:
    """Write the shim and the user-level desktop override. Idempotent."""
    if not _is_linux():
        return {
            "success": False,
            "supported": False,
            "error": f"launch shim is Linux-only (this platform: {platform.system()})",
        }
    if not os.path.exists(RESOLVE_BINARY):
        return {"success": False, "error": f"{RESOLVE_BINARY} not found — nothing to wrap"}

    shim = shim_path()
    desktop = desktop_entry_path()

    for path in (shim, desktop):
        if os.path.exists(path) and not _owned_by_us(path):
            return {
                "success": False,
                "error": (
                    f"{path} already exists and was not written by this connector — "
                    "refusing to overwrite it. Move it aside and retry."
                ),
            }

    try:
        os.makedirs(os.path.dirname(shim), exist_ok=True)
        with open(shim, "w", encoding="utf-8") as handle:
            handle.write(
                _SHIM_TEMPLATE.format(
                    marker=SHIM_MARKER, repo_root=_repo_root(), binary=RESOLVE_BINARY
                )
            )
        os.chmod(shim, 0o755)

        os.makedirs(os.path.dirname(desktop), exist_ok=True)
        source = _desktop_entry_source()
        entry = _rewrite_exec_lines(source, shim) if source else _fallback_desktop_entry(shim)
        entry = _stamp_marker(entry)
        with open(desktop, "w", encoding="utf-8") as handle:
            handle.write(entry)
        os.chmod(desktop, 0o644)
    except OSError as exc:
        return {"success": False, "error": f"could not write launch shim: {exc}"}

    result = status()
    result["success"] = True
    result["note"] = (
        "Desktop-launcher starts now go through the shim. Terminal launches do too "
        "if ~/.local/bin precedes /opt/resolve/bin on PATH — see warnings."
    )
    return result


def uninstall() -> Dict[str, Any]:
    """Remove only files this module wrote. Idempotent."""
    if not _is_linux():
        return {
            "success": False,
            "supported": False,
            "error": f"launch shim is Linux-only (this platform: {platform.system()})",
        }

    removed: List[str] = []
    skipped: List[str] = []
    for path in (shim_path(), desktop_entry_path()):
        if not os.path.exists(path):
            continue
        if not _owned_by_us(path):
            skipped.append(path)
            continue
        try:
            os.unlink(path)
            removed.append(path)
        except OSError as exc:
            return {"success": False, "error": f"could not remove {path}: {exc}"}

    return {
        "success": True,
        "removed": removed,
        "skipped_not_ours": skipped,
    }
