"""Subprocess helpers that are safe to call while the MCP stdio server is live.

The server owns the JSON-RPC stdin/stdout while serving over stdio. A child
process that inherits stdin can race-read bytes off the protocol stream and
corrupt it; ``capture_output`` only redirects stdout/stderr. These wrappers
default ``stdin`` to ``DEVNULL`` so subprocess hygiene is centralized rather
than re-applied at every call site.
"""
import os
import re
import stat
import subprocess
import tempfile
from typing import Any, Dict, List, Optional, Tuple

# Session preload libraries that must never be inherited by processes we spawn.
# NoMachine exports LD_PRELOAD=/usr/NX/lib/libnxegl.so into the whole desktop
# session; its hooks crash two classes of children: Resolve segfaults during
# NVIDIA GL context creation as soon as it races a plugin dlopen (page
# switches), and CUDA/cuDNN users (whisper, GPU ffmpeg) abort with "Cannot
# load symbol cudnnGetVersion". See tests/test_spawn_env_sanitization.py.
_CRASHY_PRELOAD_TOKENS = ("libnxegl.so",)


def sanitized_spawn_env(base_env: Optional[Dict[str, str]] = None) -> Dict[str, str]:
    """Copy of the environment safe for spawning GPU-touching children on Linux.

    Strips known-crashy entries (e.g. NoMachine's libnxegl.so) from LD_PRELOAD,
    dropping the variable entirely if nothing survives; all other variables are
    passed through unchanged.
    """
    env = dict(os.environ if base_env is None else base_env)
    preload = env.get("LD_PRELOAD", "")
    if preload:
        kept = [
            entry
            for entry in re.split(r"[:\s]+", preload)
            if entry and not any(token in entry for token in _CRASHY_PRELOAD_TOKENS)
        ]
        if kept:
            env["LD_PRELOAD"] = ":".join(kept)
        else:
            env.pop("LD_PRELOAD", None)
    return env


def preload_audit(base_env: Optional[Dict[str, str]] = None) -> Dict[str, Any]:
    """Report whether an environment carries a known-crashy LD_PRELOAD entry.

    Children we spawn are already protected by :func:`sanitized_spawn_env`, but
    that cannot help code running *in this process*: a crashy preload
    (NoMachine's libnxegl.so) still SIGABRTs in-process CUDA — e.g. a future
    in-process faster-whisper backend — and can segfault in-process GL. This
    audit lets the server say so at boot, and via the status tool, instead of
    failing obscurely later.

    Returns ``{poisoned, preload, crashy_entries, tokens, message}`` where
    ``message`` is a ready-to-log warning string when poisoned, else ``None``.
    """
    env = os.environ if base_env is None else base_env
    preload = env.get("LD_PRELOAD", "") or ""
    entries = [entry for entry in re.split(r"[:\s]+", preload) if entry]
    crashy = [
        entry
        for entry in entries
        if any(token in entry for token in _CRASHY_PRELOAD_TOKENS)
    ]
    message: Optional[str] = None
    if crashy:
        message = (
            "This server process inherited a known-crashy LD_PRELOAD "
            f"({', '.join(crashy)}). Subprocesses we spawn (Resolve, whisper, "
            "ffmpeg) are sanitized, but in-process GPU code (CUDA/cuDNN, GL) "
            "can still crash. Relaunch the server from a session without this "
            "preload (e.g. `env -u LD_PRELOAD ...`) if you hit in-process GPU "
            "aborts. See docs/guides/media-analysis-guide.md."
        )
    return {
        "poisoned": bool(crashy),
        "preload": preload,
        "crashy_entries": crashy,
        "tokens": list(_CRASHY_PRELOAD_TOKENS),
        "message": message,
    }


# Fairlight's audio engine opens the ALSA "default" device for synchronized
# duplex (8ch float playback+capture). The PipeWire and Pulse ALSA plugins both
# fail that post-prepare, so the engine loops open/close forever and every
# render stalls at 0% waiting on LoadFairlightAudioSamples. Raw hw devices work.
# The override conf must NOT include the system alsa.conf: its conf.d hooks
# re-apply the PipeWire default after any later pcm.!default line.
_ALSA_CONF_TEMPLATE = """\
# Generated by davinci-resolve-mcp: route Resolve's ALSA default to raw hw
# devices so Fairlight's duplex engine works (PipeWire/Pulse plugins stall it).
pcm.!default {{
  type asym
  playback.pcm {{ type plug; slave.pcm {{ type hw; card {p_card}; device {p_dev} }} }}
  capture.pcm {{ type plug; slave.pcm {{ type hw; card {c_card}; device {c_dev} }} }}
}}
ctl.!default {{ type hw; card {p_card} }}
"""


def _free_alsa_devices(proc_asound: str = "/proc/asound") -> Tuple[Optional[Tuple[int, int]], Optional[Tuple[int, int]]]:
    """First unheld (card, device) pair for playback and capture, from /proc/asound.

    A substream is free when its status file reads "closed" (an open PCM shows
    owner/state lines instead — e.g. PipeWire mmap-holding the analog sink).
    """
    playback: Optional[Tuple[int, int]] = None
    capture: Optional[Tuple[int, int]] = None
    try:
        with open(os.path.join(proc_asound, "pcm"), encoding="utf-8") as fh:
            lines: List[str] = fh.readlines()
    except OSError:
        return None, None
    for line in lines:
        m = re.match(r"(\d+)-(\d+):", line)
        if not m:
            continue
        card, dev = int(m.group(1)), int(m.group(2))
        for direction, suffix in (("playback", "p"), ("capture", "c")):
            if direction not in line:
                continue
            if (playback if direction == "playback" else capture) is not None:
                continue
            status_path = os.path.join(proc_asound, f"card{card}", f"pcm{dev}{suffix}", "sub0", "status")
            try:
                with open(status_path, encoding="utf-8") as fh:
                    if fh.read().strip() != "closed":
                        continue
            except OSError:
                continue
            if direction == "playback":
                playback = (card, dev)
            else:
                capture = (card, dev)
    return playback, capture


def resolve_spawn_env(
    base_env: Optional[Dict[str, str]] = None,
    proc_asound: str = "/proc/asound",
    conf_dir: Optional[str] = None,
) -> Dict[str, str]:
    """Environment for launching DaVinci Resolve itself.

    On top of :func:`sanitized_spawn_env`, points ALSA_CONFIG_PATH at a
    generated raw-hw config so Fairlight's audio engine initializes (without it
    the engine retry-loops against PipeWire/Pulse and renders never start).
    A pre-set ALSA_CONFIG_PATH is respected; if no free hw playback+capture
    pair exists the env is returned unchanged (video-only renders still work).
    """
    env = sanitized_spawn_env(base_env)
    if env.get("ALSA_CONFIG_PATH"):
        return env
    playback, capture = _free_alsa_devices(proc_asound)
    if playback is None or capture is None:
        return env
    conf = _ALSA_CONF_TEMPLATE.format(
        p_card=playback[0], p_dev=playback[1], c_card=capture[0], c_dev=capture[1]
    )
    # ALSA configs can load plugin libraries, so the file must not be writable
    # or plantable by another user: keep it in a per-user 0700 dir (not bare
    # /tmp, where the predictable name could be pre-created), and refuse to
    # follow a symlink at the final open.
    if conf_dir is None:
        conf_dir = os.path.join(tempfile.gettempdir(), f"drm-resolve-{os.getuid()}")
        try:
            os.makedirs(conf_dir, mode=0o700, exist_ok=True)
            st = os.lstat(conf_dir)
            if not stat.S_ISDIR(st.st_mode) or st.st_uid != os.getuid():
                return env
        except OSError:
            return env
    conf_path = os.path.join(conf_dir, f"drm-resolve-alsa-{os.getuid()}.conf")
    try:
        fd = os.open(
            conf_path,
            os.O_WRONLY | os.O_CREAT | os.O_TRUNC | getattr(os, "O_NOFOLLOW", 0),
            0o600,
        )
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(conf)
    except OSError:
        return env
    env["ALSA_CONFIG_PATH"] = conf_path
    return env


def safe_run(*args: Any, **kwargs: Any) -> "subprocess.CompletedProcess":
    """subprocess.run with stdin defaulted to DEVNULL and env sanitized.

    stdin can be overridden by passing it explicitly; if ``input`` is given,
    stdin is left alone — subprocess forbids passing both. ``env`` defaults to
    :func:`sanitized_spawn_env` so no caller inherits the session's crashy
    LD_PRELOAD by forgetting the kwarg (pass ``env`` explicitly to override).
    """
    if "input" not in kwargs:
        kwargs.setdefault("stdin", subprocess.DEVNULL)
    if kwargs.get("env") is None:
        kwargs["env"] = sanitized_spawn_env()
    return subprocess.run(*args, **kwargs)


def safe_popen(*args: Any, **kwargs: Any) -> "subprocess.Popen":
    """subprocess.Popen with stdin defaulted to DEVNULL and env sanitized
    (see :func:`safe_run`); override either by passing it explicitly."""
    kwargs.setdefault("stdin", subprocess.DEVNULL)
    if kwargs.get("env") is None:
        kwargs["env"] = sanitized_spawn_env()
    return subprocess.Popen(*args, **kwargs)
