"""Subprocess helpers that are safe to call while the MCP stdio server is live.

The server owns the JSON-RPC stdin/stdout while serving over stdio. A child
process that inherits stdin can race-read bytes off the protocol stream and
corrupt it; ``capture_output`` only redirects stdout/stderr. These wrappers
default ``stdin`` to ``DEVNULL`` so subprocess hygiene is centralized rather
than re-applied at every call site.
"""
import logging
import os
import platform
import re
import subprocess
from typing import Any, Dict, FrozenSet, List, Optional, Tuple

from src.core.private_tmp import private_dir, write_private_text

logger = logging.getLogger(__name__)

# Session preload libraries that must never be inherited by processes we spawn.
# NoMachine exports LD_PRELOAD=/usr/NX/lib/libnxegl.so into the whole desktop
# session; its hooks crash two classes of children: Resolve segfaults during
# NVIDIA GL context creation as soon as it races a plugin dlopen (page
# switches), and CUDA/cuDNN users (whisper, GPU ffmpeg) abort with "Cannot
# load symbol cudnnGetVersion". See tests/test_spawn_env_sanitization.py.
_CRASHY_PRELOAD_TOKENS = ("libnxegl.so",)


def sanitized_spawn_env(base_env: Optional[Dict[str, str]] = None) -> Dict[str, str]:
    """Copy of the environment safe for spawning GPU-touching children on Linux.

    Strips known-crashy entries (e.g. NoMachine's libnxegl.so) from LD_PRELOAD,
    dropping the variable entirely if nothing survives; all other variables are
    passed through unchanged.
    """
    env = dict(os.environ if base_env is None else base_env)
    preload = env.get("LD_PRELOAD", "")
    if preload:
        kept = [
            entry
            for entry in re.split(r"[:\s]+", preload)
            if entry and not any(token in entry for token in _CRASHY_PRELOAD_TOKENS)
        ]
        if kept:
            env["LD_PRELOAD"] = ":".join(kept)
        else:
            env.pop("LD_PRELOAD", None)
    return env


def preload_audit(base_env: Optional[Dict[str, str]] = None) -> Dict[str, Any]:
    """Report whether an environment carries a known-crashy LD_PRELOAD entry.

    Children we spawn are already protected by :func:`sanitized_spawn_env`, but
    that cannot help code running *in this process*: a crashy preload
    (NoMachine's libnxegl.so) still SIGABRTs in-process CUDA — e.g. a future
    in-process faster-whisper backend — and can segfault in-process GL. This
    audit lets the server say so at boot, and via the status tool, instead of
    failing obscurely later.

    Returns ``{poisoned, preload, crashy_entries, tokens, message}`` where
    ``message`` is a ready-to-log warning string when poisoned, else ``None``.
    """
    env = os.environ if base_env is None else base_env
    preload = env.get("LD_PRELOAD", "") or ""
    entries = [entry for entry in re.split(r"[:\s]+", preload) if entry]
    crashy = [
        entry
        for entry in entries
        if any(token in entry for token in _CRASHY_PRELOAD_TOKENS)
    ]
    message: Optional[str] = None
    if crashy:
        message = (
            "This server process inherited a known-crashy LD_PRELOAD "
            f"({', '.join(crashy)}). Subprocesses we spawn (Resolve, whisper, "
            "ffmpeg) are sanitized, but in-process GPU code (CUDA/cuDNN, GL) "
            "can still crash. Relaunch the server from a session without this "
            "preload (e.g. `env -u LD_PRELOAD ...`) if you hit in-process GPU "
            "aborts. See docs/guides/media-analysis-guide.md."
        )
    return {
        "poisoned": bool(crashy),
        "preload": preload,
        "crashy_entries": crashy,
        "tokens": list(_CRASHY_PRELOAD_TOKENS),
        "message": message,
    }


# Fairlight's audio engine opens the ALSA "default" device for synchronized
# duplex (8ch float playback+capture). The PipeWire and Pulse ALSA plugins both
# fail that post-prepare, so the engine loops open/close forever and every
# render stalls at 0% waiting on LoadFairlightAudioSamples. Raw hw devices work.
# The override conf must NOT include the system alsa.conf: its conf.d hooks
# re-apply the PipeWire default after any later pcm.!default line.
_ALSA_CONF_TEMPLATE = """\
# Generated by davinci-resolve-mcp: route Resolve's ALSA default to raw hw
# devices so Fairlight's duplex engine works (PipeWire/Pulse plugins stall it).
#
# This config is deliberately self-contained — including the system alsa.conf
# would let its conf.d hooks re-apply the PipeWire default and undo the whole
# point. But that also means the `hw` *name* definitions normally supplied by
# alsa.conf are absent, and anything opening a device by name (`hw:0`, `hw:1`
# — which Resolve does, repeatedly, for the mixer) fails with
# "Invalid CTL hw:0". So define them here.
pcm.hw {{
  @args [ CARD DEV SUBDEV ]
  @args.CARD {{ type string }}
  @args.DEV {{ type integer default 0 }}
  @args.SUBDEV {{ type integer default -1 }}
  type hw
  card $CARD
  device $DEV
  subdevice $SUBDEV
}}
ctl.hw {{
  @args [ CARD ]
  @args.CARD {{ type string }}
  type hw
  card $CARD
}}
pcm.!default {{
  type asym
  playback.pcm {{ type plug; slave.pcm {{ type hw; card {p_card}; device {p_dev} }} }}
  capture.pcm {{ type plug; slave.pcm {{ type hw; card {c_card}; device {c_dev} }} }}
}}
ctl.!default {{ type hw; card {p_card} }}
"""


def _hdmi_monitor_present(proc_asound: str, card: int, dev: int, hdmi_devs: List[int]) -> bool:
    """Whether the HDMI pin behind (card, dev) has a monitor attached.

    HDMI playback devices on a card map, in ascending device order, onto the
    card's ELD files ``eld#<card>.<index>``; that ELD's ``monitor_present 1``
    means a sink is actually connected. Best-effort — an unreadable/absent ELD
    reads as "no monitor" so a dead pin is never preferred over a real output.
    """
    try:
        index = sorted(hdmi_devs).index(dev)
    except ValueError:
        return False
    eld_path = os.path.join(proc_asound, f"card{card}", f"eld#{card}.{index}")
    try:
        with open(eld_path, encoding="utf-8") as fh:
            for eld_line in fh:
                if eld_line.split()[:1] == ["monitor_present"]:
                    return eld_line.split()[-1] == "1"
    except OSError:
        return False
    return False


# How long to wait on the audio server's own CLI before giving up on it.
_AUDIO_SERVER_QUERY_TIMEOUT_SECONDS = 5.0

# Set in the spawn env when the chosen devices were ones the session audio
# server was already using — i.e. the launch really will take audio away from
# the rest of the desktop, and the post-exit restore in #129 is needed. An
# uncontested launch leaves PipeWire untouched and needs no restart.
AUDIO_CONTESTED_ENV = "RESOLVE_MCP_AUDIO_CONTESTED"


def _audio_server_devices() -> Optional[FrozenSet[Tuple[int, int]]]:
    """The (card, device) pairs the session audio server has live nodes on.

    This is the question ``/proc/asound`` cannot answer. A PipeWire node that is
    merely *idle* is suspended, and a suspended substream's status file reads
    ``closed`` — indistinguishable from genuinely free. So the desktop's own
    output looks available, gets taken exclusively, and every other application
    on the machine goes silent (#131).

    ``pactl`` knows, because it asks the server rather than the kernel: every
    sink/source it lists carries the ``alsa.card`` and ``alsa.device`` of the
    PCM behind it. Two deliberate choices:

    * *sinks and sources*, not ``pactl list cards`` — the server keeps a card
      object for every ALSA card it can see, including ones whose profile is
      off and which it is therefore not using at all. On this machine that
      distinction is the whole fix: cards is {0, 1}, sinks/sources is card 1
      only, and card 0 is exactly the free output Resolve should take.
    * *(card, device)*, not card alone — ALSA exclusivity is per-PCM-device.
      Verified live: ``arecord -D hw:1,2`` succeeds while PipeWire holds
      ``hw:1,0`` RUNNING. Demoting whole cards would give up the alt capture
      device on this machine for nothing.

    Returns ``None``, not an empty set, when the answer is unknown (no
    ``pactl``, no server, a timeout). Unknown must not read as "nothing is in
    use" — the caller keeps its old behaviour instead of confidently grabbing
    the desktop's device.
    """
    devices: set = set()
    for kind in ("sinks", "sources"):
        try:
            done = subprocess.run(
                ["pactl", "list", kind],
                stdin=subprocess.DEVNULL,
                capture_output=True,
                text=True,
                encoding="utf-8",
                timeout=_AUDIO_SERVER_QUERY_TIMEOUT_SECONDS,
            )
        except Exception:
            # Deliberately broad. This probe only *improves* device ranking; a
            # launch must never fail because the audio server's CLI misbehaved.
            # Anything unexpected degrades to "ownership unknown", which is the
            # pre-#131 behaviour, rather than propagating into spawn_resolve().
            logger.debug("audio-server probe: pactl list %s failed", kind, exc_info=True)
            return None
        if done.returncode != 0:
            return None
        # Properties are grouped per sink/source, so card and device must be
        # paired within one block — scanning the whole output for each key
        # independently would cross-product them on a multi-card machine.
        for block in re.split(r"^(?=\S)", done.stdout, flags=re.MULTILINE):
            card = re.search(r'^\s*alsa\.card\s*=\s*"(\d+)"', block, re.MULTILINE)
            dev = re.search(r'^\s*alsa\.device\s*=\s*"(\d+)"', block, re.MULTILINE)
            if card and dev:
                devices.add((int(card.group(1)), int(dev.group(1))))
    return frozenset(devices)


def _rank(
    name: str,
    monitor_present: bool,
    card: int,
    dev: int,
    owned: bool = False,
) -> Tuple[int, int, int, int]:
    """Sort key ranking an ALSA output/input by likelihood of a real sink.

    The leading term is coexistence: a PCM device the session audio server is
    *not* using outranks every device it is, however good the latter looks
    otherwise. Taking a device the desktop is on means opening it exclusively
    and silencing every other application until Resolve exits, so a
    merely-adequate free device beats a perfect contested one (#131). Without
    this term the ranking below actively picks the worst option — ``analog`` is
    tier 0, and the desktop's output is almost always the analog one.

    Within a group: analog first (almost always a real device), then a
    *connected* HDMI pin, then anything unclassified, then digital/SPDIF, then
    a dead HDMI pin last. Ties break on (card, device) so the choice is
    deterministic across launches — the take-first-free bug this replaces
    picked whatever PCM PipeWire left open, so the pair changed run to run
    (#99).
    """
    name_l = name.lower()
    is_hdmi = "hdmi" in name_l
    if "analog" in name_l:
        tier = 0
    elif is_hdmi and monitor_present:
        tier = 1
    elif is_hdmi:
        tier = 4
    elif "digital" in name_l or "iec958" in name_l or "s/pdif" in name_l or "spdif" in name_l:
        tier = 3
    else:
        tier = 2
    return (1 if owned else 0, tier, card, dev)


def _free_alsa_devices(
    proc_asound: str = "/proc/asound",
    owned_devices: Optional[FrozenSet[Tuple[int, int]]] = None,
) -> Tuple[Optional[Tuple[int, int]], Optional[Tuple[int, int]], bool]:
    """Best free (card, device) pair for playback and capture, from /proc/asound.

    A substream is free when its status file reads "closed" (an open PCM shows
    owner/state lines instead — e.g. PipeWire mmap-holding the analog sink).
    Rather than taking the first free substream — which made the choice depend
    on whatever PipeWire happened to hold and picked dead HDMI pins over real
    outputs (#99) — every free candidate is ranked (see :func:`_rank`) and the
    best is chosen; the selection is logged so a bad pick is diagnosable after
    the fact.

    ``owned_devices`` are the ``(card, device)`` pairs the session audio server
    is actually using; they are ranked last so Resolve coexists with the rest of
    the desktop instead of taking its output hostage (#131). Pass an explicit
    frozenset to keep the choice hermetic; ``None`` means "ask the audio
    server", and if it cannot be asked the ranking degrades to the pre-#131
    behaviour.
    """
    try:
        with open(os.path.join(proc_asound, "pcm"), encoding="utf-8") as fh:
            lines: List[str] = fh.readlines()
    except OSError:
        return None, None, False

    # After the /proc read, not before: on a machine with no sound at all there
    # is nothing to rank, and no reason to spend a subprocess asking who owns
    # what.
    if owned_devices is None:
        owned_devices = _audio_server_devices()
    unknown_owners = owned_devices is None

    # (card, dev, name, direction) for every free substream, plus the set of
    # HDMI playback devices per card for the ELD mapping.
    candidates: Dict[str, List[Tuple[int, int, str]]] = {"playback": [], "capture": []}
    hdmi_devs: Dict[int, List[int]] = {}
    # The free set is a snapshot of a moving target — a device busy for the one
    # second we look is invisible to the ranking, and the resulting pick can
    # look inexplicable afterwards. Log what was actually on the table (#131).
    seen: List[str] = []
    for line in lines:
        m = re.match(r"(\d+)-(\d+):\s*([^:]*)", line)
        if not m:
            continue
        card, dev = int(m.group(1)), int(m.group(2))
        name = m.group(3).strip()
        if "hdmi" in name.lower():
            hdmi_devs.setdefault(card, []).append(dev)
        for direction, suffix in (("playback", "p"), ("capture", "c")):
            if direction not in line:
                continue
            status_path = os.path.join(proc_asound, f"card{card}", f"pcm{dev}{suffix}", "sub0", "status")
            try:
                with open(status_path, encoding="utf-8") as fh:
                    if fh.read().strip() != "closed":
                        continue
            except OSError:
                continue
            candidates[direction].append((card, dev, name))
            seen.append(f"{direction} hw:{card},{dev} ({name})")

    def _pick(direction: str) -> Tuple[Optional[Tuple[int, int]], str]:
        best = None
        best_name = ""
        best_owned = False
        best_key: Optional[Tuple[int, int, int, int]] = None
        for card, dev, name in candidates[direction]:
            monitor = _hdmi_monitor_present(proc_asound, card, dev, hdmi_devs.get(card, [])) \
                if "hdmi" in name.lower() else False
            owned = not unknown_owners and (card, dev) in owned_devices
            key = _rank(name, monitor, card, dev, owned)
            if best_key is None or key < best_key:
                best_key, best, best_name, best_owned = key, (card, dev), name, owned
        return (best, best_name, best_owned)

    playback, p_name, p_owned = _pick("playback")
    capture, c_name, c_owned = _pick("capture")
    logger.info(
        "ALSA autodetect: free at probe time = [%s]; audio server holds %s",
        ", ".join(seen) or "nothing",
        "unknown" if unknown_owners else sorted(owned_devices),
    )
    if playback is not None and capture is not None:
        logger.info(
            "ALSA autodetect: playback=hw:%d,%d (%s) capture=hw:%d,%d (%s)",
            playback[0], playback[1], p_name, capture[0], capture[1], c_name,
        )
        # Tier 3: nothing was free, so Resolve takes a card the desktop is on
        # and everything else goes quiet until it exits (#129's restore hands
        # the card back then). Worth a loud line — this is the degraded path,
        # and it is the one users report as "my sound card disappeared".
        if p_owned or c_owned:
            logger.warning(
                "ALSA autodetect: no free duplex pair outside the cards the session "
                "audio server is using (%s); Resolve will open %s exclusively and "
                "other applications lose audio until it exits. Load snd-aloop, or "
                "free a second card, to let them coexist (#131).",
                "unknown" if unknown_owners else sorted(owned_devices),
                "playback" if p_owned and not c_owned else
                "capture" if c_owned and not p_owned else "playback and capture",
            )
    else:
        logger.info(
            "ALSA autodetect: no free duplex pair (playback=%s capture=%s); "
            "leaving env unchanged", playback, capture,
        )
    return playback, capture, bool(p_owned or c_owned)


def resolve_spawn_env(
    base_env: Optional[Dict[str, str]] = None,
    proc_asound: str = "/proc/asound",
    conf_dir: Optional[str] = None,
    owned_devices: Optional[FrozenSet[Tuple[int, int]]] = None,
) -> Dict[str, str]:
    """Environment for launching DaVinci Resolve itself.

    On top of :func:`sanitized_spawn_env`, points ALSA_CONFIG_PATH at a
    generated raw-hw config so Fairlight's audio engine initializes (without it
    the engine retry-loops against PipeWire/Pulse and renders never start).
    A pre-set ALSA_CONFIG_PATH is respected; if no free hw playback+capture
    pair exists the env is returned unchanged (video-only renders still work).

    The chosen devices are opened *exclusively*, so selection prefers cards the
    session audio server is not using — see :func:`_free_alsa_devices` and
    ``owned_devices``, which is passed straight through.
    """
    env = sanitized_spawn_env(base_env)
    if env.get("ALSA_CONFIG_PATH"):
        return env
    playback, capture, contested = _free_alsa_devices(proc_asound, owned_devices)
    if playback is None or capture is None:
        return env
    conf = _ALSA_CONF_TEMPLATE.format(
        p_card=playback[0], p_dev=playback[1], c_card=capture[0], c_dev=capture[1]
    )
    # ALSA configs can load plugin libraries, so the file must not be writable
    # or plantable by another user: keep it in a per-user 0700 dir (not bare
    # /tmp, where the predictable name could be pre-created), and refuse to
    # follow a symlink at the final open.
    if conf_dir is None:
        # Shared with the page lock and the transport state file; see
        # src/core/private_tmp.py for why bare /tmp is not an option.
        conf_dir = private_dir()
        if conf_dir is None:
            return env
    conf_path = os.path.join(conf_dir, f"drm-resolve-alsa-{os.getuid()}.conf")
    if not write_private_text(conf_path, conf):
        return env
    env["ALSA_CONFIG_PATH"] = conf_path
    if contested:
        # Only a contested pick can strand PipeWire in the terminal `error`
        # state, so only a contested pick needs the post-exit restart (#129).
        # Marking it in the env rather than returning it keeps the signal
        # travelling with the spawn — the launch shim is a separate process and
        # reads exactly this. Restarting the session manager after an
        # uncontested launch would glitch audio the launch never disturbed.
        env[AUDIO_CONTESTED_ENV] = "1"
    return env


# The raw-hw conf above opens the card *exclusively*, so while Resolve runs the
# session's audio server cannot have it. PipeWire reacts by failing the node
# ("playback open failed: Device or resource busy") and parking it in `error`
# — a terminal state it never retries out of. So the desktop stays silent even
# after Resolve exits and the card is free again, which reads to the user as
# "the sound card disappeared until I reboot" (#129). Restarting the session
# manager makes it re-probe the card and rebuild the node.
_AUDIO_RESTORE_TIMEOUT_SECONDS = 15.0

# Candidate session managers, in preference order — the FIRST active one is
# restarted and the rest are left alone. Deliberately the session manager and
# not `pipewire` itself: re-probing the card is wireplumber's job, and bouncing
# the daemon would tear down every unrelated audio stream on the desktop.
_AUDIO_SERVER_UNITS = ("wireplumber", "pipewire-media-session")

# Set to disable the restart entirely. Two users: anyone who would rather we
# never touch their audio stack, and the offline test suite — tests/conftest.py
# sets it for the whole run so a mocked spawn can never bounce the developer's
# real session manager (the tests patch Popen, not resolve_spawn_env).
AUDIO_RESTORE_OFF_ENV = "RESOLVE_MCP_NO_AUDIO_RESTORE"


def restore_audio_server(units: Optional[Tuple[str, ...]] = None) -> bool:
    """Make the session audio server re-acquire a card Resolve had exclusively.

    Best-effort and Linux-only: restarts the first active session manager among
    ``_AUDIO_SERVER_UNITS``, which is what pulls a PipeWire node back out of the
    terminal ``error`` state it enters when the device is busy. Returns True if
    a unit was restarted. Never raises — a machine with no systemd user session,
    no PipeWire, or Resolve still holding the card just gets False, and the
    caller carries on. Opt out with ``$RESOLVE_MCP_NO_AUDIO_RESTORE``.
    """
    if platform.system().lower() != "linux":
        return False
    if os.environ.get(AUDIO_RESTORE_OFF_ENV):
        logger.debug("audio restore: skipped (%s is set)", AUDIO_RESTORE_OFF_ENV)
        return False
    for unit in units if units is not None else _AUDIO_SERVER_UNITS:
        try:
            active = subprocess.run(
                ["systemctl", "--user", "is-active", "--quiet", unit],
                stdin=subprocess.DEVNULL,
                capture_output=True,
                timeout=_AUDIO_RESTORE_TIMEOUT_SECONDS,
            )
            if active.returncode != 0:
                continue
            subprocess.run(
                ["systemctl", "--user", "restart", unit],
                stdin=subprocess.DEVNULL,
                capture_output=True,
                timeout=_AUDIO_RESTORE_TIMEOUT_SECONDS,
                check=True,
            )
        except (OSError, subprocess.SubprocessError):
            logger.debug("audio restore: could not restart user unit %s", unit, exc_info=True)
            continue
        logger.info("audio restore: restarted user unit %s", unit)
        return True
    return False


def safe_run(*args: Any, **kwargs: Any) -> "subprocess.CompletedProcess":
    """subprocess.run with stdin defaulted to DEVNULL and env sanitized.

    stdin can be overridden by passing it explicitly; if ``input`` is given,
    stdin is left alone — subprocess forbids passing both. ``env`` defaults to
    :func:`sanitized_spawn_env` so no caller inherits the session's crashy
    LD_PRELOAD by forgetting the kwarg (pass ``env`` explicitly to override).
    """
    if "input" not in kwargs:
        kwargs.setdefault("stdin", subprocess.DEVNULL)
    if kwargs.get("env") is None:
        kwargs["env"] = sanitized_spawn_env()
    return subprocess.run(*args, **kwargs)


def safe_popen(*args: Any, **kwargs: Any) -> "subprocess.Popen":
    """subprocess.Popen with stdin defaulted to DEVNULL and env sanitized
    (see :func:`safe_run`); override either by passing it explicitly."""
    kwargs.setdefault("stdin", subprocess.DEVNULL)
    if kwargs.get("env") is None:
        kwargs["env"] = sanitized_spawn_env()
    return subprocess.Popen(*args, **kwargs)
