#!/usr/bin/env python3
"""Mutation gate for the Resolve bridge helpers (#119 task 12).

The premise of #119 is that a green offline suite proved nothing about the code that
kept regressing: breaking `_api_constant` or `_has_method` outright left
`2153 passed, 0 failed`. Coverage percentages could not see that. Mutation testing
can — so it is measured here on every publish instead of being rediscovered by the
live suite (or by a user) months later.

Each mutation below re-introduces a defect that has ACTUALLY SHIPPED, or the exact
inversion the current implementation exists to prevent. Applying it must make the
offline suite fail, by at least `min_failures` tests. A mutation that survives means
the suite has gone blind to that defect again.

Usage
-----

    .venv/bin/python scripts/mutation_gate.py            # all mutations
    .venv/bin/python scripts/mutation_gate.py --list
    .venv/bin/python scripts/mutation_gate.py --only api_constant_dir_based

Exit codes: 0 all mutations killed, 1 at least one survived (or was too weakly
killed), 2 the harness itself could not run.

Thresholds are floors, not targets. Raise one when new coverage lands; never lower
one to make this pass — a falling kill count is the signal this script exists to
emit. The baselines in the comments are the numbers #119 measured before its fix.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys
import tempfile

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent

# Each entry: the body of a pytest plugin's pytest_configure, applied before
# collection. `min_failures` is the floor measured after #119's fix.
MUTATIONS = {
    "api_constant_dead": {
        "why": "_api_constant always returns None — every export falls back to "
               "passing the literal constant NAME to the API (the cc007ef symptom).",
        "baseline": "0 failed before #119 when applied to granular/common only",
        "min_failures": 5,
        "patch": """
    import src.core.envelope as env
    env._api_constant = lambda obj, name: None
""",
    },
    "api_constant_dir_based": {
        "why": "The cc007ef bug itself: resolve constants via `name in dir(obj)`. "
               "dir() lists methods only, so every EXPORT_* lookup fails and the "
               "literal name is passed to Timeline.Export()/ExportLUT().",
        "baseline": "6 failed, all in tests/core/test_api_constant_resolution.py",
        "min_failures": 10,
        "patch": """
    import src.core.envelope as env

    def _dir_based(obj, name):
        if obj is None or not name:
            return None
        return getattr(obj, name) if name in dir(obj) else None

    env._api_constant = _dir_based
""",
    },
    "api_constant_granular_copy": {
        "why": "Break ONLY the src/granular/common binding. That copy is what the "
               "export path binds; #118's regression test imports the other one, so "
               "this used to be completely invisible.",
        "baseline": "0 failed (2153 passed)",
        "min_failures": 3,
        "patch": """
    import src.granular.common as common
    common._api_constant = lambda obj, name: None
    common._has_method = lambda obj, name: True
""",
    },
    "has_method_always_true": {
        "why": "The fabrication bug _has_method exists to defend against: the bridge "
               "makes hasattr() True for any name, so a gate stuck open calls methods "
               "that do not exist and silently gets None back.",
        "baseline": "10 failed, in 10 files",
        "min_failures": 30,
        "patch": """
    import src.core.envelope as env
    import src.granular.common as common
    env._has_method = common._has_method = lambda obj, name: True
""",
    },
    "has_method_always_false": {
        "why": "The inverse: every capability reported missing, so working features "
               "are refused and capability reports tell the agent nothing works.",
        "baseline": "32 failed",
        "min_failures": 45,
        "patch": """
    import src.core.envelope as env
    import src.granular.common as common
    env._has_method = common._has_method = lambda obj, name: False
""",
    },
    "api_constant_truthiness": {
        "why": "Reject falsy constants — EXPORT_NONE is 0.0, so an `if value:` guard "
               "silently drops a valid subtype and passes the name instead.",
        "baseline": "not previously measured",
        "min_failures": 2,
        "patch": """
    import src.core.envelope as env
    _real = env._api_constant

    def _truthy_only(obj, name):
        value = _real(obj, name)
        return value if value else None

    env._api_constant = _truthy_only
""",
    },
}

_PLUGIN_TEMPLATE = '''"""Generated by scripts/mutation_gate.py — do not check in."""


def pytest_configure(config):{patch}
'''

_SUMMARY_RE = re.compile(r"(\d+) failed")


def _run_mutation(name: str, spec: dict, workdir: pathlib.Path) -> tuple[bool, str]:
    plugin_name = f"mutation_{name}"
    patch = spec["patch"].rstrip("\n")
    if not patch.strip():
        return False, "empty patch"
    (workdir / f"{plugin_name}.py").write_text(
        _PLUGIN_TEMPLATE.format(patch=patch), encoding="utf-8")

    proc = subprocess.run(
        [sys.executable, "-m", "pytest", "-q", "-p", plugin_name],
        cwd=REPO_ROOT,
        env={**_env(), "PYTHONPATH": f"{workdir}:{REPO_ROOT}"},
        capture_output=True,
        text=True,
    )
    output = proc.stdout + proc.stderr
    match = _SUMMARY_RE.search(output)
    failures = int(match.group(1)) if match else 0

    if proc.returncode == 0:
        return False, f"SURVIVED — suite stayed green ({failures} failed)"
    if failures < spec["min_failures"]:
        return False, (f"too weakly killed — {failures} failed, "
                       f"floor is {spec['min_failures']}")
    return True, f"killed by {failures} failing tests (floor {spec['min_failures']})"


def _env():
    import os
    return dict(os.environ)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--list", action="store_true",
                        help="Print the mutation inventory and exit.")
    parser.add_argument("--only", action="append", default=[],
                        help="Run only the named mutation (repeatable).")
    args = parser.parse_args(argv)

    if args.list:
        for name, spec in MUTATIONS.items():
            print(f"{name}\n    {spec['why']}\n    floor: {spec['min_failures']} "
                  f"(baseline before #119: {spec['baseline']})")
        return 0

    selected = args.only or list(MUTATIONS)
    unknown = [n for n in selected if n not in MUTATIONS]
    if unknown:
        print(f"unknown mutation(s): {', '.join(unknown)}", file=sys.stderr)
        return 2

    survivors = []
    with tempfile.TemporaryDirectory(prefix="mutation_gate_") as tmp:
        workdir = pathlib.Path(tmp)
        for name in selected:
            print(f"=== {name} ===", flush=True)
            print(f"    {MUTATIONS[name]['why']}", flush=True)
            killed, detail = _run_mutation(name, MUTATIONS[name], workdir)
            print(f"    {'OK' if killed else 'FAIL'}: {detail}", flush=True)
            if not killed:
                survivors.append(f"{name}: {detail}")

    print()
    if survivors:
        print(f"MUTATION GATE FAILED — {len(survivors)}/{len(selected)} survived:")
        for line in survivors:
            print(f"  - {line}")
        print("\nThe offline suite can no longer see a defect that has shipped "
              "before. Add coverage; do not lower the floor.")
        return 1
    print(f"MUTATION GATE PASSED — {len(selected)}/{len(selected)} mutations killed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
