"""Generated by the repo-restructure Phase 3 split (epic #52, #46).

Extracted from src/server.py; see src/core/CONTEXT.md or the matching domain
CONTEXT.md for what lives here and why.
"""
from __future__ import annotations

import base64
import os
import sys
import json
import logging
import math
import platform
import re
import shutil
import struct
import subprocess
import tempfile
import threading
import time
import zipfile
import zlib
from typing import Dict, Any, Optional, List, Tuple

from src.domains.color_grade.utils.cdl import normalize_cdl_payload
from src.core.mcp_stdio import run_fastmcp_stdio
from src.core.api_truth import lookup_api_truth, VERIFIED_ON as _API_TRUTH_VERIFIED_ON
from src.core.contracts import validate as _validate_params
from src.domains.project_lifecycle.utils.cloud_operations import cloud_sync_status_label
from src.domains.auto_edit.utils.cut_ir import build_cut_list as _build_cut_list
from src.core.page_lock import open_page_serialized as _open_page_serialized
from src.core.proc import preload_audit, resolve_spawn_env, safe_run, sanitized_spawn_env
from src.core.readback import verify_by_readback, verification_stats as _verification_stats
from src.core.update_check import (
    check_for_updates,
    clear_update_prompt_preferences,
    get_cached_update_status,
    get_update_channel,
    get_update_mode,
    ignore_update_version,
    set_update_mode,
    snooze_update_prompt,
    start_background_update_check,
    update_prompt_decision,
    update_state_path,
)
from src.domains.media_analysis.utils.caps_gating import (
    HOST_CHAT_PATHS_PROVIDER,
    HOST_CHAT_VISION_PROVIDERS,
    DEFAULT_VISION_ANALYSIS_PROMPT,
    VISION_SCHEMA_REFERENCE,
)
from src.domains.media_analysis.utils.clip_identity_registry import (
    resolve_output_root as resolve_media_analysis_output_root,
    short_hash,
    slugify,
)
from src.domains.media_analysis.utils.capabilities_and_planning import (
    build_plan as build_media_analysis_plan,
    detect_capabilities as detect_media_analysis_capabilities,
    install_guidance as media_analysis_install_guidance,
)
from src.domains.media_analysis.utils.execute_engine import (
    execute_plan_async as execute_media_analysis_plan_async,
    plan_requires_capabilities as media_analysis_plan_requires_capabilities,
)
from src.domains.media_analysis.utils.reports import (
    build_coverage_report as build_media_analysis_coverage_report,
    cleanup_artifacts as cleanup_media_analysis_artifacts,
    commit_visual_analysis,
    load_report as load_media_analysis_report,
    summarize_reports as summarize_media_analysis_reports,
)
from src.domains.media_analysis.utils.analysis_index_build import build_analysis_index
from src.domains.media_analysis.utils.analysis_index_query import (
    analysis_index_status,
    query_analysis_index,
)
from src.domains.media_analysis.utils.sync_detection import detect_sync_events_for_records as detect_media_sync_events
from src.core import actor_identity, background_jobs, resolve_busy
from src.core.resolve_busy import long_resolve_op
from src.domains.media_analysis.utils.media_analysis_jobs import (
    MEDIA_EXTENSIONS,
    batch_job_status as media_analysis_batch_job_status,
    cancel_batch_job as cancel_media_analysis_batch_job,
    create_batch_job as create_media_analysis_batch_job,
    list_batch_jobs as list_media_analysis_batch_jobs,
    resume_batch_job as resume_media_analysis_batch_job,
    run_batch_job_slice as run_media_analysis_batch_job_slice,
)
from src.core.platform import get_resolve_paths, get_resolve_plugin_paths
from src.domains.color_grade.utils.lut_paths import master_lut_dir, ensure_lut_in_master
from src.domains.extension_authoring.utils import fuse_templates, dctl_templates, script_templates
from src.domains.timeline_edit.utils.timeline_title_text import (
    candidate_title_property_keys as _candidate_title_property_keys,
    plain_to_minimal_styled_xml as _plain_to_minimal_styled_xml,
    timeline_item_get_property_map as _timeline_item_get_property_map,
)
from src.domains.media_pool_ingest.utils.multicam import build_multicam_setup_plan
from src.domains.timeline_conform_interchange.utils.timeline_xml import analyze_timeline_xml, sanitize_timeline_xml
from src.domains.fusion_composition.utils.fusion_group_settings import (
    FUSION_COMMIT_CHECKLIST,
    FUSION_GROUP_GUARDRAILS,
    default_backup_path,
    parse_setting_file,
    splice_inputs_block,
)
from src.core import analysis_runs as _analysis_runs
from src.core import brain_edits as _brain_edits
from src.domains.auto_edit.utils import edit_engine as _edit_engine_mod
from src.domains.auto_edit.utils import auto_edit as _auto_edit_mod
from src.domains.auto_edit.utils import montage_edit as _montage_edit_mod
from src.domains.orchestration.utils import orchestrate as _orchestrate_mod
from src.core import advanced_bridge as _advanced_bridge
from src.domains.auto_edit.utils import music_analysis as _music_analysis_mod
from src.domains.media_pool_ingest.utils import media_pool_changes as _media_pool_changes
from src.core import timeline_versioning as _timeline_versioning
from src.domains.project_lifecycle.utils import project_spec as _project_spec
from src.domains.project_lifecycle.utils import project_lint as _project_lint
from src.domains.timeline_edit.utils import clip_query as _clip_query
from src.core import destructive_hook as _destructive_hook
from src.core.destructive_hook import destructive_op as _destructive_op
import uuid as _ledger_uuid
from src.core import resolve_ai_ledger as _resolve_ai_ledger
from src.core import resolve_ai_governance as _resolve_ai_governance
import hashlib as _hashlib
import time as _time
import uuid as _uuid
from mcp.server.fastmcp import Context, FastMCP, Image
from mcp import types as mcp_types

logger = logging.getLogger("resolve-mcp")

from src.server import mcp

from src.core.envelope import (
    ERROR_CATEGORIES,
    _CATEGORY_RETRYABLE_DEFAULT,
    _RETRYABLE_UNSET,
    _callable_method_names,
    _check,
    _err,
    _has_method,
    _ok,
    _requires_method,
    _safe_clip_call,
    _safe_get_property,
    _ser,
    _unknown,
)
from src.core.tool_kernel import (
    _MARKER_COLORS,
    _normalize_marker_color,
    _normalize_marker_colors,
    _action_help,
    _activate_resolve_window,
    _ai_governance_check,
    _ai_governance_gate,
    _ai_governance_mode,
    _ai_governance_overrides,
    _ai_governance_preset,
    _ai_ledger_root,
    _ai_ledger_timed,
    _confirm_token_fingerprint,
    _confirm_token_gc,
    _confirm_token_required,
    _consume_confirm_token,
    _contact_sheet_png_bytes,
    _contact_sheet_sample_label,
    _draw_rect_rgb,
    _draw_tiny_text_rgb,
    _filter_to_keys,
    _find_timeline_item_by_id,
    _first_param,
    _has_any_param,
    _is_truncated,
    _issue_confirm_token,
    _media_analysis_effective_preferences,
    _normalize_sampling_mode_default,
    _normalize_setup_choice,
    _normalize_setup_list,
    _normalize_timed_marker_choice,
    _normalize_vision_default,
    _normalize_yes_no_ask,
    _opt_number,
    _path_error,
    _png_chunk,
    _read_json_strict,
    _read_media_analysis_preferences,
    _read_media_analysis_preferences_strict,
    _record_action_outcome,
    _resolve_enum_settings,
    _rgb_to_png_bytes,
    _run_maybe_background,
    _safe_int,
    _sampling_mode_choice_from_params,
    _send_resolve_keystroke_go_to_mark_in,
    _settings_diff,
    _setup_marker_limit,
    _setup_positive_int,
    _setup_text_key,
    _string_list_param,
    _thumbnail_data_to_png_bytes,
    _thumbnail_raw_rgb,
    _timed_marker_choice_from_params,
    _timeline_items_by_ids,
    _timeline_items_by_ids_report,
    _timeline_resolve_item_optional,
    _write_media_analysis_preferences,
)
from src.core.timeline_lookup import (
    _clip_file_size,
    _clip_name,
    _clip_summaries,
    _clips_from_params,
    _coerce_item_list,
    _collect_timeline_items_in_range,
    _current_timeline_frame_id,
    _find_clip,
    _find_clip_with_parent,
    _find_timeline_by_id,
    _find_timeline_by_name,
    _frame_id_to_timecode,
    _frame_int,
    _get_item,
    _get_mp,
    _get_selected_timeline_items,
    _get_tl,
    _metadata_write_field_for_field,
    _project_name_and_id,
    _project_summary,
    _range_frames_from_params,
    _range_track_indices,
    _range_track_types,
    _safe_timeline_item_id,
    _safe_timeline_item_name,
    _timecode_to_frame_id,
    _timeline_by_selector,
    _timeline_fps,
    _timeline_frame_id_to_timecode,
    _timeline_item_duration,
    _timeline_item_ids,
    _timeline_item_media_pool_item,
    _timeline_item_probe,
    _timeline_item_source_start,
    _timeline_item_summary,
    _timeline_item_track_info,
    _timeline_start_frame,
    _timeline_timecode_to_frame_id,
    _timeline_track_count,
    _track_items_sorted,
    _track_selector,
)
from src.core.live_connection import (
    get_resolve,
    _destructive_versioning_provider,
)


def _coerce_marker_number(value, field_name):
    if isinstance(value, bool):
        return None, _err(f"{field_name} must be a frame number, not a boolean")
    if isinstance(value, int):
        return value, None
    if isinstance(value, float):
        return int(value) if value.is_integer() else value, None
    if isinstance(value, str):
        raw = value.strip()
        if not raw:
            return None, _err(f"{field_name} cannot be empty")
        try:
            if "." in raw:
                number = float(raw)
                return int(number) if number.is_integer() else number, None
            return int(raw), None
        except ValueError:
            return None, _err(f"{field_name} must be a frame number")
    return None, _err(f"{field_name} must be a frame number")

def _marker_rebase_to_timeline_start(tl, frame):
    """Rebase an absolute frame to a Timeline marker frameId.

    Timeline.AddMarker frameIds are relative to the timeline start (frame 0 ==
    first frame of the timeline), while GetCurrentTimecode and the timecodes
    shown in the Resolve UI are absolute. GetMarkers() echoes back whatever
    frameId was passed without validating, so a marker stored at an absolute
    frame displays past the end of the timeline (invisible in the UI).
    Frames below the timeline start are treated as already relative (elapsed
    time), and the frame passes through unchanged when the start frame is
    unavailable.
    """
    start = _timeline_start_frame(tl)
    if start and frame >= start:
        return frame - start
    return frame

def _marker_timecode_to_frame_id(tl, timecode):
    frame, err = _timeline_timecode_to_frame_id(tl, timecode)
    if err:
        return None, err
    return _marker_rebase_to_timeline_start(tl, frame), None

def _marker_display_frame(tl, frame):
    """Absolute frame for driving the playhead at a stored marker frameId.

    Inverse of _marker_rebase_to_timeline_start: stored timeline marker keys
    are relative to the timeline start, while SetCurrentTimecode is absolute.
    Frames at or past the start frame are assumed to be legacy absolute keys
    and pass through unchanged so they still sample the intended frame.
    """
    frame = int(frame)
    start = _timeline_start_frame(tl)
    if start and frame < start:
        return frame + start
    return frame

def _current_timeline_marker_frame_id(tl):
    frame, err = _current_timeline_frame_id(tl)
    if err:
        return None, err
    return _marker_rebase_to_timeline_start(tl, frame), None

def _marker_frame_from_params(p: Dict[str, Any], tl=None, default_to_current=False):
    """Resolve marker frame params to a marker frameId.

    With a timeline, timecodes (and the playhead default) are rebased so the
    returned frameId is relative to the timeline start. Raw frame numbers are
    passed through unchanged: timeline marker frames are relative to the
    timeline start, clip marker frames are relative to the clip start.
    """
    raw_timecode = _first_param(p, "timecode", "time_code", "tc")
    if raw_timecode is not None:
        return _marker_timecode_to_frame_id(tl, raw_timecode)

    raw_frame = _first_param(p, "frame", "frame_id", "frameId", "frame_num", "frameNum")
    if raw_frame is not None:
        if isinstance(raw_frame, str):
            lowered = raw_frame.strip().lower()
            if lowered in {"current", "playhead", "current_playhead", "now"}:
                return _current_timeline_marker_frame_id(tl)
            if ":" in raw_frame or ";" in raw_frame:
                return _marker_timecode_to_frame_id(tl, raw_frame)
        return _coerce_marker_number(raw_frame, "frame")

    if default_to_current:
        return _current_timeline_marker_frame_id(tl)
    return None, _err("Missing marker frame. Provide frame, frame_id/frameId, or timecode.")

def _marker_add_payload(p: Dict[str, Any], tl=None, default_to_current=False):
    frame, err = _marker_frame_from_params(p, tl=tl, default_to_current=default_to_current)
    if err:
        return None, err

    color, err = _normalize_marker_color(_first_param(p, "color", default="Blue"))
    if err:
        return None, err

    note = str(_first_param(p, "note", "comment", "description", default="") or "")
    name = str(_first_param(p, "name", "label", default=(note or "Marker")) or "Marker")
    duration, err = _coerce_marker_number(
        _first_param(p, "duration", "duration_frames", "durationFrames", default=1),
        "duration",
    )
    if err:
        return None, err
    if duration <= 0:
        return None, _err("duration must be greater than zero")

    return {
        "frame": frame,
        "color": color,
        "name": name,
        "note": note,
        "duration": duration,
        "custom_data": str(_first_param(p, "custom_data", "customData", default="") or ""),
    }, None

def _add_marker(target, marker: Dict[str, Any]):
    try:
        result = target.AddMarker(
            marker["frame"],
            marker["color"],
            marker["name"],
            marker["note"],
            marker["duration"],
            marker["custom_data"],
        )
    except TypeError as exc:
        if marker["custom_data"]:
            return _err(f"AddMarker failed: {exc}")
        try:
            result = target.AddMarker(
                marker["frame"],
                marker["color"],
                marker["name"],
                marker["note"],
                marker["duration"],
            )
        except Exception as fallback_exc:
            return _err(f"AddMarker failed: {fallback_exc}")
    except Exception as exc:
        return _err(f"AddMarker failed: {exc}")

    out = {"success": bool(result), "frame": marker["frame"]}
    if not result:
        try:
            markers = target.GetMarkers() or {}
            frame_keys = {marker["frame"]}
            if isinstance(marker["frame"], int):
                frame_keys.add(float(marker["frame"]))
            if any(frame_key in markers for frame_key in frame_keys):
                out["reason"] = f"A marker already exists at frame {marker['frame']}"
        except Exception:
            pass
    return out

def _annotation_capabilities():
    return {
        "scopes": {
            "timeline": {
                "markers": True,
                "custom_data": True,
                "flags": False,
                "clip_color": False,
                "frame_space": "timeline frames or timeline timecode",
            },
            "timeline_item": {
                "markers": True,
                "custom_data": True,
                "flags": True,
                "clip_color": True,
                "frame_space": "timeline item local/source-facing marker frames",
            },
            "media_pool_item": {
                "markers": True,
                "custom_data": True,
                "flags": True,
                "clip_color": True,
                "frame_space": "media pool item source frames",
            },
        },
        "marker_colors": list(_MARKER_COLORS),
        "frame_aliases": ["frame", "frame_id", "frameId", "frame_num", "frameNum", "timecode", "tc"],
        "supported": [
            "marker payload normalization",
            "marker add/get/update/delete by scope",
            "custom_data round-trip by scope",
            "timeline item and media pool item flags",
            "timeline item and media pool item clip color",
            "read-only review reports",
            "direct-frame annotation copy between scopes",
        ],
        "version_or_page_dependent": [
            "current playhead marker insertion requires a current timeline and readable current timecode",
            "timeline current video item depends on playhead/page state",
        ],
        "boundaries": [
            "timeline, timeline item, and media pool item frame spaces are not equivalent",
            "copy_annotations uses direct frame numbers unless the caller maps frames explicitly",
            "clip color and flags are related review metadata but not marker records",
        ],
    }

def _marker_from_existing(frame, data: Dict[str, Any]):
    return {
        "frame": int(frame),
        "color": data.get("color", "Blue"),
        "name": data.get("name", ""),
        "note": data.get("note", ""),
        "duration": data.get("duration", 1),
        "custom_data": data.get("customData") or data.get("custom_data") or "",
    }

def _annotation_target(scope: str, p: Dict[str, Any], tl=None):
    scope = scope or "timeline"
    if scope == "timeline":
        if tl is None:
            _, tl, err = _get_tl()
            if err:
                return None, err
        return tl, None
    if scope == "timeline_item":
        if p.get("current"):
            if tl is None:
                _, tl, err = _get_tl()
                if err:
                    return None, err
            item = tl.GetCurrentVideoItem()
            if not item:
                return None, _err("No current video item")
            return item, None
        _, item, err = _get_item(p)
        if err:
            return None, err
        return item, None
    if scope == "media_pool_item":
        _, _, mp, err = _get_mp()
        if err:
            return None, err
        clip_id = p.get("clip_id")
        if clip_id:
            clip = _find_clip(mp.GetRootFolder(), clip_id)
            if not clip:
                return None, _err(f"Clip not found: {clip_id}")
            return clip, None
        if tl is None:
            _, tl, tl_err = _get_tl()
            if tl_err:
                return None, tl_err
        item = tl.GetCurrentVideoItem()
        clip = item.GetMediaPoolItem() if item else None
        if not clip:
            return None, _err("No media pool item could be resolved")
        return clip, None
    return None, _err(f"Unknown annotation scope: {scope}")

def _annotation_snapshot(scope: str, target):
    snapshot = {"scope": scope, "markers": {}, "flags": None, "clip_color": None}
    if _has_method(target, "GetMarkers"):
        snapshot["markers"] = _ser(target.GetMarkers() or {})
    if _has_method(target, "GetFlagList"):
        snapshot["flags"] = _ser(target.GetFlagList() or [])
    if _has_method(target, "GetClipColor"):
        snapshot["clip_color"] = _ser(target.GetClipColor())
    if _has_method(target, "GetUniqueId"):
        try:
            snapshot["id"] = target.GetUniqueId()
        except Exception:
            pass
    if _has_method(target, "GetName"):
        try:
            snapshot["name"] = target.GetName()
        except Exception:
            pass
    return snapshot

def _probe_annotations(tl, p: Dict[str, Any]):
    scope = p.get("scope")
    if scope:
        target, err = _annotation_target(scope, p, tl=tl)
        if err:
            return err
        return {"scopes": [_annotation_snapshot(scope, target)]}
    scopes = []
    scopes.append(_annotation_snapshot("timeline", tl))
    try:
        item = tl.GetCurrentVideoItem()
    except Exception:
        item = None
    if item:
        scopes.append(_annotation_snapshot("timeline_item", item))
        try:
            clip = item.GetMediaPoolItem()
        except Exception:
            clip = None
        if clip:
            scopes.append(_annotation_snapshot("media_pool_item", clip))
    return {"scopes": scopes, "count": len(scopes)}

def _normalize_marker_payload_action(tl, p: Dict[str, Any]):
    marker, err = _marker_add_payload(p, tl=tl, default_to_current=bool(p.get("default_to_current", False)))
    if err:
        return err
    return {"marker": marker}

def _copy_annotations(tl, p: Dict[str, Any], *, move: bool = False):
    source_p = dict(p.get("source") or {})
    target_p = dict(p.get("target") or {})
    source_scope = source_p.get("scope") or p.get("source_scope") or "timeline"
    target_scope = target_p.get("scope") or p.get("target_scope") or "timeline_item"
    source, err = _annotation_target(source_scope, source_p, tl=tl)
    if err:
        return err
    target, err = _annotation_target(target_scope, target_p, tl=tl)
    if err:
        return err
    markers = source.GetMarkers() if _has_method(source, "GetMarkers") else {}
    if not markers:
        return {"success": True, "copied": 0, "warnings": ["Source has no markers"]}
    warnings = []
    copied = 0
    for frame, data in (markers or {}).items():
        marker = _marker_from_existing(frame, data)
        result = _add_marker(target, marker)
        if result.get("success"):
            copied += 1
        else:
            warnings.append({"frame": frame, "result": result})
    if p.get("include_flags", True) and _has_method(source, "GetFlagList") and _has_method(target, "AddFlag"):
        for flag in source.GetFlagList() or []:
            if not target.AddFlag(flag):
                warnings.append({"flag": flag, "result": "AddFlag returned false"})
    if p.get("include_clip_color", True) and _has_method(source, "GetClipColor") and _has_method(target, "SetClipColor"):
        color = source.GetClipColor()
        if color and not target.SetClipColor(color):
            warnings.append({"clip_color": color, "result": "SetClipColor returned false"})
    cleared = None
    if move and copied:
        clear_color = p.get("clear_color", "All")
        cleared = bool(source.DeleteMarkersByColor(clear_color)) if _has_method(source, "DeleteMarkersByColor") else False
    return {
        "success": copied == len(markers),
        "copied": copied,
        "source_scope": source_scope,
        "target_scope": target_scope,
        "frame_mapping": "direct",
        "warnings": warnings,
        "cleared_source": cleared,
    }

def _sync_marker_custom_data(tl, p: Dict[str, Any]):
    scope = p.get("scope", "timeline")
    target, err = _annotation_target(scope, p, tl=tl)
    if err:
        return err
    frame, frame_err = _marker_frame_from_params(p, tl=tl if scope == "timeline" else None)
    if frame_err:
        return frame_err
    custom = _first_param(p, "custom_data", "customData", default="")
    if not _has_method(target, "UpdateMarkerCustomData"):
        return _err(f"{scope} does not expose UpdateMarkerCustomData")
    return {"success": bool(target.UpdateMarkerCustomData(frame, custom)), "frame": frame}

def _clear_annotations_by_scope(tl, p: Dict[str, Any]):
    scope = p.get("scope", "timeline")
    target, err = _annotation_target(scope, p, tl=tl)
    if err:
        return err
    if p.get("custom_data") or p.get("customData"):
        if not _has_method(target, "DeleteMarkerByCustomData"):
            return _err(f"{scope} does not expose DeleteMarkerByCustomData")
        return {"success": bool(target.DeleteMarkerByCustomData(_first_param(p, "custom_data", "customData", default="")))}
    color = p.get("color", "All" if p.get("all", True) else "Blue")
    if not _has_method(target, "DeleteMarkersByColor"):
        return _err(f"{scope} does not expose DeleteMarkersByColor")
    result = {"success": bool(target.DeleteMarkersByColor(color)), "color": color}
    if p.get("clear_flags") and _has_method(target, "ClearFlags"):
        result["flags_cleared"] = bool(target.ClearFlags(p.get("flag_color", "All")))
    if p.get("clear_clip_color") and _has_method(target, "ClearClipColor"):
        result["clip_color_cleared"] = bool(target.ClearClipColor())
    return result

def _export_review_report(tl, p: Dict[str, Any]):
    report = {
        "title": p.get("title", "Review Annotation Report"),
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "annotations": _probe_annotations(tl, p),
    }
    if p.get("include_capabilities", True):
        report["capabilities"] = _annotation_capabilities()
    return report

def _annotation_boundary_report(tl, p: Dict[str, Any]):
    return {
        "capabilities": _annotation_capabilities(),
        "annotations": _probe_annotations(tl, p),
    }

def _marker_value(marker: Dict[str, Any], *keys, default=None):
    for key in keys:
        if key in marker:
            return marker[key]
    return default

def _copy_timeline_item_markers(source_item, duplicate_item):
    try:
        markers = source_item.GetMarkers() or {}
    except Exception as exc:
        return {"success": False, "error": f"GetMarkers failed: {exc}"}
    copied = 0
    failed = []
    for frame, marker in markers.items():
        if not isinstance(marker, dict):
            failed.append({"frame": frame, "error": "marker payload is not an object"})
            continue
        frame_id = _frame_int(frame)
        if frame_id is None:
            failed.append({"frame": frame, "error": "marker frame is not numeric"})
            continue
        result = _add_marker(
            duplicate_item,
            {
                "frame": frame_id,
                "color": _marker_value(marker, "color", "Color", default="Blue"),
                "name": _marker_value(marker, "name", "Name", default="Marker"),
                "note": _marker_value(marker, "note", "Note", default=""),
                "duration": _frame_int(_marker_value(marker, "duration", "Duration", default=1)) or 1,
                "custom_data": str(_marker_value(marker, "customData", "custom_data", "CustomData", default="") or ""),
            },
        )
        if result.get("success"):
            copied += 1
        else:
            failed.append({"frame": frame_id, "error": result.get("error") or result.get("reason") or "AddMarker failed"})
    return {"success": not failed, "copied": copied, "failed": failed}

def _timeline_marker_rows_from_snapshot(snapshot: Dict[str, Any]) -> List[Dict[str, Any]]:
    markers = snapshot.get("markers") or {}
    rows = []
    if not isinstance(markers, dict):
        return rows
    for frame, marker in markers.items():
        if not isinstance(marker, dict):
            continue
        frame_id = _frame_int(frame)
        rows.append({
            "frame": frame_id,
            "color": _marker_value(marker, "color", "Color"),
            "name": _marker_value(marker, "name", "Name", default="Marker"),
            "note": _marker_value(marker, "note", "Note", default=""),
            "duration": _marker_value(marker, "duration", "Duration", default=1),
            "custom_data": _marker_value(marker, "customData", "custom_data", "CustomData", default=""),
        })
    rows.sort(key=lambda row: (row["frame"] is None, row["frame"] or 0))
    return rows


@mcp.tool()
def media_pool_item_markers(action: str, params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Markers and flags on media pool clips. Identify clip by clip_id.

    Actions:
      add(clip_id, frame|frame_id|frameId, color?, name?, note?, duration?, custom_data?) -> {success, frame}
      get_all(clip_id) -> {markers}
      get_by_custom_data(clip_id, custom_data) -> {markers}
      update_custom_data(clip_id, frame|frame_id|frameId, custom_data) -> {success}
      get_custom_data(clip_id, frame|frame_id|frameId) -> {data}
      delete_by_color(clip_id, color) -> {success}
      delete_at_frame(clip_id, frame|frame_id|frameId) -> {success}
      delete_by_custom_data(clip_id, custom_data) -> {success}
      add_flag(clip_id, color) -> {success}
      get_flags(clip_id) -> {flags}
      clear_flags(clip_id, color) -> {success}
      set_name(clip_id, name) -> {success}
      link_full_resolution_media(clip_id, path) -> {success}
      monitor_growing_file(clip_id) -> {success}
      replace_clip_preserve_sub_clip(clip_id, path) -> {success}
    """
    p = params or {}
    _, _, mp, err = _get_mp()
    if err:
        return err
    clip = _find_clip(mp.GetRootFolder(), p.get("clip_id", ""))
    if not clip:
        return _err(f"Clip not found: {p.get('clip_id')}")

    if action == "add":
        marker, marker_err = _marker_add_payload(p)
        if marker_err:
            return marker_err
        return _add_marker(clip, marker)
    elif action == "get_all":
        return {"markers": _ser(clip.GetMarkers())}
    elif action == "get_by_custom_data":
        return {"markers": _ser(clip.GetMarkerByCustomData(_first_param(p, "custom_data", "customData", default="")))}
    elif action == "update_custom_data":
        frame, frame_err = _marker_frame_from_params(p)
        if frame_err:
            return frame_err
        return {"success": bool(clip.UpdateMarkerCustomData(frame, _first_param(p, "custom_data", "customData", default="")))}
    elif action == "get_custom_data":
        frame, frame_err = _marker_frame_from_params(p)
        if frame_err:
            return frame_err
        return {"data": clip.GetMarkerCustomData(frame)}
    elif action == "delete_by_color":
        if not p.get("color"):
            return _err("delete_by_color requires color")
        return {"success": bool(clip.DeleteMarkersByColor(p["color"]))}
    elif action == "delete_at_frame":
        frame, frame_err = _marker_frame_from_params(p)
        if frame_err:
            return frame_err
        return {"success": bool(clip.DeleteMarkerAtFrame(frame))}
    elif action == "delete_by_custom_data":
        return {"success": bool(clip.DeleteMarkerByCustomData(_first_param(p, "custom_data", "customData", default="")))}
    elif action == "add_flag":
        return {"success": bool(clip.AddFlag(p["color"]))}
    elif action == "get_flags":
        return {"flags": clip.GetFlagList()}
    elif action == "clear_flags":
        return {"success": bool(clip.ClearFlags(p["color"]))}
    elif action == "set_name":
        return {"success": bool(clip.SetName(p["name"]))}
    elif action == "link_full_resolution_media":
        full_res_path = p.get("path") or p.get("full_res_media_path") or p.get("fullResMediaPath")
        if not full_res_path:
            return _err("Provide path or full_res_media_path")
        return {"success": bool(clip.LinkFullResolutionMedia(full_res_path))}
    elif action == "monitor_growing_file":
        return {"success": bool(clip.MonitorGrowingFile())}
    elif action == "replace_clip_preserve_sub_clip":
        replacement_path = p.get("path") or p.get("file_path") or p.get("filePath")
        if not replacement_path:
            return _err("Provide path or file_path")
        return {"success": bool(clip.ReplaceClipPreserveSubClip(replacement_path))}
    return _unknown(action, ["add","get_all","get_by_custom_data","update_custom_data","get_custom_data","delete_by_color","delete_at_frame","delete_by_custom_data","add_flag","get_flags","clear_flags","set_name","link_full_resolution_media","monitor_growing_file","replace_clip_preserve_sub_clip"])

@mcp.tool()
@_destructive_op("timeline_markers")
def timeline_markers(action: str, params: Optional[Dict[str, Any]] = None) -> Any:
    """Markers and playhead operations on the current timeline.

    Marker frames are RELATIVE to the timeline start: frame 0 is the first
    frame of the timeline, even when the timeline starts at 01:00:00:00.
    Timecode params are absolute timeline timecode as shown in the Resolve UI
    (timecodes before the start timecode are treated as elapsed time) and are
    converted to relative frames automatically.

    Actions:
      add(frame|frame_id|frameId|timecode?, color?, name?, note?, duration?, custom_data?) -> {success, frame}
        If frame/timecode is omitted, add uses the current playhead timecode.
      get_all() -> {markers}
      get_by_custom_data(custom_data) -> {markers}
      update_custom_data(frame|frame_id|frameId|timecode, custom_data) -> {success}
      get_custom_data(frame|frame_id|frameId|timecode) -> {data}
      delete_by_color(color) -> {success}
      delete_at_frame(frame|frame_id|frameId|timecode) -> {success}
      delete_by_custom_data(custom_data) -> {success}
      get_current_timecode() -> {timecode}
      set_current_timecode(timecode) -> {success}
      get_current_video_item() -> {name, id}
      get_thumbnail() -> {thumbnail}
      get_thumbnail_image() -> MCP image content for the current Color-page frame
      annotation_capabilities() -> {scopes, marker_colors, frame_aliases}
      probe_annotations(scope?, ...) -> {scopes, count}
      normalize_marker_payload(frame|timecode?, color?, name?, note?, duration?, custom_data?) -> {marker}
      copy_annotations(source={scope,...}, target={scope,...}, include_flags?, include_clip_color?) -> {success}
      move_annotations(source={scope,...}, target={scope,...}) -> {success}
      sync_marker_custom_data(scope?, frame|timecode, custom_data, ...) -> {success}
      clear_annotations_by_scope(scope?, color?, custom_data?, all?, clear_flags?, clear_clip_color?) -> {success}
      export_review_report(scope?, include_capabilities?) -> {title, annotations, capabilities?}
      annotation_boundary_report(scope?) -> {capabilities, annotations}
    """
    p = params or {}
    _, tl, err = _get_tl()
    if err:
        return err

    if action == "add":
        marker, marker_err = _marker_add_payload(p, tl=tl, default_to_current=True)
        if marker_err:
            return marker_err
        return _add_marker(tl, marker)
    elif action == "get_all":
        return {"markers": _ser(tl.GetMarkers())}
    elif action == "get_by_custom_data":
        return {"markers": _ser(tl.GetMarkerByCustomData(_first_param(p, "custom_data", "customData", default="")))}
    elif action == "update_custom_data":
        frame, frame_err = _marker_frame_from_params(p, tl=tl)
        if frame_err:
            return frame_err
        return {"success": bool(tl.UpdateMarkerCustomData(frame, _first_param(p, "custom_data", "customData", default="")))}
    elif action == "get_custom_data":
        frame, frame_err = _marker_frame_from_params(p, tl=tl)
        if frame_err:
            return frame_err
        return {"data": tl.GetMarkerCustomData(frame)}
    elif action == "delete_by_color":
        if not p.get("color"):
            return _err("delete_by_color requires color")
        return {"success": bool(tl.DeleteMarkersByColor(p["color"]))}
    elif action == "delete_at_frame":
        frame, frame_err = _marker_frame_from_params(p, tl=tl)
        if frame_err:
            return frame_err
        return {"success": bool(tl.DeleteMarkerAtFrame(frame))}
    elif action == "delete_by_custom_data":
        return {"success": bool(tl.DeleteMarkerByCustomData(_first_param(p, "custom_data", "customData", default="")))}
    elif action == "get_current_timecode":
        return {"timecode": tl.GetCurrentTimecode()}
    elif action == "set_current_timecode":
        return {"success": bool(tl.SetCurrentTimecode(p["timecode"]))}
    elif action == "get_current_video_item":
        it = tl.GetCurrentVideoItem()
        return {"name": it.GetName(), "id": it.GetUniqueId()} if it else {"name": None, "id": None}
    elif action == "get_thumbnail":
        thumbnail = tl.GetCurrentClipThumbnailImage()
        if thumbnail is None:
            return {
                "success": False,
                "thumbnail": None,
                "error": "Resolve did not return a thumbnail for the current playhead. Open the Color page and ensure a video item is under the playhead.",
            }
        return _ser(thumbnail)
    elif action == "get_thumbnail_image":
        thumbnail = tl.GetCurrentClipThumbnailImage()
        if not thumbnail:
            return _err("No thumbnail available. Open the Color page with a current clip selected.")
        try:
            return Image(data=_thumbnail_data_to_png_bytes(thumbnail), format="png")
        except ValueError as exc:
            return _err(str(exc))
    elif action == "annotation_capabilities":
        return _annotation_capabilities()
    elif action == "probe_annotations":
        return _probe_annotations(tl, p)
    elif action == "normalize_marker_payload":
        return _normalize_marker_payload_action(tl, p)
    elif action == "copy_annotations":
        return _copy_annotations(tl, p)
    elif action == "move_annotations":
        return _copy_annotations(tl, p, move=True)
    elif action == "sync_marker_custom_data":
        return _sync_marker_custom_data(tl, p)
    elif action == "clear_annotations_by_scope":
        return _clear_annotations_by_scope(tl, p)
    elif action == "export_review_report":
        return _export_review_report(tl, p)
    elif action == "annotation_boundary_report":
        return _annotation_boundary_report(tl, p)
    return _unknown(action, ["add","get_all","get_by_custom_data","update_custom_data","get_custom_data","delete_by_color","delete_at_frame","delete_by_custom_data","get_current_timecode","set_current_timecode","get_current_video_item","get_thumbnail","get_thumbnail_image",*_ANNOTATION_KERNEL_ACTIONS])

@mcp.tool()
@_destructive_op("timeline_item_markers")
def timeline_item_markers(action: str, params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Markers, flags, and clip color on timeline items. Identify by track_type, track_index, item_index (item_index is 0-BASED: 0 = first clip; track_index is 1-based).

    Actions:
      add(frame|frame_id|frameId, color?, name?, note?, duration?, custom_data?, ...) -> {success, frame}
      get_all(...) -> {markers}
      get_by_custom_data(custom_data, ...) -> {markers}
      update_custom_data(frame|frame_id|frameId, custom_data, ...) -> {success}
      get_custom_data(frame|frame_id|frameId, ...) -> {data}
      delete_by_color(color, ...) -> {success}
      delete_at_frame(frame|frame_id|frameId, ...) -> {success}
      delete_by_custom_data(custom_data, ...) -> {success}
      add_flag(color, ...) -> {success}
      get_flags(...) -> {flags}
      clear_flags(color, ...) -> {success}
      get_clip_color(...) -> {color}
      set_clip_color(color, ...) -> {success}
      clear_clip_color(...) -> {success}

    Default: track_type="video", track_index=1, item_index=0
    """
    p = params or {}
    _, item, err = _get_item(p)
    if err:
        return err

    if action == "add":
        marker, marker_err = _marker_add_payload(p)
        if marker_err:
            return marker_err
        return _add_marker(item, marker)
    elif action == "get_all":
        return {"markers": _ser(item.GetMarkers())}
    elif action == "get_by_custom_data":
        return {"markers": _ser(item.GetMarkerByCustomData(_first_param(p, "custom_data", "customData", default="")))}
    elif action == "update_custom_data":
        frame, frame_err = _marker_frame_from_params(p)
        if frame_err:
            return frame_err
        return {"success": bool(item.UpdateMarkerCustomData(frame, _first_param(p, "custom_data", "customData", default="")))}
    elif action == "get_custom_data":
        frame, frame_err = _marker_frame_from_params(p)
        if frame_err:
            return frame_err
        return {"data": item.GetMarkerCustomData(frame)}
    elif action == "delete_by_color":
        if not p.get("color"):
            return _err("delete_by_color requires color")
        return {"success": bool(item.DeleteMarkersByColor(p["color"]))}
    elif action == "delete_at_frame":
        frame, frame_err = _marker_frame_from_params(p)
        if frame_err:
            return frame_err
        return {"success": bool(item.DeleteMarkerAtFrame(frame))}
    elif action == "delete_by_custom_data":
        return {"success": bool(item.DeleteMarkerByCustomData(_first_param(p, "custom_data", "customData", default="")))}
    elif action == "add_flag":
        return {"success": bool(item.AddFlag(p["color"]))}
    elif action == "get_flags":
        return {"flags": item.GetFlagList()}
    elif action == "clear_flags":
        return {"success": bool(item.ClearFlags(p["color"]))}
    elif action == "get_clip_color":
        return {"color": item.GetClipColor()}
    elif action == "set_clip_color":
        return {"success": bool(item.SetClipColor(p["color"]))}
    elif action == "clear_clip_color":
        return {"success": bool(item.ClearClipColor())}
    return _unknown(action, ["add","get_all","get_by_custom_data","update_custom_data","get_custom_data","delete_by_color","delete_at_frame","delete_by_custom_data","add_flag","get_flags","clear_flags","get_clip_color","set_clip_color","clear_clip_color"])


_ANNOTATION_KERNEL_ACTIONS = [
    "annotation_capabilities",
    "probe_annotations",
    "normalize_marker_payload",
    "copy_annotations",
    "move_annotations",
    "sync_marker_custom_data",
    "clear_annotations_by_scope",
    "export_review_report",
    "annotation_boundary_report",
]
